In [1]:
# ---------------- 0. Imports & Config ----------------

# Core Python utilities
import json
import io
import os
import random
import time
from pathlib import Path
from collections import defaultdict

# Data processing
import cv2
import numpy as np
import pandas as pd
from PIL import Image
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt

# ML / retrieval
import torch
import faiss

# Google Cloud
from google.cloud import storage

# Transformers: same as 04_retrieval_experiments_clean.ipynb
from transformers import (
    CLIPProcessor,
    CLIPModel,
    BlipProcessor,
    BlipForImageTextRetrieval,
)

# ---------------- GCS config ----------------
BUCKET_NAME = "egorecall-data"

# ---------------- Local paths ----------------
WORK_DIR = Path("/home/jupyter/egorecall_retrieval_subset")
RESULTS_DIR = Path("/home/jupyter/results/retrieval_subset")
TMP_DIR = Path("/home/jupyter/tmp/retrieval_work")
FRAME_DIR = TMP_DIR / "frames"

for d in [WORK_DIR, RESULTS_DIR, TMP_DIR, FRAME_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ---------------- N_CLIPS=300 preprocessing config ----------------
N_CLIPS = 300
RANDOM_SEED = 42

BATCH_SIZE_CLIPS = 60
BATCH_ID = 0  # Change this later: 0, 1, 2, 3, 4

# ---------------- Model config: same as 04 baseline ----------------
CLIP_MODEL = "openai/clip-vit-base-patch32"
BLIP_MODEL = "Salesforce/blip-itm-base-coco"
BATCH_SIZE = 64

# ---------------- Frame extraction config ----------------
VIDEO_FPS = 30
INDEX_STRIDE = 30  # 1 FPS if source video is 30 FPS
TOLERANCE_SEC = 5
TOLERANCE_FRAMES = TOLERANCE_SEC * VIDEO_FPS

# ---------------- Video cleanup policy ----------------
# False means: after each batch is fully processed, we can remove the videos used by that batch.
# This keeps disk usage under control.
KEEP_VIDEOS_AFTER_BATCH = False

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device : {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")

print("N_CLIPS:", N_CLIPS)
print("BATCH_ID:", BATCH_ID)
print("BATCH_SIZE_CLIPS:", BATCH_SIZE_CLIPS)
print("Work dir:", WORK_DIR)
print("Temp dir:", TMP_DIR)
print("Frame dir:", FRAME_DIR)
print("Results dir:", RESULTS_DIR)

Device : cuda
GPU    : Tesla T4
N_CLIPS: 300
BATCH_ID: 0
BATCH_SIZE_CLIPS: 60
Work dir: /home/jupyter/egorecall_retrieval_subset
Temp dir: /home/jupyter/tmp/retrieval_work
Frame dir: /home/jupyter/tmp/retrieval_work/frames
Results dir: /home/jupyter/results/retrieval_subset

In [2]:
# ---------------- 0. Imports & Config ----------------

# Core Python utilities
import json
import io
import os
import random
import time
from pathlib import Path
from collections import defaultdict

# Data processing
import cv2
import numpy as np
import pandas as pd
from PIL import Image
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt

# ML / retrieval
import torch
import faiss

# Google Cloud
from google.cloud import storage

# Transformers: same as 04_retrieval_experiments_clean.ipynb
from transformers import (
    CLIPProcessor,
    CLIPModel,
    BlipProcessor,
    BlipForImageTextRetrieval,
)

# ---------------- GCS config ----------------
BUCKET_NAME = "egorecall-data"

# ---------------- Local paths ----------------
WORK_DIR = Path("/home/jupyter/egorecall_retrieval_subset")
RESULTS_DIR = Path("/home/jupyter/results/retrieval_subset")
TMP_DIR = Path("/home/jupyter/tmp/retrieval_work")
FRAME_DIR = TMP_DIR / "frames"

for d in [WORK_DIR, RESULTS_DIR, TMP_DIR, FRAME_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ---------------- N_CLIPS=300 preprocessing config ----------------
N_CLIPS = 300
RANDOM_SEED = 42

BATCH_SIZE_CLIPS = 60
BATCH_ID = 0  # Change this later: 0, 1, 2, 3, 4

# ---------------- Model config: same as 04 baseline ----------------
CLIP_MODEL = "openai/clip-vit-base-patch32"
BLIP_MODEL = "Salesforce/blip-itm-base-coco"
BATCH_SIZE = 64

# ---------------- Frame extraction config ----------------
VIDEO_FPS = 30
INDEX_STRIDE = 30  # 1 FPS if source video is 30 FPS
TOLERANCE_SEC = 5
TOLERANCE_FRAMES = TOLERANCE_SEC * VIDEO_FPS

# ---------------- Video cleanup policy ----------------
# False means: after each batch is fully processed, we can remove the videos used by that batch.
# This keeps disk usage under control.
KEEP_VIDEOS_AFTER_BATCH = False

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Device : {DEVICE}")
if DEVICE == "cuda":
    print(f"GPU    : {torch.cuda.get_device_name(0)}")

print("N_CLIPS:", N_CLIPS)
print("BATCH_ID:", BATCH_ID)
print("BATCH_SIZE_CLIPS:", BATCH_SIZE_CLIPS)
print("Work dir:", WORK_DIR)
print("Temp dir:", TMP_DIR)
print("Frame dir:", FRAME_DIR)
print("Results dir:", RESULTS_DIR)

Device : cuda
GPU    : Tesla T4
N_CLIPS: 300
BATCH_ID: 0
BATCH_SIZE_CLIPS: 60
Work dir: /home/jupyter/egorecall_retrieval_subset
Temp dir: /home/jupyter/tmp/retrieval_work
Frame dir: /home/jupyter/tmp/retrieval_work/frames
Results dir: /home/jupyter/results/retrieval_subset

In [3]:
# ---------------- 1. Connect to GCS and Load Metadata ----------------

gcs_client = storage.Client()
bucket = gcs_client.bucket(BUCKET_NAME)

print(f"Connected to gs://{BUCKET_NAME}")

metadata_path = WORK_DIR / "vq_query_sets.parquet"
annotation_path = WORK_DIR / "vq_val.json"

if not metadata_path.exists():
    print("Downloading processed/vq_query_sets.parquet...")
    bucket.blob("processed/vq_query_sets.parquet").download_to_filename(str(metadata_path))
else:
    print("Using local metadata:", metadata_path)

if not annotation_path.exists():
    print("Downloading ego4d/v2/annotations/vq_val.json...")
    bucket.blob("ego4d/v2/annotations/vq_val.json").download_to_filename(str(annotation_path))
else:
    print("Using local annotation:", annotation_path)

df = pd.read_parquet(metadata_path)

with open(annotation_path, "r") as f:
    val_raw = json.load(f)

val_df = df[df["split"] == "val"].copy()

print("All query-sets:", len(df))
print("Validation query-sets:", len(val_df))
print("Validation clips:", val_df["clip_uid"].nunique())
print("Columns:", df.columns.tolist())

display(
    val_df[
        [
            "split",
            "clip_uid",
            "video_uid",
            "annotation_uid",
            "qs_id",
            "object_title",
            "query_video_frame",
            "response_track_len",
            "vc_area_norm",
        ]
    ].head(5)
)

Connected to gs://egorecall-data
Using local metadata: /home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet
Using local annotation: /home/jupyter/egorecall_retrieval_subset/vq_val.json
All query-sets: 18114
Validation query-sets: 4507
Validation clips: 1157
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,clip_uid,video_uid,annotation_uid,qs_id,object_title,query_video_frame,response_track_len,vc_area_norm
13607,val,d5935c29-1b8d-417d-9bbb-5ebd47e9256d,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,3760b439-d94b-4d76-8b39-1bb355800649,3,sellotape,8598.0,59,0.015786
13608,val,d5935c29-1b8d-417d-9bbb-5ebd47e9256d,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,3760b439-d94b-4d76-8b39-1bb355800649,1,container,480.0,26,0.004053
13609,val,d5935c29-1b8d-417d-9bbb-5ebd47e9256d,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,3760b439-d94b-4d76-8b39-1bb355800649,2,cotton bud,10722.0,30,0.035157
13610,val,dfe962ab-6aa7-4888-9378-796817a30ab6,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,42288.0,30,0.066873
13611,val,dfe962ab-6aa7-4888-9378-796817a30ab6,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,46764.0,7,0.005119

In [4]:
# ---------------- 2. Sample N_CLIPS=300 validation clips ----------------

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# Use string clip_uids to avoid float/string sorting issues.
all_val_clips = val_df["clip_uid"].dropna().astype(str).unique().tolist()

subset_clips = random.sample(
    all_val_clips,
    min(N_CLIPS, len(all_val_clips))
)

subset_clip_set = set(subset_clips)
subset_df = val_df[val_df["clip_uid"].astype(str).isin(subset_clip_set)].copy()

print("Sampled clips:", len(subset_clips))
print("Query-sets in subset:", len(subset_df))

display(
    subset_df.groupby("clip_uid")
    .size()
    .reset_index(name="num_query_sets")
    .sort_values("num_query_sets", ascending=False)
    .head(10)
)

Sampled clips: 300
Query-sets in subset: 1157

                                 clip_uid  num_query_sets
189  ad9083b3-9b0b-4c27-a941-38f57be13edf              12
15   1004f7fe-c397-4123-bad9-e02df2e154dd               6
281  f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2               6
286  f54175da-19e5-4ee7-97b3-75baa247b713               6
287  f552173d-229e-496d-b414-3708df4c842e               6
280  f1350714-1aa5-421b-a268-690110ca9c06               6
10   09d85b55-d473-49c1-9ebc-e871714785cd               6
208  b8981cdd-a897-41b6-b1ef-e9957d270e9e               6
209  b8e1c869-b304-49fc-ba5f-9a5ae3b3770c               6
293  f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887               6

In [5]:
# ---------------- Build workplan: clip_uid -> video info + query-sets ----------------

workplan = {}
rt_lookup = {}  # (annotation_uid, qs_id) -> [video_frame_numbers]

for video in val_raw["videos"]:
    video_uid = video["video_uid"]

    for clip in video["clips"]:
        clip_uid = str(clip["clip_uid"])

        if clip_uid not in subset_clip_set:
            continue

        workplan[clip_uid] = {
            "video_uid": video_uid,
            "video_start_frame": clip["video_start_frame"],
            "video_end_frame": clip["video_end_frame"],
            "query_sets": [],
        }

        for anno in clip["annotations"]:
            annotation_uid = anno["annotation_uid"]

            for qs_id, qs in anno["query_sets"].items():
                if not qs.get("is_valid"):
                    continue

                workplan[clip_uid]["query_sets"].append({
                    "annotation_uid": annotation_uid,
                    "qs_id": str(qs_id),
                    "vc_blob": (
                        f"frames/retrieval/visual_crops/val/{clip_uid}/"
                        f"{annotation_uid}_{qs_id}.jpg"
                    ),
                    "object_title": qs.get("object_title", "").strip().lower(),
                })

                key = (annotation_uid, str(qs_id))
                rt_lookup[key] = [
                    b["video_frame_number"]
                    for b in qs.get("response_track", [])
                    if "video_frame_number" in b
                ]

print("Workplan clips:", len(workplan))
print("Response-track entries:", len(rt_lookup))

example_clip_uid = next(iter(workplan))
example_entry = workplan[example_clip_uid]

print("\nExample clip_uid:", example_clip_uid)
print("Example video_uid:", example_entry["video_uid"])
print("Video start frame:", example_entry["video_start_frame"])
print("Video end frame:", example_entry["video_end_frame"])
print("Number of query-sets:", len(example_entry["query_sets"]))
print("\nFirst query-set:")
print(example_entry["query_sets"][0])

Workplan clips: 300
Response-track entries: 1157

Example clip_uid: dfe962ab-6aa7-4888-9378-796817a30ab6
Example video_uid: e14e03f8-13e4-4df2-87b0-e1ad8a175f7c
Video start frame: 40500
Video end frame: 49500
Number of query-sets: 6

First query-set:
{'annotation_uid': '3b057788-ad90-432d-90ff-de1c45361df6', 'qs_id': '2', 'vc_blob': 'frames/retrieval/visual_crops/val/dfe962ab-6aa7-4888-9378-796817a30ab6/3b057788-ad90-432d-90ff-de1c45361df6_2.jpg', 'object_title': 'portable fan'}

In [6]:
# ---------------- 3. Cache directories ----------------
# Same saving targets as the 20-clip run.

CACHE_DIR = RESULTS_DIR / "cache"
INDEX_CACHE_DIR = CACHE_DIR / "index_frame_embeddings"
QUERY_CACHE_DIR = CACHE_DIR / "query_embeddings"

for d in [CACHE_DIR, INDEX_CACHE_DIR, QUERY_CACHE_DIR]:
    d.mkdir(parents=True, exist_ok=True)

print("Cache dir:", CACHE_DIR)
print("Index embedding cache dir:", INDEX_CACHE_DIR)
print("Query embedding cache dir:", QUERY_CACHE_DIR)

existing_index_caches = list(INDEX_CACHE_DIR.glob("*_index_embeddings.npz"))
existing_query_caches = list(QUERY_CACHE_DIR.glob("*_query_embeddings.npz"))
existing_videos = list(TMP_DIR.glob("*.mp4"))

print("Existing index caches:", len(existing_index_caches))
print("Existing query caches:", len(existing_query_caches))
print("Existing videos:", len(existing_videos))

Cache dir: /home/jupyter/results/retrieval_subset/cache
Index embedding cache dir: /home/jupyter/results/retrieval_subset/cache/index_frame_embeddings
Query embedding cache dir: /home/jupyter/results/retrieval_subset/cache/query_embeddings
Existing index caches: 299
Existing query caches: 299
Existing videos: 48

In [7]:
# ---------------- Select one batch from the 300-clip workplan ----------------

all_workplan_clips = list(workplan.keys())

start_idx = BATCH_ID * BATCH_SIZE_CLIPS
end_idx = min(start_idx + BATCH_SIZE_CLIPS, len(all_workplan_clips))

batch_clip_uids = all_workplan_clips[start_idx:end_idx]

print("Total workplan clips:", len(all_workplan_clips))
print("Batch ID:", BATCH_ID)
print("Batch start:", start_idx)
print("Batch end:", end_idx)
print("Batch clips:", len(batch_clip_uids))
print("First 5 batch clips:", batch_clip_uids[:5])

Total workplan clips: 300
Batch ID: 0
Batch start: 0
Batch end: 60
Batch clips: 60
First 5 batch clips: ['dfe962ab-6aa7-4888-9378-796817a30ab6', 'b157270d-c67a-41db-91ec-32bb3ec738fc', '7bb41f34-1743-42ad-97d1-c54f4472b85e', 'ea365183-5841-4f00-9a2e-1b81c5e09c98', 'b961eb69-cfdd-4d5c-b427-4b667fedfcda']

In [8]:
# ---------------- 4. Load CLIP and BLIP models ----------------
# Same as 04_retrieval_experiments_clean.ipynb.

print("Loading CLIP...")
clip_processor = CLIPProcessor.from_pretrained(CLIP_MODEL)
clip_model = CLIPModel.from_pretrained(CLIP_MODEL).to(DEVICE)
clip_model.eval()

print("Loading BLIP...")
blip_processor = BlipProcessor.from_pretrained(BLIP_MODEL)
blip_model = BlipForImageTextRetrieval.from_pretrained(BLIP_MODEL).to(DEVICE)
blip_model.eval()

print("Models loaded.")
print("clip_model type:", type(clip_model))
print("blip_model type:", type(blip_model))

Loading CLIP...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Loading BLIP...

Loading weights:   0%|          | 0/472 [00:00<?, ?it/s]

Models loaded.
clip_model type: <class 'transformers.models.clip.modeling_clip.CLIPModel'>
blip_model type: <class 'transformers.models.blip.modeling_blip.BlipForImageTextRetrieval'>

In [9]:
# ---------------- 5. Helper functions from 04 pipeline ----------------

def download_video_if_needed(video_uid, video_dir=TMP_DIR):
    """
    Download the source video from GCS if it does not already exist locally.
    Returns the local video path.
    """
    video_dir.mkdir(parents=True, exist_ok=True)
    local_video_path = video_dir / f"{video_uid}.mp4"

    if local_video_path.exists():
        print(f"Video already exists locally: {local_video_path}")
        return local_video_path

    video_blob = f"ego4d/v2/video_540ss/{video_uid}.mp4"
    print(f"Downloading video from gs://{BUCKET_NAME}/{video_blob}")

    bucket.blob(video_blob).download_to_filename(str(local_video_path))

    print(f"Downloaded video to: {local_video_path}")
    print(f"Video size: {local_video_path.stat().st_size / (1024 ** 2):.2f} MB")

    return local_video_path


def extract_index_frames(video_path, clip_uid, start_frame, end_frame, stride=INDEX_STRIDE):
    """
    Extract index frames from a source video for one clip.
    Frames are saved as {frame_number}.jpg.
    Returns a DataFrame with extracted frame paths.
    """
    output_dir = FRAME_DIR / clip_uid
    output_dir.mkdir(parents=True, exist_ok=True)

    target_frames = list(range(int(start_frame), int(end_frame), int(stride)))

    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Failed to open video: {video_path}")

    extracted_rows = []

    for frame_number in tqdm(target_frames, desc=f"Extracting frames for {clip_uid}", leave=False):
        output_path = output_dir / f"{frame_number:06d}.jpg"

        if output_path.exists():
            extracted_rows.append({
                "clip_uid": clip_uid,
                "frame_number": frame_number,
                "frame_path": str(output_path),
                "status": "exists",
            })
            continue

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
        success, frame_bgr = cap.read()

        if not success:
            extracted_rows.append({
                "clip_uid": clip_uid,
                "frame_number": frame_number,
                "frame_path": None,
                "status": "failed",
            })
            continue

        frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        Image.fromarray(frame_rgb).save(output_path, quality=90)

        extracted_rows.append({
            "clip_uid": clip_uid,
            "frame_number": frame_number,
            "frame_path": str(output_path),
            "status": "extracted",
        })

    cap.release()

    return pd.DataFrame(extracted_rows)


def ensure_index_frames_for_clip(clip_uid):
    """
    Ensure index frames exist for one clip.
    If frames already exist, extract_index_frames will skip them.
    """
    clip_info = workplan[clip_uid]
    video_uid = clip_info["video_uid"]

    video_path = download_video_if_needed(video_uid)

    extraction_df = extract_index_frames(
        video_path=video_path,
        clip_uid=clip_uid,
        start_frame=clip_info["video_start_frame"],
        end_frame=clip_info["video_end_frame"],
        stride=INDEX_STRIDE,
    )

    available = extraction_df[extraction_df["status"].isin(["extracted", "exists"])]

    if len(available) == 0:
        raise RuntimeError(f"No index frames available for clip: {clip_uid}")

    return extraction_df


def load_index_frames_for_clip(clip_uid):
    """
    Load extracted index frame images for a clip.

    Returns:
        frame_numbers: np.ndarray
        images: list of PIL images
        frame_paths: list of local image paths
    """
    clip_frame_dir = FRAME_DIR / clip_uid

    if not clip_frame_dir.exists() or len(list(clip_frame_dir.glob("*.jpg"))) == 0:
        ensure_index_frames_for_clip(clip_uid)

    frame_paths = sorted(clip_frame_dir.glob("*.jpg"))

    if len(frame_paths) == 0:
        raise FileNotFoundError(f"No extracted frame images found in: {clip_frame_dir}")

    frame_numbers = []
    images = []

    for path in frame_paths:
        frame_number = int(path.stem)
        img = Image.open(path).convert("RGB")

        frame_numbers.append(frame_number)
        images.append(img)

    frame_numbers = np.array(frame_numbers, dtype=np.int32)

    return frame_numbers, images, frame_paths


def _to_feature_tensor(output):
    """
    Convert Hugging Face model output into a tensor embedding.
    Same robust logic as 04 notebook.
    """
    if isinstance(output, torch.Tensor):
        return output

    if hasattr(output, "image_embeds") and output.image_embeds is not None:
        return output.image_embeds

    if hasattr(output, "pooler_output") and output.pooler_output is not None:
        return output.pooler_output

    if hasattr(output, "last_hidden_state") and output.last_hidden_state is not None:
        return output.last_hidden_state[:, 0, :]

    raise ValueError(f"Cannot extract tensor from output type: {type(output)}")


def embed_images(images, batch_size=BATCH_SIZE):
    """
    Embed a list of PIL images with both CLIP and BLIP.

    Returns:
        clip_embs: np.ndarray of shape (N, D_clip)
        blip_embs: np.ndarray of shape (N, D_blip)
    """
    clip_embs = []
    blip_embs = []

    for i in tqdm(range(0, len(images), batch_size), desc="Embedding images", leave=False):
        batch = images[i:i + batch_size]

        with torch.no_grad():
            # ----- CLIP -----
            clip_inputs = clip_processor(
                images=batch,
                return_tensors="pt",
                padding=True,
            ).to(DEVICE)

            clip_out = clip_model.get_image_features(**clip_inputs)
            clip_feat = _to_feature_tensor(clip_out)
            clip_feat = clip_feat / clip_feat.norm(dim=-1, keepdim=True)
            clip_embs.append(clip_feat.detach().cpu().numpy())

            # ----- BLIP -----
            blip_inputs = blip_processor(
                images=batch,
                return_tensors="pt",
                padding=True,
            ).to(DEVICE)

            blip_out = blip_model.vision_model(pixel_values=blip_inputs["pixel_values"])
            blip_feat = _to_feature_tensor(blip_out)
            blip_feat = blip_feat / blip_feat.norm(dim=-1, keepdim=True)
            blip_embs.append(blip_feat.detach().cpu().numpy())

    clip_embs = np.vstack(clip_embs).astype(np.float32)
    blip_embs = np.vstack(blip_embs).astype(np.float32)

    return clip_embs, blip_embs


def load_visual_crops_for_clip(clip_uid):
    """
    Load visual crop query images for one clip from GCS.

    Returns:
        query_images: list of PIL images
        query_metadata: list of dicts
    """
    clip_info = workplan[clip_uid]

    query_images = []
    query_metadata = []

    for qs in clip_info["query_sets"]:
        vc_blob = qs["vc_blob"]

        try:
            blob_data = bucket.blob(vc_blob).download_as_bytes()
            img = Image.open(io.BytesIO(blob_data)).convert("RGB")

            query_images.append(img)
            query_metadata.append({
                "clip_uid": clip_uid,
                "annotation_uid": qs["annotation_uid"],
                "qs_id": str(qs["qs_id"]),
                "object_title": qs["object_title"],
                "vc_blob": vc_blob,
            })

        except Exception as e:
            print(f"Failed to load visual crop: {vc_blob}")
            print("Error:", e)

    return query_images, query_metadata


def build_or_load_index_embedding_cache(clip_uid, force_recompute=False):
    """
    Build or load cached CLIP/BLIP embeddings for index frames of one clip.
    """
    cache_path = INDEX_CACHE_DIR / f"{clip_uid}_index_embeddings.npz"

    if cache_path.exists() and not force_recompute:
        print(f"Loading cached index embeddings: {cache_path}")
        data = np.load(cache_path)
        return {
            "frame_numbers": data["frame_numbers"],
            "clip_embs": data["clip_embs"],
            "blip_embs": data["blip_embs"],
        }

    print(f"Building index embedding cache for clip: {clip_uid}")

    frame_numbers, images, frame_paths = load_index_frames_for_clip(clip_uid)

    print("Number of index frames:", len(images))

    clip_embs, blip_embs = embed_images(images)

    np.savez_compressed(
        cache_path,
        frame_numbers=frame_numbers,
        clip_embs=clip_embs,
        blip_embs=blip_embs,
    )

    print(f"Saved index embeddings to: {cache_path}")
    print("CLIP index embedding shape:", clip_embs.shape)
    print("BLIP index embedding shape:", blip_embs.shape)

    return {
        "frame_numbers": frame_numbers,
        "clip_embs": clip_embs,
        "blip_embs": blip_embs,
    }


def build_or_load_query_embedding_cache(clip_uid, force_recompute=False):
    """
    Build or load cached CLIP/BLIP embeddings for visual crop query images.
    """
    cache_path = QUERY_CACHE_DIR / f"{clip_uid}_query_embeddings.npz"
    metadata_path = QUERY_CACHE_DIR / f"{clip_uid}_query_metadata.parquet"

    if cache_path.exists() and metadata_path.exists() and not force_recompute:
        print(f"Loading cached query embeddings: {cache_path}")
        data = np.load(cache_path)
        query_metadata_df = pd.read_parquet(metadata_path)

        return {
            "query_metadata": query_metadata_df,
            "clip_embs": data["clip_embs"],
            "blip_embs": data["blip_embs"],
        }

    print(f"Building query embedding cache for clip: {clip_uid}")

    query_images, query_metadata = load_visual_crops_for_clip(clip_uid)

    if len(query_images) == 0:
        raise ValueError(f"No visual crop query images loaded for clip: {clip_uid}")

    print("Number of visual crop queries:", len(query_images))

    clip_embs, blip_embs = embed_images(query_images)

    query_metadata_df = pd.DataFrame(query_metadata)

    np.savez_compressed(
        cache_path,
        clip_embs=clip_embs,
        blip_embs=blip_embs,
    )

    query_metadata_df.to_parquet(metadata_path, index=False)

    print(f"Saved query embeddings to: {cache_path}")
    print(f"Saved query metadata to: {metadata_path}")
    print("CLIP query embedding shape:", clip_embs.shape)
    print("BLIP query embedding shape:", blip_embs.shape)

    return {
        "query_metadata": query_metadata_df,
        "clip_embs": clip_embs,
        "blip_embs": blip_embs,
    }


print("Helper functions defined.")

Helper functions defined.

In [14]:
# ---------------- 6. Quick test on one clip ----------------

test_clip_uid = batch_clip_uids[0]

print("Test clip:", test_clip_uid)
print("Test video:", workplan[test_clip_uid]["video_uid"])
print("Query count:", len(workplan[test_clip_uid]["query_sets"]))

# 1. Ensure/load index frames
idx_frame_numbers, idx_images, idx_frame_paths = load_index_frames_for_clip(test_clip_uid)

print("Loaded index frames:", len(idx_images))
print("First frame number:", idx_frame_numbers[0])
print("Last frame number:", idx_frame_numbers[-1])
print("First image size:", idx_images[0].size)

# 2. Test embedding on only 2 images
test_clip_embs, test_blip_embs = embed_images(idx_images[:2])

print("CLIP embedding shape:", test_clip_embs.shape)
print("BLIP embedding shape:", test_blip_embs.shape)
print("CLIP first norm:", np.linalg.norm(test_clip_embs[0]))
print("BLIP first norm:", np.linalg.norm(test_blip_embs[0]))

# 3. Test query crop loading
query_images, query_metadata = load_visual_crops_for_clip(test_clip_uid)

print("Loaded query images:", len(query_images))
display(pd.DataFrame(query_metadata).head())

# 4. Test query embedding on up to 2 query images
q_clip_embs, q_blip_embs = embed_images(query_images[:2])

print("Query CLIP embedding shape:", q_clip_embs.shape)
print("Query BLIP embedding shape:", q_blip_embs.shape)
print("Query CLIP first norm:", np.linalg.norm(q_clip_embs[0]))
print("Query BLIP first norm:", np.linalg.norm(q_blip_embs[0]))

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Test video: e14e03f8-13e4-4df2-87b0-e1ad8a175f7c
Query count: 6
Loaded index frames: 300
First frame number: 40500
Last frame number: 49470
First image size: (960, 540)

Embedding images:   0%|          | 0/1 [00:00<?, ?it/s]

CLIP embedding shape: (2, 512)
BLIP embedding shape: (2, 768)
CLIP first norm: 1.0
BLIP first norm: 1.0
Loaded query images: 6

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,frames/retrieval/visual_crops/val/dfe962ab-6aa...
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,frames/retrieval/visual_crops/val/dfe962ab-6aa...
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,frames/retrieval/visual_crops/val/dfe962ab-6aa...
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,frames/retrieval/visual_crops/val/dfe962ab-6aa...
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,frames/retrieval/visual_crops/val/dfe962ab-6aa...

Embedding images:   0%|          | 0/1 [00:00<?, ?it/s]

Query CLIP embedding shape: (2, 512)
Query BLIP embedding shape: (2, 768)
Query CLIP first norm: 1.0
Query BLIP first norm: 0.99999994

In [12]:
# ---------------- 7. Cache status helper ----------------

def get_index_cache_path(clip_uid):
    return INDEX_CACHE_DIR / f"{clip_uid}_index_embeddings.npz"

def get_query_cache_path(clip_uid):
    return QUERY_CACHE_DIR / f"{clip_uid}_query_embeddings.npz"

def get_query_metadata_path(clip_uid):
    return QUERY_CACHE_DIR / f"{clip_uid}_query_metadata.parquet"

def check_clip_cache_status(clip_uid):
    index_cache_path = get_index_cache_path(clip_uid)
    query_cache_path = get_query_cache_path(clip_uid)
    query_metadata_path = get_query_metadata_path(clip_uid)

    return {
        "clip_uid": clip_uid,
        "index_cache_exists": index_cache_path.exists(),
        "query_cache_exists": query_cache_path.exists(),
        "query_metadata_exists": query_metadata_path.exists(),
        "fully_cached": (
            index_cache_path.exists()
            and query_cache_path.exists()
            and query_metadata_path.exists()
        ),
    }

batch_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in batch_clip_uids]
)

display(batch_cache_status_df.head())

print("Batch clips:", len(batch_cache_status_df))
print("Index caches exist:", batch_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", batch_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", batch_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", batch_cache_status_df["fully_cached"].sum())

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,dfe962ab-6aa7-4888-9378-796817a30ab6,True,True,True,True
1,b157270d-c67a-41db-91ec-32bb3ec738fc,True,True,True,True
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,True,True,True,True
3,ea365183-5841-4f00-9a2e-1b81c5e09c98,True,True,True,True
4,b961eb69-cfdd-4d5c-b427-4b667fedfcda,True,True,True,True

Batch clips: 60
Index caches exist: 60
Query caches exist: 60
Query metadata exists: 60
Fully cached: 60

In [13]:
# ---------------- 8. Preprocess one clip safely ----------------

def preprocess_one_clip_for_cache(clip_uid, force_recompute=False):
    """
    Build the same cache objects as the 20-clip run:
    1. index frame embeddings npz
    2. query visual crop embeddings npz
    3. query metadata parquet

    If all cache files already exist, skip this clip.
    """
    status_before = check_clip_cache_status(clip_uid)

    row = {
        "clip_uid": clip_uid,
        "video_uid": workplan[clip_uid]["video_uid"],
        "status": "started",
        "error": None,
        "index_cache_exists_before": status_before["index_cache_exists"],
        "query_cache_exists_before": status_before["query_cache_exists"],
        "query_metadata_exists_before": status_before["query_metadata_exists"],
    }

    try:
        if status_before["fully_cached"] and not force_recompute:
            row["status"] = "skipped_fully_cached"
            row["num_index_frames"] = None
            row["num_queries"] = len(workplan[clip_uid]["query_sets"])
            return row

        index_cache = build_or_load_index_embedding_cache(
            clip_uid,
            force_recompute=force_recompute,
        )

        query_cache = build_or_load_query_embedding_cache(
            clip_uid,
            force_recompute=force_recompute,
        )

        status_after = check_clip_cache_status(clip_uid)

        row.update({
            "status": "success",
            "num_index_frames": len(index_cache["frame_numbers"]),
            "num_queries": len(query_cache["query_metadata"]),
            "index_cache_exists_after": status_after["index_cache_exists"],
            "query_cache_exists_after": status_after["query_cache_exists"],
            "query_metadata_exists_after": status_after["query_metadata_exists"],
            "fully_cached_after": status_after["fully_cached"],
        })

        return row

    except Exception as e:
        row["status"] = "error"
        row["error"] = repr(e)
        return row

In [15]:
# ---------------- Test one clip only ----------------

test_clip_uid = batch_clip_uids[0]

one_clip_result = preprocess_one_clip_for_cache(
    test_clip_uid,
    force_recompute=False,
)

one_clip_result

{'clip_uid': 'dfe962ab-6aa7-4888-9378-796817a30ab6',
 'video_uid': 'e14e03f8-13e4-4df2-87b0-e1ad8a175f7c',
 'status': 'skipped_fully_cached',
 'error': None,
 'index_cache_exists_before': True,
 'query_cache_exists_before': True,
 'query_metadata_exists_before': True,
 'num_index_frames': None,
 'num_queries': 6}

In [16]:
# ---------------- 9. Batch-safe preprocessing loop ----------------

def run_preprocess_batch_for_cache(batch_clip_uids, batch_id, force_recompute=False):
    """
    Run preprocessing for one batch.
    Saves progress after each clip.
    """
    manifest_path = RESULTS_DIR / f"preprocess_manifest_nclips{N_CLIPS}_batch{batch_id}.csv"
    errors_path = RESULTS_DIR / f"preprocess_errors_nclips{N_CLIPS}_batch{batch_id}.json"

    rows = []
    errors = []

    for clip_uid in tqdm(batch_clip_uids, desc=f"Preprocess batch {batch_id}"):
        row = preprocess_one_clip_for_cache(
            clip_uid,
            force_recompute=force_recompute,
        )

        rows.append(row)

        if row["status"] == "error":
            errors.append(row)

        # Save progress after every clip
        pd.DataFrame(rows).to_csv(manifest_path, index=False)

        with open(errors_path, "w") as f:
            json.dump(errors, f, indent=2)

        print(
            f"Finished clip {clip_uid} | "
            f"status={row['status']} | "
            f"errors={len(errors)}"
        )

    manifest_df = pd.DataFrame(rows)

    print("\nFinished batch:", batch_id)
    print("Total clips:", len(manifest_df))
    print("Success:", (manifest_df["status"] == "success").sum())
    print("Skipped fully cached:", (manifest_df["status"] == "skipped_fully_cached").sum())
    print("Errors:", (manifest_df["status"] == "error").sum())
    print("Saved manifest to:", manifest_path)
    print("Saved errors to:", errors_path)

    return manifest_df

In [16]:
# ---------------- 10. Run full batch 0 ----------------

batch_manifest_df = run_preprocess_batch_for_cache(
    batch_clip_uids=batch_clip_uids,
    batch_id=BATCH_ID,
    force_recompute=False,
)

display(batch_manifest_df)
display(batch_manifest_df["status"].value_counts(dropna=False))

Preprocess batch 0:   0%|          | 0/60 [00:00<?, ?it/s]

Finished clip dfe962ab-6aa7-4888-9378-796817a30ab6 | status=skipped_fully_cached | errors=0
Finished clip b157270d-c67a-41db-91ec-32bb3ec738fc | status=skipped_fully_cached | errors=0
Finished clip 7bb41f34-1743-42ad-97d1-c54f4472b85e | status=skipped_fully_cached | errors=0
Finished clip ea365183-5841-4f00-9a2e-1b81c5e09c98 | status=skipped_fully_cached | errors=0
Finished clip b961eb69-cfdd-4d5c-b427-4b667fedfcda | status=skipped_fully_cached | errors=0
Finished clip c8070026-c3dc-43d3-8d36-65c5d9a1317f | status=skipped_fully_cached | errors=0
Finished clip bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76 | status=skipped_fully_cached | errors=0
Finished clip 11acf51c-9a44-4c77-9e16-46925c2e66de | status=skipped_fully_cached | errors=0
Finished clip 5e961d49-5eb3-4d6d-b2f0-c9be437ba623 | status=skipped_fully_cached | errors=0
Finished clip 7a954faf-102f-4aba-9317-96d73c8fd104 | status=skipped_fully_cached | errors=0
Finished clip cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c | status=skipped_fully_cached | errors=0
Finished clip e7ec16d2-6649-4942-8da9-83e603e78438 | status=skipped_fully_cached | errors=0
Finished clip e4728a65-3184-4239-9b84-be43dfd7377e | status=skipped_fully_cached | errors=0
Finished clip 293a2530-a4a8-4776-92d5-741142dfdd3e | status=skipped_fully_cached | errors=0
Finished clip ae8727ba-fe6f-4411-b277-48a8b7326a2a | status=skipped_fully_cached | errors=0
Finished clip 151c66b5-bdb2-42ba-b663-8ef307223d7a | status=skipped_fully_cached | errors=0
Finished clip 30ca6fa7-dbe0-4f55-84c8-8797de99c290 | status=skipped_fully_cached | errors=0
Finished clip 01b451af-466a-4425-8094-be0b2ffc0e36 | status=skipped_fully_cached | errors=0
Finished clip 307c3ec6-886e-4d25-9ef7-7bea3cf7a243 | status=skipped_fully_cached | errors=0
Finished clip 1e666456-2299-47ff-af7c-8bda73f825ea | status=skipped_fully_cached | errors=0
Finished clip b7eaf50a-2499-45bd-abd8-478463fdc4a8 | status=skipped_fully_cached | errors=0
Finished clip efc97e5a-20a0-42f1-9cfd-fcede9bbe043 | status=skipped_fully_cached | errors=0
Finished clip 7ff93f97-d65f-4195-8f37-e4040acb2d09 | status=skipped_fully_cached | errors=0
Finished clip 94106c40-8e3a-4018-a3fc-a86106979766 | status=skipped_fully_cached | errors=0
Finished clip 145b7d46-a4f7-472e-8adf-08be3ed4062c | status=skipped_fully_cached | errors=0
Finished clip d28999ab-8945-4618-aa50-b37594573391 | status=skipped_fully_cached | errors=0
Finished clip 704943b6-2922-43d7-9b16-81c021b96232 | status=skipped_fully_cached | errors=0
Finished clip 8efe1412-5806-425e-9c3e-459bb9d45079 | status=skipped_fully_cached | errors=0
Finished clip c52530be-f470-4c44-ae1a-c8aee924ff46 | status=skipped_fully_cached | errors=0
Finished clip 918f04d6-65f3-4a8f-af65-b57852de1729 | status=skipped_fully_cached | errors=0
Finished clip e7af8550-5a98-406a-b4a0-e8cf9f901d79 | status=skipped_fully_cached | errors=0
Finished clip c908ae46-123b-466d-a709-99d4d4bc8d37 | status=skipped_fully_cached | errors=0
Finished clip b9c96242-ae4d-4a43-a308-a00591f060ab | status=skipped_fully_cached | errors=0
Finished clip 69668105-9984-43d0-8c24-74a4ed2adcf4 | status=skipped_fully_cached | errors=0
Finished clip db84f0aa-15a2-4cfb-a89e-173b0aea4720 | status=skipped_fully_cached | errors=0
Finished clip eaa07b51-b07d-4cf7-91e7-314a74c8edc6 | status=skipped_fully_cached | errors=0
Finished clip ec67faf9-2d1b-41a9-ad96-da31887ba60c | status=skipped_fully_cached | errors=0
Finished clip e8a88ddf-63db-4095-93fe-9d24c386a477 | status=skipped_fully_cached | errors=0
Finished clip 593a5700-05d7-46ba-a2c2-c5150b514144 | status=skipped_fully_cached | errors=0
Finished clip 8ebdf93c-6bba-4604-be9b-45938eb2bb38 | status=skipped_fully_cached | errors=0
Finished clip 7b452799-981c-494a-affb-d011cd5c43e5 | status=skipped_fully_cached | errors=0
Finished clip b8981cdd-a897-41b6-b1ef-e9957d270e9e | status=skipped_fully_cached | errors=0
Finished clip e4daf535-ef9c-493f-9688-9c2ba35d431a | status=skipped_fully_cached | errors=0
Finished clip afc5b8d0-3146-48f2-be24-c1490cfa766f | status=skipped_fully_cached | errors=0
Finished clip 3c5b4041-8d0d-40ac-8750-1a7e744a38e5 | status=skipped_fully_cached | errors=0
Finished clip 3716dd4c-232c-4ac1-89bd-3884cc79f0a8 | status=skipped_fully_cached | errors=0
Finished clip fc838ebc-2c4e-42f2-8108-9710ecb1653a | status=skipped_fully_cached | errors=0
Finished clip 297eb153-8e44-4f25-b270-ca4d682c32bb | status=skipped_fully_cached | errors=0
Finished clip 95685c3a-9604-4fa3-a6e0-3d27a67fb3ad | status=skipped_fully_cached | errors=0
Finished clip f552173d-229e-496d-b414-3708df4c842e | status=skipped_fully_cached | errors=0
Finished clip 281b9507-4bea-4549-9912-90d6fd257f05 | status=skipped_fully_cached | errors=0
Finished clip 56c1dc45-24f5-45aa-8273-ed5835bce1f3 | status=skipped_fully_cached | errors=0
Finished clip f8bdd228-ef92-43e3-bf6f-086ff54d5c78 | status=skipped_fully_cached | errors=0
Finished clip ddb94361-b4c3-4343-8a80-daad1ea69476 | status=skipped_fully_cached | errors=0
Finished clip 9ca1c968-8346-4fc1-a704-e7dffc79afa7 | status=skipped_fully_cached | errors=0
Finished clip 148d1a43-5368-4257-8e98-8a762ad1d113 | status=skipped_fully_cached | errors=0
Finished clip b144e06c-ac25-4584-9ff4-93d6a8d04865 | status=skipped_fully_cached | errors=0
Finished clip cc711b14-cadc-40ef-b39f-611e57ec3956 | status=skipped_fully_cached | errors=0
Finished clip d149e4b3-a919-4deb-a088-4fe245896ef2 | status=skipped_fully_cached | errors=0
Finished clip 3cbf7d7e-7ef1-4486-94ea-b558c890b4b4 | status=skipped_fully_cached | errors=0

Finished batch: 0
Total clips: 60
Success: 0
Skipped fully cached: 60
Errors: 0
Saved manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
Saved errors to: /home/jupyter/results/retrieval_subset/preprocess_errors_nclips300_batch0.json

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,dfe962ab-6aa7-4888-9378-796817a30ab6,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,skipped_fully_cached,None,True,True,True,None,6
1,b157270d-c67a-41db-91ec-32bb3ec738fc,eb486644-f46f-44cf-8e4b-73245b2fc02e,skipped_fully_cached,None,True,True,True,None,6
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,eb486644-f46f-44cf-8e4b-73245b2fc02e,skipped_fully_cached,None,True,True,True,None,3
3,ea365183-5841-4f00-9a2e-1b81c5e09c98,eb486644-f46f-44cf-8e4b-73245b2fc02e,skipped_fully_cached,None,True,True,True,None,3
4,b961eb69-cfdd-4d5c-b427-4b667fedfcda,d8c40e36-c9fe-4c79-aa4c-271ab6427c2d,skipped_fully_cached,None,True,True,True,None,3
5,c8070026-c3dc-43d3-8d36-65c5d9a1317f,8a6a3316-d682-4a76-81db-b244081765c9,skipped_fully_cached,None,True,True,True,None,3
6,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,8a6a3316-d682-4a76-81db-b244081765c9,skipped_fully_cached,None,True,True,True,None,6
7,11acf51c-9a44-4c77-9e16-46925c2e66de,f20bca30-b7f0-4d2f-92ae-3982602f05df,skipped_fully_cached,None,True,True,True,None,3
8,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,7e2a3795-28a5-4314-a4d7-b91807812ed1,skipped_fully_cached,None,True,True,True,None,3
9,7a954faf-102f-4aba-9317-96d73c8fd104,32991c95-5acb-4d1b-a142-98c2fe27cbfd,skipped_fully_cached,None,True,True,True,None,3
10,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,342c7d2a-509b-4a35-83d3-0dd14c58a4da,skipped_fully_cached,None,True,True,True,None,6
11,e7ec16d2-6649-4942-8da9-83e603e78438,775acd8e-086f-48cf-adf3-c154f0d0bd2d,skipped_fully_cached,None,True,True,True,None,3
12,e4728a65-3184-4239-9b84-be43dfd7377e,570fc280-231c-4a3e-99c2-12eefed1c122,skipped_fully_cached,None,True,True,True,None,3
13,293a2530-a4a8-4776-92d5-741142dfdd3e,5dab6f94-5ca7-4985-bcd0-67f4fc04687a,skipped_fully_cached,None,True,True,True,None,2
14,ae8727ba-fe6f-4411-b277-48a8b7326a2a,092d5490-683c-4164-9750-93205cb9094c,skipped_fully_cached,None,True,True,True,None,3
15,151c66b5-bdb2-42ba-b663-8ef307223d7a,a9b0f569-cd28-4519-a44d-13f41b3eb5c8,skipped_fully_cached,None,True,True,True,None,3
16,30ca6fa7-dbe0-4f55-84c8-8797de99c290,a9b0f569-cd28-4519-a44d-13f41b3eb5c8,skipped_fully_cached,None,True,True,True,None,3
17,01b451af-466a-4425-8094-be0b2ffc0e36,a89406e0-6cb0-443c-afa1-d241853d2a6c,skipped_fully_cached,None,True,True,True,None,1
18,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,20400762-1e47-462d-a7d1-64a1b162b1f9,skipped_fully_cached,None,True,True,True,None,6
19,1e666456-2299-47ff-af7c-8bda73f825ea,d526d862-080f-4b3e-9894-6ff997f5d6ac,skipped_fully_cached,None,True,True,True,None,3
20,b7eaf50a-2499-45bd-abd8-478463fdc4a8,291e4d57-380b-4f8f-81e0-a67a3c3528a4,skipped_fully_cached,None,True,True,True,None,3
21,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,12eeb457-8acc-4ae1-a7d8-2b9814612c8e,skipped_fully_cached,None,True,True,True,None,6
22,7ff93f97-d65f-4195-8f37-e4040acb2d09,088add57-cf62-4ddd-9908-7eb738b0ec22,skipped_fully_cached,None,True,True,True,None,6
23,94106c40-8e3a-4018-a3fc-a86106979766,fc34508d-f89f-40f8-bf8e-c4d08bbbbeaf,skipped_fully_cached,None,True,True,True,None,3
24,145b7d46-a4f7-472e-8adf-08be3ed4062c,b23e6424-aa93-43a8-84f5-654f32b1eae4,skipped_fully_cached,None,True,True,True,None,3
25,d28999ab-8945-4618-aa50-b37594573391,004a1802-c546-4dcc-86ba-bf1080077017,skipped_fully_cached,None,True,True,True,None,3
26,704943b6-2922-43d7-9b16-81c021b96232,004a1802-c546-4dcc-86ba-bf1080077017,skipped_fully_cached,None,True,True,True,None,3
27,8efe1412-5806-425e-9c3e-459bb9d45079,18e84829-901a-414d-8a2b-d1d2b3244db7,skipped_fully_cached,None,True,True,True,None,3
28,c52530be-f470-4c44-ae1a-c8aee924ff46,c5d1bc36-6248-4ad4-a672-a158a9d2509b,skipped_fully_cached,None,True,True,True,None,6
29,918f04d6-65f3-4a8f-af65-b57852de1729,e65eb769-09ac-4ed0-b747-847e76252fa6,skipped_fully_cached,None,True,True,True,None,3
30,e7af8550-5a98-406a-b4a0-e8cf9f901d79,a743a90e-f46c-4e55-a94d-a7f11c771207,skipped_fully_cached,None,True,True,True,None,6
31,c908ae46-123b-466d-a709-99d4d4bc8d37,256701cd-3317-47ee-b6e3-439dc2ad2bd5,skipped_fully_cached,None,True,True,True,None,6
32,b9c96242-ae4d-4a43-a308-a00591f060ab,256701cd-3317-47ee-b6e3-439dc2ad2bd5,skipped_fully_cached,None,True,True,True,None,3
33,69668105-9984-43d0-8c24-74a4ed2adcf4,256701cd-3317-47ee-b6e3-439dc2ad2bd5,skipped_fully_cached,None,True,True,True,None,3
34,db84f0aa-15a2-4cfb-a89e-173b0aea4720,145881ef-5578-460d-bb5a-6fb80ef7d457,skipped_fully_cached,None,True,True,True,None,3
35,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,c74c1df9-bc28-4561-bc2a-28767632cb2b,skipped_fully_cached,None,True,True,True,None,3
36,ec67faf9-2d1b-41a9-ad96-da31887ba60c,c74c1df9-bc28-4561-bc2a-28767632cb2b,skipped_fully_cached,None,True,True,True,None,3
37,e8a88ddf-63db-4095-93fe-9d24c386a477,c74c1df9-bc28-4561-bc2a-28767632cb2b,skipped_fully_cached,None,True,True,True,None,3
38,593a5700-05d7-46ba-a2c2-c5150b514144,216c7a1a-7ec3-4aa0-a465-e37e7b5fd2f3,skipped_fully_cached,None,True,True,True,None,6
39,8ebdf93c-6bba-4604-be9b-45938eb2bb38,3342e81d-1809-4029-8bd9-12f05dd782f6,skipped_fully_cached,None,True,True,True,None,3
40,7b452799-981c-494a-affb-d011cd5c43e5,ebc9f0f8-924b-47d1-a639-de4f2d6e6a4c,skipped_fully_cached,None,True,True,True,None,6
41,b8981cdd-a897-41b6-b1ef-e9957d270e9e,ebc9f0f8-924b-47d1-a639-de4f2d6e6a4c,skipped_fully_cached,None,True,True,True,None,6
42,e4daf535-ef9c-493f-9688-9c2ba35d431a,ebc9f0f8-924b-47d1-a639-de4f2d6e6a4c,skipped_fully_cached,None,True,True,True,None,3
43,afc5b8d0-3146-48f2-be24-c1490cfa766f,5d9261fb-7d80-4cb0-b601-38c17fbf6f75,skipped_fully_cached,None,True,True,True,None,6
44,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,5d9261fb-7d80-4cb0-b601-38c17fbf6f75,skipped_fully_cached,None,True,True,True,None,3
45,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,a4728450-c05c-4d51-91e4-348f571d74bc,skipped_fully_cached,None,True,True,True,None,6
46,fc838ebc-2c4e-42f2-8108-9710ecb1653a,fec1f883-fc5c-4257-985e-26efaec68ddc,skipped_fully_cached,None,True,True,True,None,3
47,297eb153-8e44-4f25-b270-ca4d682c32bb,9d4612dc-de21-48a6-a003-0f7485adb8cd,skipped_fully_cached,None,True,True,True,None,3
48,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,22f68c6a-b8dd-44e6-b1fe-d4e619e72f59,skipped_fully_cached,None,True,True,True,None,3
49,f552173d-229e-496d-b414-3708df4c842e,a6a2231e-725b-4732-8076-323e9525d03a,skipped_fully_cached,None,True,True,True,None,6
50,281b9507-4bea-4549-9912-90d6fd257f05,45a02f60-e694-4bef-9c31-d5a71f556122,skipped_fully_cached,None,True,True,True,None,3
51,56c1dc45-24f5-45aa-8273-ed5835bce1f3,24c447b6-094f-49a6-9c20-ed594ab0da65,skipped_fully_cached,None,True,True,True,None,3
52,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,579bcf96-f29d-4f02-bb10-ef8b9404e362,skipped_fully_cached,None,True,True,True,None,3
53,ddb94361-b4c3-4343-8a80-daad1ea69476,579bcf96-f29d-4f02-bb10-ef8b9404e362,skipped_fully_cached,None,True,True,True,None,2
54,9ca1c968-8346-4fc1-a704-e7dffc79afa7,f6a0d8f5-468d-4e47-bfca-e7d13b75f26d,skipped_fully_cached,None,True,True,True,None,3
55,148d1a43-5368-4257-8e98-8a762ad1d113,1330508f-8168-4408-a4df-79f69fb87c83,skipped_fully_cached,None,True,True,True,None,3
56,b144e06c-ac25-4584-9ff4-93d6a8d04865,1330508f-8168-4408-a4df-79f69fb87c83,skipped_fully_cached,None,True,True,True,None,3
57,cc711b14-cadc-40ef-b39f-611e57ec3956,866fde4d-1f32-4578-833c-ba93811ee12e,skipped_fully_cached,None,True,True,True,None,3
58,d149e4b3-a919-4deb-a088-4fe245896ef2,9c59e912-2340-4400-b2df-7db3d4066723,skipped_fully_cached,None,True,True,True,None,3
59,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,9c59e912-2340-4400-b2df-7db3d4066723,skipped_fully_cached,None,True,True,True,None,3

status
skipped_fully_cached    60
Name: count, dtype: int64

In [17]:
# ---------------- 11. Switch to batch 1 ----------------

BATCH_ID = 1

all_workplan_clips = list(workplan.keys())

start_idx = BATCH_ID * BATCH_SIZE_CLIPS
end_idx = min(start_idx + BATCH_SIZE_CLIPS, len(all_workplan_clips))

batch_clip_uids = all_workplan_clips[start_idx:end_idx]

print("Total workplan clips:", len(all_workplan_clips))
print("Batch ID:", BATCH_ID)
print("Batch start:", start_idx)
print("Batch end:", end_idx)
print("Batch clips:", len(batch_clip_uids))
print("First 5 batch clips:", batch_clip_uids[:5])

Total workplan clips: 300
Batch ID: 1
Batch start: 60
Batch end: 120
Batch clips: 60
First 5 batch clips: ['dbd760b1-f99a-4a74-9f67-50579e516532', '8d22e91b-ed98-4c87-8a25-c937236ca745', '81da71e1-0e80-43cc-8752-292d231e70a2', '67c47998-eabe-4b31-9096-b286c18e1beb', 'fd82660b-9650-4326-93fc-08b1b950ac9d']

In [18]:
# ---------------- 12. Check cache status for batch 1 ----------------

batch_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in batch_clip_uids]
)

display(batch_cache_status_df.head())

print("Batch clips:", len(batch_cache_status_df))
print("Index caches exist:", batch_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", batch_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", batch_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", batch_cache_status_df["fully_cached"].sum())

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,dbd760b1-f99a-4a74-9f67-50579e516532,False,False,False,False
1,8d22e91b-ed98-4c87-8a25-c937236ca745,False,False,False,False
2,81da71e1-0e80-43cc-8752-292d231e70a2,False,False,False,False
3,67c47998-eabe-4b31-9096-b286c18e1beb,True,True,True,True
4,fd82660b-9650-4326-93fc-08b1b950ac9d,False,False,False,False

Batch clips: 60
Index caches exist: 4
Query caches exist: 4
Query metadata exists: 4
Fully cached: 4

In [21]:
# ---------------- 13. Run full batch 1 ----------------

batch_manifest_df = run_preprocess_batch_for_cache(
    batch_clip_uids=batch_clip_uids,
    batch_id=BATCH_ID,
    force_recompute=False,
)

display(batch_manifest_df)
display(batch_manifest_df["status"].value_counts(dropna=False))

Preprocess batch 0:   0%|          | 0/60 [00:00<?, ?it/s]

Finished clip dbd760b1-f99a-4a74-9f67-50579e516532 | status=skipped_fully_cached | errors=0
Finished clip 8d22e91b-ed98-4c87-8a25-c937236ca745 | status=skipped_fully_cached | errors=0
Finished clip 81da71e1-0e80-43cc-8752-292d231e70a2 | status=skipped_fully_cached | errors=0
Finished clip 67c47998-eabe-4b31-9096-b286c18e1beb | status=skipped_fully_cached | errors=0
Finished clip fd82660b-9650-4326-93fc-08b1b950ac9d | status=skipped_fully_cached | errors=0
Finished clip c77d3785-22f9-46c9-bf6d-9f7196356749 | status=skipped_fully_cached | errors=0
Finished clip 9f661edf-a6f6-444e-b168-e8428044b1d7 | status=skipped_fully_cached | errors=0
Finished clip f1eb7035-ce79-4be2-81bc-118eb1ad2887 | status=skipped_fully_cached | errors=0
Finished clip d9d45d26-743b-4e26-8137-416372bdaddb | status=skipped_fully_cached | errors=0
Finished clip 09d85b55-d473-49c1-9ebc-e871714785cd | status=skipped_fully_cached | errors=0
Finished clip 706c54f8-2740-40bb-a341-651b708392fa | status=skipped_fully_cached | errors=0
Finished clip 4570ab0a-55de-442d-b350-fe64e6956d4d | status=skipped_fully_cached | errors=0
Finished clip 8ae90b75-6ccf-417e-8c19-a63bf86a678d | status=skipped_fully_cached | errors=0
Finished clip 63f79304-5e02-415b-b375-73a39b8b4271 | status=skipped_fully_cached | errors=0
Finished clip 5699168a-b5d3-4957-8ec1-87a4377b2e94 | status=skipped_fully_cached | errors=0
Finished clip f16b6028-4624-4224-a368-a18d59aefe70 | status=skipped_fully_cached | errors=0
Finished clip 82abc0e6-c282-4492-89cb-c6005f1cb0f5 | status=skipped_fully_cached | errors=0
Finished clip 074ff05f-e0cb-41b7-96fe-25a9a79ce918 | status=skipped_fully_cached | errors=0
Finished clip 73382127-39b0-4033-af91-4e310670a349 | status=skipped_fully_cached | errors=0
Finished clip 6dd3486b-59dd-4dc6-874a-e4d773273c8a | status=skipped_fully_cached | errors=0
Finished clip 7dbdb00c-7652-487f-be2e-26a14c3f2145 | status=skipped_fully_cached | errors=0
Finished clip fbf8b92f-8472-4195-8b9c-4c365714ff94 | status=skipped_fully_cached | errors=0
Finished clip 2d76f374-48e5-4cef-8b6b-bc6f0c038d48 | status=skipped_fully_cached | errors=0
Finished clip 5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2 | status=skipped_fully_cached | errors=0
Finished clip 6ec2a3e6-f9cf-459b-815a-e8853ea7309c | status=skipped_fully_cached | errors=0
Finished clip cc7d11f0-445e-426a-904e-e7faafdb07f7 | status=skipped_fully_cached | errors=0
Finished clip 430be2d1-eb7f-4418-a3bb-06c0d71307d3 | status=skipped_fully_cached | errors=0
Finished clip e0fdd4e0-cccf-423c-9629-9b234e4a458f | status=skipped_fully_cached | errors=0
Finished clip 70bce3b1-ffdf-412d-8b28-2c5a4978015f | status=skipped_fully_cached | errors=0
Finished clip 6e945b3a-ee26-4a3c-93f0-f60e2456c44a | status=skipped_fully_cached | errors=0
Finished clip afc253af-734c-4e67-b4c2-09384fcd1e93 | status=skipped_fully_cached | errors=0
Finished clip 8059dcc2-0f52-46f8-a119-85c78d608602 | status=skipped_fully_cached | errors=0
Finished clip ee5b3977-6598-4dfd-9199-e36a0d2fd56a | status=skipped_fully_cached | errors=0
Finished clip 145ec165-a872-433e-959d-a0d748d261b0 | status=skipped_fully_cached | errors=0
Finished clip c2229daf-ec7b-45c5-84e3-bb4f4d145d93 | status=skipped_fully_cached | errors=0
Finished clip 6c88216a-cf77-48f2-9dc4-ccb4cc5160f5 | status=skipped_fully_cached | errors=0
Finished clip 6e4a69cf-b603-4797-8d68-11f27919b40c | status=skipped_fully_cached | errors=0
Finished clip 79cc2baa-4289-44f2-a013-ac6943b3f35d | status=skipped_fully_cached | errors=0
Finished clip 993b95b0-3ab2-4b31-a250-e6221a7d2864 | status=skipped_fully_cached | errors=0
Finished clip 4479363e-cd84-4fe7-994e-02eaf4531b0b | status=skipped_fully_cached | errors=0
Finished clip 7ecce159-e45f-4e35-9289-f61abfa02147 | status=skipped_fully_cached | errors=0
Finished clip bd600d49-9db0-4e6f-8698-cf18f3cef8a8 | status=skipped_fully_cached | errors=0
Finished clip 563db64f-47c4-42e3-b8bf-c543fd78655a | status=skipped_fully_cached | errors=0
Finished clip e355d07d-844b-44ff-bfab-c1fb98d48b6c | status=skipped_fully_cached | errors=0
Finished clip a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6 | status=skipped_fully_cached | errors=0
Finished clip 6f3c6977-b9dc-40de-bd32-349567343f0a | status=skipped_fully_cached | errors=0
Finished clip 412ee977-da12-496e-9609-80bfef2f4638 | status=skipped_fully_cached | errors=0
Finished clip 26f6ea45-4e7d-4208-b36c-715064151980 | status=skipped_fully_cached | errors=0
Finished clip 8f829383-08e6-48a9-85f9-0999eb9379a3 | status=skipped_fully_cached | errors=0
Finished clip 5ab141ed-312d-4db3-a424-433e417e15ef | status=skipped_fully_cached | errors=0
Finished clip b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc | status=skipped_fully_cached | errors=0
Finished clip efe7dfaa-07e0-42d5-85eb-1e6f93409ab5 | status=skipped_fully_cached | errors=0
Finished clip 2b8ddc75-2c96-4f73-8278-ff7f60920426 | status=skipped_fully_cached | errors=0
Finished clip 2809b5d6-4811-4f6a-8621-4f0f89b697a8 | status=skipped_fully_cached | errors=0
Finished clip f090ba34-9f57-40de-8fce-f2d3503d55ef | status=skipped_fully_cached | errors=0
Finished clip cb0cd08f-7a3e-4450-86ae-e7d490603188 | status=skipped_fully_cached | errors=0
Finished clip 022f1dbb-0018-4660-a18c-9e1213b88928 | status=skipped_fully_cached | errors=0
Finished clip 54892083-4f4a-4535-b0c9-8babf21492f2 | status=skipped_fully_cached | errors=0
Finished clip 984d6427-5bf1-477d-98fc-170b93165868 | status=skipped_fully_cached | errors=0
Finished clip a881f4a6-1d84-4088-8cea-8cf3a61c0914 | status=skipped_fully_cached | errors=0

Finished batch: 0
Total clips: 60
Success: 0
Skipped fully cached: 60
Errors: 0
Saved manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
Saved errors to: /home/jupyter/results/retrieval_subset/preprocess_errors_nclips300_batch0.json

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,skipped_fully_cached,None,True,True,True,None,3
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,skipped_fully_cached,None,True,True,True,None,6
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,skipped_fully_cached,None,True,True,True,None,3
3,67c47998-eabe-4b31-9096-b286c18e1beb,abbc5555-7816-4288-8d4d-f42b0683fc44,skipped_fully_cached,None,True,True,True,None,6
4,fd82660b-9650-4326-93fc-08b1b950ac9d,0b245a61-32d6-4b14-897c-724adad5b231,skipped_fully_cached,None,True,True,True,None,3
5,c77d3785-22f9-46c9-bf6d-9f7196356749,eea4b231-055e-4c4e-8f95-8dd043601da6,skipped_fully_cached,None,True,True,True,None,3
6,9f661edf-a6f6-444e-b168-e8428044b1d7,316ad960-e087-4d33-ba02-08e83c20e199,skipped_fully_cached,None,True,True,True,None,6
7,f1eb7035-ce79-4be2-81bc-118eb1ad2887,d405ceed-68da-4e50-a0ef-5d2995a94e5d,skipped_fully_cached,None,True,True,True,None,3
8,d9d45d26-743b-4e26-8137-416372bdaddb,d405ceed-68da-4e50-a0ef-5d2995a94e5d,skipped_fully_cached,None,True,True,True,None,6
9,09d85b55-d473-49c1-9ebc-e871714785cd,d405ceed-68da-4e50-a0ef-5d2995a94e5d,skipped_fully_cached,None,True,True,True,None,6
10,706c54f8-2740-40bb-a341-651b708392fa,d405ceed-68da-4e50-a0ef-5d2995a94e5d,skipped_fully_cached,None,True,True,True,None,3
11,4570ab0a-55de-442d-b350-fe64e6956d4d,82935e33-3b6e-4a9c-91be-9887ac0beab4,skipped_fully_cached,None,True,True,True,None,3
12,8ae90b75-6ccf-417e-8c19-a63bf86a678d,3c4b02ff-5304-4e58-9efe-89f22f27c4cb,skipped_fully_cached,None,True,True,True,None,3
13,63f79304-5e02-415b-b375-73a39b8b4271,4220db3a-4708-4fd1-ab67-0ef1586906cd,skipped_fully_cached,None,True,True,True,None,2
14,5699168a-b5d3-4957-8ec1-87a4377b2e94,4220db3a-4708-4fd1-ab67-0ef1586906cd,skipped_fully_cached,None,True,True,True,None,3
15,f16b6028-4624-4224-a368-a18d59aefe70,e98dd5f7-e90e-484e-b8ae-9a180882a26d,skipped_fully_cached,None,True,True,True,None,3
16,82abc0e6-c282-4492-89cb-c6005f1cb0f5,510d101a-44ba-4fcc-8de8-926681999387,skipped_fully_cached,None,True,True,True,None,3
17,074ff05f-e0cb-41b7-96fe-25a9a79ce918,510d101a-44ba-4fcc-8de8-926681999387,skipped_fully_cached,None,True,True,True,None,3
18,73382127-39b0-4033-af91-4e310670a349,510d101a-44ba-4fcc-8de8-926681999387,skipped_fully_cached,None,True,True,True,None,3
19,6dd3486b-59dd-4dc6-874a-e4d773273c8a,5fce50cf-ebc5-4c09-8704-20c48fe42c7e,skipped_fully_cached,None,True,True,True,None,3
20,7dbdb00c-7652-487f-be2e-26a14c3f2145,5fce50cf-ebc5-4c09-8704-20c48fe42c7e,skipped_fully_cached,None,True,True,True,None,6
21,fbf8b92f-8472-4195-8b9c-4c365714ff94,ac037122-f605-4043-abf0-f9486f02b898,skipped_fully_cached,None,True,True,True,None,3
22,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,67a4a7c2-d7be-4776-8764-1cca425965b7,skipped_fully_cached,None,True,True,True,None,6
23,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,f9fcba54-a13f-48ce-b848-868c50dee728,skipped_fully_cached,None,True,True,True,None,3
24,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,8795f7e7-c1ca-4ca0-b777-982a16fa68e1,skipped_fully_cached,None,True,True,True,None,6
25,cc7d11f0-445e-426a-904e-e7faafdb07f7,8795f7e7-c1ca-4ca0-b777-982a16fa68e1,skipped_fully_cached,None,True,True,True,None,3
26,430be2d1-eb7f-4418-a3bb-06c0d71307d3,af539ab4-2e40-43a2-a752-477e0240e600,skipped_fully_cached,None,True,True,True,None,3
27,e0fdd4e0-cccf-423c-9629-9b234e4a458f,bd3a319e-0573-4802-a6d1-6d89910098e8,skipped_fully_cached,None,True,True,True,None,3
28,70bce3b1-ffdf-412d-8b28-2c5a4978015f,8764c7c3-26aa-4390-9ba3-ff4de3294f45,skipped_fully_cached,None,True,True,True,None,3
29,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,8764c7c3-26aa-4390-9ba3-ff4de3294f45,skipped_fully_cached,None,True,True,True,None,6
30,afc253af-734c-4e67-b4c2-09384fcd1e93,2725d34b-04d5-411a-b405-c5e12d167ade,skipped_fully_cached,None,True,True,True,None,6
31,8059dcc2-0f52-46f8-a119-85c78d608602,85ecd8b2-922f-4845-8536-db53afc485b2,skipped_fully_cached,None,True,True,True,None,6
32,ee5b3977-6598-4dfd-9199-e36a0d2fd56a,34af64b6-2135-43dc-9a33-2899d92a0c8e,skipped_fully_cached,None,True,True,True,None,2
33,145ec165-a872-433e-959d-a0d748d261b0,34af64b6-2135-43dc-9a33-2899d92a0c8e,skipped_fully_cached,None,True,True,True,None,2
34,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,34af64b6-2135-43dc-9a33-2899d92a0c8e,skipped_fully_cached,None,True,True,True,None,3
35,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,cf9b2219-bdea-4a91-a56d-02c028547400,skipped_fully_cached,None,True,True,True,None,3
36,6e4a69cf-b603-4797-8d68-11f27919b40c,805989f6-0696-4de2-ad9b-0f194e0ac48d,skipped_fully_cached,None,True,True,True,None,6
37,79cc2baa-4289-44f2-a013-ac6943b3f35d,afbb32dd-a9f5-4086-aa3e-bfac55789e0b,skipped_fully_cached,None,True,True,True,None,6
38,993b95b0-3ab2-4b31-a250-e6221a7d2864,168f91fd-53c2-4eee-9d2d-e25e1ad73438,skipped_fully_cached,None,True,True,True,None,3
39,4479363e-cd84-4fe7-994e-02eaf4531b0b,adf65602-f5ee-456a-a098-db19a521ce38,skipped_fully_cached,None,True,True,True,None,6
40,7ecce159-e45f-4e35-9289-f61abfa02147,adf65602-f5ee-456a-a098-db19a521ce38,skipped_fully_cached,None,True,True,True,None,6
41,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,9930414f-b998-4217-b6b5-aa686236fdf8,skipped_fully_cached,None,True,True,True,None,6
42,563db64f-47c4-42e3-b8bf-c543fd78655a,9930414f-b998-4217-b6b5-aa686236fdf8,skipped_fully_cached,None,True,True,True,None,6
43,e355d07d-844b-44ff-bfab-c1fb98d48b6c,dc0ef581-bb29-464e-8ada-0953230d8f7d,skipped_fully_cached,None,True,True,True,None,3
44,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,ce444cf8-eaf9-4506-96d4-e94c3bacb28c,skipped_fully_cached,None,True,True,True,None,3
45,6f3c6977-b9dc-40de-bd32-349567343f0a,9e7fa594-5774-4681-a034-50a5c83cff8f,skipped_fully_cached,None,True,True,True,None,6
46,412ee977-da12-496e-9609-80bfef2f4638,94c24bfc-c712-4e7e-9be0-4ea3ac215a79,skipped_fully_cached,None,True,True,True,None,6
47,26f6ea45-4e7d-4208-b36c-715064151980,c864505c-9d49-4da4-bf7e-254b4c348c03,skipped_fully_cached,None,True,True,True,None,6
48,8f829383-08e6-48a9-85f9-0999eb9379a3,c864505c-9d49-4da4-bf7e-254b4c348c03,skipped_fully_cached,None,True,True,True,None,3
49,5ab141ed-312d-4db3-a424-433e417e15ef,c864505c-9d49-4da4-bf7e-254b4c348c03,skipped_fully_cached,None,True,True,True,None,3
50,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,c864505c-9d49-4da4-bf7e-254b4c348c03,skipped_fully_cached,None,True,True,True,None,3
51,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bedaa131-deae-4279-9fd4-5b6ab552644c,skipped_fully_cached,None,True,True,True,None,3
52,2b8ddc75-2c96-4f73-8278-ff7f60920426,b6d7c19a-c056-40d3-9f92-7b11c8c61d26,skipped_fully_cached,None,True,True,True,None,3
53,2809b5d6-4811-4f6a-8621-4f0f89b697a8,939dcf5d-c88c-4f93-b300-982adaff5ce3,skipped_fully_cached,None,True,True,True,None,3
54,f090ba34-9f57-40de-8fce-f2d3503d55ef,972f2966-c368-4344-a9ca-5bd8a277f177,skipped_fully_cached,None,True,True,True,None,3
55,cb0cd08f-7a3e-4450-86ae-e7d490603188,6ffeaf80-bdb0-478f-9712-1e51e1b1e1d6,skipped_fully_cached,None,True,True,True,None,6
56,022f1dbb-0018-4660-a18c-9e1213b88928,d61475bb-fd97-43e3-8b7d-a242064a9d10,skipped_fully_cached,None,True,True,True,None,3
57,54892083-4f4a-4535-b0c9-8babf21492f2,d61475bb-fd97-43e3-8b7d-a242064a9d10,skipped_fully_cached,None,True,True,True,None,6
58,984d6427-5bf1-477d-98fc-170b93165868,d61475bb-fd97-43e3-8b7d-a242064a9d10,skipped_fully_cached,None,True,True,True,None,2
59,a881f4a6-1d84-4088-8cea-8cf3a61c0914,8e605fdf-a4f1-4393-975a-f332ab6b5f79,skipped_fully_cached,None,True,True,True,None,6

status
skipped_fully_cached    60
Name: count, dtype: int64

In [22]:
# ---------------- 14. Switch to batch 2 ----------------

BATCH_ID = 2

all_workplan_clips = list(workplan.keys())

start_idx = BATCH_ID * BATCH_SIZE_CLIPS
end_idx = min(start_idx + BATCH_SIZE_CLIPS, len(all_workplan_clips))

batch_clip_uids = all_workplan_clips[start_idx:end_idx]

print("Total workplan clips:", len(all_workplan_clips))
print("Batch ID:", BATCH_ID)
print("Batch start:", start_idx)
print("Batch end:", end_idx)
print("Batch clips:", len(batch_clip_uids))
print("First 5 batch clips:", batch_clip_uids[:5])

Total workplan clips: 300
Batch ID: 2
Batch start: 120
Batch end: 180
Batch clips: 60
First 5 batch clips: ['617e8d7c-8764-4508-ba9b-c993282c70cd', 'b58bc49e-d3ac-4995-baa0-218a14e4c2fa', '81221073-c095-4129-b095-97f3d6e4a6b1', '5e66abe8-a72b-43f3-b6bf-fc05a45ff80f', '5ab23181-c60a-4478-9085-2a450a24b65b']

In [23]:
# ---------------- 15. Check cache status for batch 2 ----------------

batch_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in batch_clip_uids]
)

display(batch_cache_status_df.head())

print("Batch clips:", len(batch_cache_status_df))
print("Index caches exist:", batch_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", batch_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", batch_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", batch_cache_status_df["fully_cached"].sum())

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,617e8d7c-8764-4508-ba9b-c993282c70cd,False,False,False,False
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,False,False,False,False
2,81221073-c095-4129-b095-97f3d6e4a6b1,False,False,False,False
3,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,False,False,False,False
4,5ab23181-c60a-4478-9085-2a450a24b65b,False,False,False,False

Batch clips: 60
Index caches exist: 5
Query caches exist: 5
Query metadata exists: 5
Fully cached: 5

In [26]:
# ---------------- 16. Run full batch 2 ----------------

batch_manifest_df = run_preprocess_batch_for_cache(
    batch_clip_uids=batch_clip_uids,
    batch_id=BATCH_ID,
    force_recompute=False,
)

display(batch_manifest_df)
display(batch_manifest_df["status"].value_counts(dropna=False))

Preprocess batch 2:   0%|          | 0/60 [00:00<?, ?it/s]

Finished clip 617e8d7c-8764-4508-ba9b-c993282c70cd | status=skipped_fully_cached | errors=0
Finished clip b58bc49e-d3ac-4995-baa0-218a14e4c2fa | status=skipped_fully_cached | errors=0
Finished clip 81221073-c095-4129-b095-97f3d6e4a6b1 | status=skipped_fully_cached | errors=0
Finished clip 5e66abe8-a72b-43f3-b6bf-fc05a45ff80f | status=skipped_fully_cached | errors=0
Finished clip 5ab23181-c60a-4478-9085-2a450a24b65b | status=skipped_fully_cached | errors=0
Finished clip 99ddfcb3-bb2a-45d3-903e-d7e858969957 | status=skipped_fully_cached | errors=0
Finished clip 14ea5c3e-bbb5-44cf-abcc-e70e1223ad74 | status=skipped_fully_cached | errors=0
Finished clip 5771acd7-c7a9-4350-8064-7763bf111149 | status=skipped_fully_cached | errors=0
Finished clip aef0725a-1005-4a17-ad33-4522808c3a17 | status=skipped_fully_cached | errors=0
Finished clip f835883d-2ef1-427d-9c2f-5d9e7670cf5e | status=skipped_fully_cached | errors=0
Finished clip 629cb4e4-65a5-45f5-909d-2ff93e57a0bf | status=skipped_fully_cached | errors=0
Finished clip 49b8d3e9-de69-49cf-819b-5af1fd69b732 | status=skipped_fully_cached | errors=0
Finished clip 1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed | status=skipped_fully_cached | errors=0
Finished clip eb0359b2-72f1-40ff-ba22-64bb818d1f48 | status=skipped_fully_cached | errors=0
Finished clip 8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb | status=skipped_fully_cached | errors=0
Finished clip 6673c838-2765-4b41-81fd-9a01deba1d0b | status=skipped_fully_cached | errors=0
Finished clip ba50504a-93ad-46bc-8433-0c1f89d21f78 | status=skipped_fully_cached | errors=0
Finished clip 1b0aed98-785d-4471-ad38-940ca8673030 | status=skipped_fully_cached | errors=0
Finished clip 8450f847-5946-4199-9bc7-9d08c93c0141 | status=skipped_fully_cached | errors=0
Finished clip b47da6e2-cb60-4fd4-9705-5eb3af05877d | status=skipped_fully_cached | errors=0
Finished clip 21af903a-6c19-4854-afe0-009d81849867 | status=skipped_fully_cached | errors=0
Finished clip d2e61675-14b6-481f-9206-34bbc1375ea6 | status=skipped_fully_cached | errors=0
Finished clip d0bae6e6-356e-459d-b3dc-bc53c710611b | status=skipped_fully_cached | errors=0
Finished clip 8530a122-787b-4e95-b848-5543e8d772c7 | status=skipped_fully_cached | errors=0
Finished clip 23b8f734-c2db-4c55-9bca-cbe557d4abd4 | status=skipped_fully_cached | errors=0
Finished clip 5333a996-877f-4e30-ba79-631131744a4b | status=skipped_fully_cached | errors=0
Finished clip ccc4408f-8420-481d-b5aa-0c0013e3a109 | status=skipped_fully_cached | errors=0
Finished clip 48a81e63-9f9e-48c1-84e0-5fb90549cc4e | status=skipped_fully_cached | errors=0
Finished clip 36335d72-a5d7-4878-9f5b-9ff9635815b8 | status=skipped_fully_cached | errors=0
Finished clip c7fd4879-e196-4195-8fa8-d4430ae90a9a | status=skipped_fully_cached | errors=0
Finished clip 9737f5fb-d4b7-420c-98ee-471ec872c808 | status=skipped_fully_cached | errors=0
Finished clip f91c7008-f21c-4047-bfc1-d937787665e5 | status=skipped_fully_cached | errors=0
Finished clip 0723c03f-263c-442d-9d9b-d0fef0cef0e4 | status=skipped_fully_cached | errors=0
Finished clip 87499bfb-3dcf-46fa-aef3-204fcc0496e0 | status=skipped_fully_cached | errors=0
Finished clip 248cf237-d8dc-42d1-ae41-017221765031 | status=skipped_fully_cached | errors=0
Finished clip edfa156e-8e82-43cf-8a40-4f9be8f7c2e8 | status=skipped_fully_cached | errors=0
Finished clip 260ec80b-f26a-4646-afc5-616481889643 | status=skipped_fully_cached | errors=0
Finished clip 5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6 | status=skipped_fully_cached | errors=0
Finished clip 714ee146-e130-439d-89ff-6876efe62b07 | status=skipped_fully_cached | errors=0
Finished clip 64cc6d12-f613-452f-b56b-451f395c9c10 | status=skipped_fully_cached | errors=0
Finished clip d68ae83a-903a-448e-bc7e-7279755e0243 | status=skipped_fully_cached | errors=0
Finished clip 368755d7-886a-4b05-85f4-e3b3785a8d14 | status=skipped_fully_cached | errors=0
Finished clip 72e90719-c2b8-4b17-b120-e904dbbf1184 | status=skipped_fully_cached | errors=0
Finished clip 39f8cacc-5fd2-44c5-84d8-5bcc7fefe798 | status=skipped_fully_cached | errors=0
Finished clip b8e1c869-b304-49fc-ba5f-9a5ae3b3770c | status=skipped_fully_cached | errors=0
Finished clip 1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d | status=skipped_fully_cached | errors=0
Finished clip 860b4b8a-7219-433b-8947-cd8b93973b07 | status=skipped_fully_cached | errors=0
Finished clip ce57cce9-c6c4-4e07-be46-a84b29e7462c | status=skipped_fully_cached | errors=0
Finished clip 1ffc605c-c5f5-42d3-9897-6e9319675497 | status=skipped_fully_cached | errors=0
Finished clip 635733d7-8863-47b0-a7e2-4a0365813723 | status=skipped_fully_cached | errors=0
Finished clip 72eee417-f3cb-47dc-8266-24277c2307e2 | status=skipped_fully_cached | errors=0
Finished clip a4130ad1-bdcd-4de0-aa5e-09865e515ff3 | status=skipped_fully_cached | errors=0
Finished clip 6f7f5312-db3f-42db-98c0-f650a3899568 | status=skipped_fully_cached | errors=0
Finished clip f0a86b75-fd8e-43dd-95ee-401717b94f70 | status=skipped_fully_cached | errors=0
Finished clip d87774db-a324-4440-aa60-b39fe3276b77 | status=skipped_fully_cached | errors=0
Finished clip 55200058-9bf1-48a4-ac7f-a279f75fcaf1 | status=skipped_fully_cached | errors=0
Finished clip d111f736-d02a-43f4-8968-2b6631138d84 | status=skipped_fully_cached | errors=0
Finished clip bc576c20-68d9-47bc-9d04-b7e0bfc67abb | status=skipped_fully_cached | errors=0
Finished clip 9e9f05e9-5dbe-439b-970d-acb13ab98f10 | status=skipped_fully_cached | errors=0
Finished clip bed399ed-44af-438d-ab3f-12739adac348 | status=skipped_fully_cached | errors=0

Finished batch: 2
Total clips: 60
Success: 0
Skipped fully cached: 60
Errors: 0
Saved manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch2.csv
Saved errors to: /home/jupyter/results/retrieval_subset/preprocess_errors_nclips300_batch2.json

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,617e8d7c-8764-4508-ba9b-c993282c70cd,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,None,True,True,True,None,3
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,None,True,True,True,None,3
2,81221073-c095-4129-b095-97f3d6e4a6b1,412763ce-9a81-4bb7-b713-80fe2713e1a8,skipped_fully_cached,None,True,True,True,None,3
3,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,0aec2b0c-18e1-453b-a6ed-e484698d41df,skipped_fully_cached,None,True,True,True,None,3
4,5ab23181-c60a-4478-9085-2a450a24b65b,65ffa888-a7c8-43a7-afd8-13b2df7f7f04,skipped_fully_cached,None,True,True,True,None,3
5,99ddfcb3-bb2a-45d3-903e-d7e858969957,f88c7f52-dfb9-4a17-ac15-f3ec05de4f85,skipped_fully_cached,None,True,True,True,None,3
6,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,f88c7f52-dfb9-4a17-ac15-f3ec05de4f85,skipped_fully_cached,None,True,True,True,None,3
7,5771acd7-c7a9-4350-8064-7763bf111149,975427a5-9d66-4bf6-aa94-1266297cc5e6,skipped_fully_cached,None,True,True,True,None,3
8,aef0725a-1005-4a17-ad33-4522808c3a17,b1543ea3-e86b-4545-9195-f1bf83e02b41,skipped_fully_cached,None,True,True,True,None,3
9,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,5cab806a-3794-4578-94f2-33c3093151d1,skipped_fully_cached,None,True,True,True,None,3
10,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,7adc004f-2836-4e00-86c3-727883286c3c,skipped_fully_cached,None,True,True,True,None,3
11,49b8d3e9-de69-49cf-819b-5af1fd69b732,7adc004f-2836-4e00-86c3-727883286c3c,skipped_fully_cached,None,True,True,True,None,3
12,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,7adc004f-2836-4e00-86c3-727883286c3c,skipped_fully_cached,None,True,True,True,None,3
13,eb0359b2-72f1-40ff-ba22-64bb818d1f48,59764b58-1523-48b3-88d2-9fc07880e597,skipped_fully_cached,None,True,True,True,None,3
14,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,ec41b9e1-dbf9-45c3-bf88-4b250873cad0,skipped_fully_cached,None,True,True,True,None,3
15,6673c838-2765-4b41-81fd-9a01deba1d0b,b884e44c-07d8-426e-8356-1be4905c2675,skipped_fully_cached,None,True,True,True,None,5
16,ba50504a-93ad-46bc-8433-0c1f89d21f78,8d44b13c-464d-498b-b639-dfede202872c,skipped_fully_cached,None,True,True,True,None,6
17,1b0aed98-785d-4471-ad38-940ca8673030,20525d50-586a-4792-bfdb-fd941ee64ea9,skipped_fully_cached,None,True,True,True,None,3
18,8450f847-5946-4199-9bc7-9d08c93c0141,20525d50-586a-4792-bfdb-fd941ee64ea9,skipped_fully_cached,None,True,True,True,None,3
19,b47da6e2-cb60-4fd4-9705-5eb3af05877d,20525d50-586a-4792-bfdb-fd941ee64ea9,skipped_fully_cached,None,True,True,True,None,3
20,21af903a-6c19-4854-afe0-009d81849867,97ba861b-605c-4942-8e15-95953a3032e1,skipped_fully_cached,None,True,True,True,None,3
21,d2e61675-14b6-481f-9206-34bbc1375ea6,c8d88b2c-d6ed-4ef3-a7a1-e3b3dac0550f,skipped_fully_cached,None,True,True,True,None,3
22,d0bae6e6-356e-459d-b3dc-bc53c710611b,41309ada-0a81-47b2-bdd1-453a178db18a,skipped_fully_cached,None,True,True,True,None,6
23,8530a122-787b-4e95-b848-5543e8d772c7,41309ada-0a81-47b2-bdd1-453a178db18a,skipped_fully_cached,None,True,True,True,None,3
24,23b8f734-c2db-4c55-9bca-cbe557d4abd4,412e4659-153e-4662-b3b6-41559f562d54,skipped_fully_cached,None,True,True,True,None,3
25,5333a996-877f-4e30-ba79-631131744a4b,412e4659-153e-4662-b3b6-41559f562d54,skipped_fully_cached,None,True,True,True,None,3
26,ccc4408f-8420-481d-b5aa-0c0013e3a109,79c62f24-488e-4a69-8220-3b20cb4bf72b,skipped_fully_cached,None,True,True,True,None,3
27,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,79c62f24-488e-4a69-8220-3b20cb4bf72b,skipped_fully_cached,None,True,True,True,None,3
28,36335d72-a5d7-4878-9f5b-9ff9635815b8,79c62f24-488e-4a69-8220-3b20cb4bf72b,skipped_fully_cached,None,True,True,True,None,3
29,c7fd4879-e196-4195-8fa8-d4430ae90a9a,79c62f24-488e-4a69-8220-3b20cb4bf72b,skipped_fully_cached,None,True,True,True,None,3
30,9737f5fb-d4b7-420c-98ee-471ec872c808,57e88d87-257e-434d-953e-6025367e99fe,skipped_fully_cached,None,True,True,True,None,3
31,f91c7008-f21c-4047-bfc1-d937787665e5,57e88d87-257e-434d-953e-6025367e99fe,skipped_fully_cached,None,True,True,True,None,3
32,0723c03f-263c-442d-9d9b-d0fef0cef0e4,57e88d87-257e-434d-953e-6025367e99fe,skipped_fully_cached,None,True,True,True,None,3
33,87499bfb-3dcf-46fa-aef3-204fcc0496e0,57e88d87-257e-434d-953e-6025367e99fe,skipped_fully_cached,None,True,True,True,None,6
34,248cf237-d8dc-42d1-ae41-017221765031,57e88d87-257e-434d-953e-6025367e99fe,skipped_fully_cached,None,True,True,True,None,3
35,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,bc3d4b3a-7261-44aa-9bc2-df6d2584069a,skipped_fully_cached,None,True,True,True,None,3
36,260ec80b-f26a-4646-afc5-616481889643,8fe9742a-355f-4503-9652-0a9ebaf0ed42,skipped_fully_cached,None,True,True,True,None,3
37,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,8fe9742a-355f-4503-9652-0a9ebaf0ed42,skipped_fully_cached,None,True,True,True,None,3
38,714ee146-e130-439d-89ff-6876efe62b07,223a838a-385b-46c8-b750-b590580e6cab,skipped_fully_cached,None,True,True,True,None,3
39,64cc6d12-f613-452f-b56b-451f395c9c10,59d95c0d-7d56-4c28-82ef-9b4cb2a6e63e,skipped_fully_cached,None,True,True,True,None,3
40,d68ae83a-903a-448e-bc7e-7279755e0243,952f40df-b1d7-4562-afe4-2a4ff569e949,skipped_fully_cached,None,True,True,True,None,3
41,368755d7-886a-4b05-85f4-e3b3785a8d14,952f40df-b1d7-4562-afe4-2a4ff569e949,skipped_fully_cached,None,True,True,True,None,3
42,72e90719-c2b8-4b17-b120-e904dbbf1184,e303a071-7d0b-40e7-b8df-dea6e79ad7e8,skipped_fully_cached,None,True,True,True,None,3
43,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,e303a071-7d0b-40e7-b8df-dea6e79ad7e8,skipped_fully_cached,None,True,True,True,None,3
44,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,e303a071-7d0b-40e7-b8df-dea6e79ad7e8,skipped_fully_cached,None,True,True,True,None,6
45,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,e303a071-7d0b-40e7-b8df-dea6e79ad7e8,skipped_fully_cached,None,True,True,True,None,3
46,860b4b8a-7219-433b-8947-cd8b93973b07,56bfc9ac-00f4-41ae-8112-3851c538d9b9,skipped_fully_cached,None,True,True,True,None,3
47,ce57cce9-c6c4-4e07-be46-a84b29e7462c,56bfc9ac-00f4-41ae-8112-3851c538d9b9,skipped_fully_cached,None,True,True,True,None,3
48,1ffc605c-c5f5-42d3-9897-6e9319675497,56bfc9ac-00f4-41ae-8112-3851c538d9b9,skipped_fully_cached,None,True,True,True,None,6
49,635733d7-8863-47b0-a7e2-4a0365813723,f77f437c-4e60-43ef-a5e1-ce3881409455,skipped_fully_cached,None,True,True,True,None,3
50,72eee417-f3cb-47dc-8266-24277c2307e2,f324ccbc-bef5-4d68-9722-cc99bdaaa660,skipped_fully_cached,None,True,True,True,None,6
51,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,f324ccbc-bef5-4d68-9722-cc99bdaaa660,skipped_fully_cached,None,True,True,True,None,3
52,6f7f5312-db3f-42db-98c0-f650a3899568,2c5a603d-b9e8-45b2-8ff7-f079f6f402fc,skipped_fully_cached,None,True,True,True,None,2
53,f0a86b75-fd8e-43dd-95ee-401717b94f70,f265c11a-5b65-49e2-b77a-8735f2aa9a48,skipped_fully_cached,None,True,True,True,None,3
54,d87774db-a324-4440-aa60-b39fe3276b77,f265c11a-5b65-49e2-b77a-8735f2aa9a48,skipped_fully_cached,None,True,True,True,None,3
55,55200058-9bf1-48a4-ac7f-a279f75fcaf1,f265c11a-5b65-49e2-b77a-8735f2aa9a48,skipped_fully_cached,None,True,True,True,None,3
56,d111f736-d02a-43f4-8968-2b6631138d84,f681f510-cd33-48e3-bc10-4a8f2a518495,skipped_fully_cached,None,True,True,True,None,6
57,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,fb9fda68-f264-465d-9208-19876f5ef90f,skipped_fully_cached,None,True,True,True,None,3
58,9e9f05e9-5dbe-439b-970d-acb13ab98f10,fb9fda68-f264-465d-9208-19876f5ef90f,skipped_fully_cached,None,True,True,True,None,3
59,bed399ed-44af-438d-ab3f-12739adac348,1ea95f25-81f9-46b1-b7a1-c4ca58251c6f,skipped_fully_cached,None,True,True,True,None,6

status
skipped_fully_cached    60
Name: count, dtype: int64

In [27]:
# ---------------- 17. Switch to batch 3 ----------------

BATCH_ID = 3

all_workplan_clips = list(workplan.keys())

start_idx = BATCH_ID * BATCH_SIZE_CLIPS
end_idx = min(start_idx + BATCH_SIZE_CLIPS, len(all_workplan_clips))

batch_clip_uids = all_workplan_clips[start_idx:end_idx]

print("Total workplan clips:", len(all_workplan_clips))
print("Batch ID:", BATCH_ID)
print("Batch start:", start_idx)
print("Batch end:", end_idx)
print("Batch clips:", len(batch_clip_uids))
print("First 5 batch clips:", batch_clip_uids[:5])

Total workplan clips: 300
Batch ID: 3
Batch start: 180
Batch end: 240
Batch clips: 60
First 5 batch clips: ['cafcebbb-d1c1-439b-8228-3bd95b8d3b7f', '16fce853-9528-4c39-9f88-b0c61f30d01d', '9b9b7994-8a7a-43ac-9382-744664ee3e66', 'fe71b934-322a-45a1-862c-cd7c2db2c354', '8f1770e5-612c-4047-a7b7-a6157460bc24']

In [28]:
# ---------------- 18. Check cache status for batch 3 ----------------

batch_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in batch_clip_uids]
)

display(batch_cache_status_df.head())

print("Batch clips:", len(batch_cache_status_df))
print("Index caches exist:", batch_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", batch_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", batch_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", batch_cache_status_df["fully_cached"].sum())

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,False,False,False,False
1,16fce853-9528-4c39-9f88-b0c61f30d01d,False,False,False,False
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,False,False,False,False
3,fe71b934-322a-45a1-862c-cd7c2db2c354,False,False,False,False
4,8f1770e5-612c-4047-a7b7-a6157460bc24,False,False,False,False

Batch clips: 60
Index caches exist: 2
Query caches exist: 2
Query metadata exists: 2
Fully cached: 2

In [30]:
# ---------------- 19. Run full batch 3 ----------------

batch_manifest_df = run_preprocess_batch_for_cache(
    batch_clip_uids=batch_clip_uids,
    batch_id=BATCH_ID,
    force_recompute=False,
)

display(batch_manifest_df)
display(batch_manifest_df["status"].value_counts(dropna=False))

Preprocess batch 3:   0%|          | 0/60 [00:00<?, ?it/s]

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
Finished clip cafcebbb-d1c1-439b-8228-3bd95b8d3b7f | status=skipped_fully_cached | errors=0
Finished clip 16fce853-9528-4c39-9f88-b0c61f30d01d | status=skipped_fully_cached | errors=0
Finished clip 9b9b7994-8a7a-43ac-9382-744664ee3e66 | status=skipped_fully_cached | errors=0
Finished clip fe71b934-322a-45a1-862c-cd7c2db2c354 | status=skipped_fully_cached | errors=0
Finished clip 8f1770e5-612c-4047-a7b7-a6157460bc24 | status=skipped_fully_cached | errors=0
Finished clip f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887 | status=skipped_fully_cached | errors=0
Finished clip 63a1c028-3919-462b-9c97-9a22c5296eae | status=skipped_fully_cached | errors=0
Finished clip 6bfb9000-73c2-4698-8757-889251a4b5e9 | status=skipped_fully_cached | errors=0
Finished clip 02089b3c-2c7a-430b-9c7c-9c3f39249ec7 | status=skipped_fully_cached | errors=0
Finished clip f54175da-19e5-4ee7-97b3-75baa247b713 | status=skipped_fully_cached | errors=0
Finished clip b27d698c-ce47-47ed-86e7-652cef7d3e2c | status=skipped_fully_cached | errors=0
Finished clip c0d616c8-fc59-40b7-aafe-f54c2d60a236 | status=skipped_fully_cached | errors=0
Finished clip 74c966c9-0a8c-4e65-8811-75737d3e9c21 | status=skipped_fully_cached | errors=0
Finished clip 88f358c1-b11a-4868-aaf4-e1cb273c4b8a | status=skipped_fully_cached | errors=0
Finished clip 7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de | status=skipped_fully_cached | errors=0
Finished clip 90288170-a577-48e6-afe6-014673ae8723 | status=skipped_fully_cached | errors=0
Finished clip 6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e | status=skipped_fully_cached | errors=0
Finished clip 0c2cc98f-0b4f-4820-8687-e12483cf4d0a | status=skipped_fully_cached | errors=0
Finished clip f22ddd51-999f-44b8-9d53-319982dda0a7 | status=skipped_fully_cached | errors=0
Finished clip 17e7a80c-b5ca-435f-a29e-0d026fcf2e96 | status=skipped_fully_cached | errors=0
Finished clip d444eac6-5d1b-4198-97d8-e3ec96dae37e | status=skipped_fully_cached | errors=0
Finished clip 2b3864c6-50d7-46ff-9ab6-3d6831f741cc | status=skipped_fully_cached | errors=0
Finished clip 3482d793-9492-49fa-b98a-770b116e8767 | status=skipped_fully_cached | errors=0
Finished clip f4240b1c-c260-4354-a005-cfa8c8353f90 | status=skipped_fully_cached | errors=0
Finished clip 2ae935a5-3266-47e0-884d-f8b8acb5ed1c | status=skipped_fully_cached | errors=0
Finished clip 2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0 | status=skipped_fully_cached | errors=0
Finished clip 85b01a98-245e-4b63-bff8-4545aedaf916 | status=skipped_fully_cached | errors=0
Finished clip 898e6cc6-082c-483d-ad84-12ec417ca440 | status=skipped_fully_cached | errors=0
Finished clip dbfb3374-94ef-47cb-b179-99ad19e55ff1 | status=skipped_fully_cached | errors=0
Finished clip a879680b-7957-45fb-8786-cdc8e998f01d | status=skipped_fully_cached | errors=0
Finished clip 43ecb12f-8b33-416f-8c22-5c4544ed2370 | status=skipped_fully_cached | errors=0
Finished clip b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3 | status=skipped_fully_cached | errors=0
Finished clip 2b887413-c1ef-4257-9524-0be974fd47a8 | status=skipped_fully_cached | errors=0
Finished clip b370b4cc-0a46-43a8-9b26-1aba0f71ee09 | status=skipped_fully_cached | errors=0
Finished clip 43f1faaa-6452-4125-a702-f319fdafcc4f | status=skipped_fully_cached | errors=0
Finished clip fe3000d6-d857-4cd1-a927-0a91a7f9616e | status=skipped_fully_cached | errors=0
Finished clip 9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3 | status=skipped_fully_cached | errors=0
Finished clip 72154f42-399c-4f95-a667-e26528d1f52a | status=skipped_fully_cached | errors=0
Finished clip 1d2b62ed-fc94-4fb0-b547-8c50533b0b29 | status=skipped_fully_cached | errors=0
Finished clip 77e3af3b-a5ec-420c-a3bc-a2aff4934ce3 | status=skipped_fully_cached | errors=0
Finished clip 8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189 | status=skipped_fully_cached | errors=0
Finished clip d4196bb5-daf8-49f7-9010-bcc5797583d3 | status=skipped_fully_cached | errors=0
Finished clip 50df286e-fe12-434e-95c6-d8160787512b | status=skipped_fully_cached | errors=0
Finished clip 3e95b70a-e2b1-4d6f-a229-b07d4f8eadea | status=skipped_fully_cached | errors=0
Finished clip f1350714-1aa5-421b-a268-690110ca9c06 | status=skipped_fully_cached | errors=0
Finished clip 150bc185-821c-487f-b39c-4c5a0d52467d | status=skipped_fully_cached | errors=0
Finished clip 21e4b10c-e1c2-4b11-bee3-9528e61b56e3 | status=skipped_fully_cached | errors=0
Finished clip 92207d1e-5cc6-41b5-bbd1-ed679aa997bd | status=skipped_fully_cached | errors=0
Finished clip 785960e0-5f8e-41eb-9290-27a755dad3ef | status=skipped_fully_cached | errors=0
Finished clip 0df1db1f-40a0-4139-b120-9a1c741f571c | status=skipped_fully_cached | errors=0
Finished clip 50e73fa7-8ca7-41a3-a326-bc0b4a2f1482 | status=skipped_fully_cached | errors=0
Finished clip d029947a-03c7-4f43-86ef-8067e172b410 | status=skipped_fully_cached | errors=0
Finished clip db6e91d9-3006-46dd-af29-b74f725fe284 | status=skipped_fully_cached | errors=0
Finished clip c16cc2f1-a2a8-42f4-82f3-6867f9b6da12 | status=skipped_fully_cached | errors=0
Finished clip 70d3a98e-132b-4446-aa99-cab279318dc8 | status=skipped_fully_cached | errors=0
Finished clip 48d9f08a-abe2-471f-9c2b-4d8e67f33d59 | status=skipped_fully_cached | errors=0
Finished clip 925b50c0-c5d7-48dc-877a-c5a2593b70d6 | status=skipped_fully_cached | errors=0
Finished clip a928aa57-8047-4156-8851-f94f75d57f70 | status=skipped_fully_cached | errors=0
Finished clip 3d1bc6e6-e445-4748-9b08-727a1ce2e697 | status=skipped_fully_cached | errors=0
Building index embedding cache for clip: 18dad6e7-5969-4573-a1b3-f4ccfc53c350
Video already exists locally: /home/jupyter/tmp/retrieval_work/6e0c294c-d634-4804-8d41-cd6e9d79f0b9.mp4
Finished clip 18dad6e7-5969-4573-a1b3-f4ccfc53c350 | status=error | errors=1

Finished batch: 3
Total clips: 60
Success: 0
Skipped fully cached: 59
Errors: 1
Saved manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch3.csv
Saved errors to: /home/jupyter/results/retrieval_subset/preprocess_errors_nclips300_batch3.json

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
1,16fce853-9528-4c39-9f88-b0c61f30d01d,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,1938c632-f575-49dd-8ae0-e48dbb467920,skipped_fully_cached,NaN,True,True,True,NaN,3.0
3,fe71b934-322a-45a1-862c-cd7c2db2c354,45ef4272-053f-46f2-9343-1709be6d188c,skipped_fully_cached,NaN,True,True,True,NaN,3.0
4,8f1770e5-612c-4047-a7b7-a6157460bc24,45ef4272-053f-46f2-9343-1709be6d188c,skipped_fully_cached,NaN,True,True,True,NaN,3.0
5,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,2763dbfc-8488-4264-b31f-4b12096c4c4b,skipped_fully_cached,NaN,True,True,True,NaN,6.0
6,63a1c028-3919-462b-9c97-9a22c5296eae,c1b75b09-d3e8-4de4-996f-6c49d0efcd10,skipped_fully_cached,NaN,True,True,True,NaN,3.0
7,6bfb9000-73c2-4698-8757-889251a4b5e9,8672b38a-7682-4244-ad7a-a336c81c2d0e,skipped_fully_cached,NaN,True,True,True,NaN,3.0
8,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,18a3840b-7463-43c4-9aa9-b1d8e486fa84,skipped_fully_cached,NaN,True,True,True,NaN,3.0
9,f54175da-19e5-4ee7-97b3-75baa247b713,115774b6-534d-444f-b7aa-d1b834eb0ee7,skipped_fully_cached,NaN,True,True,True,NaN,6.0
10,b27d698c-ce47-47ed-86e7-652cef7d3e2c,115774b6-534d-444f-b7aa-d1b834eb0ee7,skipped_fully_cached,NaN,True,True,True,NaN,6.0
11,c0d616c8-fc59-40b7-aafe-f54c2d60a236,115774b6-534d-444f-b7aa-d1b834eb0ee7,skipped_fully_cached,NaN,True,True,True,NaN,6.0
12,74c966c9-0a8c-4e65-8811-75737d3e9c21,115774b6-534d-444f-b7aa-d1b834eb0ee7,skipped_fully_cached,NaN,True,True,True,NaN,6.0
13,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,115774b6-534d-444f-b7aa-d1b834eb0ee7,skipped_fully_cached,NaN,True,True,True,NaN,6.0
14,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,392b632b-40b1-4fb0-92cf-dc17044472ca,skipped_fully_cached,NaN,True,True,True,NaN,3.0
15,90288170-a577-48e6-afe6-014673ae8723,d27d4db8-c1c5-46e0-af9f-bc9aa24f1d4c,skipped_fully_cached,NaN,True,True,True,NaN,3.0
16,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,516c9abc-dbf3-4f87-b78e-db0ab9d657ea,skipped_fully_cached,NaN,True,True,True,NaN,3.0
17,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,516c9abc-dbf3-4f87-b78e-db0ab9d657ea,skipped_fully_cached,NaN,True,True,True,NaN,6.0
18,f22ddd51-999f-44b8-9d53-319982dda0a7,7b5fafdb-136a-4722-84a4-cffb213a224a,skipped_fully_cached,NaN,True,True,True,NaN,3.0
19,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,7b5fafdb-136a-4722-84a4-cffb213a224a,skipped_fully_cached,NaN,True,True,True,NaN,3.0
20,d444eac6-5d1b-4198-97d8-e3ec96dae37e,eb81442c-a322-49ea-b243-a39d2e288b9b,skipped_fully_cached,NaN,True,True,True,NaN,3.0
21,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,b2a1b8ca-99d6-4f26-953f-426e89649e90,skipped_fully_cached,NaN,True,True,True,NaN,3.0
22,3482d793-9492-49fa-b98a-770b116e8767,b2a1b8ca-99d6-4f26-953f-426e89649e90,skipped_fully_cached,NaN,True,True,True,NaN,3.0
23,f4240b1c-c260-4354-a005-cfa8c8353f90,571265e5-c7b7-4313-9386-fa8655b23706,skipped_fully_cached,NaN,True,True,True,NaN,3.0
24,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,d340e569-12d3-42ef-a56b-a9a25c37ef95,skipped_fully_cached,NaN,True,True,True,NaN,3.0
25,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,cfb6d2fa-3020-48f1-8c6e-b5120e9b55f8,skipped_fully_cached,NaN,True,True,True,NaN,3.0
26,85b01a98-245e-4b63-bff8-4545aedaf916,a7a3be02-2f1f-474d-abc8-73d85c5b3b75,skipped_fully_cached,NaN,True,True,True,NaN,3.0
27,898e6cc6-082c-483d-ad84-12ec417ca440,b8c58079-3314-46df-afee-766ac64ce1de,skipped_fully_cached,NaN,True,True,True,NaN,3.0
28,dbfb3374-94ef-47cb-b179-99ad19e55ff1,b8c58079-3314-46df-afee-766ac64ce1de,skipped_fully_cached,NaN,True,True,True,NaN,6.0
29,a879680b-7957-45fb-8786-cdc8e998f01d,4f2d8f79-e0c1-4fa1-96fe-1de9653189a2,skipped_fully_cached,NaN,True,True,True,NaN,6.0
30,43ecb12f-8b33-416f-8c22-5c4544ed2370,e456df39-0980-4b2c-92e8-b03193a6e90f,skipped_fully_cached,NaN,True,True,True,NaN,3.0
31,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,e456df39-0980-4b2c-92e8-b03193a6e90f,skipped_fully_cached,NaN,True,True,True,NaN,3.0
32,2b887413-c1ef-4257-9524-0be974fd47a8,04994ce8-9d47-44d6-a7b0-42b395e69390,skipped_fully_cached,NaN,True,True,True,NaN,6.0
33,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,e6010cdf-bb36-4886-9ebf-68678877758a,skipped_fully_cached,NaN,True,True,True,NaN,6.0
34,43f1faaa-6452-4125-a702-f319fdafcc4f,1a58c3e1-e04c-40eb-974b-379773a18736,skipped_fully_cached,NaN,True,True,True,NaN,3.0
35,fe3000d6-d857-4cd1-a927-0a91a7f9616e,53da674a-089d-428a-a719-e322b2de002b,skipped_fully_cached,NaN,True,True,True,NaN,3.0
36,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,53da674a-089d-428a-a719-e322b2de002b,skipped_fully_cached,NaN,True,True,True,NaN,6.0
37,72154f42-399c-4f95-a667-e26528d1f52a,53da674a-089d-428a-a719-e322b2de002b,skipped_fully_cached,NaN,True,True,True,NaN,3.0
38,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,53da674a-089d-428a-a719-e322b2de002b,skipped_fully_cached,NaN,True,True,True,NaN,6.0
39,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,86343e9e-b932-41d3-ad6f-83f2c2fe5486,skipped_fully_cached,NaN,True,True,True,NaN,6.0
40,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,e9cf88ec-cf09-40aa-8ec7-daece398830a,skipped_fully_cached,NaN,True,True,True,NaN,3.0
41,d4196bb5-daf8-49f7-9010-bcc5797583d3,3804430e-a07a-4817-a5d2-9cc3e948d02a,skipped_fully_cached,NaN,True,True,True,NaN,3.0
42,50df286e-fe12-434e-95c6-d8160787512b,3534864b-2289-4aaf-b3ed-10eeeee7acd2,skipped_fully_cached,NaN,True,True,True,NaN,3.0
43,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,3534864b-2289-4aaf-b3ed-10eeeee7acd2,skipped_fully_cached,NaN,True,True,True,NaN,3.0
44,f1350714-1aa5-421b-a268-690110ca9c06,8d84ee2b-5dcb-4311-9769-a52e7b68d9e1,skipped_fully_cached,NaN,True,True,True,NaN,6.0
45,150bc185-821c-487f-b39c-4c5a0d52467d,8d84ee2b-5dcb-4311-9769-a52e7b68d9e1,skipped_fully_cached,NaN,True,True,True,NaN,6.0
46,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,e250017c-16ff-4825-9c30-160f391e1549,skipped_fully_cached,NaN,True,True,True,NaN,3.0
47,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,e250017c-16ff-4825-9c30-160f391e1549,skipped_fully_cached,NaN,True,True,True,NaN,6.0
48,785960e0-5f8e-41eb-9290-27a755dad3ef,a2c3a84e-ae75-4e72-8a52-64511ed67080,skipped_fully_cached,NaN,True,True,True,NaN,3.0
49,0df1db1f-40a0-4139-b120-9a1c741f571c,43e5e6ea-c3ab-46af-b00a-2b04d38e4741,skipped_fully_cached,NaN,True,True,True,NaN,3.0
50,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,fbc425c4-def6-49a7-8b88-5d5d00b5524e,skipped_fully_cached,NaN,True,True,True,NaN,6.0
51,d029947a-03c7-4f43-86ef-8067e172b410,fbc425c4-def6-49a7-8b88-5d5d00b5524e,skipped_fully_cached,NaN,True,True,True,NaN,3.0
52,db6e91d9-3006-46dd-af29-b74f725fe284,0066ab25-04ad-41b2-89ab-283d2bfa1c4b,skipped_fully_cached,NaN,True,True,True,NaN,6.0
53,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,a6d45e95-8dc0-4932-83bf-ec53e265a16a,skipped_fully_cached,NaN,True,True,True,NaN,6.0
54,70d3a98e-132b-4446-aa99-cab279318dc8,182dffe9-d2bf-4a7d-b1d8-137470f0143d,skipped_fully_cached,NaN,True,True,True,NaN,3.0
55,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,eb10e128-1298-4a29-9bde-788c36cc656c,skipped_fully_cached,NaN,True,True,True,NaN,3.0
56,925b50c0-c5d7-48dc-877a-c5a2593b70d6,e8283c8f-ecc0-448a-84d2-9f16160d7a4b,skipped_fully_cached,NaN,True,True,True,NaN,3.0
57,a928aa57-8047-4156-8851-f94f75d57f70,e8283c8f-ecc0-448a-84d2-9f16160d7a4b,skipped_fully_cached,NaN,True,True,True,NaN,3.0
58,3d1bc6e6-e445-4748-9b08-727a1ce2e697,9954bb90-a2fd-444f-bc5b-437058a7db07,skipped_fully_cached,NaN,True,True,True,NaN,3.0
59,18dad6e7-5969-4573-a1b3-f4ccfc53c350,6e0c294c-d634-4804-8d41-cd6e9d79f0b9,error,"OSError(28, 'No space left on device')",False,False,False,NaN,NaN

status
skipped_fully_cached    59
error                    1
Name: count, dtype: int64

In [31]:
# ---------------- 20. Switch to batch 4 ----------------

BATCH_ID = 4

all_workplan_clips = list(workplan.keys())

start_idx = BATCH_ID * BATCH_SIZE_CLIPS
end_idx = min(start_idx + BATCH_SIZE_CLIPS, len(all_workplan_clips))

batch_clip_uids = all_workplan_clips[start_idx:end_idx]

print("Total workplan clips:", len(all_workplan_clips))
print("Batch ID:", BATCH_ID)
print("Batch start:", start_idx)
print("Batch end:", end_idx)
print("Batch clips:", len(batch_clip_uids))
print("First 5 batch clips:", batch_clip_uids[:5])

Total workplan clips: 300
Batch ID: 4
Batch start: 240
Batch end: 300
Batch clips: 60
First 5 batch clips: ['cc994557-a65b-48a9-94c6-122ede470347', '4a491385-b165-49ec-a23b-7b0ed26737f9', 'dc3ba39f-62f4-480b-a187-ca723c8666bd', 'bc01d0dd-be04-474e-9fc6-de83292a5062', 'bcd1ea04-bde8-4769-acb4-3d504183cbf2']

In [32]:
# ---------------- 21. Check cache status for batch 4 ----------------

batch_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in batch_clip_uids]
)

display(batch_cache_status_df.head())

print("Batch clips:", len(batch_cache_status_df))
print("Index caches exist:", batch_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", batch_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", batch_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", batch_cache_status_df["fully_cached"].sum())

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,cc994557-a65b-48a9-94c6-122ede470347,False,False,False,False
1,4a491385-b165-49ec-a23b-7b0ed26737f9,False,False,False,False
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,False,False,False,False
3,bc01d0dd-be04-474e-9fc6-de83292a5062,False,False,False,False
4,bcd1ea04-bde8-4769-acb4-3d504183cbf2,False,False,False,False

Batch clips: 60
Index caches exist: 3
Query caches exist: 3
Query metadata exists: 3
Fully cached: 3

In [36]:
# ---------------- 22. Run final batch 4 ----------------

batch_manifest_df = run_preprocess_batch_for_cache(
    batch_clip_uids=batch_clip_uids,
    batch_id=BATCH_ID,
    force_recompute=False,
)

display(batch_manifest_df)
display(batch_manifest_df["status"].value_counts(dropna=False))

Preprocess batch 4:   0%|          | 0/60 [00:00<?, ?it/s]

Finished clip cc994557-a65b-48a9-94c6-122ede470347 | status=skipped_fully_cached | errors=0
Finished clip 4a491385-b165-49ec-a23b-7b0ed26737f9 | status=skipped_fully_cached | errors=0
Finished clip dc3ba39f-62f4-480b-a187-ca723c8666bd | status=skipped_fully_cached | errors=0
Finished clip bc01d0dd-be04-474e-9fc6-de83292a5062 | status=skipped_fully_cached | errors=0
Finished clip bcd1ea04-bde8-4769-acb4-3d504183cbf2 | status=skipped_fully_cached | errors=0
Finished clip cf82756f-8e87-443a-972c-405b25858e78 | status=skipped_fully_cached | errors=0
Finished clip 2ddf340f-de44-4f5d-9994-1e0f7db05caf | status=skipped_fully_cached | errors=0
Finished clip 7380c46e-cb33-4d49-bf73-a7bfe57c3feb | status=skipped_fully_cached | errors=0
Finished clip f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2 | status=skipped_fully_cached | errors=0
Finished clip 4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9 | status=skipped_fully_cached | errors=0
Finished clip 17043256-42c5-4e4f-846b-7923afe3ead4 | status=skipped_fully_cached | errors=0
Finished clip 72479834-1994-44a8-a9a5-ae13b3417307 | status=skipped_fully_cached | errors=0
Finished clip a408cff1-1387-421f-aad6-7480899a4fe0 | status=skipped_fully_cached | errors=0
Finished clip d3b18a63-002a-4538-adef-21ac1f476704 | status=skipped_fully_cached | errors=0
Finished clip 00e1c569-6c15-4447-8dd4-dfbe1f79dcdc | status=skipped_fully_cached | errors=0
Finished clip 5c87b9e2-7d54-469f-96ff-02ff7493c6ae | status=skipped_fully_cached | errors=0
Finished clip 38dc82c8-d59a-4ef9-818c-c3affb046e17 | status=skipped_fully_cached | errors=0
Finished clip 83e54fdc-6336-439c-b8a5-44682989a329 | status=skipped_fully_cached | errors=0
Finished clip 045dafcd-1ae7-443c-9a55-cd6b390372b3 | status=skipped_fully_cached | errors=0
Finished clip 5aa0d7aa-21af-4bfc-a204-f05554a3933e | status=skipped_fully_cached | errors=0
Finished clip 20a6cd02-f686-46c3-b1e3-f3376a99ddc6 | status=skipped_fully_cached | errors=0
Finished clip b2dcb4b2-7a5e-4d68-aec9-41ec96915168 | status=skipped_fully_cached | errors=0
Finished clip b0612ea7-11f9-486e-a4aa-e0f8ba67e2df | status=skipped_fully_cached | errors=0
Finished clip 7816c769-612c-4256-9bac-885a57ec513f | status=skipped_fully_cached | errors=0
Finished clip 19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5 | status=skipped_fully_cached | errors=0
Finished clip f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af | status=skipped_fully_cached | errors=0
Finished clip f0861378-ff5f-47d8-b1b3-59cf5b07acc7 | status=skipped_fully_cached | errors=0
Finished clip 1e938429-6376-4bc8-a145-7225f885e026 | status=skipped_fully_cached | errors=0
Finished clip c96304a7-f17c-49bf-be81-a95450fb0358 | status=skipped_fully_cached | errors=0
Finished clip 5a7efdba-6701-4aaa-bff6-fbab6b293ed9 | status=skipped_fully_cached | errors=0
Finished clip 39b791e1-7e1c-4c3e-bd68-e6598ef8694b | status=skipped_fully_cached | errors=0
Finished clip daee0288-b01a-4fc4-bcd8-3884846d829d | status=skipped_fully_cached | errors=0
Finished clip fa43490f-22c7-44db-868f-4998791069ac | status=skipped_fully_cached | errors=0
Finished clip 61f93683-2f3d-4d44-867d-c980d9316775 | status=skipped_fully_cached | errors=0
Finished clip ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a | status=skipped_fully_cached | errors=0
Finished clip f9671fc0-7e56-4e98-842a-dfbbd99d385f | status=skipped_fully_cached | errors=0
Finished clip ad9083b3-9b0b-4c27-a941-38f57be13edf | status=skipped_fully_cached | errors=0
Finished clip 3970c9a9-e6ca-4675-866c-2e21913eacb2 | status=skipped_fully_cached | errors=0
Finished clip 0ba8203a-5825-464b-8d95-32a24e84acf0 | status=skipped_fully_cached | errors=0
Finished clip 0432e5c6-d2e3-4729-bf1e-0ea8803687ee | status=skipped_fully_cached | errors=0
Finished clip b391003e-a302-43a0-a451-75cc8b4ccede | status=skipped_fully_cached | errors=0
Finished clip 09dde7aa-58bd-402e-a107-32c0f33e7115 | status=skipped_fully_cached | errors=0
Finished clip 4eddd9cf-ce91-4273-8184-a88e7255a65e | status=skipped_fully_cached | errors=0
Finished clip 9b15d755-f374-4731-8370-26847aadc08b | status=skipped_fully_cached | errors=0
Finished clip 2c9b9f23-8907-44a0-89e6-8f29d7b05828 | status=skipped_fully_cached | errors=0
Finished clip f052ac6f-832d-41f0-b00f-7cb85c20a15c | status=skipped_fully_cached | errors=0
Finished clip 7bb5593c-c017-4e68-aa69-0bc2bb50e2a1 | status=skipped_fully_cached | errors=0
Finished clip c552b2d7-9d27-4765-9dce-8223581c1ca7 | status=skipped_fully_cached | errors=0
Finished clip e118e100-cc06-48c5-a542-e07c44d72469 | status=skipped_fully_cached | errors=0
Finished clip a71f6663-ef4b-4283-8210-652b21b37a36 | status=skipped_fully_cached | errors=0
Finished clip 0080281f-4db1-4a49-9753-e70c41bd9bc7 | status=skipped_fully_cached | errors=0
Finished clip a051a8ce-cb33-40f8-a46e-1a3a263de18f | status=skipped_fully_cached | errors=0
Finished clip dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04 | status=skipped_fully_cached | errors=0
Finished clip b338a041-3164-4155-ae40-faa77a9fd08a | status=skipped_fully_cached | errors=0
Finished clip 3e654a1a-b706-456d-ab6d-565effcf159c | status=skipped_fully_cached | errors=0
Finished clip 0858668c-35b2-4593-acb0-f6d4a8da483d | status=skipped_fully_cached | errors=0
Finished clip b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e | status=skipped_fully_cached | errors=0
Finished clip 1004f7fe-c397-4123-bad9-e02df2e154dd | status=skipped_fully_cached | errors=0
Finished clip 6c0c2145-2b3d-48cd-a61c-e29d8541218f | status=skipped_fully_cached | errors=0
Finished clip f04d9e03-3189-4ffb-a79a-2521355905bb | status=skipped_fully_cached | errors=0

Finished batch: 4
Total clips: 60
Success: 0
Skipped fully cached: 60
Errors: 0
Saved manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch4.csv
Saved errors to: /home/jupyter/results/retrieval_subset/preprocess_errors_nclips300_batch4.json

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cc994557-a65b-48a9-94c6-122ede470347,6e0c294c-d634-4804-8d41-cd6e9d79f0b9,skipped_fully_cached,None,True,True,True,None,3
1,4a491385-b165-49ec-a23b-7b0ed26737f9,3ee7070a-fe81-49a9-97a2-902268af9985,skipped_fully_cached,None,True,True,True,None,6
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,ecc633d2-72b5-4bd0-a6a1-f1cedb21d757,skipped_fully_cached,None,True,True,True,None,3
3,bc01d0dd-be04-474e-9fc6-de83292a5062,f4f76ace-2b4b-4e7a-b380-cc08f7642223,skipped_fully_cached,None,True,True,True,None,3
4,bcd1ea04-bde8-4769-acb4-3d504183cbf2,2876b375-e848-412c-8a6f-0664cbab6a33,skipped_fully_cached,None,True,True,True,None,3
5,cf82756f-8e87-443a-972c-405b25858e78,8fec5995-c65d-4cae-adaf-45eb76956085,skipped_fully_cached,None,True,True,True,None,6
6,2ddf340f-de44-4f5d-9994-1e0f7db05caf,033c136a-7a79-4c7e-a0c3-15e4ad0a22cf,skipped_fully_cached,None,True,True,True,None,3
7,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,e191e0de-e570-4925-9cbb-e05fe1132a47,skipped_fully_cached,None,True,True,True,None,3
8,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,7b3bea48-bd62-46b7-888d-2cc6e4bbd11b,skipped_fully_cached,None,True,True,True,None,6
9,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,5cae3bb3-1e1e-4b9f-82e8-87dbaad8f73d,skipped_fully_cached,None,True,True,True,None,6
10,17043256-42c5-4e4f-846b-7923afe3ead4,262fd2ec-8eba-44d9-8082-4d0574f7a515,skipped_fully_cached,None,True,True,True,None,3
11,72479834-1994-44a8-a9a5-ae13b3417307,ee6f0404-9c97-4240-bd7b-2dcb340031d5,skipped_fully_cached,None,True,True,True,None,3
12,a408cff1-1387-421f-aad6-7480899a4fe0,0deec3a4-11da-4d65-b1dc-6de9b0f2c57a,skipped_fully_cached,None,True,True,True,None,3
13,d3b18a63-002a-4538-adef-21ac1f476704,32ccccb7-547d-4bd3-9669-d6bb71466fe4,skipped_fully_cached,None,True,True,True,None,3
14,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,50d413f2-5709-475d-8999-6135dcd7d63f,skipped_fully_cached,None,True,True,True,None,3
15,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,59f00ff2-4e01-4498-ab40-4713217686bc,skipped_fully_cached,None,True,True,True,None,6
16,38dc82c8-d59a-4ef9-818c-c3affb046e17,59f00ff2-4e01-4498-ab40-4713217686bc,skipped_fully_cached,None,True,True,True,None,3
17,83e54fdc-6336-439c-b8a5-44682989a329,624a6c0a-a4cb-4073-b501-48e4b6b679e4,skipped_fully_cached,None,True,True,True,None,3
18,045dafcd-1ae7-443c-9a55-cd6b390372b3,a65500f7-956f-486d-872a-61742acb90d8,skipped_fully_cached,None,True,True,True,None,3
19,5aa0d7aa-21af-4bfc-a204-f05554a3933e,d38f271c-53f3-4771-8c17-a5157e723067,skipped_fully_cached,None,True,True,True,None,3
20,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,63d56e4c-e454-48c2-a8f2-5bc2c34622ca,skipped_fully_cached,None,True,True,True,None,3
21,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,d88d4e54-5e5e-4c08-9a87-80958f9e4ec1,skipped_fully_cached,None,True,True,True,None,6
22,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,c1e6482e-2457-4f99-a25d-21701bed69ec,skipped_fully_cached,None,True,True,True,None,3
23,7816c769-612c-4256-9bac-885a57ec513f,8717d09f-391c-4203-8e6c-7fa1f035cdda,skipped_fully_cached,None,True,True,True,None,3
24,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,42159efd-19ef-439a-90fe-bf9bcd8169f0,skipped_fully_cached,None,True,True,True,None,3
25,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,14a05360-fcc4-4bf6-97d3-2d77bc282c84,skipped_fully_cached,None,True,True,True,None,3
26,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,6ae63a5f-09ea-47d2-9ac8-97c04927da86,skipped_fully_cached,None,True,True,True,None,3
27,1e938429-6376-4bc8-a145-7225f885e026,8383791d-2df9-4bac-89b6-4cc01df5f4d1,skipped_fully_cached,None,True,True,True,None,3
28,c96304a7-f17c-49bf-be81-a95450fb0358,6f93978d-a3d0-467d-b401-e23b3c92f3bf,skipped_fully_cached,None,True,True,True,None,6
29,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,af33167f-658d-4c19-a35e-aaaf95efd3d0,skipped_fully_cached,None,True,True,True,None,6
30,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,35d92405-7ebf-4e54-8b9a-7cce8af30a79,skipped_fully_cached,None,True,True,True,None,3
31,daee0288-b01a-4fc4-bcd8-3884846d829d,72f48fb2-90ff-4add-bd1b-7fe57fe4dc4e,skipped_fully_cached,None,True,True,True,None,3
32,fa43490f-22c7-44db-868f-4998791069ac,f41432c6-1ef3-48f6-8646-887ab70cb031,skipped_fully_cached,None,True,True,True,None,6
33,61f93683-2f3d-4d44-867d-c980d9316775,1dcc108c-8bd4-42ad-b2c5-03662be62eda,skipped_fully_cached,None,True,True,True,None,3
34,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,1dcc108c-8bd4-42ad-b2c5-03662be62eda,skipped_fully_cached,None,True,True,True,None,3
35,f9671fc0-7e56-4e98-842a-dfbbd99d385f,9abbf7f4-68f0-4f52-812f-df2a3df48f7b,skipped_fully_cached,None,True,True,True,None,3
36,ad9083b3-9b0b-4c27-a941-38f57be13edf,fdcdf464-a350-452d-9741-f6725e138192,skipped_fully_cached,None,True,True,True,None,12
37,3970c9a9-e6ca-4675-866c-2e21913eacb2,7d6d6cae-0601-485d-b900-482b4254e9f8,skipped_fully_cached,None,True,True,True,None,3
38,0ba8203a-5825-464b-8d95-32a24e84acf0,7d6d6cae-0601-485d-b900-482b4254e9f8,skipped_fully_cached,None,True,True,True,None,3
39,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,7d6d6cae-0601-485d-b900-482b4254e9f8,skipped_fully_cached,None,True,True,True,None,6
40,b391003e-a302-43a0-a451-75cc8b4ccede,8b9b9816-d6eb-4544-818e-9d59e400b80d,skipped_fully_cached,None,True,True,True,None,6
41,09dde7aa-58bd-402e-a107-32c0f33e7115,f442873e-6f2b-493f-a6db-718cd20a732a,skipped_fully_cached,None,True,True,True,None,6
42,4eddd9cf-ce91-4273-8184-a88e7255a65e,37d183ce-ba64-4ad2-8a54-ae2fb791fd38,skipped_fully_cached,None,True,True,True,None,3
43,9b15d755-f374-4731-8370-26847aadc08b,3e92e0d2-2468-47f1-bbdf-1ebe1eb736c8,skipped_fully_cached,None,True,True,True,None,3
44,2c9b9f23-8907-44a0-89e6-8f29d7b05828,2c5d38ed-012f-4732-9eb8-89beddb07641,skipped_fully_cached,None,True,True,True,None,6
45,f052ac6f-832d-41f0-b00f-7cb85c20a15c,477feff8-a1ff-4f43-b726-273ca0fa47e9,skipped_fully_cached,None,True,True,True,None,3
46,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,477feff8-a1ff-4f43-b726-273ca0fa47e9,skipped_fully_cached,None,True,True,True,None,3
47,c552b2d7-9d27-4765-9dce-8223581c1ca7,0475a0b9-9445-4083-8c6a-42f0171ff3e4,skipped_fully_cached,None,True,True,True,None,3
48,e118e100-cc06-48c5-a542-e07c44d72469,1c7426ad-b6ba-4494-897c-537dd4a201e9,skipped_fully_cached,None,True,True,True,None,6
49,a71f6663-ef4b-4283-8210-652b21b37a36,1c7426ad-b6ba-4494-897c-537dd4a201e9,skipped_fully_cached,None,True,True,True,None,6
50,0080281f-4db1-4a49-9753-e70c41bd9bc7,1c7426ad-b6ba-4494-897c-537dd4a201e9,skipped_fully_cached,None,True,True,True,None,6
51,a051a8ce-cb33-40f8-a46e-1a3a263de18f,5ab334f2-ecc8-4a05-96f8-4320225379b2,skipped_fully_cached,None,True,True,True,None,3
52,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,5ab334f2-ecc8-4a05-96f8-4320225379b2,skipped_fully_cached,None,True,True,True,None,3
53,b338a041-3164-4155-ae40-faa77a9fd08a,5ab334f2-ecc8-4a05-96f8-4320225379b2,skipped_fully_cached,None,True,True,True,None,3
54,3e654a1a-b706-456d-ab6d-565effcf159c,5ab334f2-ecc8-4a05-96f8-4320225379b2,skipped_fully_cached,None,True,True,True,None,3
55,0858668c-35b2-4593-acb0-f6d4a8da483d,702aa273-b108-4114-a3b6-a43a8386f06a,skipped_fully_cached,None,True,True,True,None,3
56,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,46937f34-8c29-4daf-93ef-966b78e161cb,skipped_fully_cached,None,True,True,True,None,3
57,1004f7fe-c397-4123-bad9-e02df2e154dd,b1b01372-64c3-4a6a-93fc-a86409f518ab,skipped_fully_cached,None,True,True,True,None,6
58,6c0c2145-2b3d-48cd-a61c-e29d8541218f,9239bf0f-db8c-4378-866d-15f302da08b5,skipped_fully_cached,None,True,True,True,None,6
59,f04d9e03-3189-4ffb-a79a-2521355905bb,99482472-b8cc-47c9-9f54-e0ff4e42182b,skipped_fully_cached,None,True,True,True,None,3

status
skipped_fully_cached    60
Name: count, dtype: int64

In [37]:
# ---------------- 23. Final manifest summary for all 5 batches ----------------

manifest_paths = [
    RESULTS_DIR / f"preprocess_manifest_nclips{N_CLIPS}_batch{i}.csv"
    for i in range(5)
]

all_manifest_dfs = []

for i, path in enumerate(manifest_paths):
    print(f"Batch {i} manifest exists:", path.exists(), "|", path)

    if path.exists():
        df_i = pd.read_csv(path)
        df_i["batch_id"] = i
        all_manifest_dfs.append(df_i)

all_manifest_df = pd.concat(all_manifest_dfs, ignore_index=True)

print("\n================ Final preprocessing summary ================")
print("Total manifest rows:", len(all_manifest_df))
print("Unique clips:", all_manifest_df["clip_uid"].nunique())

print("\nStatus counts:")
display(all_manifest_df["status"].value_counts(dropna=False))

print("\nBatch x status:")
display(
    all_manifest_df
    .groupby(["batch_id", "status"])
    .size()
    .reset_index(name="count")
)

final_manifest_path = RESULTS_DIR / f"preprocess_manifest_nclips{N_CLIPS}_all_batches.csv"
all_manifest_df.to_csv(final_manifest_path, index=False)

print("\nSaved combined manifest to:", final_manifest_path)

Batch 0 manifest exists: True | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
Batch 1 manifest exists: True | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch1.csv
Batch 2 manifest exists: True | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch2.csv
Batch 3 manifest exists: True | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch3.csv
Batch 4 manifest exists: True | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch4.csv

================ Final preprocessing summary ================
Total manifest rows: 300
Unique clips: 240

Status counts:

status
skipped_fully_cached    243
success                  56
error                     1
Name: count, dtype: int64

Batch x status:

   batch_id                status  count
0         0  skipped_fully_cached     60
1         1  skipped_fully_cached      4
2         1               success     56
3         2  skipped_fully_cached     60
4         3                 error      1
5         3  skipped_fully_cached     59
6         4  skipped_fully_cached     60

Saved combined manifest to: /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_all_batches.csv

In [38]:
# ---------------- 24. Final cache completeness check ----------------

all_300_clip_uids = list(workplan.keys())

final_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in all_300_clip_uids]
)

display(final_cache_status_df.head())

print("Total clips checked:", len(final_cache_status_df))
print("Index caches exist:", final_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", final_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", final_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", final_cache_status_df["fully_cached"].sum())

missing_cache_df = final_cache_status_df[~final_cache_status_df["fully_cached"]].copy()

print("\nMissing / incomplete cache clips:", len(missing_cache_df))
display(missing_cache_df)

final_cache_status_path = RESULTS_DIR / f"cache_status_nclips{N_CLIPS}_final.csv"
final_cache_status_df.to_csv(final_cache_status_path, index=False)

print("\nSaved final cache status to:", final_cache_status_path)

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,dfe962ab-6aa7-4888-9378-796817a30ab6,True,True,True,True
1,b157270d-c67a-41db-91ec-32bb3ec738fc,True,True,True,True
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,True,True,True,True
3,ea365183-5841-4f00-9a2e-1b81c5e09c98,True,True,True,True
4,b961eb69-cfdd-4d5c-b427-4b667fedfcda,True,True,True,True

Total clips checked: 300
Index caches exist: 299
Query caches exist: 299
Query metadata exists: 299
Fully cached: 299

Missing / incomplete cache clips: 1

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
239,18dad6e7-5969-4573-a1b3-f4ccfc53c350,False,False,False,False

Saved final cache status to: /home/jupyter/results/retrieval_subset/cache_status_nclips300_final.csv

In [17]:
print("workplan exists:", "workplan" in globals())
print("check_clip_cache_status exists:", "check_clip_cache_status" in globals())
print("preprocess_one_clip_for_cache exists:", "preprocess_one_clip_for_cache" in globals())
print("N_CLIPS:", N_CLIPS)
print("Workplan clips:", len(workplan))

workplan exists: True
check_clip_cache_status exists: True
preprocess_one_clip_for_cache exists: True
N_CLIPS: 300
Workplan clips: 300

In [18]:
# ---------------- Repair the one missing cache clip ----------------

missing_clip_uid = "18dad6e7-5969-4573-a1b3-f4ccfc53c350"

print("Before repair:")
before_status = check_clip_cache_status(missing_clip_uid)
print(before_status)

repair_result = preprocess_one_clip_for_cache(
    missing_clip_uid,
    force_recompute=False,
)

print("\nRepair result:")
print(repair_result)

print("\nAfter repair:")
after_status = check_clip_cache_status(missing_clip_uid)
print(after_status)

Before repair:
{'clip_uid': '18dad6e7-5969-4573-a1b3-f4ccfc53c350', 'index_cache_exists': False, 'query_cache_exists': False, 'query_metadata_exists': False, 'fully_cached': False}
Building index embedding cache for clip: 18dad6e7-5969-4573-a1b3-f4ccfc53c350
Video already exists locally: /home/jupyter/tmp/retrieval_work/6e0c294c-d634-4804-8d41-cd6e9d79f0b9.mp4

Extracting frames for 18dad6e7-5969-4573-a1b3-f4ccfc53c350:   0%|          | 0/300 [00:00<?, ?it/s]

Number of index frames: 300

Embedding images:   0%|          | 0/5 [00:00<?, ?it/s]

Saved index embeddings to: /home/jupyter/results/retrieval_subset/cache/index_frame_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_index_embeddings.npz
CLIP index embedding shape: (300, 512)
BLIP index embedding shape: (300, 768)
Building query embedding cache for clip: 18dad6e7-5969-4573-a1b3-f4ccfc53c350
Number of visual crop queries: 3

Embedding images:   0%|          | 0/1 [00:00<?, ?it/s]

Saved query embeddings to: /home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_embeddings.npz
Saved query metadata to: /home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_metadata.parquet
CLIP query embedding shape: (3, 512)
BLIP query embedding shape: (3, 768)

Repair result:
{'clip_uid': '18dad6e7-5969-4573-a1b3-f4ccfc53c350', 'video_uid': '6e0c294c-d634-4804-8d41-cd6e9d79f0b9', 'status': 'success', 'error': None, 'index_cache_exists_before': False, 'query_cache_exists_before': False, 'query_metadata_exists_before': False, 'num_index_frames': 300, 'num_queries': 3, 'index_cache_exists_after': True, 'query_cache_exists_after': True, 'query_metadata_exists_after': True, 'fully_cached_after': True}

After repair:
{'clip_uid': '18dad6e7-5969-4573-a1b3-f4ccfc53c350', 'index_cache_exists': True, 'query_cache_exists': True, 'query_metadata_exists': True, 'fully_cached': True}

In [19]:
# ---------------- Re-check final cache completeness ----------------

all_300_clip_uids = list(workplan.keys())

final_cache_status_df = pd.DataFrame(
    [check_clip_cache_status(clip_uid) for clip_uid in all_300_clip_uids]
)

display(final_cache_status_df.head())

print("Total clips checked:", len(final_cache_status_df))
print("Unique clips checked:", final_cache_status_df["clip_uid"].nunique())
print("Index caches exist:", final_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", final_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", final_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", final_cache_status_df["fully_cached"].sum())

missing_cache_df = final_cache_status_df[~final_cache_status_df["fully_cached"]].copy()

print("\nMissing / incomplete cache clips:", len(missing_cache_df))
display(missing_cache_df)

final_cache_status_path = RESULTS_DIR / f"cache_status_nclips{N_CLIPS}_final_after_repair.csv"
final_cache_status_df.to_csv(final_cache_status_path, index=False)

print("\nSaved final cache status to:", final_cache_status_path)

,clip_uid,index_cache_exists,query_cache_exists,query_metadata_exists,fully_cached
0,dfe962ab-6aa7-4888-9378-796817a30ab6,True,True,True,True
1,b157270d-c67a-41db-91ec-32bb3ec738fc,True,True,True,True
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,True,True,True,True
3,ea365183-5841-4f00-9a2e-1b81c5e09c98,True,True,True,True
4,b961eb69-cfdd-4d5c-b427-4b667fedfcda,True,True,True,True

Total clips checked: 300
Unique clips checked: 300
Index caches exist: 300
Query caches exist: 300
Query metadata exists: 300
Fully cached: 300

Missing / incomplete cache clips: 0

Empty DataFrame
Columns: [clip_uid, index_cache_exists, query_cache_exists, query_metadata_exists, fully_cached]
Index: []

Saved final cache status to: /home/jupyter/results/retrieval_subset/cache_status_nclips300_final_after_repair.csv