In [1]:
# ---------------- 1. Imports + paths ----------------

from pathlib import Path
import json
import numpy as np
import pandas as pd
from tqdm.auto import tqdm

# Main directories
RESULTS_DIR = Path("/home/jupyter/results/retrieval_subset")
CACHE_DIR = RESULTS_DIR / "cache"
INDEX_CACHE_DIR = CACHE_DIR / "index_frame_embeddings"
QUERY_CACHE_DIR = CACHE_DIR / "query_embeddings"

# Metadata / saved status files
N_CLIPS = 300
FINAL_CACHE_STATUS_PATH = RESULTS_DIR / f"cache_status_nclips{N_CLIPS}_final_after_repair.csv"
COMBINED_MANIFEST_PATH = RESULTS_DIR / f"preprocess_manifest_nclips{N_CLIPS}_all_batches.csv"

print("RESULTS_DIR:", RESULTS_DIR)
print("CACHE_DIR:", CACHE_DIR)
print("INDEX_CACHE_DIR:", INDEX_CACHE_DIR)
print("QUERY_CACHE_DIR:", QUERY_CACHE_DIR)

print("\nExists:")
print("RESULTS_DIR:", RESULTS_DIR.exists())
print("CACHE_DIR:", CACHE_DIR.exists())
print("INDEX_CACHE_DIR:", INDEX_CACHE_DIR.exists())
print("QUERY_CACHE_DIR:", QUERY_CACHE_DIR.exists())
print("FINAL_CACHE_STATUS_PATH:", FINAL_CACHE_STATUS_PATH.exists())
print("COMBINED_MANIFEST_PATH:", COMBINED_MANIFEST_PATH.exists())

RESULTS_DIR: /home/jupyter/results/retrieval_subset
CACHE_DIR: /home/jupyter/results/retrieval_subset/cache
INDEX_CACHE_DIR: /home/jupyter/results/retrieval_subset/cache/index_frame_embeddings
QUERY_CACHE_DIR: /home/jupyter/results/retrieval_subset/cache/query_embeddings

Exists:
RESULTS_DIR: False
CACHE_DIR: False
INDEX_CACHE_DIR: False
QUERY_CACHE_DIR: False
FINAL_CACHE_STATUS_PATH: False
COMBINED_MANIFEST_PATH: False

In [2]:
# ---------------- 2. Load 300 cached clip list ----------------

final_cache_status_df = pd.read_csv(FINAL_CACHE_STATUS_PATH)

print("Final cache status shape:", final_cache_status_df.shape)
display(final_cache_status_df.head())

# Use this file as the source of truth for the 300 clips.
all_300_clip_uids = final_cache_status_df["clip_uid"].astype(str).tolist()

print("Total clip rows:", len(all_300_clip_uids))
print("Unique clip_uids:", len(set(all_300_clip_uids)))

print("\nCache completeness:")
print("Index caches exist:", final_cache_status_df["index_cache_exists"].sum())
print("Query caches exist:", final_cache_status_df["query_cache_exists"].sum())
print("Query metadata exists:", final_cache_status_df["query_metadata_exists"].sum())
print("Fully cached:", final_cache_status_df["fully_cached"].sum())

missing_cache_df = final_cache_status_df[~final_cache_status_df["fully_cached"]].copy()
print("\nMissing / incomplete cache clips:", len(missing_cache_df))
display(missing_cache_df)

FileNotFoundError: [Errno 2] No such file or directory: '/home/jupyter/results/retrieval_subset/cache_status_nclips300_final_after_repair.csv'

In [ ]:
# ---------------- 3. Cache loading sanity check ----------------

def load_index_cache(clip_uid):
    path = INDEX_CACHE_DIR / f"{clip_uid}_index_embeddings.npz"
    data = np.load(path, allow_pickle=True)

    return {
        "path": path,
        "frame_numbers": data["frame_numbers"],
        "clip_embs": data["clip_embs"],
        "blip_embs": data["blip_embs"],
    }


def load_query_cache(clip_uid):
    emb_path = QUERY_CACHE_DIR / f"{clip_uid}_query_embeddings.npz"
    meta_path = QUERY_CACHE_DIR / f"{clip_uid}_query_metadata.parquet"

    data = np.load(emb_path, allow_pickle=True)
    query_metadata = pd.read_parquet(meta_path)

    return {
        "emb_path": emb_path,
        "meta_path": meta_path,
        "query_metadata": query_metadata,
        "clip_embs": data["clip_embs"],
        "blip_embs": data["blip_embs"],
    }


# Test one clip
test_clip_uid = all_300_clip_uids[0]

index_cache = load_index_cache(test_clip_uid)
query_cache = load_query_cache(test_clip_uid)

print("Test clip_uid:", test_clip_uid)

print("\nIndex cache:")
print("Frame numbers shape:", index_cache["frame_numbers"].shape)
print("CLIP index embedding shape:", index_cache["clip_embs"].shape)
print("BLIP index embedding shape:", index_cache["blip_embs"].shape)

print("\nQuery cache:")
print("Query metadata shape:", query_cache["query_metadata"].shape)
print("CLIP query embedding shape:", query_cache["clip_embs"].shape)
print("BLIP query embedding shape:", query_cache["blip_embs"].shape)

display(query_cache["query_metadata"].head())

Test clip_uid: dfe962ab-6aa7-4888-9378-796817a30ab6

Index cache:
Frame numbers shape: (300,)
CLIP index embedding shape: (300, 512)
BLIP index embedding shape: (300, 768)

Query cache:
Query metadata shape: (6, 5)
CLIP query embedding shape: (6, 512)
BLIP query embedding shape: (6, 768)

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,frames/retrieval/visual_crops/val/dfe962ab-6aa...
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,frames/retrieval/visual_crops/val/dfe962ab-6aa...
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,frames/retrieval/visual_crops/val/dfe962ab-6aa...
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,frames/retrieval/visual_crops/val/dfe962ab-6aa...
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,frames/retrieval/visual_crops/val/dfe962ab-6aa...

In [ ]:
# ---------------- 4. Define success and retrieval helper functions ----------------

TOLERANCE_FRAMES = 5

def is_success(retrieved_frame, rt_min_frame, rt_max_frame, tolerance_frames=TOLERANCE_FRAMES):
    """
    Check whether retrieved frame falls inside the response-track range,
    allowing a small tolerance.
    """
    if pd.isna(retrieved_frame) or pd.isna(rt_min_frame) or pd.isna(rt_max_frame):
        return False

    return (
        retrieved_frame >= rt_min_frame - tolerance_frames
        and retrieved_frame <= rt_max_frame + tolerance_frames
    )


def compute_similarity_scores(index_embs, query_emb):
    """
    Embeddings are already L2-normalized.
    Dot product is cosine similarity.
    """
    return index_embs @ query_emb


def get_topk_frames(frame_numbers, scores, k=100):
    """
    Return top-k frame numbers and scores, sorted by descending score.
    """
    k = min(k, len(scores))
    top_idx = np.argsort(scores)[::-1][:k]

    return pd.DataFrame({
        "rank": np.arange(1, k + 1),
        "frame_number": frame_numbers[top_idx],
        "score": scores[top_idx],
    })


def first_correct_rank(topk_df, rt_min_frame, rt_max_frame, tolerance_frames=TOLERANCE_FRAMES):
    """
    Find the first rank where the retrieved frame is successful.
    Return np.nan if no correct frame appears in top-k.
    """
    for _, row in topk_df.iterrows():
        if is_success(
            retrieved_frame=row["frame_number"],
            rt_min_frame=rt_min_frame,
            rt_max_frame=rt_max_frame,
            tolerance_frames=tolerance_frames,
        ):
            return int(row["rank"])

    return np.nan


print("Helper functions defined.")
print("TOLERANCE_FRAMES:", TOLERANCE_FRAMES)

Helper functions defined.
TOLERANCE_FRAMES: 5

In [ ]:
# ---------------- 5. Check response-track lookup ----------------

print("rt_lookup exists:", "rt_lookup" in globals())

if "rt_lookup" in globals():
    print("Response-track entries:", len(rt_lookup))
    sample_key = next(iter(rt_lookup))
    print("Sample key:", sample_key)
    print("Sample value:", rt_lookup[sample_key])
else:
    print("rt_lookup is not defined yet.")
    print("We need to load or rebuild response-track labels before baseline retrieval.")

rt_lookup exists: False
rt_lookup is not defined yet.
We need to load or rebuild response-track labels before baseline retrieval.

In [ ]:
# ---------------- 6. Locate possible label / response-track files ----------------

from pathlib import Path

search_roots = [
    Path("/home/jupyter/results/retrieval_subset"),
    Path("/home/jupyter/egorecall_retrieval_subset"),
    Path("/home/jupyter/egorecall_retrieval_work"),
    Path("/home/jupyter/tmp/retrieval_work"),
    Path("/home/jupyter"),
]

keywords = [
    "response",
    "track",
    "query",
    "vq",
    "label",
    "metadata",
    "manifest",
]

matched_files = []

for root in search_roots:
    if not root.exists():
        continue

    for p in root.rglob("*"):
        if p.is_file():
            name_lower = p.name.lower()
            if any(k in name_lower for k in keywords):
                matched_files.append(p)

print("Matched files:", len(matched_files))

for p in matched_files[:200]:
    try:
        size_mb = p.stat().st_size / 1024 / 1024
        print(f"{size_mb:8.2f} MB | {p}")
    except Exception as e:
        print("Could not stat:", p, e)

Matched files: 1264
    0.01 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch2.csv
    0.00 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0_sanity3.csv
    0.01 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch4.csv
    0.01 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch1.csv
    0.04 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_all_batches.csv
    0.01 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch3.csv
    0.01 MB | /home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/09d85b55-d473-49c1-9ebc-e871714785cd_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c2229daf-ec7b-45c5-84e3-bb4f4d145d93_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f22ddd51-999f-44b8-9d53-319982dda0a7_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/3970c9a9-e6ca-4675-866c-2e21913eacb2_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/db84f0aa-15a2-4cfb-a89e-173b0aea4720_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/4479363e-cd84-4fe7-994e-02eaf4531b0b_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/3e654a1a-b706-456d-ab6d-565effcf159c_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/eaa07b51-b07d-4cf7-91e7-314a74c8edc6_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/a879680b-7957-45fb-8786-cdc8e998f01d_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/ae8727ba-fe6f-4411-b277-48a8b7326a2a_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/7b452799-981c-494a-affb-d011cd5c43e5_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/dfe962ab-6aa7-4888-9378-796817a30ab6_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/a879680b-7957-45fb-8786-cdc8e998f01d_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/39f8cacc-5fd2-44c5-84d8-5bcc7fefe798_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/6673c838-2765-4b41-81fd-9a01deba1d0b_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/aef0725a-1005-4a17-ad33-4522808c3a17_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/7bb41f34-1743-42ad-97d1-c54f4472b85e_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/61f93683-2f3d-4d44-867d-c980d9316775_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c52530be-f470-4c44-ae1a-c8aee924ff46_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/297eb153-8e44-4f25-b270-ca4d682c32bb_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/85b01a98-245e-4b63-bff8-4545aedaf916_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b2dcb4b2-7a5e-4d68-aec9-41ec96915168_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/efc97e5a-20a0-42f1-9cfd-fcede9bbe043_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b157270d-c67a-41db-91ec-32bb3ec738fc_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/5c87b9e2-7d54-469f-96ff-02ff7493c6ae_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8f1770e5-612c-4047-a7b7-a6157460bc24_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/0df1db1f-40a0-4139-b120-9a1c741f571c_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f1eb7035-ce79-4be2-81bc-118eb1ad2887_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9e9f05e9-5dbe-439b-970d-acb13ab98f10_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/d87774db-a324-4440-aa60-b39fe3276b77_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/d68ae83a-903a-448e-bc7e-7279755e0243_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/90288170-a577-48e6-afe6-014673ae8723_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/2ddf340f-de44-4f5d-9994-1e0f7db05caf_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/6f3c6977-b9dc-40de-bd32-349567343f0a_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9f661edf-a6f6-444e-b168-e8428044b1d7_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/cc994557-a65b-48a9-94c6-122ede470347_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/2b887413-c1ef-4257-9524-0be974fd47a8_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/d2e61675-14b6-481f-9206-34bbc1375ea6_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f052ac6f-832d-41f0-b00f-7cb85c20a15c_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f552173d-229e-496d-b414-3708df4c842e_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/0723c03f-263c-442d-9d9b-d0fef0cef0e4_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/3d1bc6e6-e445-4748-9b08-727a1ce2e697_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9b15d755-f374-4731-8370-26847aadc08b_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f0861378-ff5f-47d8-b1b3-59cf5b07acc7_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/0858668c-35b2-4593-acb0-f6d4a8da483d_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/01b451af-466a-4425-8094-be0b2ffc0e36_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/cb0cd08f-7a3e-4450-86ae-e7d490603188_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/81da71e1-0e80-43cc-8752-292d231e70a2_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/11acf51c-9a44-4c77-9e16-46925c2e66de_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/563db64f-47c4-42e3-b8bf-c543fd78655a_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/860b4b8a-7219-433b-8947-cd8b93973b07_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/1d2b62ed-fc94-4fb0-b547-8c50533b0b29_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/ea365183-5841-4f00-9a2e-1b81c5e09c98_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b338a041-3164-4155-ae40-faa77a9fd08a_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/d3b18a63-002a-4538-adef-21ac1f476704_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/3cbf7d7e-7ef1-4486-94ea-b558c890b4b4_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/d68ae83a-903a-448e-bc7e-7279755e0243_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/55200058-9bf1-48a4-ac7f-a279f75fcaf1_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/23b8f734-c2db-4c55-9bca-cbe557d4abd4_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/88f358c1-b11a-4868-aaf4-e1cb273c4b8a_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9b15d755-f374-4731-8370-26847aadc08b_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/145ec165-a872-433e-959d-a0d748d261b0_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/17043256-42c5-4e4f-846b-7923afe3ead4_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/82abc0e6-c282-4492-89cb-c6005f1cb0f5_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/bcd1ea04-bde8-4769-acb4-3d504183cbf2_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/3716dd4c-232c-4ac1-89bd-3884cc79f0a8_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/67c47998-eabe-4b31-9096-b286c18e1beb_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f8bdd228-ef92-43e3-bf6f-086ff54d5c78_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/99ddfcb3-bb2a-45d3-903e-d7e858969957_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f4240b1c-c260-4354-a005-cfa8c8353f90_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8efe1412-5806-425e-9c3e-459bb9d45079_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/4570ab0a-55de-442d-b350-fe64e6956d4d_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f9671fc0-7e56-4e98-842a-dfbbd99d385f_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c552b2d7-9d27-4765-9dce-8223581c1ca7_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/bed399ed-44af-438d-ab3f-12739adac348_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c96304a7-f17c-49bf-be81-a95450fb0358_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/92207d1e-5cc6-41b5-bbd1-ed679aa997bd_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/fc838ebc-2c4e-42f2-8108-9710ecb1653a_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8059dcc2-0f52-46f8-a119-85c78d608602_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/74c966c9-0a8c-4e65-8811-75737d3e9c21_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f552173d-229e-496d-b414-3708df4c842e_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/5ab23181-c60a-4478-9085-2a450a24b65b_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c96304a7-f17c-49bf-be81-a95450fb0358_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8450f847-5946-4199-9bc7-9d08c93c0141_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b8981cdd-a897-41b6-b1ef-e9957d270e9e_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/ee5b3977-6598-4dfd-9199-e36a0d2fd56a_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/2b8ddc75-2c96-4f73-8278-ff7f60920426_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/dc3ba39f-62f4-480b-a187-ca723c8666bd_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/260ec80b-f26a-4646-afc5-616481889643_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/ad9083b3-9b0b-4c27-a941-38f57be13edf_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/984d6427-5bf1-477d-98fc-170b93165868_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b8e1c869-b304-49fc-ba5f-9a5ae3b3770c_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/6dd3486b-59dd-4dc6-874a-e4d773273c8a_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/1ffc605c-c5f5-42d3-9897-6e9319675497_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/a881f4a6-1d84-4088-8cea-8cf3a61c0914_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8f829383-08e6-48a9-85f9-0999eb9379a3_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/b9c96242-ae4d-4a43-a308-a00591f060ab_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/9b9b7994-8a7a-43ac-9382-744664ee3e66_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/a928aa57-8047-4156-8851-f94f75d57f70_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/db6e91d9-3006-46dd-af29-b74f725fe284_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/69668105-9984-43d0-8c24-74a4ed2adcf4_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/e4728a65-3184-4239-9b84-be43dfd7377e_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/5333a996-877f-4e30-ba79-631131744a4b_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/c7fd4879-e196-4195-8fa8-d4430ae90a9a_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/dfe962ab-6aa7-4888-9378-796817a30ab6_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/412ee977-da12-496e-9609-80bfef2f4638_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/563db64f-47c4-42e3-b8bf-c543fd78655a_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/77e3af3b-a5ec-420c-a3bc-a2aff4934ce3_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/fe3000d6-d857-4cd1-a927-0a91a7f9616e_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/248cf237-d8dc-42d1-ae41-017221765031_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/63a1c028-3919-462b-9c97-9a22c5296eae_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/8ebdf93c-6bba-4604-be9b-45938eb2bb38_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/e8a88ddf-63db-4095-93fe-9d24c386a477_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/7a954faf-102f-4aba-9317-96d73c8fd104_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/48a81e63-9f9e-48c1-84e0-5fb90549cc4e_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/efe7dfaa-07e0-42d5-85eb-1e6f93409ab5_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/fe71b934-322a-45a1-862c-cd7c2db2c354_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/f91c7008-f21c-4047-bfc1-d937787665e5_query_metadata.parquet
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/70d3a98e-132b-4446-aa99-cab279318dc8_query_metadata.parquet
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/a051a8ce-cb33-40f8-a46e-1a3a263de18f_query_embeddings.npz
    0.00 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/7ecce159-e45f-4e35-9289-f61abfa02147_query_metadata.parquet
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c_query_embeddings.npz
    0.03 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/26f6ea45-4e7d-4208-b36c-715064151980_query_embeddings.npz
    0.01 MB | /home/jupyter/results/retrieval_subset/cache/query_embeddings/38dc82c8-d59a-4ef9-818c-c3affb046e17_query_embeddings.npz

In [ ]:
# ---------------- 7. Inspect candidate table files ----------------

candidate_table_files = [
    p for p in matched_files
    if p.suffix.lower() in [".parquet", ".csv"]
]

print("Candidate table files:", len(candidate_table_files))

for p in candidate_table_files:
    print("=" * 100)
    print(p)

    try:
        if p.suffix.lower() == ".parquet":
            df_tmp = pd.read_parquet(p)
        else:
            df_tmp = pd.read_csv(p)

        print("Shape:", df_tmp.shape)
        print("Columns:", df_tmp.columns.tolist())
        display(df_tmp.head(3))

    except Exception as e:
        print("Failed to read:", repr(e))

Candidate table files: 662
====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch2.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,617e8d7c-8764-4508-ba9b-c993282c70cd,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,NaN,True,True,True,NaN,3
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,NaN,True,True,True,NaN,3
2,81221073-c095-4129-b095-97f3d6e4a6b1,412763ce-9a81-4bb7-b713-80fe2713e1a8,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0_sanity3.csv
Shape: (3, 8)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'video_exists_before', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before']

,clip_uid,video_uid,status,error,video_exists_before,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before
0,159ac0ad-e5ec-449d-a69e-556655f79b2a,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,error,"AttributeError(""'BaseModelOutputWithPooling' o...",False,False,False,False
1,830e1b42-1d4a-4a4b-b0ad-c40fc4ace19c,eb486644-f46f-44cf-8e4b-73245b2fc02e,error,"AttributeError(""'BaseModelOutputWithPooling' o...",False,False,False,False
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,eb486644-f46f-44cf-8e4b-73245b2fc02e,error,"AttributeError(""'BaseModelOutputWithPooling' o...",True,False,False,False

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch4.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cc994557-a65b-48a9-94c6-122ede470347,6e0c294c-d634-4804-8d41-cd6e9d79f0b9,skipped_fully_cached,NaN,True,True,True,NaN,3
1,4a491385-b165-49ec-a23b-7b0ed26737f9,3ee7070a-fe81-49a9-97a2-902268af9985,skipped_fully_cached,NaN,True,True,True,NaN,6
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,ecc633d2-72b5-4bd0-a6a1-f1cedb21d757,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch1.csv
Shape: (60, 13)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries', 'index_cache_exists_after', 'query_cache_exists_after', 'query_metadata_exists_after', 'fully_cached_after']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries,index_cache_exists_after,query_cache_exists_after,query_metadata_exists_after,fully_cached_after
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,success,NaN,False,False,False,480.0,3,True,True,True,True
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,success,NaN,False,False,False,480.0,6,True,True,True,True
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,success,NaN,False,False,False,300.0,3,True,True,True,True

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_all_batches.csv
Shape: (300, 14)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries', 'batch_id', 'index_cache_exists_after', 'query_cache_exists_after', 'query_metadata_exists_after', 'fully_cached_after']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries,batch_id,index_cache_exists_after,query_cache_exists_after,query_metadata_exists_after,fully_cached_after
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,skipped_fully_cached,NaN,True,True,True,NaN,3.0,0,NaN,NaN,NaN,NaN
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,skipped_fully_cached,NaN,True,True,True,NaN,6.0,0,NaN,NaN,NaN,NaN
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,skipped_fully_cached,NaN,True,True,True,NaN,3.0,0,NaN,NaN,NaN,NaN

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch3.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
1,16fce853-9528-4c39-9f88-b0c61f30d01d,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,1938c632-f575-49dd-8ae0-e48dbb467920,skipped_fully_cached,NaN,True,True,True,NaN,3.0

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,skipped_fully_cached,NaN,True,True,True,NaN,3
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,skipped_fully_cached,NaN,True,True,True,NaN,6
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/09d85b55-d473-49c1-9ebc-e871714785cd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,1,calculator,frames/retrieval/visual_crops/val/09d85b55-d47...
1,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,2,tray,frames/retrieval/visual_crops/val/09d85b55-d47...
2,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,3,spray bottle,frames/retrieval/visual_crops/val/09d85b55-d47...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f22ddd51-999f-44b8-9d53-319982dda0a7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,1,scissor,frames/retrieval/visual_crops/val/f22ddd51-999...
1,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,2,sandal,frames/retrieval/visual_crops/val/f22ddd51-999...
2,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,3,gloves,frames/retrieval/visual_crops/val/f22ddd51-999...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,3,books,frames/retrieval/visual_crops/val/f14ea4c5-2a1...
1,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,1,kitchen towel,frames/retrieval/visual_crops/val/f14ea4c5-2a1...
2,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,2,chopping board,frames/retrieval/visual_crops/val/f14ea4c5-2a1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3970c9a9-e6ca-4675-866c-2e21913eacb2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,2,bucket,frames/retrieval/visual_crops/val/3970c9a9-e6c...
1,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,3,stepstool,frames/retrieval/visual_crops/val/3970c9a9-e6c...
2,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,1,mask,frames/retrieval/visual_crops/val/3970c9a9-e6c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/db84f0aa-15a2-4cfb-a89e-173b0aea4720_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,1,cooking pot,frames/retrieval/visual_crops/val/db84f0aa-15a...
1,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,2,basin,frames/retrieval/visual_crops/val/db84f0aa-15a...
2,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,3,tray,frames/retrieval/visual_crops/val/db84f0aa-15a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ae8727ba-fe6f-4411-b277-48a8b7326a2a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,1,container,frames/retrieval/visual_crops/val/ae8727ba-fe6...
1,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,2,bottle,frames/retrieval/visual_crops/val/ae8727ba-fe6...
2,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,3,chair,frames/retrieval/visual_crops/val/ae8727ba-fe6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a879680b-7957-45fb-8786-cdc8e998f01d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,1,screw driver,frames/retrieval/visual_crops/val/a879680b-795...
1,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,2,ratchet drill,frames/retrieval/visual_crops/val/a879680b-795...
2,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,3,spanner,frames/retrieval/visual_crops/val/a879680b-795...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/39f8cacc-5fd2-44c5-84d8-5bcc7fefe798_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,2,electric kettle,frames/retrieval/visual_crops/val/39f8cacc-5fd...
1,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,1,paper towel,frames/retrieval/visual_crops/val/39f8cacc-5fd...
2,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,3,microwave,frames/retrieval/visual_crops/val/39f8cacc-5fd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6673c838-2765-4b41-81fd-9a01deba1d0b_query_metadata.parquet
Shape: (5, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6673c838-2765-4b41-81fd-9a01deba1d0b,e894d030-577e-46e2-a333-f916b4dda9d8,2,lid,frames/retrieval/visual_crops/val/6673c838-276...
1,6673c838-2765-4b41-81fd-9a01deba1d0b,e894d030-577e-46e2-a333-f916b4dda9d8,3,can,frames/retrieval/visual_crops/val/6673c838-276...
2,6673c838-2765-4b41-81fd-9a01deba1d0b,6f31662c-5251-454b-b815-f1b1da0a6d4e,3,iron,frames/retrieval/visual_crops/val/6673c838-276...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/aef0725a-1005-4a17-ad33-4522808c3a17_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,2,kettle,frames/retrieval/visual_crops/val/aef0725a-100...
1,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,1,jug,frames/retrieval/visual_crops/val/aef0725a-100...
2,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,3,bottle,frames/retrieval/visual_crops/val/aef0725a-100...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c52530be-f470-4c44-ae1a-c8aee924ff46_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,1,hat,frames/retrieval/visual_crops/val/c52530be-f47...
1,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,2,bedside lamp,frames/retrieval/visual_crops/val/c52530be-f47...
2,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,3,fire-extinguisher,frames/retrieval/visual_crops/val/c52530be-f47...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/297eb153-8e44-4f25-b270-ca4d682c32bb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,3,sickle tool,frames/retrieval/visual_crops/val/297eb153-8e4...
1,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,1,tied sack,frames/retrieval/visual_crops/val/297eb153-8e4...
2,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,2,cooking pot,frames/retrieval/visual_crops/val/297eb153-8e4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b2dcb4b2-7a5e-4d68-aec9-41ec96915168_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,1,soup scoop spoon,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...
1,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,2,shoes,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...
2,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,3,rice cooker,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5c87b9e2-7d54-469f-96ff-02ff7493c6ae_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,1,sellotape,frames/retrieval/visual_crops/val/5c87b9e2-7d5...
1,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,2,impact driver,frames/retrieval/visual_crops/val/5c87b9e2-7d5...
2,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,3,ear muff,frames/retrieval/visual_crops/val/5c87b9e2-7d5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f1eb7035-ce79-4be2-81bc-118eb1ad2887_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,1,pestle,frames/retrieval/visual_crops/val/f1eb7035-ce7...
1,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,2,container,frames/retrieval/visual_crops/val/f1eb7035-ce7...
2,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,3,test tube,frames/retrieval/visual_crops/val/f1eb7035-ce7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9e9f05e9-5dbe-439b-970d-acb13ab98f10_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,1,music keyboard,frames/retrieval/visual_crops/val/9e9f05e9-5db...
1,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,2,television,frames/retrieval/visual_crops/val/9e9f05e9-5db...
2,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,3,drink cans,frames/retrieval/visual_crops/val/9e9f05e9-5db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,1,flower pot,frames/retrieval/visual_crops/val/8530a122-787...
1,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,2,trash bin,frames/retrieval/visual_crops/val/8530a122-787...
2,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,3,bucket,frames/retrieval/visual_crops/val/8530a122-787...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d68ae83a-903a-448e-bc7e-7279755e0243_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,3,plastic tin,frames/retrieval/visual_crops/val/d68ae83a-903...
1,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,2,water bottle,frames/retrieval/visual_crops/val/d68ae83a-903...
2,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,1,speed square,frames/retrieval/visual_crops/val/d68ae83a-903...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ddf340f-de44-4f5d-9994-1e0f7db05caf_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,3,scarf,frames/retrieval/visual_crops/val/2ddf340f-de4...
1,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,1,basket,frames/retrieval/visual_crops/val/2ddf340f-de4...
2,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,2,sweater,frames/retrieval/visual_crops/val/2ddf340f-de4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9f661edf-a6f6-444e-b168-e8428044b1d7_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,1,plastic cup,frames/retrieval/visual_crops/val/9f661edf-a6f...
1,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,2,green bottle,frames/retrieval/visual_crops/val/9f661edf-a6f...
2,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,3,bowl,frames/retrieval/visual_crops/val/9f661edf-a6f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b887413-c1ef-4257-9524-0be974fd47a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,1,drill,frames/retrieval/visual_crops/val/2b887413-c1e...
1,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,2,lawnmower,frames/retrieval/visual_crops/val/2b887413-c1e...
2,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,3,tiling trowel,frames/retrieval/visual_crops/val/2b887413-c1e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,1,hangers,frames/retrieval/visual_crops/val/5a74f8ec-f3c...
1,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,3,phone,frames/retrieval/visual_crops/val/5a74f8ec-f3c...
2,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,2,laptop,frames/retrieval/visual_crops/val/5a74f8ec-f3c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,1,exercise ball,frames/retrieval/visual_crops/val/18dad6e7-596...
1,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,2,phone,frames/retrieval/visual_crops/val/18dad6e7-596...
2,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,3,packed food box,frames/retrieval/visual_crops/val/18dad6e7-596...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0723c03f-263c-442d-9d9b-d0fef0cef0e4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,1,basin,frames/retrieval/visual_crops/val/0723c03f-263...
1,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,3,paper bag,frames/retrieval/visual_crops/val/0723c03f-263...
2,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,2,measuring cup,frames/retrieval/visual_crops/val/0723c03f-263...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9b15d755-f374-4731-8370-26847aadc08b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,1,purse,frames/retrieval/visual_crops/val/9b15d755-f37...
1,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,2,tray,frames/retrieval/visual_crops/val/9b15d755-f37...
2,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,3,phone,frames/retrieval/visual_crops/val/9b15d755-f37...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cb0cd08f-7a3e-4450-86ae-e7d490603188_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,1,padlock,frames/retrieval/visual_crops/val/cb0cd08f-7a3...
1,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,2,bottle,frames/retrieval/visual_crops/val/cb0cd08f-7a3...
2,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,3,plier,frames/retrieval/visual_crops/val/cb0cd08f-7a3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/81da71e1-0e80-43cc-8752-292d231e70a2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,1,bottle,frames/retrieval/visual_crops/val/81da71e1-0e8...
1,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,2,flat file,frames/retrieval/visual_crops/val/81da71e1-0e8...
2,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,3,bucket,frames/retrieval/visual_crops/val/81da71e1-0e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/11acf51c-9a44-4c77-9e16-46925c2e66de_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,2,scissor,frames/retrieval/visual_crops/val/11acf51c-9a4...
1,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,1,utensils rinsing soap,frames/retrieval/visual_crops/val/11acf51c-9a4...
2,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,3,tape,frames/retrieval/visual_crops/val/11acf51c-9a4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/860b4b8a-7219-433b-8947-cd8b93973b07_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,1,waste bin,frames/retrieval/visual_crops/val/860b4b8a-721...
1,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,2,swivel chair,frames/retrieval/visual_crops/val/860b4b8a-721...
2,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,3,glass jar,frames/retrieval/visual_crops/val/860b4b8a-721...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,3,tissue paper,frames/retrieval/visual_crops/val/4e9b50a0-1a9...
1,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,1,cup,frames/retrieval/visual_crops/val/4e9b50a0-1a9...
2,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,2,frying pan,frames/retrieval/visual_crops/val/4e9b50a0-1a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b338a041-3164-4155-ae40-faa77a9fd08a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,1,red car,frames/retrieval/visual_crops/val/b338a041-316...
1,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,2,bench,frames/retrieval/visual_crops/val/b338a041-316...
2,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,3,tennis ball,frames/retrieval/visual_crops/val/b338a041-316...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3cbf7d7e-7ef1-4486-94ea-b558c890b4b4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,1,water barrel,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...
1,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,2,wood,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...
2,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,3,jerrycan,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/55200058-9bf1-48a4-ac7f-a279f75fcaf1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,1,book,frames/retrieval/visual_crops/val/55200058-9bf...
1,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,2,stool,frames/retrieval/visual_crops/val/55200058-9bf...
2,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,3,fire extinguisher,frames/retrieval/visual_crops/val/55200058-9bf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/23b8f734-c2db-4c55-9bca-cbe557d4abd4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,1,spray bottle,frames/retrieval/visual_crops/val/23b8f734-c2d...
1,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,2,sink,frames/retrieval/visual_crops/val/23b8f734-c2d...
2,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,3,dust bin,frames/retrieval/visual_crops/val/23b8f734-c2d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/145ec165-a872-433e-959d-a0d748d261b0_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,145ec165-a872-433e-959d-a0d748d261b0,2b430174-48a2-47d2-8b0c-09971df50e02,2,glove,frames/retrieval/visual_crops/val/145ec165-a87...
1,145ec165-a872-433e-959d-a0d748d261b0,2b430174-48a2-47d2-8b0c-09971df50e02,3,box,frames/retrieval/visual_crops/val/145ec165-a87...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bcd1ea04-bde8-4769-acb4-3d504183cbf2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,2,sanitizer,frames/retrieval/visual_crops/val/bcd1ea04-bde...
1,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,3,fire extinguisher,frames/retrieval/visual_crops/val/bcd1ea04-bde...
2,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,1,bag,frames/retrieval/visual_crops/val/bcd1ea04-bde...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3716dd4c-232c-4ac1-89bd-3884cc79f0a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,1,bowl,frames/retrieval/visual_crops/val/3716dd4c-232...
1,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,3,serving spoon,frames/retrieval/visual_crops/val/3716dd4c-232...
2,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,2,spray gun,frames/retrieval/visual_crops/val/3716dd4c-232...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/99ddfcb3-bb2a-45d3-903e-d7e858969957_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,1,bag,frames/retrieval/visual_crops/val/99ddfcb3-bb2...
1,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,2,pruning sheers,frames/retrieval/visual_crops/val/99ddfcb3-bb2...
2,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,3,basket,frames/retrieval/visual_crops/val/99ddfcb3-bb2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,1,towel,frames/retrieval/visual_crops/val/b2a48c96-9b7...
1,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,2,funnel,frames/retrieval/visual_crops/val/b2a48c96-9b7...
2,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,3,stool,frames/retrieval/visual_crops/val/b2a48c96-9b7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8efe1412-5806-425e-9c3e-459bb9d45079_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,2,spray can,frames/retrieval/visual_crops/val/8efe1412-580...
1,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,1,scalpel,frames/retrieval/visual_crops/val/8efe1412-580...
2,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,3,car,frames/retrieval/visual_crops/val/8efe1412-580...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4570ab0a-55de-442d-b350-fe64e6956d4d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,1,glass,frames/retrieval/visual_crops/val/4570ab0a-55d...
1,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,2,paint,frames/retrieval/visual_crops/val/4570ab0a-55d...
2,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,3,cup,frames/retrieval/visual_crops/val/4570ab0a-55d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,3,jug,frames/retrieval/visual_crops/val/9cfc44fe-5f7...
1,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,1,dough mixer,frames/retrieval/visual_crops/val/9cfc44fe-5f7...
2,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,2,flour,frames/retrieval/visual_crops/val/9cfc44fe-5f7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,2,bottle,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...
1,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,1,plastic jerry can,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...
2,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,3,stool,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bed399ed-44af-438d-ab3f-12739adac348_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,1,dumbbell,frames/retrieval/visual_crops/val/bed399ed-44a...
1,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,3,sandpaper disc,frames/retrieval/visual_crops/val/bed399ed-44a...
2,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,2,spanner,frames/retrieval/visual_crops/val/bed399ed-44a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/92207d1e-5cc6-41b5-bbd1-ed679aa997bd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,3,pen,frames/retrieval/visual_crops/val/92207d1e-5cc...
1,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,1,cup,frames/retrieval/visual_crops/val/92207d1e-5cc...
2,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,2,sieve,frames/retrieval/visual_crops/val/92207d1e-5cc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/74c966c9-0a8c-4e65-8811-75737d3e9c21_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,1,tap,frames/retrieval/visual_crops/val/74c966c9-0a8...
1,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,2,dough scrapper,frames/retrieval/visual_crops/val/74c966c9-0a8...
2,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,3,cup,frames/retrieval/visual_crops/val/74c966c9-0a8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f552173d-229e-496d-b414-3708df4c842e_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,1,mug,frames/retrieval/visual_crops/val/f552173d-229...
1,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,3,hand glove,frames/retrieval/visual_crops/val/f552173d-229...
2,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,2,jerry can,frames/retrieval/visual_crops/val/f552173d-229...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ab23181-c60a-4478-9085-2a450a24b65b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,1,bottle,frames/retrieval/visual_crops/val/5ab23181-c60...
1,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,2,machete,frames/retrieval/visual_crops/val/5ab23181-c60...
2,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,3,chocolate cover,frames/retrieval/visual_crops/val/5ab23181-c60...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c96304a7-f17c-49bf-be81-a95450fb0358_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,1,bottle,frames/retrieval/visual_crops/val/c96304a7-f17...
1,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,2,flower pot,frames/retrieval/visual_crops/val/c96304a7-f17...
2,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,3,plastic bowl,frames/retrieval/visual_crops/val/c96304a7-f17...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8450f847-5946-4199-9bc7-9d08c93c0141_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,3,flowerpot,frames/retrieval/visual_crops/val/8450f847-594...
1,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,1,mirror,frames/retrieval/visual_crops/val/8450f847-594...
2,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,2,table lamp,frames/retrieval/visual_crops/val/8450f847-594...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ee5b3977-6598-4dfd-9199-e36a0d2fd56a_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ee5b3977-6598-4dfd-9199-e36a0d2fd56a,ac62aa4f-d0cd-431b-894e-cc5e24660e2e,2,tool box,frames/retrieval/visual_crops/val/ee5b3977-659...
1,ee5b3977-6598-4dfd-9199-e36a0d2fd56a,ac62aa4f-d0cd-431b-894e-cc5e24660e2e,3,tissue,frames/retrieval/visual_crops/val/ee5b3977-659...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ad9083b3-9b0b-4c27-a941-38f57be13edf_query_metadata.parquet
Shape: (12, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,1,hammer,frames/retrieval/visual_crops/val/ad9083b3-9b0...
1,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,2,scissor,frames/retrieval/visual_crops/val/ad9083b3-9b0...
2,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,3,spray can,frames/retrieval/visual_crops/val/ad9083b3-9b0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/984d6427-5bf1-477d-98fc-170b93165868_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,984d6427-5bf1-477d-98fc-170b93165868,83ad176b-3ded-4298-90df-b43096882d31,2,pen,frames/retrieval/visual_crops/val/984d6427-5bf...
1,984d6427-5bf1-477d-98fc-170b93165868,83ad176b-3ded-4298-90df-b43096882d31,3,perfume bottle,frames/retrieval/visual_crops/val/984d6427-5bf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1ffc605c-c5f5-42d3-9897-6e9319675497_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,1,waste bin,frames/retrieval/visual_crops/val/1ffc605c-c5f...
1,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,2,bottle,frames/retrieval/visual_crops/val/1ffc605c-c5f...
2,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,3,calculator,frames/retrieval/visual_crops/val/1ffc605c-c5f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a881f4a6-1d84-4088-8cea-8cf3a61c0914_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,3,vehicle,frames/retrieval/visual_crops/val/a881f4a6-1d8...
1,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,1,tooth brush,frames/retrieval/visual_crops/val/a881f4a6-1d8...
2,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,2,plastic jerry can tap,frames/retrieval/visual_crops/val/a881f4a6-1d8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8f829383-08e6-48a9-85f9-0999eb9379a3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,1,weighing scale,frames/retrieval/visual_crops/val/8f829383-08e...
1,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,2,soap dish bottle,frames/retrieval/visual_crops/val/8f829383-08e...
2,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,3,funnel,frames/retrieval/visual_crops/val/8f829383-08e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9b9b7994-8a7a-43ac-9382-744664ee3e66_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,1,cup,frames/retrieval/visual_crops/val/9b9b7994-8a7...
1,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,2,regulator,frames/retrieval/visual_crops/val/9b9b7994-8a7...
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,3,washing machine,frames/retrieval/visual_crops/val/9b9b7994-8a7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a928aa57-8047-4156-8851-f94f75d57f70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,2,drill,frames/retrieval/visual_crops/val/a928aa57-804...
1,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,1,tissue,frames/retrieval/visual_crops/val/a928aa57-804...
2,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,3,container,frames/retrieval/visual_crops/val/a928aa57-804...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c7fd4879-e196-4195-8fa8-d4430ae90a9a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,1,bottle,frames/retrieval/visual_crops/val/c7fd4879-e19...
1,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,2,nylon,frames/retrieval/visual_crops/val/c7fd4879-e19...
2,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,3,brush,frames/retrieval/visual_crops/val/c7fd4879-e19...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dfe962ab-6aa7-4888-9378-796817a30ab6_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,frames/retrieval/visual_crops/val/dfe962ab-6aa...
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,frames/retrieval/visual_crops/val/dfe962ab-6aa...
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,frames/retrieval/visual_crops/val/dfe962ab-6aa...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/412ee977-da12-496e-9609-80bfef2f4638_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,1,plate,frames/retrieval/visual_crops/val/412ee977-da1...
1,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,2,cooking pot,frames/retrieval/visual_crops/val/412ee977-da1...
2,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,3,kitchen oven,frames/retrieval/visual_crops/val/412ee977-da1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/563db64f-47c4-42e3-b8bf-c543fd78655a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,1,yellow chair,frames/retrieval/visual_crops/val/563db64f-47c...
1,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,2,dustbin,frames/retrieval/visual_crops/val/563db64f-47c...
2,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,3,stapler,frames/retrieval/visual_crops/val/563db64f-47c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/77e3af3b-a5ec-420c-a3bc-a2aff4934ce3_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,1,round tray,frames/retrieval/visual_crops/val/77e3af3b-a5e...
1,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,3,strainer bowl,frames/retrieval/visual_crops/val/77e3af3b-a5e...
2,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,2,pedestal fan,frames/retrieval/visual_crops/val/77e3af3b-a5e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fe3000d6-d857-4cd1-a927-0a91a7f9616e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,3,jug,frames/retrieval/visual_crops/val/fe3000d6-d85...
1,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,2,scraper,frames/retrieval/visual_crops/val/fe3000d6-d85...
2,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,1,red dough scraper,frames/retrieval/visual_crops/val/fe3000d6-d85...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/248cf237-d8dc-42d1-ae41-017221765031_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,1,microwave,frames/retrieval/visual_crops/val/248cf237-d8d...
1,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,2,basin,frames/retrieval/visual_crops/val/248cf237-d8d...
2,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,3,brush,frames/retrieval/visual_crops/val/248cf237-d8d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/63a1c028-3919-462b-9c97-9a22c5296eae_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,2,container,frames/retrieval/visual_crops/val/63a1c028-391...
1,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,3,ring boiler,frames/retrieval/visual_crops/val/63a1c028-391...
2,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,1,pillow,frames/retrieval/visual_crops/val/63a1c028-391...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8ebdf93c-6bba-4604-be9b-45938eb2bb38_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,3,plastic bags,frames/retrieval/visual_crops/val/8ebdf93c-6bb...
1,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,2,red pepper,frames/retrieval/visual_crops/val/8ebdf93c-6bb...
2,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,1,shopping basket,frames/retrieval/visual_crops/val/8ebdf93c-6bb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e8a88ddf-63db-4095-93fe-9d24c386a477_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,1,cup,frames/retrieval/visual_crops/val/e8a88ddf-63d...
1,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,2,remote control,frames/retrieval/visual_crops/val/e8a88ddf-63d...
2,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,3,soft drink,frames/retrieval/visual_crops/val/e8a88ddf-63d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7a954faf-102f-4aba-9317-96d73c8fd104_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,3,shopping basket,frames/retrieval/visual_crops/val/7a954faf-102...
1,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,2,belt,frames/retrieval/visual_crops/val/7a954faf-102...
2,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,1,marvin hat,frames/retrieval/visual_crops/val/7a954faf-102...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/efe7dfaa-07e0-42d5-85eb-1e6f93409ab5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,1,plastic bottle,frames/retrieval/visual_crops/val/efe7dfaa-07e...
1,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,2,screwdriver,frames/retrieval/visual_crops/val/efe7dfaa-07e...
2,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,3,t wrench,frames/retrieval/visual_crops/val/efe7dfaa-07e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fe71b934-322a-45a1-862c-cd7c2db2c354_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,1,gamepad,frames/retrieval/visual_crops/val/fe71b934-322...
1,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,2,paper roll,frames/retrieval/visual_crops/val/fe71b934-322...
2,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,3,television,frames/retrieval/visual_crops/val/fe71b934-322...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f91c7008-f21c-4047-bfc1-d937787665e5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,1,scraper tool,frames/retrieval/visual_crops/val/f91c7008-f21...
1,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,3,stack of baskets,frames/retrieval/visual_crops/val/f91c7008-f21...
2,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,2,rolling stick,frames/retrieval/visual_crops/val/f91c7008-f21...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/70d3a98e-132b-4446-aa99-cab279318dc8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,2,serving spoon,frames/retrieval/visual_crops/val/70d3a98e-132...
1,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,3,stainless plate,frames/retrieval/visual_crops/val/70d3a98e-132...
2,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,1,water bottle,frames/retrieval/visual_crops/val/70d3a98e-132...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7ecce159-e45f-4e35-9289-f61abfa02147_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,1,plier,frames/retrieval/visual_crops/val/7ecce159-e45...
1,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,2,brush broom,frames/retrieval/visual_crops/val/7ecce159-e45...
2,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,3,creeper seat,frames/retrieval/visual_crops/val/7ecce159-e45...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6bfb9000-73c2-4698-8757-889251a4b5e9_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,1,marvin,frames/retrieval/visual_crops/val/6bfb9000-73c...
1,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,3,tie box,frames/retrieval/visual_crops/val/6bfb9000-73c...
2,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,2,purse,frames/retrieval/visual_crops/val/6bfb9000-73c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0df1db1f-40a0-4139-b120-9a1c741f571c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,2,cake,frames/retrieval/visual_crops/val/0df1db1f-40a...
1,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,1,basket trolley,frames/retrieval/visual_crops/val/0df1db1f-40a...
2,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,3,calculator,frames/retrieval/visual_crops/val/0df1db1f-40a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,1,lamp shade,frames/retrieval/visual_crops/val/8b1676e2-8a9...
1,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,2,desk top,frames/retrieval/visual_crops/val/8b1676e2-8a9...
2,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,3,plant pot,frames/retrieval/visual_crops/val/8b1676e2-8a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f54175da-19e5-4ee7-97b3-75baa247b713_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,3,scoop,frames/retrieval/visual_crops/val/f54175da-19e...
1,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,1,bowl,frames/retrieval/visual_crops/val/f54175da-19e...
2,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,2,chair,frames/retrieval/visual_crops/val/f54175da-19e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,1,garage spray,frames/retrieval/visual_crops/val/1b0d8f14-d03...
1,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,2,cutting pliers,frames/retrieval/visual_crops/val/1b0d8f14-d03...
2,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,3,brake rotor,frames/retrieval/visual_crops/val/1b0d8f14-d03...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a408cff1-1387-421f-aad6-7480899a4fe0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,1,scarf,frames/retrieval/visual_crops/val/a408cff1-138...
1,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,3,mirror,frames/retrieval/visual_crops/val/a408cff1-138...
2,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,2,cloth.,frames/retrieval/visual_crops/val/a408cff1-138...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/17e7a80c-b5ca-435f-a29e-0d026fcf2e96_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,2,gloves,frames/retrieval/visual_crops/val/17e7a80c-b5c...
1,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,1,scissor,frames/retrieval/visual_crops/val/17e7a80c-b5c...
2,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,3,sandals,frames/retrieval/visual_crops/val/17e7a80c-b5c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ea365183-5841-4f00-9a2e-1b81c5e09c98_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,1,spray bottle,frames/retrieval/visual_crops/val/ea365183-584...
1,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,3,red jerry can,frames/retrieval/visual_crops/val/ea365183-584...
2,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,2,orange shock absorber,frames/retrieval/visual_crops/val/ea365183-584...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/67c47998-eabe-4b31-9096-b286c18e1beb_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,1,basket,frames/retrieval/visual_crops/val/67c47998-eab...
1,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,2,wallet,frames/retrieval/visual_crops/val/67c47998-eab...
2,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,3,receipt,frames/retrieval/visual_crops/val/67c47998-eab...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e118e100-cc06-48c5-a542-e07c44d72469_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,1,bottle,frames/retrieval/visual_crops/val/e118e100-cc0...
1,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,3,bottle,frames/retrieval/visual_crops/val/e118e100-cc0...
2,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,2,wire,frames/retrieval/visual_crops/val/e118e100-cc0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d9d45d26-743b-4e26-8137-416372bdaddb_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,2,calculator,frames/retrieval/visual_crops/val/d9d45d26-743...
1,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,1,sample bottle,frames/retrieval/visual_crops/val/d9d45d26-743...
2,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,3,container,frames/retrieval/visual_crops/val/d9d45d26-743...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f052ac6f-832d-41f0-b00f-7cb85c20a15c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,1,plastic container,frames/retrieval/visual_crops/val/f052ac6f-832...
1,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,3,paper towel,frames/retrieval/visual_crops/val/f052ac6f-832...
2,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,2,toothbrush,frames/retrieval/visual_crops/val/f052ac6f-832...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,1,kettle,frames/retrieval/visual_crops/val/1eb0ae30-d0b...
1,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,2,tissue,frames/retrieval/visual_crops/val/1eb0ae30-d0b...
2,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,3,stand mixer,frames/retrieval/visual_crops/val/1eb0ae30-d0b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/64cc6d12-f613-452f-b56b-451f395c9c10_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,3,coffee maker,frames/retrieval/visual_crops/val/64cc6d12-f61...
1,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,2,remote,frames/retrieval/visual_crops/val/64cc6d12-f61...
2,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,1,television,frames/retrieval/visual_crops/val/64cc6d12-f61...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/706c54f8-2740-40bb-a341-651b708392fa_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,1,scissor,frames/retrieval/visual_crops/val/706c54f8-274...
1,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,2,tweezer,frames/retrieval/visual_crops/val/706c54f8-274...
2,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,3,torch,frames/retrieval/visual_crops/val/706c54f8-274...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/02089b3c-2c7a-430b-9c7c-9c3f39249ec7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,2,vacuum cleaner,frames/retrieval/visual_crops/val/02089b3c-2c7...
1,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,1,battery,frames/retrieval/visual_crops/val/02089b3c-2c7...
2,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,3,frame,frames/retrieval/visual_crops/val/02089b3c-2c7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/293a2530-a4a8-4776-92d5-741142dfdd3e_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,1,cooking pan,frames/retrieval/visual_crops/val/293a2530-a4a...
1,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,3,bucket,frames/retrieval/visual_crops/val/293a2530-a4a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b7eaf50a-2499-45bd-abd8-478463fdc4a8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,1,coffee cup,frames/retrieval/visual_crops/val/b7eaf50a-249...
1,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,2,eggplant,frames/retrieval/visual_crops/val/b7eaf50a-249...
2,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,3,sack,frames/retrieval/visual_crops/val/b7eaf50a-249...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c908ae46-123b-466d-a709-99d4d4bc8d37_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,1,jug,frames/retrieval/visual_crops/val/c908ae46-123...
1,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,2,coffee table,frames/retrieval/visual_crops/val/c908ae46-123...
2,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,3,sport shoe,frames/retrieval/visual_crops/val/c908ae46-123...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,1,tape measure,frames/retrieval/visual_crops/val/2ceb0fb0-91f...
1,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,2,box,frames/retrieval/visual_crops/val/2ceb0fb0-91f...
2,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,3,timber,frames/retrieval/visual_crops/val/2ceb0fb0-91f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/30ca6fa7-dbe0-4f55-84c8-8797de99c290_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,3,flower pot,frames/retrieval/visual_crops/val/30ca6fa7-dbe...
1,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,1,pillows,frames/retrieval/visual_crops/val/30ca6fa7-dbe...
2,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,2,cloth,frames/retrieval/visual_crops/val/30ca6fa7-dbe...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/148d1a43-5368-4257-8e98-8a762ad1d113_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,2,long sleeved t-shirt,frames/retrieval/visual_crops/val/148d1a43-536...
1,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,1,shoes,frames/retrieval/visual_crops/val/148d1a43-536...
2,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,3,marvin,frames/retrieval/visual_crops/val/148d1a43-536...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/21e4b10c-e1c2-4b11-bee3-9528e61b56e3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,3,bottle,frames/retrieval/visual_crops/val/21e4b10c-e1c...
1,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,1,pos machine,frames/retrieval/visual_crops/val/21e4b10c-e1c...
2,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,2,phone,frames/retrieval/visual_crops/val/21e4b10c-e1c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a71f6663-ef4b-4283-8210-652b21b37a36_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,1,brush,frames/retrieval/visual_crops/val/a71f6663-ef4...
1,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,2,impact wrench,frames/retrieval/visual_crops/val/a71f6663-ef4...
2,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,3,container,frames/retrieval/visual_crops/val/a71f6663-ef4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/eb0359b2-72f1-40ff-ba22-64bb818d1f48_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,2,shopping basket,frames/retrieval/visual_crops/val/eb0359b2-72f...
1,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,1,boots,frames/retrieval/visual_crops/val/eb0359b2-72f...
2,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,3,wallet,frames/retrieval/visual_crops/val/eb0359b2-72f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7b452799-981c-494a-affb-d011cd5c43e5_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,1,plastic bowl,frames/retrieval/visual_crops/val/7b452799-981...
1,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,2,liquid soap bottle,frames/retrieval/visual_crops/val/7b452799-981...
2,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,3,kettle,frames/retrieval/visual_crops/val/7b452799-981...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/714ee146-e130-439d-89ff-6876efe62b07_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,1,phone,frames/retrieval/visual_crops/val/714ee146-e13...
1,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,2,cup,frames/retrieval/visual_crops/val/714ee146-e13...
2,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,3,knife,frames/retrieval/visual_crops/val/714ee146-e13...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/16fce853-9528-4c39-9f88-b0c61f30d01d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,2,shears,frames/retrieval/visual_crops/val/16fce853-952...
1,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,3,grapes,frames/retrieval/visual_crops/val/16fce853-952...
2,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,1,crate,frames/retrieval/visual_crops/val/16fce853-952...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/90288170-a577-48e6-afe6-014673ae8723_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,1,tin,frames/retrieval/visual_crops/val/90288170-a57...
1,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,3,metal basin,frames/retrieval/visual_crops/val/90288170-a57...
2,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,2,winnowing basket,frames/retrieval/visual_crops/val/90288170-a57...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/593a5700-05d7-46ba-a2c2-c5150b514144_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,1,paper,frames/retrieval/visual_crops/val/593a5700-05d...
1,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,2,sack,frames/retrieval/visual_crops/val/593a5700-05d...
2,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,3,slippers,frames/retrieval/visual_crops/val/593a5700-05d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1e938429-6376-4bc8-a145-7225f885e026_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,1,pair of scissors,frames/retrieval/visual_crops/val/1e938429-637...
1,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,2,cellphone,frames/retrieval/visual_crops/val/1e938429-637...
2,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,3,spoon,frames/retrieval/visual_crops/val/1e938429-637...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/56c1dc45-24f5-45aa-8273-ed5835bce1f3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,1,weighing scale,frames/retrieval/visual_crops/val/56c1dc45-24f...
1,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,2,shopping basket,frames/retrieval/visual_crops/val/56c1dc45-24f...
2,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,3,sauce bottle,frames/retrieval/visual_crops/val/56c1dc45-24f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/635733d7-8863-47b0-a7e2-4a0365813723_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,1,yellow tin,frames/retrieval/visual_crops/val/635733d7-886...
1,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,2,spray bottle,frames/retrieval/visual_crops/val/635733d7-886...
2,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,3,plate,frames/retrieval/visual_crops/val/635733d7-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d0bae6e6-356e-459d-b3dc-bc53c710611b_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,1,flower pot,frames/retrieval/visual_crops/val/d0bae6e6-356...
1,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,2,safety sign,frames/retrieval/visual_crops/val/d0bae6e6-356...
2,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,3,spray bottle,frames/retrieval/visual_crops/val/d0bae6e6-356...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/26f6ea45-4e7d-4208-b36c-715064151980_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,1,sponge,frames/retrieval/visual_crops/val/26f6ea45-4e7...
1,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,3,sieve,frames/retrieval/visual_crops/val/26f6ea45-4e7...
2,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,2,brush,frames/retrieval/visual_crops/val/26f6ea45-4e7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ddb94361-b4c3-4343-8a80-daad1ea69476_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,1,book stand,frames/retrieval/visual_crops/val/ddb94361-b4c...
1,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,3,house plant,frames/retrieval/visual_crops/val/ddb94361-b4c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ae935a5-3266-47e0-884d-f8b8acb5ed1c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,2,tablet,frames/retrieval/visual_crops/val/2ae935a5-326...
1,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,1,memory card,frames/retrieval/visual_crops/val/2ae935a5-326...
2,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,3,fire extinguisher,frames/retrieval/visual_crops/val/2ae935a5-326...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e4daf535-ef9c-493f-9688-9c2ba35d431a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,1,lightning connector,frames/retrieval/visual_crops/val/e4daf535-ef9...
1,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,3,water bottle,frames/retrieval/visual_crops/val/e4daf535-ef9...
2,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,2,towel,frames/retrieval/visual_crops/val/e4daf535-ef9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/918f04d6-65f3-4a8f-af65-b57852de1729_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,1,flower pot,frames/retrieval/visual_crops/val/918f04d6-65f...
1,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,2,rack,frames/retrieval/visual_crops/val/918f04d6-65f...
2,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,3,mop stick,frames/retrieval/visual_crops/val/918f04d6-65f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bd600d49-9db0-4e6f-8698-cf18f3cef8a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,3,trolley,frames/retrieval/visual_crops/val/bd600d49-9db...
1,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,1,nylon roll,frames/retrieval/visual_crops/val/bd600d49-9db...
2,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,2,stainless bowl,frames/retrieval/visual_crops/val/bd600d49-9db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/85b01a98-245e-4b63-bff8-4545aedaf916_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,1,shopping basket,frames/retrieval/visual_crops/val/85b01a98-245...
1,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,2,oreo biscuits,frames/retrieval/visual_crops/val/85b01a98-245...
2,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,3,warning sigh,frames/retrieval/visual_crops/val/85b01a98-245...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b27d698c-ce47-47ed-86e7-652cef7d3e2c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,1,plastic bucket,frames/retrieval/visual_crops/val/b27d698c-ce4...
1,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,3,jug,frames/retrieval/visual_crops/val/b27d698c-ce4...
2,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,2,plate,frames/retrieval/visual_crops/val/b27d698c-ce4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ab141ed-312d-4db3-a424-433e417e15ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,1,scissors,frames/retrieval/visual_crops/val/5ab141ed-312...
1,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,2,container,frames/retrieval/visual_crops/val/5ab141ed-312...
2,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,3,pot,frames/retrieval/visual_crops/val/5ab141ed-312...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7bb5593c-c017-4e68-aa69-0bc2bb50e2a1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,1,bicycle,frames/retrieval/visual_crops/val/7bb5593c-c01...
1,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,2,tissue,frames/retrieval/visual_crops/val/7bb5593c-c01...
2,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,3,dust pan and brush,frames/retrieval/visual_crops/val/7bb5593c-c01...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3d1bc6e6-e445-4748-9b08-727a1ce2e697_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,1,toolbox,frames/retrieval/visual_crops/val/3d1bc6e6-e44...
1,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,2,ladder,frames/retrieval/visual_crops/val/3d1bc6e6-e44...
2,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,3,container,frames/retrieval/visual_crops/val/3d1bc6e6-e44...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fc838ebc-2c4e-42f2-8108-9710ecb1653a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,2,trash can,frames/retrieval/visual_crops/val/fc838ebc-2c4...
1,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,3,bottle,frames/retrieval/visual_crops/val/fc838ebc-2c4...
2,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,1,a phone,frames/retrieval/visual_crops/val/fc838ebc-2c4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/50e73fa7-8ca7-41a3-a326-bc0b4a2f1482_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,1,basket,frames/retrieval/visual_crops/val/50e73fa7-8ca...
1,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,3,grocery bag,frames/retrieval/visual_crops/val/50e73fa7-8ca...
2,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,2,trolley,frames/retrieval/visual_crops/val/50e73fa7-8ca...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/48a81e63-9f9e-48c1-84e0-5fb90549cc4e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,1,paint brush,frames/retrieval/visual_crops/val/48a81e63-9f9...
1,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,3,polytene bag,frames/retrieval/visual_crops/val/48a81e63-9f9...
2,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,2,bucket,frames/retrieval/visual_crops/val/48a81e63-9f9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/63f79304-5e02-415b-b375-73a39b8b4271_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,63f79304-5e02-415b-b375-73a39b8b4271,ee858c8b-6293-4055-bcd0-b9e78b03ae1f,2,scissors,frames/retrieval/visual_crops/val/63f79304-5e0...
1,63f79304-5e02-415b-b375-73a39b8b4271,ee858c8b-6293-4055-bcd0-b9e78b03ae1f,3,brown box,frames/retrieval/visual_crops/val/63f79304-5e0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0432e5c6-d2e3-4729-bf1e-0ea8803687ee_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,1,frame,frames/retrieval/visual_crops/val/0432e5c6-d2e...
1,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,2,fluffy toy,frames/retrieval/visual_crops/val/0432e5c6-d2e...
2,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,3,brush,frames/retrieval/visual_crops/val/0432e5c6-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,3,kitchen towel,frames/retrieval/visual_crops/val/19ad94cc-302...
1,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,2,umbrella,frames/retrieval/visual_crops/val/19ad94cc-302...
2,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,1,scissors,frames/retrieval/visual_crops/val/19ad94cc-302...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c16cc2f1-a2a8-42f4-82f3-6867f9b6da12_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,1,guitar,frames/retrieval/visual_crops/val/c16cc2f1-a2a...
1,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,2,paper,frames/retrieval/visual_crops/val/c16cc2f1-a2a...
2,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,3,container,frames/retrieval/visual_crops/val/c16cc2f1-a2a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,1,bowl,frames/retrieval/visual_crops/val/b4e513cf-28d...
1,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,2,spoon,frames/retrieval/visual_crops/val/b4e513cf-28d...
2,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,3,bowl,frames/retrieval/visual_crops/val/b4e513cf-28d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cafcebbb-d1c1-439b-8228-3bd95b8d3b7f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,1,crate,frames/retrieval/visual_crops/val/cafcebbb-d1c...
1,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,2,shears,frames/retrieval/visual_crops/val/cafcebbb-d1c...
2,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,3,grapes,frames/retrieval/visual_crops/val/cafcebbb-d1c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/79cc2baa-4289-44f2-a013-ac6943b3f35d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,1,phone,frames/retrieval/visual_crops/val/79cc2baa-428...
1,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,2,liquid wash,frames/retrieval/visual_crops/val/79cc2baa-428...
2,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,3,earphones,frames/retrieval/visual_crops/val/79cc2baa-428...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e4728a65-3184-4239-9b84-be43dfd7377e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,2,jug,frames/retrieval/visual_crops/val/e4728a65-318...
1,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,3,wood cutting machine,frames/retrieval/visual_crops/val/e4728a65-318...
2,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,1,container,frames/retrieval/visual_crops/val/e4728a65-318...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/925b50c0-c5d7-48dc-877a-c5a2593b70d6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,2,spanner,frames/retrieval/visual_crops/val/925b50c0-c5d...
1,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,3,tool box,frames/retrieval/visual_crops/val/925b50c0-c5d...
2,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,1,tissue paper,frames/retrieval/visual_crops/val/925b50c0-c5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6f3c6977-b9dc-40de-bd32-349567343f0a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,3,bottle,frames/retrieval/visual_crops/val/6f3c6977-b9d...
1,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,1,pen,frames/retrieval/visual_crops/val/6f3c6977-b9d...
2,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,2,baloon,frames/retrieval/visual_crops/val/6f3c6977-b9d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/88f358c1-b11a-4868-aaf4-e1cb273c4b8a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,2,chair,frames/retrieval/visual_crops/val/88f358c1-b11...
1,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,3,container,frames/retrieval/visual_crops/val/88f358c1-b11...
2,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,1,dough press,frames/retrieval/visual_crops/val/88f358c1-b11...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0858668c-35b2-4593-acb0-f6d4a8da483d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,2,shopping basket,frames/retrieval/visual_crops/val/0858668c-35b...
1,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,1,weighing scale,frames/retrieval/visual_crops/val/0858668c-35b...
2,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,3,stand,frames/retrieval/visual_crops/val/0858668c-35b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2809b5d6-4811-4f6a-8621-4f0f89b697a8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,1,pen,frames/retrieval/visual_crops/val/2809b5d6-481...
1,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,2,jerrycan,frames/retrieval/visual_crops/val/2809b5d6-481...
2,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,3,green cello tape,frames/retrieval/visual_crops/val/2809b5d6-481...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b9c96242-ae4d-4a43-a308-a00591f060ab_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,1,keyboard,frames/retrieval/visual_crops/val/b9c96242-ae4...
1,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,2,tissue box,frames/retrieval/visual_crops/val/b9c96242-ae4...
2,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,3,electric kettle,frames/retrieval/visual_crops/val/b9c96242-ae4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/151c66b5-bdb2-42ba-b663-8ef307223d7a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,2,paint tin,frames/retrieval/visual_crops/val/151c66b5-bdb...
1,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,1,paint palette try,frames/retrieval/visual_crops/val/151c66b5-bdb...
2,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,3,throw pillows,frames/retrieval/visual_crops/val/151c66b5-bdb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/045dafcd-1ae7-443c-9a55-cd6b390372b3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,2,cup,frames/retrieval/visual_crops/val/045dafcd-1ae...
1,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,1,bottle,frames/retrieval/visual_crops/val/045dafcd-1ae...
2,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,3,phone,frames/retrieval/visual_crops/val/045dafcd-1ae...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/48d9f08a-abe2-471f-9c2b-4d8e67f33d59_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,1,book,frames/retrieval/visual_crops/val/48d9f08a-abe...
1,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,2,cup,frames/retrieval/visual_crops/val/48d9f08a-abe...
2,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,3,house plant,frames/retrieval/visual_crops/val/48d9f08a-abe...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc994557-a65b-48a9-94c6-122ede470347_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,2,exercise ball,frames/retrieval/visual_crops/val/cc994557-a65...
1,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,3,remote control,frames/retrieval/visual_crops/val/cc994557-a65...
2,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,1,phone,frames/retrieval/visual_crops/val/cc994557-a65...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/54892083-4f4a-4535-b0c9-8babf21492f2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,1,water bottle,frames/retrieval/visual_crops/val/54892083-4f4...
1,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,2,cap,frames/retrieval/visual_crops/val/54892083-4f4...
2,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,3,syringe tube,frames/retrieval/visual_crops/val/54892083-4f4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d28999ab-8945-4618-aa50-b37594573391_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,1,magazine,frames/retrieval/visual_crops/val/d28999ab-894...
1,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,2,nut bottle,frames/retrieval/visual_crops/val/d28999ab-894...
2,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,3,cake,frames/retrieval/visual_crops/val/d28999ab-894...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/01b451af-466a-4425-8094-be0b2ffc0e36_query_metadata.parquet
Shape: (1, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,01b451af-466a-4425-8094-be0b2ffc0e36,41a71f4b-d87b-4047-a553-eb0927b590e2,1,green hose,frames/retrieval/visual_crops/val/01b451af-466...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/022f1dbb-0018-4660-a18c-9e1213b88928_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,1,water bottle,frames/retrieval/visual_crops/val/022f1dbb-001...
1,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,2,playing cards,frames/retrieval/visual_crops/val/022f1dbb-001...
2,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,3,spraying can,frames/retrieval/visual_crops/val/022f1dbb-001...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,2,bicycle tube,frames/retrieval/visual_crops/val/ac85fd41-ff1...
1,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,1,plier,frames/retrieval/visual_crops/val/ac85fd41-ff1...
2,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,3,screwdriver,frames/retrieval/visual_crops/val/ac85fd41-ff1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d029947a-03c7-4f43-86ef-8067e172b410_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,1,bottle,frames/retrieval/visual_crops/val/d029947a-03c...
1,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,2,paper,frames/retrieval/visual_crops/val/d029947a-03c...
2,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,3,trolley,frames/retrieval/visual_crops/val/d029947a-03c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b961eb69-cfdd-4d5c-b427-4b667fedfcda_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,1,weighing scale,frames/retrieval/visual_crops/val/b961eb69-cfd...
1,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,2,chair,frames/retrieval/visual_crops/val/b961eb69-cfd...
2,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,3,shopping list,frames/retrieval/visual_crops/val/b961eb69-cfd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e7af8550-5a98-406a-b4a0-e8cf9f901d79_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,2,hose,frames/retrieval/visual_crops/val/e7af8550-5a9...
1,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,1,phone,frames/retrieval/visual_crops/val/e7af8550-5a9...
2,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,3,rim,frames/retrieval/visual_crops/val/e7af8550-5a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bc576c20-68d9-47bc-9d04-b7e0bfc67abb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,2,plate,frames/retrieval/visual_crops/val/bc576c20-68d...
1,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,1,decorative flower,frames/retrieval/visual_crops/val/bc576c20-68d...
2,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,3,decoration,frames/retrieval/visual_crops/val/bc576c20-68d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9737f5fb-d4b7-420c-98ee-471ec872c808_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,1,measuring cup,frames/retrieval/visual_crops/val/9737f5fb-d4b...
1,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,2,basin,frames/retrieval/visual_crops/val/9737f5fb-d4b...
2,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,3,scraper,frames/retrieval/visual_crops/val/9737f5fb-d4b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b58bc49e-d3ac-4995-baa0-218a14e4c2fa_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,2,container,frames/retrieval/visual_crops/val/b58bc49e-d3a...
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,1,plastic paper,frames/retrieval/visual_crops/val/b58bc49e-d3a...
2,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,3,nuts & bolts tin,frames/retrieval/visual_crops/val/b58bc49e-d3a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc711b14-cadc-40ef-b39f-611e57ec3956_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,2,sickle,frames/retrieval/visual_crops/val/cc711b14-cad...
1,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,3,plastic stool,frames/retrieval/visual_crops/val/cc711b14-cad...
2,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,1,maize scooper,frames/retrieval/visual_crops/val/cc711b14-cad...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5771acd7-c7a9-4350-8064-7763bf111149_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,1,phone,frames/retrieval/visual_crops/val/5771acd7-c7a...
1,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,2,busket,frames/retrieval/visual_crops/val/5771acd7-c7a...
2,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,3,oreo biscuits,frames/retrieval/visual_crops/val/5771acd7-c7a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/00e1c569-6c15-4447-8dd4-dfbe1f79dcdc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,1,container,frames/retrieval/visual_crops/val/00e1c569-6c1...
1,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,2,hand drill,frames/retrieval/visual_crops/val/00e1c569-6c1...
2,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,3,pliers,frames/retrieval/visual_crops/val/00e1c569-6c1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7380c46e-cb33-4d49-bf73-a7bfe57c3feb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,3,tong,frames/retrieval/visual_crops/val/7380c46e-cb3...
1,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,1,kettle,frames/retrieval/visual_crops/val/7380c46e-cb3...
2,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,2,paper towel,frames/retrieval/visual_crops/val/7380c46e-cb3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4479363e-cd84-4fe7-994e-02eaf4531b0b_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,1,spray bottle,frames/retrieval/visual_crops/val/4479363e-cd8...
1,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,2,battery,frames/retrieval/visual_crops/val/4479363e-cd8...
2,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,3,plastic bottle.,frames/retrieval/visual_crops/val/4479363e-cd8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5e961d49-5eb3-4d6d-b2f0-c9be437ba623_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,3,remote,frames/retrieval/visual_crops/val/5e961d49-5eb...
1,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,2,gamepad,frames/retrieval/visual_crops/val/5e961d49-5eb...
2,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,1,television,frames/retrieval/visual_crops/val/5e961d49-5eb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ce57cce9-c6c4-4e07-be46-a84b29e7462c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,1,trash bin,frames/retrieval/visual_crops/val/ce57cce9-c6c...
1,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,2,book,frames/retrieval/visual_crops/val/ce57cce9-c6c...
2,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,3,bottle,frames/retrieval/visual_crops/val/ce57cce9-c6c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/43ecb12f-8b33-416f-8c22-5c4544ed2370_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,1,bottle,frames/retrieval/visual_crops/val/43ecb12f-8b3...
1,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,2,pot,frames/retrieval/visual_crops/val/43ecb12f-8b3...
2,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,3,shoes,frames/retrieval/visual_crops/val/43ecb12f-8b3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d4196bb5-daf8-49f7-9010-bcc5797583d3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,3,beanie hat,frames/retrieval/visual_crops/val/d4196bb5-daf...
1,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,1,boots,frames/retrieval/visual_crops/val/d4196bb5-daf...
2,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,2,advert bilboard,frames/retrieval/visual_crops/val/d4196bb5-daf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/efc97e5a-20a0-42f1-9cfd-fcede9bbe043_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,1,wood,frames/retrieval/visual_crops/val/efc97e5a-20a...
1,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,2,polyethene bag,frames/retrieval/visual_crops/val/efc97e5a-20a...
2,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,3,vacuum cleaner,frames/retrieval/visual_crops/val/efc97e5a-20a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/61f93683-2f3d-4d44-867d-c980d9316775_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,1,doormat,frames/retrieval/visual_crops/val/61f93683-2f3...
1,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,2,polythene bag,frames/retrieval/visual_crops/val/61f93683-2f3...
2,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,3,wrapper,frames/retrieval/visual_crops/val/61f93683-2f3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b144e06c-ac25-4584-9ff4-93d6a8d04865_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,1,basket,frames/retrieval/visual_crops/val/b144e06c-ac2...
1,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,2,phone,frames/retrieval/visual_crops/val/b144e06c-ac2...
2,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,3,mirror,frames/retrieval/visual_crops/val/b144e06c-ac2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/617e8d7c-8764-4508-ba9b-c993282c70cd_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,3,parker,frames/retrieval/visual_crops/val/617e8d7c-876...
1,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,1,pliers,frames/retrieval/visual_crops/val/617e8d7c-876...
2,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,2,container,frames/retrieval/visual_crops/val/617e8d7c-876...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4eddd9cf-ce91-4273-8184-a88e7255a65e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,3,bowl,frames/retrieval/visual_crops/val/4eddd9cf-ce9...
1,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,1,gas cooker,frames/retrieval/visual_crops/val/4eddd9cf-ce9...
2,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,2,jerrycan,frames/retrieval/visual_crops/val/4eddd9cf-ce9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,1,plastic bowl,frames/retrieval/visual_crops/val/5ba7c109-3a1...
1,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,2,cup,frames/retrieval/visual_crops/val/5ba7c109-3a1...
2,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,3,pot,frames/retrieval/visual_crops/val/5ba7c109-3a1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1b0aed98-785d-4471-ad38-940ca8673030_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,1,flower basket,frames/retrieval/visual_crops/val/1b0aed98-785...
1,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,2,television,frames/retrieval/visual_crops/val/1b0aed98-785...
2,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,3,box,frames/retrieval/visual_crops/val/1b0aed98-785...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/38dc82c8-d59a-4ef9-818c-c3affb046e17_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,1,lighter,frames/retrieval/visual_crops/val/38dc82c8-d59...
1,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,2,sellotape,frames/retrieval/visual_crops/val/38dc82c8-d59...
2,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,3,chisel,frames/retrieval/visual_crops/val/38dc82c8-d59...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b0612ea7-11f9-486e-a4aa-e0f8ba67e2df_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,1,drill,frames/retrieval/visual_crops/val/b0612ea7-11f...
1,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,2,hammer,frames/retrieval/visual_crops/val/b0612ea7-11f...
2,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,3,tin,frames/retrieval/visual_crops/val/b0612ea7-11f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fd82660b-9650-4326-93fc-08b1b950ac9d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,1,tin,frames/retrieval/visual_crops/val/fd82660b-965...
1,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,2,box,frames/retrieval/visual_crops/val/fd82660b-965...
2,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,3,spade,frames/retrieval/visual_crops/val/fd82660b-965...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/daee0288-b01a-4fc4-bcd8-3884846d829d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,2,paint bucket,frames/retrieval/visual_crops/val/daee0288-b01...
1,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,1,scissors,frames/retrieval/visual_crops/val/daee0288-b01...
2,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,3,plier,frames/retrieval/visual_crops/val/daee0288-b01...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72eee417-f3cb-47dc-8266-24277c2307e2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,1,bottle,frames/retrieval/visual_crops/val/72eee417-f3c...
1,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,2,vase,frames/retrieval/visual_crops/val/72eee417-f3c...
2,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,3,package,frames/retrieval/visual_crops/val/72eee417-f3c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/39b791e1-7e1c-4c3e-bd68-e6598ef8694b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,1,fire hydrant,frames/retrieval/visual_crops/val/39b791e1-7e1...
1,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,2,freshener,frames/retrieval/visual_crops/val/39b791e1-7e1...
2,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,3,television,frames/retrieval/visual_crops/val/39b791e1-7e1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/260ec80b-f26a-4646-afc5-616481889643_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,1,bag,frames/retrieval/visual_crops/val/260ec80b-f26...
1,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,2,spectacles,frames/retrieval/visual_crops/val/260ec80b-f26...
2,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,3,hanger,frames/retrieval/visual_crops/val/260ec80b-f26...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/95685c3a-9604-4fa3-a6e0-3d27a67fb3ad_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,2,earthgro,frames/retrieval/visual_crops/val/95685c3a-960...
1,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,1,cloth,frames/retrieval/visual_crops/val/95685c3a-960...
2,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,3,bottle,frames/retrieval/visual_crops/val/95685c3a-960...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,2,cloth,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...
1,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,1,laundry bag,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...
2,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,3,luggage,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0c2cc98f-0b4f-4820-8687-e12483cf4d0a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,2,broom,frames/retrieval/visual_crops/val/0c2cc98f-0b4...
1,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,1,table lamp,frames/retrieval/visual_crops/val/0c2cc98f-0b4...
2,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,3,side table,frames/retrieval/visual_crops/val/0c2cc98f-0b4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5333a996-877f-4e30-ba79-631131744a4b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,1,spray bottle,frames/retrieval/visual_crops/val/5333a996-877...
1,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,2,sink,frames/retrieval/visual_crops/val/5333a996-877...
2,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,3,jacuzzi,frames/retrieval/visual_crops/val/5333a996-877...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/db6e91d9-3006-46dd-af29-b74f725fe284_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,1,knife,frames/retrieval/visual_crops/val/db6e91d9-300...
1,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,3,rack,frames/retrieval/visual_crops/val/db6e91d9-300...
2,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,2,shoe,frames/retrieval/visual_crops/val/db6e91d9-300...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a051a8ce-cb33-40f8-a46e-1a3a263de18f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,2,dogs reflector,frames/retrieval/visual_crops/val/a051a8ce-cb3...
1,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,1,ball,frames/retrieval/visual_crops/val/a051a8ce-cb3...
2,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,3,picnic table,frames/retrieval/visual_crops/val/a051a8ce-cb3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f8bdd228-ef92-43e3-bf6f-086ff54d5c78_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,1,game pad,frames/retrieval/visual_crops/val/f8bdd228-ef9...
1,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,2,remote,frames/retrieval/visual_crops/val/f8bdd228-ef9...
2,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,3,vase,frames/retrieval/visual_crops/val/f8bdd228-ef9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e0fdd4e0-cccf-423c-9629-9b234e4a458f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,1,tissue roll,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...
1,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,2,spray bottle,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...
2,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,3,litter bin,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d111f736-d02a-43f4-8968-2b6631138d84_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,3,rim,frames/retrieval/visual_crops/val/d111f736-d02...
1,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,1,rolling creeper,frames/retrieval/visual_crops/val/d111f736-d02...
2,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,2,motor oil bottle,frames/retrieval/visual_crops/val/d111f736-d02...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/21af903a-6c19-4854-afe0-009d81849867_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,3,tissue paper,frames/retrieval/visual_crops/val/21af903a-6c1...
1,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,1,bottle,frames/retrieval/visual_crops/val/21af903a-6c1...
2,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,2,bowl,frames/retrieval/visual_crops/val/21af903a-6c1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8f1770e5-612c-4047-a7b7-a6157460bc24_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,1,television,frames/retrieval/visual_crops/val/8f1770e5-612...
1,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,2,cup,frames/retrieval/visual_crops/val/8f1770e5-612...
2,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,3,trash can,frames/retrieval/visual_crops/val/8f1770e5-612...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9671fc0-7e56-4e98-842a-dfbbd99d385f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,1,cup,frames/retrieval/visual_crops/val/f9671fc0-7e5...
1,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,2,jenga block,frames/retrieval/visual_crops/val/f9671fc0-7e5...
2,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,3,play station pad,frames/retrieval/visual_crops/val/f9671fc0-7e5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c552b2d7-9d27-4765-9dce-8223581c1ca7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,1,training ball,frames/retrieval/visual_crops/val/c552b2d7-9d2...
1,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,3,mat,frames/retrieval/visual_crops/val/c552b2d7-9d2...
2,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,2,television,frames/retrieval/visual_crops/val/c552b2d7-9d2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d149e4b3-a919-4deb-a088-4fe245896ef2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,1,watering can,frames/retrieval/visual_crops/val/d149e4b3-a91...
1,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,2,garden broom,frames/retrieval/visual_crops/val/d149e4b3-a91...
2,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,3,firewood,frames/retrieval/visual_crops/val/d149e4b3-a91...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/17043256-42c5-4e4f-846b-7923afe3ead4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,1,vase,frames/retrieval/visual_crops/val/17043256-42c...
1,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,2,game controller,frames/retrieval/visual_crops/val/17043256-42c...
2,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,3,laundry basket,frames/retrieval/visual_crops/val/17043256-42c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5aa0d7aa-21af-4bfc-a204-f05554a3933e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,1,cutter,frames/retrieval/visual_crops/val/5aa0d7aa-21a...
1,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,2,dustbin,frames/retrieval/visual_crops/val/5aa0d7aa-21a...
2,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,3,bucket,frames/retrieval/visual_crops/val/5aa0d7aa-21a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,1,tennis ball,frames/retrieval/visual_crops/val/dab3cd5d-ad3...
1,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,2,bottle,frames/retrieval/visual_crops/val/dab3cd5d-ad3...
2,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,3,dustbin,frames/retrieval/visual_crops/val/dab3cd5d-ad3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1e666456-2299-47ff-af7c-8bda73f825ea_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,1,plate,frames/retrieval/visual_crops/val/1e666456-229...
1,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,3,packet of chips,frames/retrieval/visual_crops/val/1e666456-229...
2,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,2,polythene bag,frames/retrieval/visual_crops/val/1e666456-229...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/20a6cd02-f686-46c3-b1e3-f3376a99ddc6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,3,box of ties,frames/retrieval/visual_crops/val/20a6cd02-f68...
1,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,2,shoes,frames/retrieval/visual_crops/val/20a6cd02-f68...
2,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,1,neck scarf,frames/retrieval/visual_crops/val/20a6cd02-f68...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/368755d7-886a-4b05-85f4-e3b3785a8d14_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,1,blower,frames/retrieval/visual_crops/val/368755d7-886...
1,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,2,tool box,frames/retrieval/visual_crops/val/368755d7-886...
2,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,3,tape measure,frames/retrieval/visual_crops/val/368755d7-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6c88216a-cf77-48f2-9dc4-ccb4cc5160f5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,1,drill,frames/retrieval/visual_crops/val/6c88216a-cf7...
1,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,2,tire,frames/retrieval/visual_crops/val/6c88216a-cf7...
2,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,3,wheel,frames/retrieval/visual_crops/val/6c88216a-cf7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4a491385-b165-49ec-a23b-7b0ed26737f9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,1,bowl,frames/retrieval/visual_crops/val/4a491385-b16...
1,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,2,rice cooker,frames/retrieval/visual_crops/val/4a491385-b16...
2,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,3,kettle,frames/retrieval/visual_crops/val/4a491385-b16...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f0a86b75-fd8e-43dd-95ee-401717b94f70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,1,book,frames/retrieval/visual_crops/val/f0a86b75-fd8...
1,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,2,mobile phone,frames/retrieval/visual_crops/val/f0a86b75-fd8...
2,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,3,scissors,frames/retrieval/visual_crops/val/f0a86b75-fd8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/afc253af-734c-4e67-b4c2-09384fcd1e93_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,2,metal bowl,frames/retrieval/visual_crops/val/afc253af-734...
1,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,1,liquid soap,frames/retrieval/visual_crops/val/afc253af-734...
2,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,3,kitchen mat,frames/retrieval/visual_crops/val/afc253af-734...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3e95b70a-e2b1-4d6f-a229-b07d4f8eadea_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,1,dough cutter,frames/retrieval/visual_crops/val/3e95b70a-e2b...
1,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,2,scrubber,frames/retrieval/visual_crops/val/3e95b70a-e2b...
2,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,3,weighing scale,frames/retrieval/visual_crops/val/3e95b70a-e2b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/afc5b8d0-3146-48f2-be24-c1490cfa766f_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,1,paint bucket,frames/retrieval/visual_crops/val/afc5b8d0-314...
1,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,2,slippers,frames/retrieval/visual_crops/val/afc5b8d0-314...
2,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,3,plastic jar,frames/retrieval/visual_crops/val/afc5b8d0-314...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d87774db-a324-4440-aa60-b39fe3276b77_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,1,book,frames/retrieval/visual_crops/val/d87774db-a32...
1,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,2,glove,frames/retrieval/visual_crops/val/d87774db-a32...
2,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,3,stool,frames/retrieval/visual_crops/val/d87774db-a32...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ba50504a-93ad-46bc-8433-0c1f89d21f78_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,1,scraper,frames/retrieval/visual_crops/val/ba50504a-93a...
1,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,2,paint bucket,frames/retrieval/visual_crops/val/ba50504a-93a...
2,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,3,cell phone,frames/retrieval/visual_crops/val/ba50504a-93a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b370b4cc-0a46-43a8-9b26-1aba0f71ee09_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,1,can,frames/retrieval/visual_crops/val/b370b4cc-0a4...
1,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,2,dustbin,frames/retrieval/visual_crops/val/b370b4cc-0a4...
2,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,3,pan,frames/retrieval/visual_crops/val/b370b4cc-0a4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/150bc185-821c-487f-b39c-4c5a0d52467d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,1,dustbin,frames/retrieval/visual_crops/val/150bc185-821...
1,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,3,puller slide hammer,frames/retrieval/visual_crops/val/150bc185-821...
2,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,2,fire extinguisher,frames/retrieval/visual_crops/val/150bc185-821...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3e654a1a-b706-456d-ab6d-565effcf159c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,1,trash can,frames/retrieval/visual_crops/val/3e654a1a-b70...
1,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,2,trash can,frames/retrieval/visual_crops/val/3e654a1a-b70...
2,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,3,desk,frames/retrieval/visual_crops/val/3e654a1a-b70...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,1,bin,frames/retrieval/visual_crops/val/b0ef48a2-dc6...
1,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,2,sanitizer,frames/retrieval/visual_crops/val/b0ef48a2-dc6...
2,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,3,basket,frames/retrieval/visual_crops/val/b0ef48a2-dc6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b47da6e2-cb60-4fd4-9705-5eb3af05877d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,1,flower basket,frames/retrieval/visual_crops/val/b47da6e2-cb6...
1,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,3,can,frames/retrieval/visual_crops/val/b47da6e2-cb6...
2,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,2,table lamp,frames/retrieval/visual_crops/val/b47da6e2-cb6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f835883d-2ef1-427d-9c2f-5d9e7670cf5e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,2,power bank,frames/retrieval/visual_crops/val/f835883d-2ef...
1,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,1,novel,frames/retrieval/visual_crops/val/f835883d-2ef...
2,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,3,cap,frames/retrieval/visual_crops/val/f835883d-2ef...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6dd3486b-59dd-4dc6-874a-e4d773273c8a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,1,bottle,frames/retrieval/visual_crops/val/6dd3486b-59d...
1,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,2,speed square,frames/retrieval/visual_crops/val/6dd3486b-59d...
2,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,3,marker pen,frames/retrieval/visual_crops/val/6dd3486b-59d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0080281f-4db1-4a49-9753-e70c41bd9bc7_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,1,measuring tape,frames/retrieval/visual_crops/val/0080281f-4db...
1,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,3,bottle,frames/retrieval/visual_crops/val/0080281f-4db...
2,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,2,brush,frames/retrieval/visual_crops/val/0080281f-4db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/36335d72-a5d7-4878-9f5b-9ff9635815b8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,1,painting brush,frames/retrieval/visual_crops/val/36335d72-a5d...
1,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,2,thread,frames/retrieval/visual_crops/val/36335d72-a5d...
2,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,3,needle,frames/retrieval/visual_crops/val/36335d72-a5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/73382127-39b0-4033-af91-4e310670a349_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,1,spraying bottle,frames/retrieval/visual_crops/val/73382127-39b...
1,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,2,piece of material,frames/retrieval/visual_crops/val/73382127-39b...
2,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,3,touch,frames/retrieval/visual_crops/val/73382127-39b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b8981cdd-a897-41b6-b1ef-e9957d270e9e_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,1,laptop,frames/retrieval/visual_crops/val/b8981cdd-a89...
1,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,2,microwave,frames/retrieval/visual_crops/val/b8981cdd-a89...
2,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,3,water can,frames/retrieval/visual_crops/val/b8981cdd-a89...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72479834-1994-44a8-a9a5-ae13b3417307_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,2,spraying bottle,frames/retrieval/visual_crops/val/72479834-199...
1,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,3,screw driver,frames/retrieval/visual_crops/val/72479834-199...
2,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,1,telephone,frames/retrieval/visual_crops/val/72479834-199...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/94106c40-8e3a-4018-a3fc-a86106979766_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,1,bicycle,frames/retrieval/visual_crops/val/94106c40-8e3...
1,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,2,bottle,frames/retrieval/visual_crops/val/94106c40-8e3...
2,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,3,vase,frames/retrieval/visual_crops/val/94106c40-8e3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72154f42-399c-4f95-a667-e26528d1f52a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,1,weighing scale,frames/retrieval/visual_crops/val/72154f42-399...
1,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,2,brown scraper,frames/retrieval/visual_crops/val/72154f42-399...
2,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,3,brown gloves,frames/retrieval/visual_crops/val/72154f42-399...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e355d07d-844b-44ff-bfab-c1fb98d48b6c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,1,basket,frames/retrieval/visual_crops/val/e355d07d-844...
1,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,2,splier,frames/retrieval/visual_crops/val/e355d07d-844...
2,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,3,bag,frames/retrieval/visual_crops/val/e355d07d-844...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,2,sellotape,frames/retrieval/visual_crops/val/a3d47c6b-f0e...
1,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,3,sandal,frames/retrieval/visual_crops/val/a3d47c6b-f0e...
2,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,1,bucket,frames/retrieval/visual_crops/val/a3d47c6b-f0e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8d22e91b-ed98-4c87-8a25-c937236ca745_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,1,box,frames/retrieval/visual_crops/val/8d22e91b-ed9...
1,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,2,lawn mower,frames/retrieval/visual_crops/val/8d22e91b-ed9...
2,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,3,bucket,frames/retrieval/visual_crops/val/8d22e91b-ed9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f4240b1c-c260-4354-a005-cfa8c8353f90_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,1,cable,frames/retrieval/visual_crops/val/f4240b1c-c26...
1,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,2,battery jump starter,frames/retrieval/visual_crops/val/f4240b1c-c26...
2,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,3,rachet,frames/retrieval/visual_crops/val/f4240b1c-c26...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/43f1faaa-6452-4125-a702-f319fdafcc4f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,1,scissors,frames/retrieval/visual_crops/val/43f1faaa-645...
1,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,2,paper,frames/retrieval/visual_crops/val/43f1faaa-645...
2,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,3,string,frames/retrieval/visual_crops/val/43f1faaa-645...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/83e54fdc-6336-439c-b8a5-44682989a329_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,1,hammer,frames/retrieval/visual_crops/val/83e54fdc-633...
1,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,2,dust pan,frames/retrieval/visual_crops/val/83e54fdc-633...
2,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,3,bucket,frames/retrieval/visual_crops/val/83e54fdc-633...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b8ddc75-2c96-4f73-8278-ff7f60920426_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,1,fire extinguisher,frames/retrieval/visual_crops/val/2b8ddc75-2c9...
1,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,3,pen,frames/retrieval/visual_crops/val/2b8ddc75-2c9...
2,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,2,plastic,frames/retrieval/visual_crops/val/2b8ddc75-2c9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b3864c6-50d7-46ff-9ab6-3d6831f741cc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,1,stainless steel basin,frames/retrieval/visual_crops/val/2b3864c6-50d...
1,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,2,rolling board,frames/retrieval/visual_crops/val/2b3864c6-50d...
2,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,3,pan,frames/retrieval/visual_crops/val/2b3864c6-50d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/145b7d46-a4f7-472e-8adf-08be3ed4062c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,1,cup,frames/retrieval/visual_crops/val/145b7d46-a4f...
1,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,2,phone,frames/retrieval/visual_crops/val/145b7d46-a4f...
2,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,3,cell tape,frames/retrieval/visual_crops/val/145b7d46-a4f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8059dcc2-0f52-46f8-a119-85c78d608602_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,1,knife,frames/retrieval/visual_crops/val/8059dcc2-0f5...
1,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,2,tray,frames/retrieval/visual_crops/val/8059dcc2-0f5...
2,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,3,dough,frames/retrieval/visual_crops/val/8059dcc2-0f5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2d76f374-48e5-4cef-8b6b-bc6f0c038d48_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,1,mesh strainer bowl,frames/retrieval/visual_crops/val/2d76f374-48e...
1,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,2,spatula,frames/retrieval/visual_crops/val/2d76f374-48e...
2,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,3,pan,frames/retrieval/visual_crops/val/2d76f374-48e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f04d9e03-3189-4ffb-a79a-2521355905bb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,2,bottle,frames/retrieval/visual_crops/val/f04d9e03-318...
1,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,1,cooking pot,frames/retrieval/visual_crops/val/f04d9e03-318...
2,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,3,phone,frames/retrieval/visual_crops/val/f04d9e03-318...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/70bce3b1-ffdf-412d-8b28-2c5a4978015f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,3,vacuum cleaner,frames/retrieval/visual_crops/val/70bce3b1-ffd...
1,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,1,adhesive gun,frames/retrieval/visual_crops/val/70bce3b1-ffd...
2,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,2,bucket,frames/retrieval/visual_crops/val/70bce3b1-ffd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8ae90b75-6ccf-417e-8c19-a63bf86a678d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,1,shoe rack,frames/retrieval/visual_crops/val/8ae90b75-6cc...
1,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,3,hat,frames/retrieval/visual_crops/val/8ae90b75-6cc...
2,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,2,t-shirt,frames/retrieval/visual_crops/val/8ae90b75-6cc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5e66abe8-a72b-43f3-b6bf-fc05a45ff80f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,1,bowl,frames/retrieval/visual_crops/val/5e66abe8-a72...
1,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,2,sack,frames/retrieval/visual_crops/val/5e66abe8-a72...
2,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,3,bottle,frames/retrieval/visual_crops/val/5e66abe8-a72...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b8e1c869-b304-49fc-ba5f-9a5ae3b3770c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,1,rice maker,frames/retrieval/visual_crops/val/b8e1c869-b30...
1,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,3,plastic tin,frames/retrieval/visual_crops/val/b8e1c869-b30...
2,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,2,tray,frames/retrieval/visual_crops/val/b8e1c869-b30...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/993b95b0-3ab2-4b31-a250-e6221a7d2864_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,2,cat house,frames/retrieval/visual_crops/val/993b95b0-3ab...
1,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,1,remote,frames/retrieval/visual_crops/val/993b95b0-3ab...
2,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,3,throw pillow,frames/retrieval/visual_crops/val/993b95b0-3ab...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dbd760b1-f99a-4a74-9f67-50579e516532_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,2,ball,frames/retrieval/visual_crops/val/dbd760b1-f99...
1,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,1,flowerpot,frames/retrieval/visual_crops/val/dbd760b1-f99...
2,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,3,box,frames/retrieval/visual_crops/val/dbd760b1-f99...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6ec2a3e6-f9cf-459b-815a-e8853ea7309c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,1,yellow cloth,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...
1,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,2,blue dress,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...
2,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,3,iron box,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/edfa156e-8e82-43cf-8a40-4f9be8f7c2e8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,1,jerrycan,frames/retrieval/visual_crops/val/edfa156e-8e8...
1,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,2,phone,frames/retrieval/visual_crops/val/edfa156e-8e8...
2,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,3,jack,frames/retrieval/visual_crops/val/edfa156e-8e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7dbdb00c-7652-487f-be2e-26a14c3f2145_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,1,wallet,frames/retrieval/visual_crops/val/7dbdb00c-765...
1,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,3,hand cutter,frames/retrieval/visual_crops/val/7dbdb00c-765...
2,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,2,flask,frames/retrieval/visual_crops/val/7dbdb00c-765...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72e90719-c2b8-4b17-b120-e904dbbf1184_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,1,tray,frames/retrieval/visual_crops/val/72e90719-c2b...
1,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,3,plastic water jar,frames/retrieval/visual_crops/val/72e90719-c2b...
2,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,2,pressure cooker,frames/retrieval/visual_crops/val/72e90719-c2b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/eaa07b51-b07d-4cf7-91e7-314a74c8edc6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,1,remote control,frames/retrieval/visual_crops/val/eaa07b51-b07...
1,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,2,pair of scissors,frames/retrieval/visual_crops/val/eaa07b51-b07...
2,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,3,television,frames/retrieval/visual_crops/val/eaa07b51-b07...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c0d616c8-fc59-40b7-aafe-f54c2d60a236_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,1,tray,frames/retrieval/visual_crops/val/c0d616c8-fc5...
1,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,2,jug,frames/retrieval/visual_crops/val/c0d616c8-fc5...
2,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,3,plastic container,frames/retrieval/visual_crops/val/c0d616c8-fc5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,2,wall art,frames/retrieval/visual_crops/val/cbd49e40-6bb...
1,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,1,dough,frames/retrieval/visual_crops/val/cbd49e40-6bb...
2,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,3,container==,frames/retrieval/visual_crops/val/cbd49e40-6bb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c8070026-c3dc-43d3-8d36-65c5d9a1317f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,1,gloves,frames/retrieval/visual_crops/val/c8070026-c3d...
1,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,2,golf stick,frames/retrieval/visual_crops/val/c8070026-c3d...
2,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,3,golf ball,frames/retrieval/visual_crops/val/c8070026-c3d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/14ea5c3e-bbb5-44cf-abcc-e70e1223ad74_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,1,basket,frames/retrieval/visual_crops/val/14ea5c3e-bbb...
1,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,2,bag,frames/retrieval/visual_crops/val/14ea5c3e-bbb...
2,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,3,bucket,frames/retrieval/visual_crops/val/14ea5c3e-bbb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5a7efdba-6701-4aaa-bff6-fbab6b293ed9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,3,cup,frames/retrieval/visual_crops/val/5a7efdba-670...
1,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,1,paper tape,frames/retrieval/visual_crops/val/5a7efdba-670...
2,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,2,phone,frames/retrieval/visual_crops/val/5a7efdba-670...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3c5b4041-8d0d-40ac-8750-1a7e744a38e5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,1,wood,frames/retrieval/visual_crops/val/3c5b4041-8d0...
1,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,2,deep frying pot,frames/retrieval/visual_crops/val/3c5b4041-8d0...
2,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,3,water bucket,frames/retrieval/visual_crops/val/3c5b4041-8d0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc7d11f0-445e-426a-904e-e7faafdb07f7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,3,kurta tunic,frames/retrieval/visual_crops/val/cc7d11f0-445...
1,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,1,iron box,frames/retrieval/visual_crops/val/cc7d11f0-445...
2,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,2,cloth,frames/retrieval/visual_crops/val/cc7d11f0-445...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/785960e0-5f8e-41eb-9290-27a755dad3ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,1,television,frames/retrieval/visual_crops/val/785960e0-5f8...
1,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,3,phone,frames/retrieval/visual_crops/val/785960e0-5f8...
2,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,2,cup,frames/retrieval/visual_crops/val/785960e0-5f8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1d2b62ed-fc94-4fb0-b547-8c50533b0b29_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,1,bucket,frames/retrieval/visual_crops/val/1d2b62ed-fc9...
1,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,2,sack,frames/retrieval/visual_crops/val/1d2b62ed-fc9...
2,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,3,bowl,frames/retrieval/visual_crops/val/1d2b62ed-fc9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c77d3785-22f9-46c9-bf6d-9f7196356749_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,3,tv decoder,frames/retrieval/visual_crops/val/c77d3785-22f...
1,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,2,gamepad,frames/retrieval/visual_crops/val/c77d3785-22f...
2,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,1,dog bed,frames/retrieval/visual_crops/val/c77d3785-22f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a4130ad1-bdcd-4de0-aa5e-09865e515ff3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,2,broom,frames/retrieval/visual_crops/val/a4130ad1-bdc...
1,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,1,bucket,frames/retrieval/visual_crops/val/a4130ad1-bdc...
2,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,3,phone,frames/retrieval/visual_crops/val/a4130ad1-bdc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2c9b9f23-8907-44a0-89e6-8f29d7b05828_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,1,can container,frames/retrieval/visual_crops/val/2c9b9f23-890...
1,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,2,bottle water,frames/retrieval/visual_crops/val/2c9b9f23-890...
2,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,3,paint brush,frames/retrieval/visual_crops/val/2c9b9f23-890...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7bb41f34-1743-42ad-97d1-c54f4472b85e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,1,carton box,frames/retrieval/visual_crops/val/7bb41f34-174...
1,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,2,bottle spray,frames/retrieval/visual_crops/val/7bb41f34-174...
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,3,bulb box,frames/retrieval/visual_crops/val/7bb41f34-174...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f1350714-1aa5-421b-a268-690110ca9c06_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,1,wheels,frames/retrieval/visual_crops/val/f1350714-1aa...
1,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,2,power drill,frames/retrieval/visual_crops/val/f1350714-1aa...
2,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,3,brake shoe,frames/retrieval/visual_crops/val/f1350714-1aa...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ec67faf9-2d1b-41a9-ad96-da31887ba60c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,2,playstation pad,frames/retrieval/visual_crops/val/ec67faf9-2d1...
1,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,1,remote control,frames/retrieval/visual_crops/val/ec67faf9-2d1...
2,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,3,mug,frames/retrieval/visual_crops/val/ec67faf9-2d1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7816c769-612c-4256-9bac-885a57ec513f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,1,oil bottle,frames/retrieval/visual_crops/val/7816c769-612...
1,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,2,lawn mower,frames/retrieval/visual_crops/val/7816c769-612...
2,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,3,bucket,frames/retrieval/visual_crops/val/7816c769-612...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3482d793-9492-49fa-b98a-770b116e8767_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,1,pan,frames/retrieval/visual_crops/val/3482d793-949...
1,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,2,tray,frames/retrieval/visual_crops/val/3482d793-949...
2,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,3,frying pan,frames/retrieval/visual_crops/val/3482d793-949...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,1,wall picture,frames/retrieval/visual_crops/val/8bf2886e-f2e...
1,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,2,global table ball map,frames/retrieval/visual_crops/val/8bf2886e-f2e...
2,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,3,study lamp,frames/retrieval/visual_crops/val/8bf2886e-f2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7ff93f97-d65f-4195-8f37-e4040acb2d09_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,1,grater,frames/retrieval/visual_crops/val/7ff93f97-d65...
1,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,2,bottle,frames/retrieval/visual_crops/val/7ff93f97-d65...
2,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,3,bucket,frames/retrieval/visual_crops/val/7ff93f97-d65...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6e945b3a-ee26-4a3c-93f0-f60e2456c44a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,1,bag,frames/retrieval/visual_crops/val/6e945b3a-ee2...
1,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,2,plastic cylinder,frames/retrieval/visual_crops/val/6e945b3a-ee2...
2,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,3,stool,frames/retrieval/visual_crops/val/6e945b3a-ee2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/430be2d1-eb7f-4418-a3bb-06c0d71307d3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,2,box,frames/retrieval/visual_crops/val/430be2d1-eb7...
1,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,1,diary,frames/retrieval/visual_crops/val/430be2d1-eb7...
2,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,3,cup,frames/retrieval/visual_crops/val/430be2d1-eb7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/87499bfb-3dcf-46fa-aef3-204fcc0496e0_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,1,yellow bowl,frames/retrieval/visual_crops/val/87499bfb-3dc...
1,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,2,dough cutter,frames/retrieval/visual_crops/val/87499bfb-3dc...
2,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,3,dough bowl,frames/retrieval/visual_crops/val/87499bfb-3dc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d3b18a63-002a-4538-adef-21ac1f476704_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,1,wood,frames/retrieval/visual_crops/val/d3b18a63-002...
1,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,2,#unsure,frames/retrieval/visual_crops/val/d3b18a63-002...
2,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,3,bottle,frames/retrieval/visual_crops/val/d3b18a63-002...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cf82756f-8e87-443a-972c-405b25858e78_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,1,bucket,frames/retrieval/visual_crops/val/cf82756f-8e8...
1,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,2,broom,frames/retrieval/visual_crops/val/cf82756f-8e8...
2,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,3,curtain,frames/retrieval/visual_crops/val/cf82756f-8e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/69668105-9984-43d0-8c24-74a4ed2adcf4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,1,electric kettle,frames/retrieval/visual_crops/val/69668105-998...
1,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,2,jug,frames/retrieval/visual_crops/val/69668105-998...
2,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,3,book,frames/retrieval/visual_crops/val/69668105-998...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e7ec16d2-6649-4942-8da9-83e603e78438_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,2,house,frames/retrieval/visual_crops/val/e7ec16d2-664...
1,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,1,basketball board,frames/retrieval/visual_crops/val/e7ec16d2-664...
2,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,3,pick-up,frames/retrieval/visual_crops/val/e7ec16d2-664...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/898e6cc6-082c-483d-ad84-12ec417ca440_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,1,scraper,frames/retrieval/visual_crops/val/898e6cc6-082...
1,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,2,piece of cloth,frames/retrieval/visual_crops/val/898e6cc6-082...
2,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,3,bottle,frames/retrieval/visual_crops/val/898e6cc6-082...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dbfb3374-94ef-47cb-b179-99ad19e55ff1_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,1,car jack,frames/retrieval/visual_crops/val/dbfb3374-94e...
1,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,2,terminal,frames/retrieval/visual_crops/val/dbfb3374-94e...
2,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,3,trash can,frames/retrieval/visual_crops/val/dbfb3374-94e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c2229daf-ec7b-45c5-84e3-bb4f4d145d93_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,1,tin,frames/retrieval/visual_crops/val/c2229daf-ec7...
1,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,2,glove,frames/retrieval/visual_crops/val/c2229daf-ec7...
2,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,3,drill,frames/retrieval/visual_crops/val/c2229daf-ec7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/49b8d3e9-de69-49cf-819b-5af1fd69b732_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,1,hammer,frames/retrieval/visual_crops/val/49b8d3e9-de6...
1,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,2,toolbox,frames/retrieval/visual_crops/val/49b8d3e9-de6...
2,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,3,pliers,frames/retrieval/visual_crops/val/49b8d3e9-de6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b391003e-a302-43a0-a451-75cc8b4ccede_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,1,sponge,frames/retrieval/visual_crops/val/b391003e-a30...
1,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,2,stainless bowl,frames/retrieval/visual_crops/val/b391003e-a30...
2,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,3,watering can,frames/retrieval/visual_crops/val/b391003e-a30...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9ca1c968-8346-4fc1-a704-e7dffc79afa7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,1,cup,frames/retrieval/visual_crops/val/9ca1c968-834...
1,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,3,plastic bag,frames/retrieval/visual_crops/val/9ca1c968-834...
2,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,2,kitchen towel,frames/retrieval/visual_crops/val/9ca1c968-834...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/281b9507-4bea-4549-9912-90d6fd257f05_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,3,green serving spoon,frames/retrieval/visual_crops/val/281b9507-4be...
1,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,1,chopping board,frames/retrieval/visual_crops/val/281b9507-4be...
2,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,2,cloth,frames/retrieval/visual_crops/val/281b9507-4be...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6c0c2145-2b3d-48cd-a61c-e29d8541218f_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,1,white flipflop,frames/retrieval/visual_crops/val/6c0c2145-2b3...
1,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,2,transparent cup,frames/retrieval/visual_crops/val/6c0c2145-2b3...
2,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,3,chopsticks,frames/retrieval/visual_crops/val/6c0c2145-2b3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fa43490f-22c7-44db-868f-4998791069ac_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,1,tool box,frames/retrieval/visual_crops/val/fa43490f-22c...
1,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,2,jerrycan,frames/retrieval/visual_crops/val/fa43490f-22c...
2,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,3,micropipette,frames/retrieval/visual_crops/val/fa43490f-22c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/629cb4e4-65a5-45f5-909d-2ff93e57a0bf_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,1,cutting pliers,frames/retrieval/visual_crops/val/629cb4e4-65a...
1,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,2,ball pein hammer,frames/retrieval/visual_crops/val/629cb4e4-65a...
2,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,3,brake rotor,frames/retrieval/visual_crops/val/629cb4e4-65a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0ba8203a-5825-464b-8d95-32a24e84acf0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,1,paper bag,frames/retrieval/visual_crops/val/0ba8203a-582...
1,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,2,chair,frames/retrieval/visual_crops/val/0ba8203a-582...
2,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,3,knife,frames/retrieval/visual_crops/val/0ba8203a-582...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/09dde7aa-58bd-402e-a107-32c0f33e7115_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,2,bottle,frames/retrieval/visual_crops/val/09dde7aa-58b...
1,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,1,washing machine,frames/retrieval/visual_crops/val/09dde7aa-58b...
2,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,3,pan,frames/retrieval/visual_crops/val/09dde7aa-58b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6f7f5312-db3f-42db-98c0-f650a3899568_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6f7f5312-db3f-42db-98c0-f650a3899568,d05881bc-4d63-4dcb-a5ef-08d1db73712f,1,phone,frames/retrieval/visual_crops/val/6f7f5312-db3...
1,6f7f5312-db3f-42db-98c0-f650a3899568,d05881bc-4d63-4dcb-a5ef-08d1db73712f,2,mug,frames/retrieval/visual_crops/val/6f7f5312-db3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/074ff05f-e0cb-41b7-96fe-25a9a79ce918_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,1,oil drum,frames/retrieval/visual_crops/val/074ff05f-e0c...
1,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,3,oil box,frames/retrieval/visual_crops/val/074ff05f-e0c...
2,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,2,phone,frames/retrieval/visual_crops/val/074ff05f-e0c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d444eac6-5d1b-4198-97d8-e3ec96dae37e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,1,pair of glasses,frames/retrieval/visual_crops/val/d444eac6-5d1...
1,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,2,bag,frames/retrieval/visual_crops/val/d444eac6-5d1...
2,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,3,dog,frames/retrieval/visual_crops/val/d444eac6-5d1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bc01d0dd-be04-474e-9fc6-de83292a5062_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,1,water bottle,frames/retrieval/visual_crops/val/bc01d0dd-be0...
1,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,3,cup,frames/retrieval/visual_crops/val/bc01d0dd-be0...
2,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,2,mobile phone,frames/retrieval/visual_crops/val/bc01d0dd-be0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f090ba34-9f57-40de-8fce-f2d3503d55ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,1,hose pipe,frames/retrieval/visual_crops/val/f090ba34-9f5...
1,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,3,pliers,frames/retrieval/visual_crops/val/f090ba34-9f5...
2,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,2,cellphone,frames/retrieval/visual_crops/val/f090ba34-9f5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/81221073-c095-4129-b095-97f3d6e4a6b1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,2,bangle,frames/retrieval/visual_crops/val/81221073-c09...
1,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,3,wire,frames/retrieval/visual_crops/val/81221073-c09...
2,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,1,post,frames/retrieval/visual_crops/val/81221073-c09...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f16b6028-4624-4224-a368-a18d59aefe70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,2,cloth,frames/retrieval/visual_crops/val/f16b6028-462...
1,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,3,carton box,frames/retrieval/visual_crops/val/f16b6028-462...
2,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,1,bucket,frames/retrieval/visual_crops/val/f16b6028-462...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5699168a-b5d3-4957-8ec1-87a4377b2e94_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,1,scissors,frames/retrieval/visual_crops/val/5699168a-b5d...
1,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,2,basket,frames/retrieval/visual_crops/val/5699168a-b5d...
2,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,3,box pack,frames/retrieval/visual_crops/val/5699168a-b5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f0861378-ff5f-47d8-b1b3-59cf5b07acc7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,1,backpack,frames/retrieval/visual_crops/val/f0861378-ff5...
1,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,2,yellow nylon,frames/retrieval/visual_crops/val/f0861378-ff5...
2,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,3,bicycle,frames/retrieval/visual_crops/val/f0861378-ff5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/50df286e-fe12-434e-95c6-d8160787512b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,1,sweeping brush,frames/retrieval/visual_crops/val/50df286e-fe1...
1,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,2,baking weighing scale,frames/retrieval/visual_crops/val/50df286e-fe1...
2,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,3,measuring jar,frames/retrieval/visual_crops/val/50df286e-fe1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fbf8b92f-8472-4195-8b9c-4c365714ff94_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,1,toilet paper,frames/retrieval/visual_crops/val/fbf8b92f-847...
1,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,2,shopping basket,frames/retrieval/visual_crops/val/fbf8b92f-847...
2,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,3,disposable cup,frames/retrieval/visual_crops/val/fbf8b92f-847...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d2e61675-14b6-481f-9206-34bbc1375ea6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,1,vase,frames/retrieval/visual_crops/val/d2e61675-14b...
1,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,2,tv,frames/retrieval/visual_crops/val/d2e61675-14b...
2,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,3,paper towel,frames/retrieval/visual_crops/val/d2e61675-14b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b157270d-c67a-41db-91ec-32bb3ec738fc_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,1,dispensing bottle,frames/retrieval/visual_crops/val/b157270d-c67...
1,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,3,adapter,frames/retrieval/visual_crops/val/b157270d-c67...
2,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,2,impact driver,frames/retrieval/visual_crops/val/b157270d-c67...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,1,plastic chair,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...
1,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,2,plastic stool,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...
2,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,3,sack,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/704943b6-2922-43d7-9b16-81c021b96232_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,2,bulb,frames/retrieval/visual_crops/val/704943b6-292...
1,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,3,chair,frames/retrieval/visual_crops/val/704943b6-292...
2,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,1,bottle,frames/retrieval/visual_crops/val/704943b6-292...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6e4a69cf-b603-4797-8d68-11f27919b40c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,1,pliers,frames/retrieval/visual_crops/val/6e4a69cf-b60...
1,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,3,nut gun,frames/retrieval/visual_crops/val/6e4a69cf-b60...
2,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,2,spanner,frames/retrieval/visual_crops/val/6e4a69cf-b60...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/82abc0e6-c282-4492-89cb-c6005f1cb0f5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,1,spray tin,frames/retrieval/visual_crops/val/82abc0e6-c28...
1,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,2,cordless drill,frames/retrieval/visual_crops/val/82abc0e6-c28...
2,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,3,phone,frames/retrieval/visual_crops/val/82abc0e6-c28...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/307c3ec6-886e-4d25-9ef7-7bea3cf7a243_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,1,blowtorch,frames/retrieval/visual_crops/val/307c3ec6-886...
1,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,2,tape,frames/retrieval/visual_crops/val/307c3ec6-886...
2,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,3,plastic container,frames/retrieval/visual_crops/val/307c3ec6-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,3,ball,frames/retrieval/visual_crops/val/bd87e5e6-d2e...
1,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,2,golf stick,frames/retrieval/visual_crops/val/bd87e5e6-d2e...
2,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,1,mobile phone,frames/retrieval/visual_crops/val/bd87e5e6-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1004f7fe-c397-4123-bad9-e02df2e154dd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,1,plate,frames/retrieval/visual_crops/val/1004f7fe-c39...
1,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,2,bowl,frames/retrieval/visual_crops/val/1004f7fe-c39...
2,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,3,cooking pot,frames/retrieval/visual_crops/val/1004f7fe-c39...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,2,rice cooker,frames/retrieval/visual_crops/val/6ed430d1-e42...
1,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,1,bowl,frames/retrieval/visual_crops/val/6ed430d1-e42...
2,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,3,tissue paper,frames/retrieval/visual_crops/val/6ed430d1-e42...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ccc4408f-8420-481d-b5aa-0c0013e3a109_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,1,pliers,frames/retrieval/visual_crops/val/ccc4408f-842...
1,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,3,painting brush,frames/retrieval/visual_crops/val/ccc4408f-842...
2,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,2,thread,frames/retrieval/visual_crops/val/ccc4408f-842...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dc3ba39f-62f4-480b-a187-ca723c8666bd_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,1,shopping basket,frames/retrieval/visual_crops/val/dc3ba39f-62f...
1,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,3,scarf,frames/retrieval/visual_crops/val/dc3ba39f-62f...
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,2,knitted beret,frames/retrieval/visual_crops/val/dc3ba39f-62f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/b144e06c-ac25-4584-9ff4-93d6a8d04865_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,1,basket,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a basket
1,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,2,phone,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a phone
2,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,3,mirror,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a mirror

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,1,lamp shade,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a lamp shade
1,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,2,desk top,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a desk top
2,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,3,plant pot,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a plant pot

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,1,flower pot,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a flower pot
1,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,2,trash bin,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a trash bin
2,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,3,bucket,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a bucket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/293a2530-a4a8-4776-92d5-741142dfdd3e_text_metadata_a_photo_of_a_object.parquet
Shape: (2, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,1,cooking pan,frames/retrieval/visual_crops/val/293a2530-a4a...,a photo of a cooking pan
1,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,3,bucket,frames/retrieval/visual_crops/val/293a2530-a4a...,a photo of a bucket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/cc7d11f0-445e-426a-904e-e7faafdb07f7_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,3,kurta tunic,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a kurta tunic
1,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,1,iron box,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a iron box
2,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,2,cloth,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a cloth

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/aef0725a-1005-4a17-ad33-4522808c3a17_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,2,kettle,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a kettle
1,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,1,jug,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a jug
2,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,3,bottle,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a bottle

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/3e95b70a-e2b1-4d6f-a229-b07d4f8eadea_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,1,dough cutter,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a dough cutter
1,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,2,scrubber,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a scrubber
2,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,3,weighing scale,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a weighing scale

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/f1350714-1aa5-421b-a268-690110ca9c06_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,1,wheels,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a wheels
1,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,2,power drill,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a power drill
2,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,3,brake shoe,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a brake shoe

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/99ddfcb3-bb2a-45d3-903e-d7e858969957_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,1,bag,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a bag
1,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,2,pruning sheers,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a pruning sheers
2,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,3,basket,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a basket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/30ca6fa7-dbe0-4f55-84c8-8797de99c290_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,3,flower pot,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a flower pot
1,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,1,pillows,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a pillows
2,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,2,cloth,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a cloth

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/b0612ea7-11f9-486e-a4aa-e0f8ba67e2df_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,1,drill,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a drill
1,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,2,hammer,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a hammer
2,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,3,tin,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a tin

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/f052ac6f-832d-41f0-b00f-7cb85c20a15c_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,1,plastic container,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a plastic container
1,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,3,paper towel,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a paper towel
2,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,2,toothbrush,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a toothbrush

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/72e90719-c2b8-4b17-b120-e904dbbf1184_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,1,tray,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a tray
1,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,3,plastic water jar,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a plastic water jar
2,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,2,pressure cooker,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a pressure cooker

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/ddb94361-b4c3-4343-8a80-daad1ea69476_text_metadata_a_photo_of_a_object.parquet
Shape: (2, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,1,book stand,frames/retrieval/visual_crops/val/ddb94361-b4c...,a photo of a book stand
1,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,3,house plant,frames/retrieval/visual_crops/val/ddb94361-b4c...,a photo of a house plant

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/efe7dfaa-07e0-42d5-85eb-1e6f93409ab5_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,1,plastic bottle,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a plastic bottle
1,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,2,screwdriver,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a screwdriver
2,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,3,t wrench,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a t wrench

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/ae8727ba-fe6f-4411-b277-48a8b7326a2a_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,1,container,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a container
1,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,2,bottle,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a bottle
2,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,3,chair,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a chair

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/6c0c2145-2b3d-48cd-a61c-e29d8541218f_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,1,white flipflop,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a white flipflop
1,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,2,transparent cup,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a transparent cup
2,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,3,chopsticks,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a chopsticks

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/09d85b55-d473-49c1-9ebc-e871714785cd_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,1,calculator,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a calculator
1,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,2,tray,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a tray
2,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,3,spray bottle,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a spray bottle

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/e4728a65-3184-4239-9b84-be43dfd7377e_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,2,jug,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a jug
1,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,3,wood cutting machine,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a wood cutting machine
2,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,1,container,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a container

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/67c47998-eabe-4b31-9096-b286c18e1beb_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,1,basket,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a basket
1,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,2,wallet,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a wallet
2,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,3,receipt,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a receipt

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/extraction_manifest.parquet
Shape: (1743, 7)
Columns: ['video_uid', 'split', 'n_clips', 'detection_frames', 'yolo_labels', 'visual_crops', 'status']

,video_uid,split,n_clips,detection_frames,yolo_labels,visual_crops,status
0,56a3b49c-6979-4253-9ff5-2733c3e2f229,train,5.0,281.0,281.0,24.0,ok
1,a7a6e05d-ffe6-47a4-a08c-b4b386e9911f,train,2.0,55.0,55.0,6.0,ok
2,ee114c86-05fc-4d47-8c9a-8dfeafed0457,train,2.0,140.0,140.0,9.0,ok

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/retrieval_metadata.parquet
Failed to read: ArrowInvalid("Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes")
====================================================================================================
/home/jupyter/egorecall_retrieval_work/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667

====================================================================================================
/home/jupyter/egorecall_retrieval_work/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/extraction_manifest.parquet
Shape: (1743, 7)
Columns: ['video_uid', 'split', 'n_clips', 'detection_frames', 'yolo_labels', 'visual_crops', 'status']

,video_uid,split,n_clips,detection_frames,yolo_labels,visual_crops,status
0,56a3b49c-6979-4253-9ff5-2733c3e2f229,train,5.0,281.0,281.0,24.0,ok
1,a7a6e05d-ffe6-47a4-a08c-b4b386e9911f,train,2.0,55.0,55.0,6.0,ok
2,ee114c86-05fc-4d47-8c9a-8dfeafed0457,train,2.0,140.0,140.0,9.0,ok

====================================================================================================
/home/jupyter/egorecall_retrieval_subset/retrieval_metadata.parquet
Failed to read: ArrowInvalid("Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes")
====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch2.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,617e8d7c-8764-4508-ba9b-c993282c70cd,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,NaN,True,True,True,NaN,3
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,25beabfc-48c0-4f81-b419-c47297aecf6f,skipped_fully_cached,NaN,True,True,True,NaN,3
2,81221073-c095-4129-b095-97f3d6e4a6b1,412763ce-9a81-4bb7-b713-80fe2713e1a8,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0_sanity3.csv
Shape: (3, 8)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'video_exists_before', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before']

,clip_uid,video_uid,status,error,video_exists_before,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before
0,159ac0ad-e5ec-449d-a69e-556655f79b2a,e14e03f8-13e4-4df2-87b0-e1ad8a175f7c,error,"AttributeError(""'BaseModelOutputWithPooling' o...",False,False,False,False
1,830e1b42-1d4a-4a4b-b0ad-c40fc4ace19c,eb486644-f46f-44cf-8e4b-73245b2fc02e,error,"AttributeError(""'BaseModelOutputWithPooling' o...",False,False,False,False
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,eb486644-f46f-44cf-8e4b-73245b2fc02e,error,"AttributeError(""'BaseModelOutputWithPooling' o...",True,False,False,False

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch4.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cc994557-a65b-48a9-94c6-122ede470347,6e0c294c-d634-4804-8d41-cd6e9d79f0b9,skipped_fully_cached,NaN,True,True,True,NaN,3
1,4a491385-b165-49ec-a23b-7b0ed26737f9,3ee7070a-fe81-49a9-97a2-902268af9985,skipped_fully_cached,NaN,True,True,True,NaN,6
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,ecc633d2-72b5-4bd0-a6a1-f1cedb21d757,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch1.csv
Shape: (60, 13)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries', 'index_cache_exists_after', 'query_cache_exists_after', 'query_metadata_exists_after', 'fully_cached_after']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries,index_cache_exists_after,query_cache_exists_after,query_metadata_exists_after,fully_cached_after
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,success,NaN,False,False,False,480.0,3,True,True,True,True
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,success,NaN,False,False,False,480.0,6,True,True,True,True
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,success,NaN,False,False,False,300.0,3,True,True,True,True

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_all_batches.csv
Shape: (300, 14)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries', 'batch_id', 'index_cache_exists_after', 'query_cache_exists_after', 'query_metadata_exists_after', 'fully_cached_after']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries,batch_id,index_cache_exists_after,query_cache_exists_after,query_metadata_exists_after,fully_cached_after
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,skipped_fully_cached,NaN,True,True,True,NaN,3.0,0,NaN,NaN,NaN,NaN
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,skipped_fully_cached,NaN,True,True,True,NaN,6.0,0,NaN,NaN,NaN,NaN
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,skipped_fully_cached,NaN,True,True,True,NaN,3.0,0,NaN,NaN,NaN,NaN

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch3.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
1,16fce853-9528-4c39-9f88-b0c61f30d01d,2bc60910-3a1f-4498-a579-a1bcf105aee7,skipped_fully_cached,NaN,True,True,True,NaN,3.0
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,1938c632-f575-49dd-8ae0-e48dbb467920,skipped_fully_cached,NaN,True,True,True,NaN,3.0

====================================================================================================
/home/jupyter/results/retrieval_subset/preprocess_manifest_nclips300_batch0.csv
Shape: (60, 9)
Columns: ['clip_uid', 'video_uid', 'status', 'error', 'index_cache_exists_before', 'query_cache_exists_before', 'query_metadata_exists_before', 'num_index_frames', 'num_queries']

,clip_uid,video_uid,status,error,index_cache_exists_before,query_cache_exists_before,query_metadata_exists_before,num_index_frames,num_queries
0,dbd760b1-f99a-4a74-9f67-50579e516532,d79f9434-2456-4a01-bf72-d597a5668e86,skipped_fully_cached,NaN,True,True,True,NaN,3
1,8d22e91b-ed98-4c87-8a25-c937236ca745,73773748-14ac-40ba-9ef8-d5a70865aeea,skipped_fully_cached,NaN,True,True,True,NaN,6
2,81da71e1-0e80-43cc-8752-292d231e70a2,b707b510-4ccb-4912-b662-5e2dbdaa6ef2,skipped_fully_cached,NaN,True,True,True,NaN,3

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/09d85b55-d473-49c1-9ebc-e871714785cd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,1,calculator,frames/retrieval/visual_crops/val/09d85b55-d47...
1,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,2,tray,frames/retrieval/visual_crops/val/09d85b55-d47...
2,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,3,spray bottle,frames/retrieval/visual_crops/val/09d85b55-d47...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f22ddd51-999f-44b8-9d53-319982dda0a7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,1,scissor,frames/retrieval/visual_crops/val/f22ddd51-999...
1,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,2,sandal,frames/retrieval/visual_crops/val/f22ddd51-999...
2,f22ddd51-999f-44b8-9d53-319982dda0a7,2170bb81-78b0-48b9-826e-d880967ae9fc,3,gloves,frames/retrieval/visual_crops/val/f22ddd51-999...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,3,books,frames/retrieval/visual_crops/val/f14ea4c5-2a1...
1,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,1,kitchen towel,frames/retrieval/visual_crops/val/f14ea4c5-2a1...
2,f14ea4c5-2a1a-4855-a212-3b2abe7aa0f2,80338a27-278e-4575-bfa8-095d52b94070,2,chopping board,frames/retrieval/visual_crops/val/f14ea4c5-2a1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3970c9a9-e6ca-4675-866c-2e21913eacb2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,2,bucket,frames/retrieval/visual_crops/val/3970c9a9-e6c...
1,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,3,stepstool,frames/retrieval/visual_crops/val/3970c9a9-e6c...
2,3970c9a9-e6ca-4675-866c-2e21913eacb2,a593eced-5167-4f2f-9f9f-6bf3a04edfd3,1,mask,frames/retrieval/visual_crops/val/3970c9a9-e6c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/db84f0aa-15a2-4cfb-a89e-173b0aea4720_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,1,cooking pot,frames/retrieval/visual_crops/val/db84f0aa-15a...
1,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,2,basin,frames/retrieval/visual_crops/val/db84f0aa-15a...
2,db84f0aa-15a2-4cfb-a89e-173b0aea4720,e9a83975-564e-40c9-b9cd-b0b1c240cf50,3,tray,frames/retrieval/visual_crops/val/db84f0aa-15a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ae8727ba-fe6f-4411-b277-48a8b7326a2a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,1,container,frames/retrieval/visual_crops/val/ae8727ba-fe6...
1,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,2,bottle,frames/retrieval/visual_crops/val/ae8727ba-fe6...
2,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,3,chair,frames/retrieval/visual_crops/val/ae8727ba-fe6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a879680b-7957-45fb-8786-cdc8e998f01d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,1,screw driver,frames/retrieval/visual_crops/val/a879680b-795...
1,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,2,ratchet drill,frames/retrieval/visual_crops/val/a879680b-795...
2,a879680b-7957-45fb-8786-cdc8e998f01d,176bd827-caa7-4e74-9591-b8af10d02a41,3,spanner,frames/retrieval/visual_crops/val/a879680b-795...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/39f8cacc-5fd2-44c5-84d8-5bcc7fefe798_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,2,electric kettle,frames/retrieval/visual_crops/val/39f8cacc-5fd...
1,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,1,paper towel,frames/retrieval/visual_crops/val/39f8cacc-5fd...
2,39f8cacc-5fd2-44c5-84d8-5bcc7fefe798,bc4d842a-ef12-4388-a7ba-426098392f14,3,microwave,frames/retrieval/visual_crops/val/39f8cacc-5fd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6673c838-2765-4b41-81fd-9a01deba1d0b_query_metadata.parquet
Shape: (5, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6673c838-2765-4b41-81fd-9a01deba1d0b,e894d030-577e-46e2-a333-f916b4dda9d8,2,lid,frames/retrieval/visual_crops/val/6673c838-276...
1,6673c838-2765-4b41-81fd-9a01deba1d0b,e894d030-577e-46e2-a333-f916b4dda9d8,3,can,frames/retrieval/visual_crops/val/6673c838-276...
2,6673c838-2765-4b41-81fd-9a01deba1d0b,6f31662c-5251-454b-b815-f1b1da0a6d4e,3,iron,frames/retrieval/visual_crops/val/6673c838-276...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/aef0725a-1005-4a17-ad33-4522808c3a17_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,2,kettle,frames/retrieval/visual_crops/val/aef0725a-100...
1,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,1,jug,frames/retrieval/visual_crops/val/aef0725a-100...
2,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,3,bottle,frames/retrieval/visual_crops/val/aef0725a-100...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c52530be-f470-4c44-ae1a-c8aee924ff46_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,1,hat,frames/retrieval/visual_crops/val/c52530be-f47...
1,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,2,bedside lamp,frames/retrieval/visual_crops/val/c52530be-f47...
2,c52530be-f470-4c44-ae1a-c8aee924ff46,0149ba12-b6fb-4d59-8b17-17ac64aa1681,3,fire-extinguisher,frames/retrieval/visual_crops/val/c52530be-f47...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/297eb153-8e44-4f25-b270-ca4d682c32bb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,3,sickle tool,frames/retrieval/visual_crops/val/297eb153-8e4...
1,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,1,tied sack,frames/retrieval/visual_crops/val/297eb153-8e4...
2,297eb153-8e44-4f25-b270-ca4d682c32bb,e77a77d8-3dd2-4012-a9e2-e1d2ad448e80,2,cooking pot,frames/retrieval/visual_crops/val/297eb153-8e4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b2dcb4b2-7a5e-4d68-aec9-41ec96915168_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,1,soup scoop spoon,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...
1,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,2,shoes,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...
2,b2dcb4b2-7a5e-4d68-aec9-41ec96915168,64490429-5eca-41b9-b4ef-12adb7c6f597,3,rice cooker,frames/retrieval/visual_crops/val/b2dcb4b2-7a5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5c87b9e2-7d54-469f-96ff-02ff7493c6ae_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,1,sellotape,frames/retrieval/visual_crops/val/5c87b9e2-7d5...
1,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,2,impact driver,frames/retrieval/visual_crops/val/5c87b9e2-7d5...
2,5c87b9e2-7d54-469f-96ff-02ff7493c6ae,7aedd082-1d33-45c3-9e72-a9dd5f8750d4,3,ear muff,frames/retrieval/visual_crops/val/5c87b9e2-7d5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f1eb7035-ce79-4be2-81bc-118eb1ad2887_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,1,pestle,frames/retrieval/visual_crops/val/f1eb7035-ce7...
1,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,2,container,frames/retrieval/visual_crops/val/f1eb7035-ce7...
2,f1eb7035-ce79-4be2-81bc-118eb1ad2887,cc821da0-d5ad-4024-8f29-3b483dff4087,3,test tube,frames/retrieval/visual_crops/val/f1eb7035-ce7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9e9f05e9-5dbe-439b-970d-acb13ab98f10_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,1,music keyboard,frames/retrieval/visual_crops/val/9e9f05e9-5db...
1,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,2,television,frames/retrieval/visual_crops/val/9e9f05e9-5db...
2,9e9f05e9-5dbe-439b-970d-acb13ab98f10,07b4b516-85da-46da-9aca-95109be0050c,3,drink cans,frames/retrieval/visual_crops/val/9e9f05e9-5db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,1,flower pot,frames/retrieval/visual_crops/val/8530a122-787...
1,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,2,trash bin,frames/retrieval/visual_crops/val/8530a122-787...
2,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,3,bucket,frames/retrieval/visual_crops/val/8530a122-787...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d68ae83a-903a-448e-bc7e-7279755e0243_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,3,plastic tin,frames/retrieval/visual_crops/val/d68ae83a-903...
1,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,2,water bottle,frames/retrieval/visual_crops/val/d68ae83a-903...
2,d68ae83a-903a-448e-bc7e-7279755e0243,d14c829d-c7c6-488c-94b9-a8e9036d2163,1,speed square,frames/retrieval/visual_crops/val/d68ae83a-903...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ddf340f-de44-4f5d-9994-1e0f7db05caf_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,3,scarf,frames/retrieval/visual_crops/val/2ddf340f-de4...
1,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,1,basket,frames/retrieval/visual_crops/val/2ddf340f-de4...
2,2ddf340f-de44-4f5d-9994-1e0f7db05caf,6fadeb6c-25db-4404-aa16-81de57711e1a,2,sweater,frames/retrieval/visual_crops/val/2ddf340f-de4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9f661edf-a6f6-444e-b168-e8428044b1d7_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,1,plastic cup,frames/retrieval/visual_crops/val/9f661edf-a6f...
1,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,2,green bottle,frames/retrieval/visual_crops/val/9f661edf-a6f...
2,9f661edf-a6f6-444e-b168-e8428044b1d7,42fe4f78-784f-4d9b-b939-f70d2c2ffa52,3,bowl,frames/retrieval/visual_crops/val/9f661edf-a6f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b887413-c1ef-4257-9524-0be974fd47a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,1,drill,frames/retrieval/visual_crops/val/2b887413-c1e...
1,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,2,lawnmower,frames/retrieval/visual_crops/val/2b887413-c1e...
2,2b887413-c1ef-4257-9524-0be974fd47a8,c293aef7-c806-4ed3-85a1-b21d1344031d,3,tiling trowel,frames/retrieval/visual_crops/val/2b887413-c1e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,1,hangers,frames/retrieval/visual_crops/val/5a74f8ec-f3c...
1,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,3,phone,frames/retrieval/visual_crops/val/5a74f8ec-f3c...
2,5a74f8ec-f3c2-4d2d-a6c6-6f7558943bb6,a5416e34-73e0-45df-b954-b1629918e359,2,laptop,frames/retrieval/visual_crops/val/5a74f8ec-f3c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/18dad6e7-5969-4573-a1b3-f4ccfc53c350_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,1,exercise ball,frames/retrieval/visual_crops/val/18dad6e7-596...
1,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,2,phone,frames/retrieval/visual_crops/val/18dad6e7-596...
2,18dad6e7-5969-4573-a1b3-f4ccfc53c350,3e4b2b61-4de8-4c1a-91aa-634bcbcf65ee,3,packed food box,frames/retrieval/visual_crops/val/18dad6e7-596...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0723c03f-263c-442d-9d9b-d0fef0cef0e4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,1,basin,frames/retrieval/visual_crops/val/0723c03f-263...
1,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,3,paper bag,frames/retrieval/visual_crops/val/0723c03f-263...
2,0723c03f-263c-442d-9d9b-d0fef0cef0e4,967a8169-da09-4a95-80df-3b3997115b8f,2,measuring cup,frames/retrieval/visual_crops/val/0723c03f-263...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9b15d755-f374-4731-8370-26847aadc08b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,1,purse,frames/retrieval/visual_crops/val/9b15d755-f37...
1,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,2,tray,frames/retrieval/visual_crops/val/9b15d755-f37...
2,9b15d755-f374-4731-8370-26847aadc08b,e5df09b3-076b-4a7c-a049-ed4aa856440b,3,phone,frames/retrieval/visual_crops/val/9b15d755-f37...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cb0cd08f-7a3e-4450-86ae-e7d490603188_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,1,padlock,frames/retrieval/visual_crops/val/cb0cd08f-7a3...
1,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,2,bottle,frames/retrieval/visual_crops/val/cb0cd08f-7a3...
2,cb0cd08f-7a3e-4450-86ae-e7d490603188,f19425be-5cf8-4122-856a-c9ecdb0477c1,3,plier,frames/retrieval/visual_crops/val/cb0cd08f-7a3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/81da71e1-0e80-43cc-8752-292d231e70a2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,1,bottle,frames/retrieval/visual_crops/val/81da71e1-0e8...
1,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,2,flat file,frames/retrieval/visual_crops/val/81da71e1-0e8...
2,81da71e1-0e80-43cc-8752-292d231e70a2,b62a4a48-99be-418b-9791-b0abe24fcf8d,3,bucket,frames/retrieval/visual_crops/val/81da71e1-0e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/11acf51c-9a44-4c77-9e16-46925c2e66de_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,2,scissor,frames/retrieval/visual_crops/val/11acf51c-9a4...
1,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,1,utensils rinsing soap,frames/retrieval/visual_crops/val/11acf51c-9a4...
2,11acf51c-9a44-4c77-9e16-46925c2e66de,18b6f943-ceb5-40f7-b1e3-1ea7594ff21d,3,tape,frames/retrieval/visual_crops/val/11acf51c-9a4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/860b4b8a-7219-433b-8947-cd8b93973b07_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,1,waste bin,frames/retrieval/visual_crops/val/860b4b8a-721...
1,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,2,swivel chair,frames/retrieval/visual_crops/val/860b4b8a-721...
2,860b4b8a-7219-433b-8947-cd8b93973b07,a6c3b8ab-95c9-4f83-8341-03bd0d0afb67,3,glass jar,frames/retrieval/visual_crops/val/860b4b8a-721...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,3,tissue paper,frames/retrieval/visual_crops/val/4e9b50a0-1a9...
1,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,1,cup,frames/retrieval/visual_crops/val/4e9b50a0-1a9...
2,4e9b50a0-1a9b-4e23-9f3b-4bfde1a7cae9,2e5b5fb6-456d-4471-af74-5e60aaf9459e,2,frying pan,frames/retrieval/visual_crops/val/4e9b50a0-1a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b338a041-3164-4155-ae40-faa77a9fd08a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,1,red car,frames/retrieval/visual_crops/val/b338a041-316...
1,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,2,bench,frames/retrieval/visual_crops/val/b338a041-316...
2,b338a041-3164-4155-ae40-faa77a9fd08a,d5a9e8d7-4548-4ff6-ade3-b75d9ed4e2d5,3,tennis ball,frames/retrieval/visual_crops/val/b338a041-316...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3cbf7d7e-7ef1-4486-94ea-b558c890b4b4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,1,water barrel,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...
1,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,2,wood,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...
2,3cbf7d7e-7ef1-4486-94ea-b558c890b4b4,8cd4e137-97f4-4b97-b22c-45c9f7b44b52,3,jerrycan,frames/retrieval/visual_crops/val/3cbf7d7e-7ef...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/55200058-9bf1-48a4-ac7f-a279f75fcaf1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,1,book,frames/retrieval/visual_crops/val/55200058-9bf...
1,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,2,stool,frames/retrieval/visual_crops/val/55200058-9bf...
2,55200058-9bf1-48a4-ac7f-a279f75fcaf1,bfb5940a-c507-4915-a365-68e6dd66c5e5,3,fire extinguisher,frames/retrieval/visual_crops/val/55200058-9bf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/23b8f734-c2db-4c55-9bca-cbe557d4abd4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,1,spray bottle,frames/retrieval/visual_crops/val/23b8f734-c2d...
1,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,2,sink,frames/retrieval/visual_crops/val/23b8f734-c2d...
2,23b8f734-c2db-4c55-9bca-cbe557d4abd4,d4091f7b-5432-4c4f-adaa-e51c88c70ac2,3,dust bin,frames/retrieval/visual_crops/val/23b8f734-c2d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/145ec165-a872-433e-959d-a0d748d261b0_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,145ec165-a872-433e-959d-a0d748d261b0,2b430174-48a2-47d2-8b0c-09971df50e02,2,glove,frames/retrieval/visual_crops/val/145ec165-a87...
1,145ec165-a872-433e-959d-a0d748d261b0,2b430174-48a2-47d2-8b0c-09971df50e02,3,box,frames/retrieval/visual_crops/val/145ec165-a87...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bcd1ea04-bde8-4769-acb4-3d504183cbf2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,2,sanitizer,frames/retrieval/visual_crops/val/bcd1ea04-bde...
1,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,3,fire extinguisher,frames/retrieval/visual_crops/val/bcd1ea04-bde...
2,bcd1ea04-bde8-4769-acb4-3d504183cbf2,7f62baf1-3750-4e23-8f03-34e69bdfd28c,1,bag,frames/retrieval/visual_crops/val/bcd1ea04-bde...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3716dd4c-232c-4ac1-89bd-3884cc79f0a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,1,bowl,frames/retrieval/visual_crops/val/3716dd4c-232...
1,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,3,serving spoon,frames/retrieval/visual_crops/val/3716dd4c-232...
2,3716dd4c-232c-4ac1-89bd-3884cc79f0a8,dfad3ba2-5ced-4dd7-8b61-d2b7f78e8180,2,spray gun,frames/retrieval/visual_crops/val/3716dd4c-232...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/99ddfcb3-bb2a-45d3-903e-d7e858969957_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,1,bag,frames/retrieval/visual_crops/val/99ddfcb3-bb2...
1,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,2,pruning sheers,frames/retrieval/visual_crops/val/99ddfcb3-bb2...
2,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,3,basket,frames/retrieval/visual_crops/val/99ddfcb3-bb2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,1,towel,frames/retrieval/visual_crops/val/b2a48c96-9b7...
1,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,2,funnel,frames/retrieval/visual_crops/val/b2a48c96-9b7...
2,b2a48c96-9b7f-4c74-9eb4-1bb4ae7c76bc,763f34c0-eb3d-4a54-8af2-00542f5256bc,3,stool,frames/retrieval/visual_crops/val/b2a48c96-9b7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8efe1412-5806-425e-9c3e-459bb9d45079_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,2,spray can,frames/retrieval/visual_crops/val/8efe1412-580...
1,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,1,scalpel,frames/retrieval/visual_crops/val/8efe1412-580...
2,8efe1412-5806-425e-9c3e-459bb9d45079,5ac86c46-638a-4238-a730-7173461cd116,3,car,frames/retrieval/visual_crops/val/8efe1412-580...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4570ab0a-55de-442d-b350-fe64e6956d4d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,1,glass,frames/retrieval/visual_crops/val/4570ab0a-55d...
1,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,2,paint,frames/retrieval/visual_crops/val/4570ab0a-55d...
2,4570ab0a-55de-442d-b350-fe64e6956d4d,9e4bbc53-d4f4-4814-9eaf-caac82877d97,3,cup,frames/retrieval/visual_crops/val/4570ab0a-55d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,3,jug,frames/retrieval/visual_crops/val/9cfc44fe-5f7...
1,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,1,dough mixer,frames/retrieval/visual_crops/val/9cfc44fe-5f7...
2,9cfc44fe-5f79-46a6-8a4b-77ea495f3ef3,36ebb8de-c615-463c-9c85-8e3d3b402610,2,flour,frames/retrieval/visual_crops/val/9cfc44fe-5f7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,2,bottle,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...
1,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,1,plastic jerry can,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...
2,f9cbfb3a-d2e2-4f30-9c01-ee341b5e8887,81a8f196-c666-43de-8ec2-df189c564036,3,stool,frames/retrieval/visual_crops/val/f9cbfb3a-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bed399ed-44af-438d-ab3f-12739adac348_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,1,dumbbell,frames/retrieval/visual_crops/val/bed399ed-44a...
1,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,3,sandpaper disc,frames/retrieval/visual_crops/val/bed399ed-44a...
2,bed399ed-44af-438d-ab3f-12739adac348,1db169a9-520b-41fb-a620-f529acc13da0,2,spanner,frames/retrieval/visual_crops/val/bed399ed-44a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/92207d1e-5cc6-41b5-bbd1-ed679aa997bd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,3,pen,frames/retrieval/visual_crops/val/92207d1e-5cc...
1,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,1,cup,frames/retrieval/visual_crops/val/92207d1e-5cc...
2,92207d1e-5cc6-41b5-bbd1-ed679aa997bd,34a43552-93c0-4275-a663-3d85ad9344f7,2,sieve,frames/retrieval/visual_crops/val/92207d1e-5cc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/74c966c9-0a8c-4e65-8811-75737d3e9c21_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,1,tap,frames/retrieval/visual_crops/val/74c966c9-0a8...
1,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,2,dough scrapper,frames/retrieval/visual_crops/val/74c966c9-0a8...
2,74c966c9-0a8c-4e65-8811-75737d3e9c21,ac1004a7-a599-45ed-9293-da1762a27f44,3,cup,frames/retrieval/visual_crops/val/74c966c9-0a8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f552173d-229e-496d-b414-3708df4c842e_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,1,mug,frames/retrieval/visual_crops/val/f552173d-229...
1,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,3,hand glove,frames/retrieval/visual_crops/val/f552173d-229...
2,f552173d-229e-496d-b414-3708df4c842e,3a5280bd-ff53-4798-a5ca-7657915fba5e,2,jerry can,frames/retrieval/visual_crops/val/f552173d-229...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ab23181-c60a-4478-9085-2a450a24b65b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,1,bottle,frames/retrieval/visual_crops/val/5ab23181-c60...
1,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,2,machete,frames/retrieval/visual_crops/val/5ab23181-c60...
2,5ab23181-c60a-4478-9085-2a450a24b65b,1eadb050-64ce-4b65-b414-51476b8a2687,3,chocolate cover,frames/retrieval/visual_crops/val/5ab23181-c60...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c96304a7-f17c-49bf-be81-a95450fb0358_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,1,bottle,frames/retrieval/visual_crops/val/c96304a7-f17...
1,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,2,flower pot,frames/retrieval/visual_crops/val/c96304a7-f17...
2,c96304a7-f17c-49bf-be81-a95450fb0358,a46b16eb-92b6-45ef-b437-0a728effbeca,3,plastic bowl,frames/retrieval/visual_crops/val/c96304a7-f17...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8450f847-5946-4199-9bc7-9d08c93c0141_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,3,flowerpot,frames/retrieval/visual_crops/val/8450f847-594...
1,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,1,mirror,frames/retrieval/visual_crops/val/8450f847-594...
2,8450f847-5946-4199-9bc7-9d08c93c0141,631e3899-27e2-48ec-9a30-9d34b396bd34,2,table lamp,frames/retrieval/visual_crops/val/8450f847-594...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ee5b3977-6598-4dfd-9199-e36a0d2fd56a_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ee5b3977-6598-4dfd-9199-e36a0d2fd56a,ac62aa4f-d0cd-431b-894e-cc5e24660e2e,2,tool box,frames/retrieval/visual_crops/val/ee5b3977-659...
1,ee5b3977-6598-4dfd-9199-e36a0d2fd56a,ac62aa4f-d0cd-431b-894e-cc5e24660e2e,3,tissue,frames/retrieval/visual_crops/val/ee5b3977-659...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ad9083b3-9b0b-4c27-a941-38f57be13edf_query_metadata.parquet
Shape: (12, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,1,hammer,frames/retrieval/visual_crops/val/ad9083b3-9b0...
1,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,2,scissor,frames/retrieval/visual_crops/val/ad9083b3-9b0...
2,ad9083b3-9b0b-4c27-a941-38f57be13edf,c5d8e8dd-19f5-4e38-9bbb-e94e04bd2b4b,3,spray can,frames/retrieval/visual_crops/val/ad9083b3-9b0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/984d6427-5bf1-477d-98fc-170b93165868_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,984d6427-5bf1-477d-98fc-170b93165868,83ad176b-3ded-4298-90df-b43096882d31,2,pen,frames/retrieval/visual_crops/val/984d6427-5bf...
1,984d6427-5bf1-477d-98fc-170b93165868,83ad176b-3ded-4298-90df-b43096882d31,3,perfume bottle,frames/retrieval/visual_crops/val/984d6427-5bf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1ffc605c-c5f5-42d3-9897-6e9319675497_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,1,waste bin,frames/retrieval/visual_crops/val/1ffc605c-c5f...
1,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,2,bottle,frames/retrieval/visual_crops/val/1ffc605c-c5f...
2,1ffc605c-c5f5-42d3-9897-6e9319675497,eca5853b-5ec4-40fd-9fe9-643267bd4ca5,3,calculator,frames/retrieval/visual_crops/val/1ffc605c-c5f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a881f4a6-1d84-4088-8cea-8cf3a61c0914_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,3,vehicle,frames/retrieval/visual_crops/val/a881f4a6-1d8...
1,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,1,tooth brush,frames/retrieval/visual_crops/val/a881f4a6-1d8...
2,a881f4a6-1d84-4088-8cea-8cf3a61c0914,7e82390e-ce12-4eb5-b72a-212d623b3dea,2,plastic jerry can tap,frames/retrieval/visual_crops/val/a881f4a6-1d8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8f829383-08e6-48a9-85f9-0999eb9379a3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,1,weighing scale,frames/retrieval/visual_crops/val/8f829383-08e...
1,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,2,soap dish bottle,frames/retrieval/visual_crops/val/8f829383-08e...
2,8f829383-08e6-48a9-85f9-0999eb9379a3,9e973d0b-c6ee-4c35-8c24-cbc5b3b8bf9b,3,funnel,frames/retrieval/visual_crops/val/8f829383-08e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9b9b7994-8a7a-43ac-9382-744664ee3e66_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,1,cup,frames/retrieval/visual_crops/val/9b9b7994-8a7...
1,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,2,regulator,frames/retrieval/visual_crops/val/9b9b7994-8a7...
2,9b9b7994-8a7a-43ac-9382-744664ee3e66,2dbd262a-dee0-4166-8a2a-5886b58221b9,3,washing machine,frames/retrieval/visual_crops/val/9b9b7994-8a7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a928aa57-8047-4156-8851-f94f75d57f70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,2,drill,frames/retrieval/visual_crops/val/a928aa57-804...
1,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,1,tissue,frames/retrieval/visual_crops/val/a928aa57-804...
2,a928aa57-8047-4156-8851-f94f75d57f70,40c9533b-2b62-4735-a619-9c32bfba119d,3,container,frames/retrieval/visual_crops/val/a928aa57-804...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c7fd4879-e196-4195-8fa8-d4430ae90a9a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,1,bottle,frames/retrieval/visual_crops/val/c7fd4879-e19...
1,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,2,nylon,frames/retrieval/visual_crops/val/c7fd4879-e19...
2,c7fd4879-e196-4195-8fa8-d4430ae90a9a,01fb677a-c777-435b-b748-262376bf3eb4,3,brush,frames/retrieval/visual_crops/val/c7fd4879-e19...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dfe962ab-6aa7-4888-9378-796817a30ab6_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,frames/retrieval/visual_crops/val/dfe962ab-6aa...
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,frames/retrieval/visual_crops/val/dfe962ab-6aa...
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,frames/retrieval/visual_crops/val/dfe962ab-6aa...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/412ee977-da12-496e-9609-80bfef2f4638_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,1,plate,frames/retrieval/visual_crops/val/412ee977-da1...
1,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,2,cooking pot,frames/retrieval/visual_crops/val/412ee977-da1...
2,412ee977-da12-496e-9609-80bfef2f4638,5699a24b-dc46-4604-b127-a89c14ceac31,3,kitchen oven,frames/retrieval/visual_crops/val/412ee977-da1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/563db64f-47c4-42e3-b8bf-c543fd78655a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,1,yellow chair,frames/retrieval/visual_crops/val/563db64f-47c...
1,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,2,dustbin,frames/retrieval/visual_crops/val/563db64f-47c...
2,563db64f-47c4-42e3-b8bf-c543fd78655a,c1c14e1e-3560-4887-b6f0-1a2095f6d5b3,3,stapler,frames/retrieval/visual_crops/val/563db64f-47c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/77e3af3b-a5ec-420c-a3bc-a2aff4934ce3_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,1,round tray,frames/retrieval/visual_crops/val/77e3af3b-a5e...
1,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,3,strainer bowl,frames/retrieval/visual_crops/val/77e3af3b-a5e...
2,77e3af3b-a5ec-420c-a3bc-a2aff4934ce3,8353783b-2400-4873-b1aa-31ac729c3487,2,pedestal fan,frames/retrieval/visual_crops/val/77e3af3b-a5e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fe3000d6-d857-4cd1-a927-0a91a7f9616e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,3,jug,frames/retrieval/visual_crops/val/fe3000d6-d85...
1,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,2,scraper,frames/retrieval/visual_crops/val/fe3000d6-d85...
2,fe3000d6-d857-4cd1-a927-0a91a7f9616e,f00d43d7-5ab6-4eba-85b6-be7644c86708,1,red dough scraper,frames/retrieval/visual_crops/val/fe3000d6-d85...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/248cf237-d8dc-42d1-ae41-017221765031_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,1,microwave,frames/retrieval/visual_crops/val/248cf237-d8d...
1,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,2,basin,frames/retrieval/visual_crops/val/248cf237-d8d...
2,248cf237-d8dc-42d1-ae41-017221765031,25d4665d-501b-4c3e-a73f-bf4c17ad8253,3,brush,frames/retrieval/visual_crops/val/248cf237-d8d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/63a1c028-3919-462b-9c97-9a22c5296eae_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,2,container,frames/retrieval/visual_crops/val/63a1c028-391...
1,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,3,ring boiler,frames/retrieval/visual_crops/val/63a1c028-391...
2,63a1c028-3919-462b-9c97-9a22c5296eae,0a472307-40e1-4d95-b73a-20f095f7ecd7,1,pillow,frames/retrieval/visual_crops/val/63a1c028-391...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8ebdf93c-6bba-4604-be9b-45938eb2bb38_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,3,plastic bags,frames/retrieval/visual_crops/val/8ebdf93c-6bb...
1,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,2,red pepper,frames/retrieval/visual_crops/val/8ebdf93c-6bb...
2,8ebdf93c-6bba-4604-be9b-45938eb2bb38,cdca6b28-4283-4979-ba6f-c757060c097d,1,shopping basket,frames/retrieval/visual_crops/val/8ebdf93c-6bb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e8a88ddf-63db-4095-93fe-9d24c386a477_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,1,cup,frames/retrieval/visual_crops/val/e8a88ddf-63d...
1,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,2,remote control,frames/retrieval/visual_crops/val/e8a88ddf-63d...
2,e8a88ddf-63db-4095-93fe-9d24c386a477,64cd1fef-c06e-48d0-92fc-602bc814ca66,3,soft drink,frames/retrieval/visual_crops/val/e8a88ddf-63d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7a954faf-102f-4aba-9317-96d73c8fd104_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,3,shopping basket,frames/retrieval/visual_crops/val/7a954faf-102...
1,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,2,belt,frames/retrieval/visual_crops/val/7a954faf-102...
2,7a954faf-102f-4aba-9317-96d73c8fd104,65fd6ec9-c1c3-460c-9891-2e821aa3e0c6,1,marvin hat,frames/retrieval/visual_crops/val/7a954faf-102...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/efe7dfaa-07e0-42d5-85eb-1e6f93409ab5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,1,plastic bottle,frames/retrieval/visual_crops/val/efe7dfaa-07e...
1,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,2,screwdriver,frames/retrieval/visual_crops/val/efe7dfaa-07e...
2,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,3,t wrench,frames/retrieval/visual_crops/val/efe7dfaa-07e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fe71b934-322a-45a1-862c-cd7c2db2c354_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,1,gamepad,frames/retrieval/visual_crops/val/fe71b934-322...
1,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,2,paper roll,frames/retrieval/visual_crops/val/fe71b934-322...
2,fe71b934-322a-45a1-862c-cd7c2db2c354,147a4e1c-3621-4cb1-9850-0357d7ac8422,3,television,frames/retrieval/visual_crops/val/fe71b934-322...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f91c7008-f21c-4047-bfc1-d937787665e5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,1,scraper tool,frames/retrieval/visual_crops/val/f91c7008-f21...
1,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,3,stack of baskets,frames/retrieval/visual_crops/val/f91c7008-f21...
2,f91c7008-f21c-4047-bfc1-d937787665e5,0671faef-9d2a-4db4-b0d9-e25d3f1ca73a,2,rolling stick,frames/retrieval/visual_crops/val/f91c7008-f21...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/70d3a98e-132b-4446-aa99-cab279318dc8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,2,serving spoon,frames/retrieval/visual_crops/val/70d3a98e-132...
1,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,3,stainless plate,frames/retrieval/visual_crops/val/70d3a98e-132...
2,70d3a98e-132b-4446-aa99-cab279318dc8,fdf5f199-550c-46dc-8c7f-7548af5170d4,1,water bottle,frames/retrieval/visual_crops/val/70d3a98e-132...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7ecce159-e45f-4e35-9289-f61abfa02147_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,1,plier,frames/retrieval/visual_crops/val/7ecce159-e45...
1,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,2,brush broom,frames/retrieval/visual_crops/val/7ecce159-e45...
2,7ecce159-e45f-4e35-9289-f61abfa02147,cb7f574a-7ce6-496f-92f8-0b3daa84f9eb,3,creeper seat,frames/retrieval/visual_crops/val/7ecce159-e45...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6bfb9000-73c2-4698-8757-889251a4b5e9_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,1,marvin,frames/retrieval/visual_crops/val/6bfb9000-73c...
1,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,3,tie box,frames/retrieval/visual_crops/val/6bfb9000-73c...
2,6bfb9000-73c2-4698-8757-889251a4b5e9,4b308fe0-9cba-48f4-a436-7241c6086ef8,2,purse,frames/retrieval/visual_crops/val/6bfb9000-73c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0df1db1f-40a0-4139-b120-9a1c741f571c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,2,cake,frames/retrieval/visual_crops/val/0df1db1f-40a...
1,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,1,basket trolley,frames/retrieval/visual_crops/val/0df1db1f-40a...
2,0df1db1f-40a0-4139-b120-9a1c741f571c,813dccaf-259d-4fad-a325-d87dc7fca5d5,3,calculator,frames/retrieval/visual_crops/val/0df1db1f-40a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,1,lamp shade,frames/retrieval/visual_crops/val/8b1676e2-8a9...
1,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,2,desk top,frames/retrieval/visual_crops/val/8b1676e2-8a9...
2,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,3,plant pot,frames/retrieval/visual_crops/val/8b1676e2-8a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f54175da-19e5-4ee7-97b3-75baa247b713_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,3,scoop,frames/retrieval/visual_crops/val/f54175da-19e...
1,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,1,bowl,frames/retrieval/visual_crops/val/f54175da-19e...
2,f54175da-19e5-4ee7-97b3-75baa247b713,5ecdee7a-6e50-4bd1-9f7e-f68671fb26d0,2,chair,frames/retrieval/visual_crops/val/f54175da-19e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,1,garage spray,frames/retrieval/visual_crops/val/1b0d8f14-d03...
1,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,2,cutting pliers,frames/retrieval/visual_crops/val/1b0d8f14-d03...
2,1b0d8f14-d03f-43e4-9ad4-421d7d7c6eed,faf580b5-1865-4929-b62b-2ada4221170b,3,brake rotor,frames/retrieval/visual_crops/val/1b0d8f14-d03...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a408cff1-1387-421f-aad6-7480899a4fe0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,1,scarf,frames/retrieval/visual_crops/val/a408cff1-138...
1,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,3,mirror,frames/retrieval/visual_crops/val/a408cff1-138...
2,a408cff1-1387-421f-aad6-7480899a4fe0,e6d469a9-e2d5-466e-8087-7b2e0a6cf09c,2,cloth.,frames/retrieval/visual_crops/val/a408cff1-138...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/17e7a80c-b5ca-435f-a29e-0d026fcf2e96_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,2,gloves,frames/retrieval/visual_crops/val/17e7a80c-b5c...
1,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,1,scissor,frames/retrieval/visual_crops/val/17e7a80c-b5c...
2,17e7a80c-b5ca-435f-a29e-0d026fcf2e96,d8274e26-b77e-425c-8588-979d1f3cbccc,3,sandals,frames/retrieval/visual_crops/val/17e7a80c-b5c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ea365183-5841-4f00-9a2e-1b81c5e09c98_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,1,spray bottle,frames/retrieval/visual_crops/val/ea365183-584...
1,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,3,red jerry can,frames/retrieval/visual_crops/val/ea365183-584...
2,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,2,orange shock absorber,frames/retrieval/visual_crops/val/ea365183-584...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/67c47998-eabe-4b31-9096-b286c18e1beb_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,1,basket,frames/retrieval/visual_crops/val/67c47998-eab...
1,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,2,wallet,frames/retrieval/visual_crops/val/67c47998-eab...
2,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,3,receipt,frames/retrieval/visual_crops/val/67c47998-eab...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e118e100-cc06-48c5-a542-e07c44d72469_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,1,bottle,frames/retrieval/visual_crops/val/e118e100-cc0...
1,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,3,bottle,frames/retrieval/visual_crops/val/e118e100-cc0...
2,e118e100-cc06-48c5-a542-e07c44d72469,3e643302-a147-46c3-aa7a-fa0fc734385a,2,wire,frames/retrieval/visual_crops/val/e118e100-cc0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d9d45d26-743b-4e26-8137-416372bdaddb_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,2,calculator,frames/retrieval/visual_crops/val/d9d45d26-743...
1,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,1,sample bottle,frames/retrieval/visual_crops/val/d9d45d26-743...
2,d9d45d26-743b-4e26-8137-416372bdaddb,b10166d2-43fd-4634-976f-9f60e805ce27,3,container,frames/retrieval/visual_crops/val/d9d45d26-743...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f052ac6f-832d-41f0-b00f-7cb85c20a15c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,1,plastic container,frames/retrieval/visual_crops/val/f052ac6f-832...
1,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,3,paper towel,frames/retrieval/visual_crops/val/f052ac6f-832...
2,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,2,toothbrush,frames/retrieval/visual_crops/val/f052ac6f-832...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,1,kettle,frames/retrieval/visual_crops/val/1eb0ae30-d0b...
1,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,2,tissue,frames/retrieval/visual_crops/val/1eb0ae30-d0b...
2,1eb0ae30-d0b2-4208-87e5-5ba23e1eeb1d,7dcac5af-8a4b-4411-b8e8-af051469106d,3,stand mixer,frames/retrieval/visual_crops/val/1eb0ae30-d0b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/64cc6d12-f613-452f-b56b-451f395c9c10_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,3,coffee maker,frames/retrieval/visual_crops/val/64cc6d12-f61...
1,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,2,remote,frames/retrieval/visual_crops/val/64cc6d12-f61...
2,64cc6d12-f613-452f-b56b-451f395c9c10,533d6d12-4005-4119-b103-e4ea0ebe26e3,1,television,frames/retrieval/visual_crops/val/64cc6d12-f61...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/706c54f8-2740-40bb-a341-651b708392fa_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,1,scissor,frames/retrieval/visual_crops/val/706c54f8-274...
1,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,2,tweezer,frames/retrieval/visual_crops/val/706c54f8-274...
2,706c54f8-2740-40bb-a341-651b708392fa,7ce88054-18db-4b10-bf3c-e89ae2521d17,3,torch,frames/retrieval/visual_crops/val/706c54f8-274...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/02089b3c-2c7a-430b-9c7c-9c3f39249ec7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,2,vacuum cleaner,frames/retrieval/visual_crops/val/02089b3c-2c7...
1,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,1,battery,frames/retrieval/visual_crops/val/02089b3c-2c7...
2,02089b3c-2c7a-430b-9c7c-9c3f39249ec7,3d63b76a-0cde-4c0d-b019-f3ffcd23551d,3,frame,frames/retrieval/visual_crops/val/02089b3c-2c7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/293a2530-a4a8-4776-92d5-741142dfdd3e_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,1,cooking pan,frames/retrieval/visual_crops/val/293a2530-a4a...
1,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,3,bucket,frames/retrieval/visual_crops/val/293a2530-a4a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b7eaf50a-2499-45bd-abd8-478463fdc4a8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,1,coffee cup,frames/retrieval/visual_crops/val/b7eaf50a-249...
1,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,2,eggplant,frames/retrieval/visual_crops/val/b7eaf50a-249...
2,b7eaf50a-2499-45bd-abd8-478463fdc4a8,bc955e4e-87fa-4508-b548-f95bf229630c,3,sack,frames/retrieval/visual_crops/val/b7eaf50a-249...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c908ae46-123b-466d-a709-99d4d4bc8d37_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,1,jug,frames/retrieval/visual_crops/val/c908ae46-123...
1,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,2,coffee table,frames/retrieval/visual_crops/val/c908ae46-123...
2,c908ae46-123b-466d-a709-99d4d4bc8d37,3e68885c-126b-46ba-b9ee-663158d3af4a,3,sport shoe,frames/retrieval/visual_crops/val/c908ae46-123...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,1,tape measure,frames/retrieval/visual_crops/val/2ceb0fb0-91f...
1,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,2,box,frames/retrieval/visual_crops/val/2ceb0fb0-91f...
2,2ceb0fb0-91f3-49a9-9bf2-319094f4ecd0,3eb0c0b6-50aa-45f6-8c37-5c6319c87e67,3,timber,frames/retrieval/visual_crops/val/2ceb0fb0-91f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/30ca6fa7-dbe0-4f55-84c8-8797de99c290_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,3,flower pot,frames/retrieval/visual_crops/val/30ca6fa7-dbe...
1,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,1,pillows,frames/retrieval/visual_crops/val/30ca6fa7-dbe...
2,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,2,cloth,frames/retrieval/visual_crops/val/30ca6fa7-dbe...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/148d1a43-5368-4257-8e98-8a762ad1d113_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,2,long sleeved t-shirt,frames/retrieval/visual_crops/val/148d1a43-536...
1,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,1,shoes,frames/retrieval/visual_crops/val/148d1a43-536...
2,148d1a43-5368-4257-8e98-8a762ad1d113,672d6811-99b5-4fc6-a2ae-c591426bd97f,3,marvin,frames/retrieval/visual_crops/val/148d1a43-536...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/21e4b10c-e1c2-4b11-bee3-9528e61b56e3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,3,bottle,frames/retrieval/visual_crops/val/21e4b10c-e1c...
1,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,1,pos machine,frames/retrieval/visual_crops/val/21e4b10c-e1c...
2,21e4b10c-e1c2-4b11-bee3-9528e61b56e3,fee0aa2a-8b34-4842-8ade-b460938f6c38,2,phone,frames/retrieval/visual_crops/val/21e4b10c-e1c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a71f6663-ef4b-4283-8210-652b21b37a36_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,1,brush,frames/retrieval/visual_crops/val/a71f6663-ef4...
1,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,2,impact wrench,frames/retrieval/visual_crops/val/a71f6663-ef4...
2,a71f6663-ef4b-4283-8210-652b21b37a36,6401c224-c762-4106-9429-889673e23a77,3,container,frames/retrieval/visual_crops/val/a71f6663-ef4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/eb0359b2-72f1-40ff-ba22-64bb818d1f48_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,2,shopping basket,frames/retrieval/visual_crops/val/eb0359b2-72f...
1,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,1,boots,frames/retrieval/visual_crops/val/eb0359b2-72f...
2,eb0359b2-72f1-40ff-ba22-64bb818d1f48,352cd72b-e02b-4d5d-b13f-340184c698ce,3,wallet,frames/retrieval/visual_crops/val/eb0359b2-72f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7b452799-981c-494a-affb-d011cd5c43e5_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,1,plastic bowl,frames/retrieval/visual_crops/val/7b452799-981...
1,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,2,liquid soap bottle,frames/retrieval/visual_crops/val/7b452799-981...
2,7b452799-981c-494a-affb-d011cd5c43e5,a589348d-669f-42c5-bc2b-b38342fa2783,3,kettle,frames/retrieval/visual_crops/val/7b452799-981...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/714ee146-e130-439d-89ff-6876efe62b07_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,1,phone,frames/retrieval/visual_crops/val/714ee146-e13...
1,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,2,cup,frames/retrieval/visual_crops/val/714ee146-e13...
2,714ee146-e130-439d-89ff-6876efe62b07,9b288f90-c465-447e-8a63-0fc819a00a72,3,knife,frames/retrieval/visual_crops/val/714ee146-e13...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/16fce853-9528-4c39-9f88-b0c61f30d01d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,2,shears,frames/retrieval/visual_crops/val/16fce853-952...
1,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,3,grapes,frames/retrieval/visual_crops/val/16fce853-952...
2,16fce853-9528-4c39-9f88-b0c61f30d01d,9f52e605-43b5-4504-ab2a-e395da715b8e,1,crate,frames/retrieval/visual_crops/val/16fce853-952...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/90288170-a577-48e6-afe6-014673ae8723_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,1,tin,frames/retrieval/visual_crops/val/90288170-a57...
1,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,3,metal basin,frames/retrieval/visual_crops/val/90288170-a57...
2,90288170-a577-48e6-afe6-014673ae8723,e661708d-25c3-4386-a9b9-1c1bb3ba9e8f,2,winnowing basket,frames/retrieval/visual_crops/val/90288170-a57...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/593a5700-05d7-46ba-a2c2-c5150b514144_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,1,paper,frames/retrieval/visual_crops/val/593a5700-05d...
1,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,2,sack,frames/retrieval/visual_crops/val/593a5700-05d...
2,593a5700-05d7-46ba-a2c2-c5150b514144,b5ea0b2e-0f2f-4aed-9666-3e62600a4441,3,slippers,frames/retrieval/visual_crops/val/593a5700-05d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1e938429-6376-4bc8-a145-7225f885e026_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,1,pair of scissors,frames/retrieval/visual_crops/val/1e938429-637...
1,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,2,cellphone,frames/retrieval/visual_crops/val/1e938429-637...
2,1e938429-6376-4bc8-a145-7225f885e026,b17a3260-b0f7-448c-a394-42053e86cd9f,3,spoon,frames/retrieval/visual_crops/val/1e938429-637...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/56c1dc45-24f5-45aa-8273-ed5835bce1f3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,1,weighing scale,frames/retrieval/visual_crops/val/56c1dc45-24f...
1,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,2,shopping basket,frames/retrieval/visual_crops/val/56c1dc45-24f...
2,56c1dc45-24f5-45aa-8273-ed5835bce1f3,1632ef13-2915-4beb-a114-054c34ae2d68,3,sauce bottle,frames/retrieval/visual_crops/val/56c1dc45-24f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/635733d7-8863-47b0-a7e2-4a0365813723_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,1,yellow tin,frames/retrieval/visual_crops/val/635733d7-886...
1,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,2,spray bottle,frames/retrieval/visual_crops/val/635733d7-886...
2,635733d7-8863-47b0-a7e2-4a0365813723,0aa71194-1386-4752-ba2b-27ebfc5976be,3,plate,frames/retrieval/visual_crops/val/635733d7-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d0bae6e6-356e-459d-b3dc-bc53c710611b_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,1,flower pot,frames/retrieval/visual_crops/val/d0bae6e6-356...
1,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,2,safety sign,frames/retrieval/visual_crops/val/d0bae6e6-356...
2,d0bae6e6-356e-459d-b3dc-bc53c710611b,56442162-ca28-4a66-a02d-a2711b3bc836,3,spray bottle,frames/retrieval/visual_crops/val/d0bae6e6-356...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/26f6ea45-4e7d-4208-b36c-715064151980_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,1,sponge,frames/retrieval/visual_crops/val/26f6ea45-4e7...
1,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,3,sieve,frames/retrieval/visual_crops/val/26f6ea45-4e7...
2,26f6ea45-4e7d-4208-b36c-715064151980,0423b9af-c4e1-4d8e-b97c-e9800f4f4a18,2,brush,frames/retrieval/visual_crops/val/26f6ea45-4e7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ddb94361-b4c3-4343-8a80-daad1ea69476_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,1,book stand,frames/retrieval/visual_crops/val/ddb94361-b4c...
1,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,3,house plant,frames/retrieval/visual_crops/val/ddb94361-b4c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2ae935a5-3266-47e0-884d-f8b8acb5ed1c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,2,tablet,frames/retrieval/visual_crops/val/2ae935a5-326...
1,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,1,memory card,frames/retrieval/visual_crops/val/2ae935a5-326...
2,2ae935a5-3266-47e0-884d-f8b8acb5ed1c,ebf92585-bd81-4431-8deb-b57e97078d7e,3,fire extinguisher,frames/retrieval/visual_crops/val/2ae935a5-326...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e4daf535-ef9c-493f-9688-9c2ba35d431a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,1,lightning connector,frames/retrieval/visual_crops/val/e4daf535-ef9...
1,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,3,water bottle,frames/retrieval/visual_crops/val/e4daf535-ef9...
2,e4daf535-ef9c-493f-9688-9c2ba35d431a,177fd21b-ef86-4226-89f8-d54ff324462c,2,towel,frames/retrieval/visual_crops/val/e4daf535-ef9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/918f04d6-65f3-4a8f-af65-b57852de1729_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,1,flower pot,frames/retrieval/visual_crops/val/918f04d6-65f...
1,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,2,rack,frames/retrieval/visual_crops/val/918f04d6-65f...
2,918f04d6-65f3-4a8f-af65-b57852de1729,1f8b5b4d-a774-4ca6-b3ff-b32bf69e0481,3,mop stick,frames/retrieval/visual_crops/val/918f04d6-65f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bd600d49-9db0-4e6f-8698-cf18f3cef8a8_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,3,trolley,frames/retrieval/visual_crops/val/bd600d49-9db...
1,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,1,nylon roll,frames/retrieval/visual_crops/val/bd600d49-9db...
2,bd600d49-9db0-4e6f-8698-cf18f3cef8a8,e234a58f-7b2b-454a-a555-6a961992c102,2,stainless bowl,frames/retrieval/visual_crops/val/bd600d49-9db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/85b01a98-245e-4b63-bff8-4545aedaf916_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,1,shopping basket,frames/retrieval/visual_crops/val/85b01a98-245...
1,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,2,oreo biscuits,frames/retrieval/visual_crops/val/85b01a98-245...
2,85b01a98-245e-4b63-bff8-4545aedaf916,8aa27d07-aa6d-4535-9672-a10baa076a0c,3,warning sigh,frames/retrieval/visual_crops/val/85b01a98-245...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b27d698c-ce47-47ed-86e7-652cef7d3e2c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,1,plastic bucket,frames/retrieval/visual_crops/val/b27d698c-ce4...
1,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,3,jug,frames/retrieval/visual_crops/val/b27d698c-ce4...
2,b27d698c-ce47-47ed-86e7-652cef7d3e2c,6e266743-7822-4079-90f6-a08996ee3d90,2,plate,frames/retrieval/visual_crops/val/b27d698c-ce4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ab141ed-312d-4db3-a424-433e417e15ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,1,scissors,frames/retrieval/visual_crops/val/5ab141ed-312...
1,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,2,container,frames/retrieval/visual_crops/val/5ab141ed-312...
2,5ab141ed-312d-4db3-a424-433e417e15ef,db87ce31-1c01-4e8e-89d4-371c7ad4d52d,3,pot,frames/retrieval/visual_crops/val/5ab141ed-312...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7bb5593c-c017-4e68-aa69-0bc2bb50e2a1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,1,bicycle,frames/retrieval/visual_crops/val/7bb5593c-c01...
1,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,2,tissue,frames/retrieval/visual_crops/val/7bb5593c-c01...
2,7bb5593c-c017-4e68-aa69-0bc2bb50e2a1,1f831d1b-51a3-4beb-a6b2-dd0bb33ec0b4,3,dust pan and brush,frames/retrieval/visual_crops/val/7bb5593c-c01...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3d1bc6e6-e445-4748-9b08-727a1ce2e697_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,1,toolbox,frames/retrieval/visual_crops/val/3d1bc6e6-e44...
1,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,2,ladder,frames/retrieval/visual_crops/val/3d1bc6e6-e44...
2,3d1bc6e6-e445-4748-9b08-727a1ce2e697,81bdea0e-45a8-4824-a898-360fbb940ae1,3,container,frames/retrieval/visual_crops/val/3d1bc6e6-e44...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fc838ebc-2c4e-42f2-8108-9710ecb1653a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,2,trash can,frames/retrieval/visual_crops/val/fc838ebc-2c4...
1,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,3,bottle,frames/retrieval/visual_crops/val/fc838ebc-2c4...
2,fc838ebc-2c4e-42f2-8108-9710ecb1653a,07a00a78-c74b-4422-a34f-4e3a7c1d83be,1,a phone,frames/retrieval/visual_crops/val/fc838ebc-2c4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/50e73fa7-8ca7-41a3-a326-bc0b4a2f1482_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,1,basket,frames/retrieval/visual_crops/val/50e73fa7-8ca...
1,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,3,grocery bag,frames/retrieval/visual_crops/val/50e73fa7-8ca...
2,50e73fa7-8ca7-41a3-a326-bc0b4a2f1482,65223764-3f2e-4a59-b36e-f6bc5fb2f65d,2,trolley,frames/retrieval/visual_crops/val/50e73fa7-8ca...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/48a81e63-9f9e-48c1-84e0-5fb90549cc4e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,1,paint brush,frames/retrieval/visual_crops/val/48a81e63-9f9...
1,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,3,polytene bag,frames/retrieval/visual_crops/val/48a81e63-9f9...
2,48a81e63-9f9e-48c1-84e0-5fb90549cc4e,876dbbe7-8067-4a86-9ede-5c027cee9302,2,bucket,frames/retrieval/visual_crops/val/48a81e63-9f9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/63f79304-5e02-415b-b375-73a39b8b4271_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,63f79304-5e02-415b-b375-73a39b8b4271,ee858c8b-6293-4055-bcd0-b9e78b03ae1f,2,scissors,frames/retrieval/visual_crops/val/63f79304-5e0...
1,63f79304-5e02-415b-b375-73a39b8b4271,ee858c8b-6293-4055-bcd0-b9e78b03ae1f,3,brown box,frames/retrieval/visual_crops/val/63f79304-5e0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0432e5c6-d2e3-4729-bf1e-0ea8803687ee_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,1,frame,frames/retrieval/visual_crops/val/0432e5c6-d2e...
1,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,2,fluffy toy,frames/retrieval/visual_crops/val/0432e5c6-d2e...
2,0432e5c6-d2e3-4729-bf1e-0ea8803687ee,4049a6be-e7f0-4338-aa6b-39fb0cd139c0,3,brush,frames/retrieval/visual_crops/val/0432e5c6-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,3,kitchen towel,frames/retrieval/visual_crops/val/19ad94cc-302...
1,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,2,umbrella,frames/retrieval/visual_crops/val/19ad94cc-302...
2,19ad94cc-3029-4d4b-bcbe-8bad52fe0ea5,e2e2daaf-62d4-4fff-88a9-7a7e0c525794,1,scissors,frames/retrieval/visual_crops/val/19ad94cc-302...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c16cc2f1-a2a8-42f4-82f3-6867f9b6da12_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,1,guitar,frames/retrieval/visual_crops/val/c16cc2f1-a2a...
1,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,2,paper,frames/retrieval/visual_crops/val/c16cc2f1-a2a...
2,c16cc2f1-a2a8-42f4-82f3-6867f9b6da12,19aa1a52-dea8-4055-8ed8-176e782317c5,3,container,frames/retrieval/visual_crops/val/c16cc2f1-a2a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,1,bowl,frames/retrieval/visual_crops/val/b4e513cf-28d...
1,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,2,spoon,frames/retrieval/visual_crops/val/b4e513cf-28d...
2,b4e513cf-28d8-4e5d-b7d5-9b85fdfb72a3,54d85f23-dc57-40d9-8a70-05ebd17880e7,3,bowl,frames/retrieval/visual_crops/val/b4e513cf-28d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cafcebbb-d1c1-439b-8228-3bd95b8d3b7f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,1,crate,frames/retrieval/visual_crops/val/cafcebbb-d1c...
1,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,2,shears,frames/retrieval/visual_crops/val/cafcebbb-d1c...
2,cafcebbb-d1c1-439b-8228-3bd95b8d3b7f,634c72c5-8dbd-4be6-bdc8-4a60fc0069f7,3,grapes,frames/retrieval/visual_crops/val/cafcebbb-d1c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/79cc2baa-4289-44f2-a013-ac6943b3f35d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,1,phone,frames/retrieval/visual_crops/val/79cc2baa-428...
1,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,2,liquid wash,frames/retrieval/visual_crops/val/79cc2baa-428...
2,79cc2baa-4289-44f2-a013-ac6943b3f35d,45ee097f-c3f9-4124-ad88-a0bfcb4180ae,3,earphones,frames/retrieval/visual_crops/val/79cc2baa-428...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e4728a65-3184-4239-9b84-be43dfd7377e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,2,jug,frames/retrieval/visual_crops/val/e4728a65-318...
1,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,3,wood cutting machine,frames/retrieval/visual_crops/val/e4728a65-318...
2,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,1,container,frames/retrieval/visual_crops/val/e4728a65-318...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/925b50c0-c5d7-48dc-877a-c5a2593b70d6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,2,spanner,frames/retrieval/visual_crops/val/925b50c0-c5d...
1,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,3,tool box,frames/retrieval/visual_crops/val/925b50c0-c5d...
2,925b50c0-c5d7-48dc-877a-c5a2593b70d6,f639f52f-35cd-413b-9b79-009cfd0787f3,1,tissue paper,frames/retrieval/visual_crops/val/925b50c0-c5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6f3c6977-b9dc-40de-bd32-349567343f0a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,3,bottle,frames/retrieval/visual_crops/val/6f3c6977-b9d...
1,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,1,pen,frames/retrieval/visual_crops/val/6f3c6977-b9d...
2,6f3c6977-b9dc-40de-bd32-349567343f0a,2f04099a-f7a0-405b-a1c2-1b74d87ec203,2,baloon,frames/retrieval/visual_crops/val/6f3c6977-b9d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/88f358c1-b11a-4868-aaf4-e1cb273c4b8a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,2,chair,frames/retrieval/visual_crops/val/88f358c1-b11...
1,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,3,container,frames/retrieval/visual_crops/val/88f358c1-b11...
2,88f358c1-b11a-4868-aaf4-e1cb273c4b8a,be320736-8b98-4a14-91f1-0fb7f75f6eaf,1,dough press,frames/retrieval/visual_crops/val/88f358c1-b11...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0858668c-35b2-4593-acb0-f6d4a8da483d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,2,shopping basket,frames/retrieval/visual_crops/val/0858668c-35b...
1,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,1,weighing scale,frames/retrieval/visual_crops/val/0858668c-35b...
2,0858668c-35b2-4593-acb0-f6d4a8da483d,f7ad7153-dce6-49d0-a3b0-24b80e7ec623,3,stand,frames/retrieval/visual_crops/val/0858668c-35b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2809b5d6-4811-4f6a-8621-4f0f89b697a8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,1,pen,frames/retrieval/visual_crops/val/2809b5d6-481...
1,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,2,jerrycan,frames/retrieval/visual_crops/val/2809b5d6-481...
2,2809b5d6-4811-4f6a-8621-4f0f89b697a8,ccaf25f0-e38b-4fe2-9bae-7c0e35fe70f7,3,green cello tape,frames/retrieval/visual_crops/val/2809b5d6-481...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b9c96242-ae4d-4a43-a308-a00591f060ab_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,1,keyboard,frames/retrieval/visual_crops/val/b9c96242-ae4...
1,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,2,tissue box,frames/retrieval/visual_crops/val/b9c96242-ae4...
2,b9c96242-ae4d-4a43-a308-a00591f060ab,41dec48b-ac6a-43b2-8608-0fb78356ccd3,3,electric kettle,frames/retrieval/visual_crops/val/b9c96242-ae4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/151c66b5-bdb2-42ba-b663-8ef307223d7a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,2,paint tin,frames/retrieval/visual_crops/val/151c66b5-bdb...
1,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,1,paint palette try,frames/retrieval/visual_crops/val/151c66b5-bdb...
2,151c66b5-bdb2-42ba-b663-8ef307223d7a,0ee2e7fa-d05d-4ae7-8ef4-54094788f7d8,3,throw pillows,frames/retrieval/visual_crops/val/151c66b5-bdb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/045dafcd-1ae7-443c-9a55-cd6b390372b3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,2,cup,frames/retrieval/visual_crops/val/045dafcd-1ae...
1,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,1,bottle,frames/retrieval/visual_crops/val/045dafcd-1ae...
2,045dafcd-1ae7-443c-9a55-cd6b390372b3,da5d1a9c-b4dc-4f00-a646-d13733f9401b,3,phone,frames/retrieval/visual_crops/val/045dafcd-1ae...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/48d9f08a-abe2-471f-9c2b-4d8e67f33d59_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,1,book,frames/retrieval/visual_crops/val/48d9f08a-abe...
1,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,2,cup,frames/retrieval/visual_crops/val/48d9f08a-abe...
2,48d9f08a-abe2-471f-9c2b-4d8e67f33d59,1552ad0f-3eb0-4bcb-8d87-e6f7cd72764b,3,house plant,frames/retrieval/visual_crops/val/48d9f08a-abe...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc994557-a65b-48a9-94c6-122ede470347_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,2,exercise ball,frames/retrieval/visual_crops/val/cc994557-a65...
1,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,3,remote control,frames/retrieval/visual_crops/val/cc994557-a65...
2,cc994557-a65b-48a9-94c6-122ede470347,f5cbc0fe-46e9-4118-965e-36ecef1439cc,1,phone,frames/retrieval/visual_crops/val/cc994557-a65...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/54892083-4f4a-4535-b0c9-8babf21492f2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,1,water bottle,frames/retrieval/visual_crops/val/54892083-4f4...
1,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,2,cap,frames/retrieval/visual_crops/val/54892083-4f4...
2,54892083-4f4a-4535-b0c9-8babf21492f2,f16eadc1-fc9b-409e-bd06-e8d2591c0a80,3,syringe tube,frames/retrieval/visual_crops/val/54892083-4f4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d28999ab-8945-4618-aa50-b37594573391_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,1,magazine,frames/retrieval/visual_crops/val/d28999ab-894...
1,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,2,nut bottle,frames/retrieval/visual_crops/val/d28999ab-894...
2,d28999ab-8945-4618-aa50-b37594573391,f7af84c6-1d23-4591-89e4-741aef392260,3,cake,frames/retrieval/visual_crops/val/d28999ab-894...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/01b451af-466a-4425-8094-be0b2ffc0e36_query_metadata.parquet
Shape: (1, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,01b451af-466a-4425-8094-be0b2ffc0e36,41a71f4b-d87b-4047-a553-eb0927b590e2,1,green hose,frames/retrieval/visual_crops/val/01b451af-466...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/022f1dbb-0018-4660-a18c-9e1213b88928_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,1,water bottle,frames/retrieval/visual_crops/val/022f1dbb-001...
1,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,2,playing cards,frames/retrieval/visual_crops/val/022f1dbb-001...
2,022f1dbb-0018-4660-a18c-9e1213b88928,9cf66810-ad51-4ec0-8724-b92d55b50fc4,3,spraying can,frames/retrieval/visual_crops/val/022f1dbb-001...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,2,bicycle tube,frames/retrieval/visual_crops/val/ac85fd41-ff1...
1,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,1,plier,frames/retrieval/visual_crops/val/ac85fd41-ff1...
2,ac85fd41-ff1e-47a7-9f7b-2596f4f05b9a,fa59f37d-d22c-4b08-a20a-b6858a53b889,3,screwdriver,frames/retrieval/visual_crops/val/ac85fd41-ff1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d029947a-03c7-4f43-86ef-8067e172b410_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,1,bottle,frames/retrieval/visual_crops/val/d029947a-03c...
1,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,2,paper,frames/retrieval/visual_crops/val/d029947a-03c...
2,d029947a-03c7-4f43-86ef-8067e172b410,2fcfe275-0643-4312-8a5c-3973956f583d,3,trolley,frames/retrieval/visual_crops/val/d029947a-03c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b961eb69-cfdd-4d5c-b427-4b667fedfcda_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,1,weighing scale,frames/retrieval/visual_crops/val/b961eb69-cfd...
1,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,2,chair,frames/retrieval/visual_crops/val/b961eb69-cfd...
2,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,3,shopping list,frames/retrieval/visual_crops/val/b961eb69-cfd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e7af8550-5a98-406a-b4a0-e8cf9f901d79_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,2,hose,frames/retrieval/visual_crops/val/e7af8550-5a9...
1,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,1,phone,frames/retrieval/visual_crops/val/e7af8550-5a9...
2,e7af8550-5a98-406a-b4a0-e8cf9f901d79,708539e4-4c08-4f90-a998-a0f77dfbb5b9,3,rim,frames/retrieval/visual_crops/val/e7af8550-5a9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bc576c20-68d9-47bc-9d04-b7e0bfc67abb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,2,plate,frames/retrieval/visual_crops/val/bc576c20-68d...
1,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,1,decorative flower,frames/retrieval/visual_crops/val/bc576c20-68d...
2,bc576c20-68d9-47bc-9d04-b7e0bfc67abb,546b35f2-8fc3-44f0-8b78-ff7499bc32f9,3,decoration,frames/retrieval/visual_crops/val/bc576c20-68d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9737f5fb-d4b7-420c-98ee-471ec872c808_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,1,measuring cup,frames/retrieval/visual_crops/val/9737f5fb-d4b...
1,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,2,basin,frames/retrieval/visual_crops/val/9737f5fb-d4b...
2,9737f5fb-d4b7-420c-98ee-471ec872c808,16e1d341-8c12-427e-85d4-6435f24cf56b,3,scraper,frames/retrieval/visual_crops/val/9737f5fb-d4b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b58bc49e-d3ac-4995-baa0-218a14e4c2fa_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,2,container,frames/retrieval/visual_crops/val/b58bc49e-d3a...
1,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,1,plastic paper,frames/retrieval/visual_crops/val/b58bc49e-d3a...
2,b58bc49e-d3ac-4995-baa0-218a14e4c2fa,c52779f9-c9b3-404c-89d9-06ac5041170c,3,nuts & bolts tin,frames/retrieval/visual_crops/val/b58bc49e-d3a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc711b14-cadc-40ef-b39f-611e57ec3956_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,2,sickle,frames/retrieval/visual_crops/val/cc711b14-cad...
1,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,3,plastic stool,frames/retrieval/visual_crops/val/cc711b14-cad...
2,cc711b14-cadc-40ef-b39f-611e57ec3956,e2b8fada-91d6-49b4-a2f3-de492f9c18be,1,maize scooper,frames/retrieval/visual_crops/val/cc711b14-cad...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5771acd7-c7a9-4350-8064-7763bf111149_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,1,phone,frames/retrieval/visual_crops/val/5771acd7-c7a...
1,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,2,busket,frames/retrieval/visual_crops/val/5771acd7-c7a...
2,5771acd7-c7a9-4350-8064-7763bf111149,ea7a9822-da39-4e4b-9435-b49c8ee1c9a8,3,oreo biscuits,frames/retrieval/visual_crops/val/5771acd7-c7a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/00e1c569-6c15-4447-8dd4-dfbe1f79dcdc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,1,container,frames/retrieval/visual_crops/val/00e1c569-6c1...
1,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,2,hand drill,frames/retrieval/visual_crops/val/00e1c569-6c1...
2,00e1c569-6c15-4447-8dd4-dfbe1f79dcdc,68f5510c-187b-4aaf-9053-bca709617082,3,pliers,frames/retrieval/visual_crops/val/00e1c569-6c1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7380c46e-cb33-4d49-bf73-a7bfe57c3feb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,3,tong,frames/retrieval/visual_crops/val/7380c46e-cb3...
1,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,1,kettle,frames/retrieval/visual_crops/val/7380c46e-cb3...
2,7380c46e-cb33-4d49-bf73-a7bfe57c3feb,ff101266-df57-46d0-b20f-8a74325e1702,2,paper towel,frames/retrieval/visual_crops/val/7380c46e-cb3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4479363e-cd84-4fe7-994e-02eaf4531b0b_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,1,spray bottle,frames/retrieval/visual_crops/val/4479363e-cd8...
1,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,2,battery,frames/retrieval/visual_crops/val/4479363e-cd8...
2,4479363e-cd84-4fe7-994e-02eaf4531b0b,a47c67d3-acd6-4e4b-ae36-e362c24a7e43,3,plastic bottle.,frames/retrieval/visual_crops/val/4479363e-cd8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5e961d49-5eb3-4d6d-b2f0-c9be437ba623_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,3,remote,frames/retrieval/visual_crops/val/5e961d49-5eb...
1,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,2,gamepad,frames/retrieval/visual_crops/val/5e961d49-5eb...
2,5e961d49-5eb3-4d6d-b2f0-c9be437ba623,1fedc695-6ad7-4e61-8a2d-6ab072f213a5,1,television,frames/retrieval/visual_crops/val/5e961d49-5eb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ce57cce9-c6c4-4e07-be46-a84b29e7462c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,1,trash bin,frames/retrieval/visual_crops/val/ce57cce9-c6c...
1,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,2,book,frames/retrieval/visual_crops/val/ce57cce9-c6c...
2,ce57cce9-c6c4-4e07-be46-a84b29e7462c,6438d992-2a18-4079-b982-3aa372d5188c,3,bottle,frames/retrieval/visual_crops/val/ce57cce9-c6c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/43ecb12f-8b33-416f-8c22-5c4544ed2370_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,1,bottle,frames/retrieval/visual_crops/val/43ecb12f-8b3...
1,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,2,pot,frames/retrieval/visual_crops/val/43ecb12f-8b3...
2,43ecb12f-8b33-416f-8c22-5c4544ed2370,e2cdb68c-f4f2-482d-87b7-34936da4539f,3,shoes,frames/retrieval/visual_crops/val/43ecb12f-8b3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d4196bb5-daf8-49f7-9010-bcc5797583d3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,3,beanie hat,frames/retrieval/visual_crops/val/d4196bb5-daf...
1,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,1,boots,frames/retrieval/visual_crops/val/d4196bb5-daf...
2,d4196bb5-daf8-49f7-9010-bcc5797583d3,b4d1a182-1bcb-4f5a-81fa-9bb0d61c6849,2,advert bilboard,frames/retrieval/visual_crops/val/d4196bb5-daf...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/efc97e5a-20a0-42f1-9cfd-fcede9bbe043_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,1,wood,frames/retrieval/visual_crops/val/efc97e5a-20a...
1,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,2,polyethene bag,frames/retrieval/visual_crops/val/efc97e5a-20a...
2,efc97e5a-20a0-42f1-9cfd-fcede9bbe043,c7cc22a8-118a-4b8f-96bf-435744286a64,3,vacuum cleaner,frames/retrieval/visual_crops/val/efc97e5a-20a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/61f93683-2f3d-4d44-867d-c980d9316775_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,1,doormat,frames/retrieval/visual_crops/val/61f93683-2f3...
1,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,2,polythene bag,frames/retrieval/visual_crops/val/61f93683-2f3...
2,61f93683-2f3d-4d44-867d-c980d9316775,09465ff8-55bd-4392-9233-3764aa9fd10f,3,wrapper,frames/retrieval/visual_crops/val/61f93683-2f3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b144e06c-ac25-4584-9ff4-93d6a8d04865_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,1,basket,frames/retrieval/visual_crops/val/b144e06c-ac2...
1,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,2,phone,frames/retrieval/visual_crops/val/b144e06c-ac2...
2,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,3,mirror,frames/retrieval/visual_crops/val/b144e06c-ac2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/617e8d7c-8764-4508-ba9b-c993282c70cd_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,3,parker,frames/retrieval/visual_crops/val/617e8d7c-876...
1,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,1,pliers,frames/retrieval/visual_crops/val/617e8d7c-876...
2,617e8d7c-8764-4508-ba9b-c993282c70cd,5258693d-0d88-4bda-8f7b-e1613d6288aa,2,container,frames/retrieval/visual_crops/val/617e8d7c-876...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4eddd9cf-ce91-4273-8184-a88e7255a65e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,3,bowl,frames/retrieval/visual_crops/val/4eddd9cf-ce9...
1,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,1,gas cooker,frames/retrieval/visual_crops/val/4eddd9cf-ce9...
2,4eddd9cf-ce91-4273-8184-a88e7255a65e,36546a1a-069c-454a-99f4-b0a94126a18b,2,jerrycan,frames/retrieval/visual_crops/val/4eddd9cf-ce9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,1,plastic bowl,frames/retrieval/visual_crops/val/5ba7c109-3a1...
1,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,2,cup,frames/retrieval/visual_crops/val/5ba7c109-3a1...
2,5ba7c109-3a1c-473f-94b3-1e1bd81b8ac2,ceb4049b-03b6-4fed-9845-1e01b9b20bbb,3,pot,frames/retrieval/visual_crops/val/5ba7c109-3a1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1b0aed98-785d-4471-ad38-940ca8673030_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,1,flower basket,frames/retrieval/visual_crops/val/1b0aed98-785...
1,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,2,television,frames/retrieval/visual_crops/val/1b0aed98-785...
2,1b0aed98-785d-4471-ad38-940ca8673030,27792a7e-435d-4ecc-a8b6-2a0643d75cce,3,box,frames/retrieval/visual_crops/val/1b0aed98-785...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/38dc82c8-d59a-4ef9-818c-c3affb046e17_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,1,lighter,frames/retrieval/visual_crops/val/38dc82c8-d59...
1,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,2,sellotape,frames/retrieval/visual_crops/val/38dc82c8-d59...
2,38dc82c8-d59a-4ef9-818c-c3affb046e17,bba41501-d898-47fd-905b-9afddedadee2,3,chisel,frames/retrieval/visual_crops/val/38dc82c8-d59...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b0612ea7-11f9-486e-a4aa-e0f8ba67e2df_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,1,drill,frames/retrieval/visual_crops/val/b0612ea7-11f...
1,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,2,hammer,frames/retrieval/visual_crops/val/b0612ea7-11f...
2,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,3,tin,frames/retrieval/visual_crops/val/b0612ea7-11f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fd82660b-9650-4326-93fc-08b1b950ac9d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,1,tin,frames/retrieval/visual_crops/val/fd82660b-965...
1,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,2,box,frames/retrieval/visual_crops/val/fd82660b-965...
2,fd82660b-9650-4326-93fc-08b1b950ac9d,73f5a167-05a2-4d72-a08a-20a132456b55,3,spade,frames/retrieval/visual_crops/val/fd82660b-965...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/daee0288-b01a-4fc4-bcd8-3884846d829d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,2,paint bucket,frames/retrieval/visual_crops/val/daee0288-b01...
1,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,1,scissors,frames/retrieval/visual_crops/val/daee0288-b01...
2,daee0288-b01a-4fc4-bcd8-3884846d829d,e85389e5-0251-4228-9869-0345050cb6ef,3,plier,frames/retrieval/visual_crops/val/daee0288-b01...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72eee417-f3cb-47dc-8266-24277c2307e2_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,1,bottle,frames/retrieval/visual_crops/val/72eee417-f3c...
1,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,2,vase,frames/retrieval/visual_crops/val/72eee417-f3c...
2,72eee417-f3cb-47dc-8266-24277c2307e2,00c70204-6e59-4a45-a5b3-71446068fa07,3,package,frames/retrieval/visual_crops/val/72eee417-f3c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/39b791e1-7e1c-4c3e-bd68-e6598ef8694b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,1,fire hydrant,frames/retrieval/visual_crops/val/39b791e1-7e1...
1,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,2,freshener,frames/retrieval/visual_crops/val/39b791e1-7e1...
2,39b791e1-7e1c-4c3e-bd68-e6598ef8694b,e4423bee-a5d4-4c4f-88a3-eafcd77e0991,3,television,frames/retrieval/visual_crops/val/39b791e1-7e1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/260ec80b-f26a-4646-afc5-616481889643_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,1,bag,frames/retrieval/visual_crops/val/260ec80b-f26...
1,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,2,spectacles,frames/retrieval/visual_crops/val/260ec80b-f26...
2,260ec80b-f26a-4646-afc5-616481889643,a225ac61-b139-4c39-8011-342a3285ba89,3,hanger,frames/retrieval/visual_crops/val/260ec80b-f26...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/95685c3a-9604-4fa3-a6e0-3d27a67fb3ad_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,2,earthgro,frames/retrieval/visual_crops/val/95685c3a-960...
1,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,1,cloth,frames/retrieval/visual_crops/val/95685c3a-960...
2,95685c3a-9604-4fa3-a6e0-3d27a67fb3ad,7af228b0-e237-4f85-8619-f951781d859e,3,bottle,frames/retrieval/visual_crops/val/95685c3a-960...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,2,cloth,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...
1,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,1,laundry bag,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...
2,7f9dc6bd-dd7c-4528-90b9-0a9aeeda39de,bf3b0098-0fa2-4a3d-bac6-b30cbbd96350,3,luggage,frames/retrieval/visual_crops/val/7f9dc6bd-dd7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0c2cc98f-0b4f-4820-8687-e12483cf4d0a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,2,broom,frames/retrieval/visual_crops/val/0c2cc98f-0b4...
1,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,1,table lamp,frames/retrieval/visual_crops/val/0c2cc98f-0b4...
2,0c2cc98f-0b4f-4820-8687-e12483cf4d0a,dff99469-2776-46b2-8c41-5c042dbca1d7,3,side table,frames/retrieval/visual_crops/val/0c2cc98f-0b4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5333a996-877f-4e30-ba79-631131744a4b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,1,spray bottle,frames/retrieval/visual_crops/val/5333a996-877...
1,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,2,sink,frames/retrieval/visual_crops/val/5333a996-877...
2,5333a996-877f-4e30-ba79-631131744a4b,260398b7-7e1b-4067-ab62-4dbf8b8d7bec,3,jacuzzi,frames/retrieval/visual_crops/val/5333a996-877...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/db6e91d9-3006-46dd-af29-b74f725fe284_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,1,knife,frames/retrieval/visual_crops/val/db6e91d9-300...
1,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,3,rack,frames/retrieval/visual_crops/val/db6e91d9-300...
2,db6e91d9-3006-46dd-af29-b74f725fe284,38f0c7f6-ae26-4bed-acff-a74efe8ebbca,2,shoe,frames/retrieval/visual_crops/val/db6e91d9-300...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a051a8ce-cb33-40f8-a46e-1a3a263de18f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,2,dogs reflector,frames/retrieval/visual_crops/val/a051a8ce-cb3...
1,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,1,ball,frames/retrieval/visual_crops/val/a051a8ce-cb3...
2,a051a8ce-cb33-40f8-a46e-1a3a263de18f,1b067ad1-ff8e-4699-b69f-dfc9ac291a5e,3,picnic table,frames/retrieval/visual_crops/val/a051a8ce-cb3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f8bdd228-ef92-43e3-bf6f-086ff54d5c78_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,1,game pad,frames/retrieval/visual_crops/val/f8bdd228-ef9...
1,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,2,remote,frames/retrieval/visual_crops/val/f8bdd228-ef9...
2,f8bdd228-ef92-43e3-bf6f-086ff54d5c78,d3965123-e3e3-4598-829c-6d8b846395bd,3,vase,frames/retrieval/visual_crops/val/f8bdd228-ef9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e0fdd4e0-cccf-423c-9629-9b234e4a458f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,1,tissue roll,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...
1,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,2,spray bottle,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...
2,e0fdd4e0-cccf-423c-9629-9b234e4a458f,927271de-3f8d-48aa-a4b9-502e046a7984,3,litter bin,frames/retrieval/visual_crops/val/e0fdd4e0-ccc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d111f736-d02a-43f4-8968-2b6631138d84_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,3,rim,frames/retrieval/visual_crops/val/d111f736-d02...
1,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,1,rolling creeper,frames/retrieval/visual_crops/val/d111f736-d02...
2,d111f736-d02a-43f4-8968-2b6631138d84,54c51be6-0ae8-4ed6-8ffc-d25d94f6c67f,2,motor oil bottle,frames/retrieval/visual_crops/val/d111f736-d02...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/21af903a-6c19-4854-afe0-009d81849867_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,3,tissue paper,frames/retrieval/visual_crops/val/21af903a-6c1...
1,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,1,bottle,frames/retrieval/visual_crops/val/21af903a-6c1...
2,21af903a-6c19-4854-afe0-009d81849867,1e709696-895f-41c6-bece-2801fd20b824,2,bowl,frames/retrieval/visual_crops/val/21af903a-6c1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8f1770e5-612c-4047-a7b7-a6157460bc24_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,1,television,frames/retrieval/visual_crops/val/8f1770e5-612...
1,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,2,cup,frames/retrieval/visual_crops/val/8f1770e5-612...
2,8f1770e5-612c-4047-a7b7-a6157460bc24,35a52d36-a337-4152-bdee-8c1498676bb6,3,trash can,frames/retrieval/visual_crops/val/8f1770e5-612...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9671fc0-7e56-4e98-842a-dfbbd99d385f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,1,cup,frames/retrieval/visual_crops/val/f9671fc0-7e5...
1,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,2,jenga block,frames/retrieval/visual_crops/val/f9671fc0-7e5...
2,f9671fc0-7e56-4e98-842a-dfbbd99d385f,0bdac31d-a685-447d-9400-8805a08ff338,3,play station pad,frames/retrieval/visual_crops/val/f9671fc0-7e5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c552b2d7-9d27-4765-9dce-8223581c1ca7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,1,training ball,frames/retrieval/visual_crops/val/c552b2d7-9d2...
1,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,3,mat,frames/retrieval/visual_crops/val/c552b2d7-9d2...
2,c552b2d7-9d27-4765-9dce-8223581c1ca7,79a3f459-328a-44a6-ba8c-ab29314ae15f,2,television,frames/retrieval/visual_crops/val/c552b2d7-9d2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d149e4b3-a919-4deb-a088-4fe245896ef2_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,1,watering can,frames/retrieval/visual_crops/val/d149e4b3-a91...
1,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,2,garden broom,frames/retrieval/visual_crops/val/d149e4b3-a91...
2,d149e4b3-a919-4deb-a088-4fe245896ef2,c07c0f49-8faf-4ea4-a0b1-3ae09b56aae4,3,firewood,frames/retrieval/visual_crops/val/d149e4b3-a91...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/17043256-42c5-4e4f-846b-7923afe3ead4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,1,vase,frames/retrieval/visual_crops/val/17043256-42c...
1,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,2,game controller,frames/retrieval/visual_crops/val/17043256-42c...
2,17043256-42c5-4e4f-846b-7923afe3ead4,529df992-51be-4f5c-a6ac-c79eed7217bd,3,laundry basket,frames/retrieval/visual_crops/val/17043256-42c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5aa0d7aa-21af-4bfc-a204-f05554a3933e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,1,cutter,frames/retrieval/visual_crops/val/5aa0d7aa-21a...
1,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,2,dustbin,frames/retrieval/visual_crops/val/5aa0d7aa-21a...
2,5aa0d7aa-21af-4bfc-a204-f05554a3933e,e543d7f0-e18e-4ce1-9762-a641442fbb16,3,bucket,frames/retrieval/visual_crops/val/5aa0d7aa-21a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,1,tennis ball,frames/retrieval/visual_crops/val/dab3cd5d-ad3...
1,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,2,bottle,frames/retrieval/visual_crops/val/dab3cd5d-ad3...
2,dab3cd5d-ad3a-4d7b-8a01-8b3fb0dfad04,fc831aa3-1fdc-4e65-8784-27d5a4741d99,3,dustbin,frames/retrieval/visual_crops/val/dab3cd5d-ad3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1e666456-2299-47ff-af7c-8bda73f825ea_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,1,plate,frames/retrieval/visual_crops/val/1e666456-229...
1,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,3,packet of chips,frames/retrieval/visual_crops/val/1e666456-229...
2,1e666456-2299-47ff-af7c-8bda73f825ea,11853438-f8f7-46c9-991b-b620375b07c3,2,polythene bag,frames/retrieval/visual_crops/val/1e666456-229...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/20a6cd02-f686-46c3-b1e3-f3376a99ddc6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,3,box of ties,frames/retrieval/visual_crops/val/20a6cd02-f68...
1,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,2,shoes,frames/retrieval/visual_crops/val/20a6cd02-f68...
2,20a6cd02-f686-46c3-b1e3-f3376a99ddc6,e3608d77-b8f6-43f5-b5c5-229db1a6a9fd,1,neck scarf,frames/retrieval/visual_crops/val/20a6cd02-f68...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/368755d7-886a-4b05-85f4-e3b3785a8d14_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,1,blower,frames/retrieval/visual_crops/val/368755d7-886...
1,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,2,tool box,frames/retrieval/visual_crops/val/368755d7-886...
2,368755d7-886a-4b05-85f4-e3b3785a8d14,80a75dc2-7704-41c8-a431-5390098f47d9,3,tape measure,frames/retrieval/visual_crops/val/368755d7-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6c88216a-cf77-48f2-9dc4-ccb4cc5160f5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,1,drill,frames/retrieval/visual_crops/val/6c88216a-cf7...
1,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,2,tire,frames/retrieval/visual_crops/val/6c88216a-cf7...
2,6c88216a-cf77-48f2-9dc4-ccb4cc5160f5,fdb5c4b9-e3ab-4ee2-9b8d-18940706ecee,3,wheel,frames/retrieval/visual_crops/val/6c88216a-cf7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/4a491385-b165-49ec-a23b-7b0ed26737f9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,1,bowl,frames/retrieval/visual_crops/val/4a491385-b16...
1,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,2,rice cooker,frames/retrieval/visual_crops/val/4a491385-b16...
2,4a491385-b165-49ec-a23b-7b0ed26737f9,a41b71f6-8aa7-45c9-9148-a5780da79c30,3,kettle,frames/retrieval/visual_crops/val/4a491385-b16...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f0a86b75-fd8e-43dd-95ee-401717b94f70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,1,book,frames/retrieval/visual_crops/val/f0a86b75-fd8...
1,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,2,mobile phone,frames/retrieval/visual_crops/val/f0a86b75-fd8...
2,f0a86b75-fd8e-43dd-95ee-401717b94f70,d2a69805-a611-4c46-ab3a-8081212d765d,3,scissors,frames/retrieval/visual_crops/val/f0a86b75-fd8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/afc253af-734c-4e67-b4c2-09384fcd1e93_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,2,metal bowl,frames/retrieval/visual_crops/val/afc253af-734...
1,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,1,liquid soap,frames/retrieval/visual_crops/val/afc253af-734...
2,afc253af-734c-4e67-b4c2-09384fcd1e93,269a4b2c-903f-48ec-b29d-83c6e244a6f8,3,kitchen mat,frames/retrieval/visual_crops/val/afc253af-734...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3e95b70a-e2b1-4d6f-a229-b07d4f8eadea_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,1,dough cutter,frames/retrieval/visual_crops/val/3e95b70a-e2b...
1,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,2,scrubber,frames/retrieval/visual_crops/val/3e95b70a-e2b...
2,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,3,weighing scale,frames/retrieval/visual_crops/val/3e95b70a-e2b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/afc5b8d0-3146-48f2-be24-c1490cfa766f_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,1,paint bucket,frames/retrieval/visual_crops/val/afc5b8d0-314...
1,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,2,slippers,frames/retrieval/visual_crops/val/afc5b8d0-314...
2,afc5b8d0-3146-48f2-be24-c1490cfa766f,eaf3d080-87cf-4dd6-badd-4c39c63fca01,3,plastic jar,frames/retrieval/visual_crops/val/afc5b8d0-314...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d87774db-a324-4440-aa60-b39fe3276b77_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,1,book,frames/retrieval/visual_crops/val/d87774db-a32...
1,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,2,glove,frames/retrieval/visual_crops/val/d87774db-a32...
2,d87774db-a324-4440-aa60-b39fe3276b77,24a9bdb6-2657-4823-aa93-5d39c57aba41,3,stool,frames/retrieval/visual_crops/val/d87774db-a32...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ba50504a-93ad-46bc-8433-0c1f89d21f78_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,1,scraper,frames/retrieval/visual_crops/val/ba50504a-93a...
1,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,2,paint bucket,frames/retrieval/visual_crops/val/ba50504a-93a...
2,ba50504a-93ad-46bc-8433-0c1f89d21f78,1476468e-38d8-4dee-a04a-722c3b0fd314,3,cell phone,frames/retrieval/visual_crops/val/ba50504a-93a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b370b4cc-0a46-43a8-9b26-1aba0f71ee09_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,1,can,frames/retrieval/visual_crops/val/b370b4cc-0a4...
1,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,2,dustbin,frames/retrieval/visual_crops/val/b370b4cc-0a4...
2,b370b4cc-0a46-43a8-9b26-1aba0f71ee09,0341f427-0c4f-4436-9ce8-5d9963ef8d1d,3,pan,frames/retrieval/visual_crops/val/b370b4cc-0a4...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/150bc185-821c-487f-b39c-4c5a0d52467d_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,1,dustbin,frames/retrieval/visual_crops/val/150bc185-821...
1,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,3,puller slide hammer,frames/retrieval/visual_crops/val/150bc185-821...
2,150bc185-821c-487f-b39c-4c5a0d52467d,130155e4-74fd-460b-a473-112039acc09d,2,fire extinguisher,frames/retrieval/visual_crops/val/150bc185-821...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3e654a1a-b706-456d-ab6d-565effcf159c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,1,trash can,frames/retrieval/visual_crops/val/3e654a1a-b70...
1,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,2,trash can,frames/retrieval/visual_crops/val/3e654a1a-b70...
2,3e654a1a-b706-456d-ab6d-565effcf159c,dd68f2a3-cea5-424b-b2f6-3a84e720b234,3,desk,frames/retrieval/visual_crops/val/3e654a1a-b70...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,1,bin,frames/retrieval/visual_crops/val/b0ef48a2-dc6...
1,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,2,sanitizer,frames/retrieval/visual_crops/val/b0ef48a2-dc6...
2,b0ef48a2-dc6c-41a8-9d46-e1b95b648e2e,a6ece7cd-f616-4853-bcad-4c5a9ff466bd,3,basket,frames/retrieval/visual_crops/val/b0ef48a2-dc6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b47da6e2-cb60-4fd4-9705-5eb3af05877d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,1,flower basket,frames/retrieval/visual_crops/val/b47da6e2-cb6...
1,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,3,can,frames/retrieval/visual_crops/val/b47da6e2-cb6...
2,b47da6e2-cb60-4fd4-9705-5eb3af05877d,d9d10807-7e57-41e7-b1d0-a974f3810c34,2,table lamp,frames/retrieval/visual_crops/val/b47da6e2-cb6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f835883d-2ef1-427d-9c2f-5d9e7670cf5e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,2,power bank,frames/retrieval/visual_crops/val/f835883d-2ef...
1,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,1,novel,frames/retrieval/visual_crops/val/f835883d-2ef...
2,f835883d-2ef1-427d-9c2f-5d9e7670cf5e,379cb960-00e4-4140-b256-4018f39a81f0,3,cap,frames/retrieval/visual_crops/val/f835883d-2ef...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6dd3486b-59dd-4dc6-874a-e4d773273c8a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,1,bottle,frames/retrieval/visual_crops/val/6dd3486b-59d...
1,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,2,speed square,frames/retrieval/visual_crops/val/6dd3486b-59d...
2,6dd3486b-59dd-4dc6-874a-e4d773273c8a,10acd90b-5d08-4420-a51a-f9fc5b8eef3f,3,marker pen,frames/retrieval/visual_crops/val/6dd3486b-59d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0080281f-4db1-4a49-9753-e70c41bd9bc7_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,1,measuring tape,frames/retrieval/visual_crops/val/0080281f-4db...
1,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,3,bottle,frames/retrieval/visual_crops/val/0080281f-4db...
2,0080281f-4db1-4a49-9753-e70c41bd9bc7,474b3a9c-14cc-4f46-95e2-e8c8c0ebd89e,2,brush,frames/retrieval/visual_crops/val/0080281f-4db...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/36335d72-a5d7-4878-9f5b-9ff9635815b8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,1,painting brush,frames/retrieval/visual_crops/val/36335d72-a5d...
1,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,2,thread,frames/retrieval/visual_crops/val/36335d72-a5d...
2,36335d72-a5d7-4878-9f5b-9ff9635815b8,ec40003b-4d96-4f59-b963-a591f19fc125,3,needle,frames/retrieval/visual_crops/val/36335d72-a5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/73382127-39b0-4033-af91-4e310670a349_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,1,spraying bottle,frames/retrieval/visual_crops/val/73382127-39b...
1,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,2,piece of material,frames/retrieval/visual_crops/val/73382127-39b...
2,73382127-39b0-4033-af91-4e310670a349,9ced13e1-95b1-45a0-b550-c91ddb9b8afc,3,touch,frames/retrieval/visual_crops/val/73382127-39b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b8981cdd-a897-41b6-b1ef-e9957d270e9e_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,1,laptop,frames/retrieval/visual_crops/val/b8981cdd-a89...
1,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,2,microwave,frames/retrieval/visual_crops/val/b8981cdd-a89...
2,b8981cdd-a897-41b6-b1ef-e9957d270e9e,62cc9773-f79b-4fd7-9623-742e83dc4eef,3,water can,frames/retrieval/visual_crops/val/b8981cdd-a89...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72479834-1994-44a8-a9a5-ae13b3417307_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,2,spraying bottle,frames/retrieval/visual_crops/val/72479834-199...
1,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,3,screw driver,frames/retrieval/visual_crops/val/72479834-199...
2,72479834-1994-44a8-a9a5-ae13b3417307,424bc81b-9603-4b28-9b09-de0b9e2c2179,1,telephone,frames/retrieval/visual_crops/val/72479834-199...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/94106c40-8e3a-4018-a3fc-a86106979766_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,1,bicycle,frames/retrieval/visual_crops/val/94106c40-8e3...
1,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,2,bottle,frames/retrieval/visual_crops/val/94106c40-8e3...
2,94106c40-8e3a-4018-a3fc-a86106979766,3e3e6d8a-9640-4a4d-a4c8-2bebac444055,3,vase,frames/retrieval/visual_crops/val/94106c40-8e3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72154f42-399c-4f95-a667-e26528d1f52a_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,1,weighing scale,frames/retrieval/visual_crops/val/72154f42-399...
1,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,2,brown scraper,frames/retrieval/visual_crops/val/72154f42-399...
2,72154f42-399c-4f95-a667-e26528d1f52a,e1dda302-52bc-4f50-a27d-e3ef4455a61d,3,brown gloves,frames/retrieval/visual_crops/val/72154f42-399...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e355d07d-844b-44ff-bfab-c1fb98d48b6c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,1,basket,frames/retrieval/visual_crops/val/e355d07d-844...
1,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,2,splier,frames/retrieval/visual_crops/val/e355d07d-844...
2,e355d07d-844b-44ff-bfab-c1fb98d48b6c,5bf7eae5-d58d-4792-b5c9-e5db93b08bf3,3,bag,frames/retrieval/visual_crops/val/e355d07d-844...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,2,sellotape,frames/retrieval/visual_crops/val/a3d47c6b-f0e...
1,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,3,sandal,frames/retrieval/visual_crops/val/a3d47c6b-f0e...
2,a3d47c6b-f0e3-410c-8cc1-cebcdf067ea6,8e44d0a3-baf1-4730-a3cd-ff045ef11edb,1,bucket,frames/retrieval/visual_crops/val/a3d47c6b-f0e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8d22e91b-ed98-4c87-8a25-c937236ca745_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,1,box,frames/retrieval/visual_crops/val/8d22e91b-ed9...
1,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,2,lawn mower,frames/retrieval/visual_crops/val/8d22e91b-ed9...
2,8d22e91b-ed98-4c87-8a25-c937236ca745,eb55595a-4e58-4d28-a51b-1e6595b4615f,3,bucket,frames/retrieval/visual_crops/val/8d22e91b-ed9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f4240b1c-c260-4354-a005-cfa8c8353f90_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,1,cable,frames/retrieval/visual_crops/val/f4240b1c-c26...
1,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,2,battery jump starter,frames/retrieval/visual_crops/val/f4240b1c-c26...
2,f4240b1c-c260-4354-a005-cfa8c8353f90,580974dc-e729-48ab-a0a0-e13c21dd3e7f,3,rachet,frames/retrieval/visual_crops/val/f4240b1c-c26...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/43f1faaa-6452-4125-a702-f319fdafcc4f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,1,scissors,frames/retrieval/visual_crops/val/43f1faaa-645...
1,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,2,paper,frames/retrieval/visual_crops/val/43f1faaa-645...
2,43f1faaa-6452-4125-a702-f319fdafcc4f,dc46dc0f-f7d3-4fce-89b9-ff3c66c74c75,3,string,frames/retrieval/visual_crops/val/43f1faaa-645...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/83e54fdc-6336-439c-b8a5-44682989a329_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,1,hammer,frames/retrieval/visual_crops/val/83e54fdc-633...
1,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,2,dust pan,frames/retrieval/visual_crops/val/83e54fdc-633...
2,83e54fdc-6336-439c-b8a5-44682989a329,2cb6c8e9-4440-468c-bc3f-fdd13466277a,3,bucket,frames/retrieval/visual_crops/val/83e54fdc-633...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b8ddc75-2c96-4f73-8278-ff7f60920426_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,1,fire extinguisher,frames/retrieval/visual_crops/val/2b8ddc75-2c9...
1,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,3,pen,frames/retrieval/visual_crops/val/2b8ddc75-2c9...
2,2b8ddc75-2c96-4f73-8278-ff7f60920426,5e34b363-fc30-48fd-8b62-0762acfba900,2,plastic,frames/retrieval/visual_crops/val/2b8ddc75-2c9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2b3864c6-50d7-46ff-9ab6-3d6831f741cc_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,1,stainless steel basin,frames/retrieval/visual_crops/val/2b3864c6-50d...
1,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,2,rolling board,frames/retrieval/visual_crops/val/2b3864c6-50d...
2,2b3864c6-50d7-46ff-9ab6-3d6831f741cc,35366a51-803e-4a1c-8f99-ee4c110e450d,3,pan,frames/retrieval/visual_crops/val/2b3864c6-50d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/145b7d46-a4f7-472e-8adf-08be3ed4062c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,1,cup,frames/retrieval/visual_crops/val/145b7d46-a4f...
1,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,2,phone,frames/retrieval/visual_crops/val/145b7d46-a4f...
2,145b7d46-a4f7-472e-8adf-08be3ed4062c,899c2be2-674e-4638-a108-2995732fee7a,3,cell tape,frames/retrieval/visual_crops/val/145b7d46-a4f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8059dcc2-0f52-46f8-a119-85c78d608602_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,1,knife,frames/retrieval/visual_crops/val/8059dcc2-0f5...
1,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,2,tray,frames/retrieval/visual_crops/val/8059dcc2-0f5...
2,8059dcc2-0f52-46f8-a119-85c78d608602,655c74a3-fafc-4c0e-8a13-fd4999abf837,3,dough,frames/retrieval/visual_crops/val/8059dcc2-0f5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2d76f374-48e5-4cef-8b6b-bc6f0c038d48_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,1,mesh strainer bowl,frames/retrieval/visual_crops/val/2d76f374-48e...
1,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,2,spatula,frames/retrieval/visual_crops/val/2d76f374-48e...
2,2d76f374-48e5-4cef-8b6b-bc6f0c038d48,35841cc2-44b5-4521-ac7b-c88189c64457,3,pan,frames/retrieval/visual_crops/val/2d76f374-48e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f04d9e03-3189-4ffb-a79a-2521355905bb_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,2,bottle,frames/retrieval/visual_crops/val/f04d9e03-318...
1,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,1,cooking pot,frames/retrieval/visual_crops/val/f04d9e03-318...
2,f04d9e03-3189-4ffb-a79a-2521355905bb,7ac3428d-3b7a-4e7c-b900-83edf1936a34,3,phone,frames/retrieval/visual_crops/val/f04d9e03-318...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/70bce3b1-ffdf-412d-8b28-2c5a4978015f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,3,vacuum cleaner,frames/retrieval/visual_crops/val/70bce3b1-ffd...
1,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,1,adhesive gun,frames/retrieval/visual_crops/val/70bce3b1-ffd...
2,70bce3b1-ffdf-412d-8b28-2c5a4978015f,390f2775-9770-4a4b-8367-577dbb774f69,2,bucket,frames/retrieval/visual_crops/val/70bce3b1-ffd...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8ae90b75-6ccf-417e-8c19-a63bf86a678d_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,1,shoe rack,frames/retrieval/visual_crops/val/8ae90b75-6cc...
1,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,3,hat,frames/retrieval/visual_crops/val/8ae90b75-6cc...
2,8ae90b75-6ccf-417e-8c19-a63bf86a678d,7a8ca507-b307-4884-870e-5ffd34bb5d29,2,t-shirt,frames/retrieval/visual_crops/val/8ae90b75-6cc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5e66abe8-a72b-43f3-b6bf-fc05a45ff80f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,1,bowl,frames/retrieval/visual_crops/val/5e66abe8-a72...
1,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,2,sack,frames/retrieval/visual_crops/val/5e66abe8-a72...
2,5e66abe8-a72b-43f3-b6bf-fc05a45ff80f,5cb78135-8817-4326-b8ef-84465b875062,3,bottle,frames/retrieval/visual_crops/val/5e66abe8-a72...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b8e1c869-b304-49fc-ba5f-9a5ae3b3770c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,1,rice maker,frames/retrieval/visual_crops/val/b8e1c869-b30...
1,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,3,plastic tin,frames/retrieval/visual_crops/val/b8e1c869-b30...
2,b8e1c869-b304-49fc-ba5f-9a5ae3b3770c,8fbabbe4-81f8-4336-aecd-59325392658b,2,tray,frames/retrieval/visual_crops/val/b8e1c869-b30...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/993b95b0-3ab2-4b31-a250-e6221a7d2864_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,2,cat house,frames/retrieval/visual_crops/val/993b95b0-3ab...
1,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,1,remote,frames/retrieval/visual_crops/val/993b95b0-3ab...
2,993b95b0-3ab2-4b31-a250-e6221a7d2864,152683e2-11c3-4181-8945-74f8788ed126,3,throw pillow,frames/retrieval/visual_crops/val/993b95b0-3ab...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dbd760b1-f99a-4a74-9f67-50579e516532_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,2,ball,frames/retrieval/visual_crops/val/dbd760b1-f99...
1,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,1,flowerpot,frames/retrieval/visual_crops/val/dbd760b1-f99...
2,dbd760b1-f99a-4a74-9f67-50579e516532,a5ab7a5a-170c-4d67-b940-23f56e73c4cc,3,box,frames/retrieval/visual_crops/val/dbd760b1-f99...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6ec2a3e6-f9cf-459b-815a-e8853ea7309c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,1,yellow cloth,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...
1,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,2,blue dress,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...
2,6ec2a3e6-f9cf-459b-815a-e8853ea7309c,5366c573-44f1-42ec-a1eb-15cafa93a447,3,iron box,frames/retrieval/visual_crops/val/6ec2a3e6-f9c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/edfa156e-8e82-43cf-8a40-4f9be8f7c2e8_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,1,jerrycan,frames/retrieval/visual_crops/val/edfa156e-8e8...
1,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,2,phone,frames/retrieval/visual_crops/val/edfa156e-8e8...
2,edfa156e-8e82-43cf-8a40-4f9be8f7c2e8,2c85fbd4-9516-41ee-9310-d0d95c8e489c,3,jack,frames/retrieval/visual_crops/val/edfa156e-8e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7dbdb00c-7652-487f-be2e-26a14c3f2145_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,1,wallet,frames/retrieval/visual_crops/val/7dbdb00c-765...
1,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,3,hand cutter,frames/retrieval/visual_crops/val/7dbdb00c-765...
2,7dbdb00c-7652-487f-be2e-26a14c3f2145,249f1f94-2b52-4e71-840a-73f54a5b6e0d,2,flask,frames/retrieval/visual_crops/val/7dbdb00c-765...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/72e90719-c2b8-4b17-b120-e904dbbf1184_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,1,tray,frames/retrieval/visual_crops/val/72e90719-c2b...
1,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,3,plastic water jar,frames/retrieval/visual_crops/val/72e90719-c2b...
2,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,2,pressure cooker,frames/retrieval/visual_crops/val/72e90719-c2b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/eaa07b51-b07d-4cf7-91e7-314a74c8edc6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,1,remote control,frames/retrieval/visual_crops/val/eaa07b51-b07...
1,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,2,pair of scissors,frames/retrieval/visual_crops/val/eaa07b51-b07...
2,eaa07b51-b07d-4cf7-91e7-314a74c8edc6,b72c7a43-5ba2-4ca8-9e28-34422bc7afda,3,television,frames/retrieval/visual_crops/val/eaa07b51-b07...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c0d616c8-fc59-40b7-aafe-f54c2d60a236_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,1,tray,frames/retrieval/visual_crops/val/c0d616c8-fc5...
1,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,2,jug,frames/retrieval/visual_crops/val/c0d616c8-fc5...
2,c0d616c8-fc59-40b7-aafe-f54c2d60a236,e7ae704b-1b0e-421c-bb2f-d6531d5370c8,3,plastic container,frames/retrieval/visual_crops/val/c0d616c8-fc5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,2,wall art,frames/retrieval/visual_crops/val/cbd49e40-6bb...
1,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,1,dough,frames/retrieval/visual_crops/val/cbd49e40-6bb...
2,cbd49e40-6bbb-4083-b0e2-b6f37d92ad1c,c2ee0608-571e-4625-8db9-68838bbf3fdc,3,container==,frames/retrieval/visual_crops/val/cbd49e40-6bb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c8070026-c3dc-43d3-8d36-65c5d9a1317f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,1,gloves,frames/retrieval/visual_crops/val/c8070026-c3d...
1,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,2,golf stick,frames/retrieval/visual_crops/val/c8070026-c3d...
2,c8070026-c3dc-43d3-8d36-65c5d9a1317f,ed90f8ef-cd2a-4d95-bd55-7c1f75e0cc28,3,golf ball,frames/retrieval/visual_crops/val/c8070026-c3d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/14ea5c3e-bbb5-44cf-abcc-e70e1223ad74_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,1,basket,frames/retrieval/visual_crops/val/14ea5c3e-bbb...
1,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,2,bag,frames/retrieval/visual_crops/val/14ea5c3e-bbb...
2,14ea5c3e-bbb5-44cf-abcc-e70e1223ad74,afa2dc61-61e6-48da-b013-7d48a3092b67,3,bucket,frames/retrieval/visual_crops/val/14ea5c3e-bbb...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5a7efdba-6701-4aaa-bff6-fbab6b293ed9_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,3,cup,frames/retrieval/visual_crops/val/5a7efdba-670...
1,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,1,paper tape,frames/retrieval/visual_crops/val/5a7efdba-670...
2,5a7efdba-6701-4aaa-bff6-fbab6b293ed9,9b2c9c46-8fe5-4681-8018-55a9cd1fe7bb,2,phone,frames/retrieval/visual_crops/val/5a7efdba-670...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3c5b4041-8d0d-40ac-8750-1a7e744a38e5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,1,wood,frames/retrieval/visual_crops/val/3c5b4041-8d0...
1,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,2,deep frying pot,frames/retrieval/visual_crops/val/3c5b4041-8d0...
2,3c5b4041-8d0d-40ac-8750-1a7e744a38e5,67951326-f093-4b5f-b84f-da3a137cb28f,3,water bucket,frames/retrieval/visual_crops/val/3c5b4041-8d0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cc7d11f0-445e-426a-904e-e7faafdb07f7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,3,kurta tunic,frames/retrieval/visual_crops/val/cc7d11f0-445...
1,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,1,iron box,frames/retrieval/visual_crops/val/cc7d11f0-445...
2,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,2,cloth,frames/retrieval/visual_crops/val/cc7d11f0-445...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/785960e0-5f8e-41eb-9290-27a755dad3ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,1,television,frames/retrieval/visual_crops/val/785960e0-5f8...
1,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,3,phone,frames/retrieval/visual_crops/val/785960e0-5f8...
2,785960e0-5f8e-41eb-9290-27a755dad3ef,b74dc3ef-1f80-4a46-97a8-b63f73f3b079,2,cup,frames/retrieval/visual_crops/val/785960e0-5f8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1d2b62ed-fc94-4fb0-b547-8c50533b0b29_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,1,bucket,frames/retrieval/visual_crops/val/1d2b62ed-fc9...
1,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,2,sack,frames/retrieval/visual_crops/val/1d2b62ed-fc9...
2,1d2b62ed-fc94-4fb0-b547-8c50533b0b29,0a49f43d-3a72-4138-bfe2-2838ad09d3b9,3,bowl,frames/retrieval/visual_crops/val/1d2b62ed-fc9...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c77d3785-22f9-46c9-bf6d-9f7196356749_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,3,tv decoder,frames/retrieval/visual_crops/val/c77d3785-22f...
1,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,2,gamepad,frames/retrieval/visual_crops/val/c77d3785-22f...
2,c77d3785-22f9-46c9-bf6d-9f7196356749,ec969346-07e8-4bb8-b7a5-5abb7807989e,1,dog bed,frames/retrieval/visual_crops/val/c77d3785-22f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/a4130ad1-bdcd-4de0-aa5e-09865e515ff3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,2,broom,frames/retrieval/visual_crops/val/a4130ad1-bdc...
1,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,1,bucket,frames/retrieval/visual_crops/val/a4130ad1-bdc...
2,a4130ad1-bdcd-4de0-aa5e-09865e515ff3,811f6364-99e4-4325-958d-4c48608e8d90,3,phone,frames/retrieval/visual_crops/val/a4130ad1-bdc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/2c9b9f23-8907-44a0-89e6-8f29d7b05828_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,1,can container,frames/retrieval/visual_crops/val/2c9b9f23-890...
1,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,2,bottle water,frames/retrieval/visual_crops/val/2c9b9f23-890...
2,2c9b9f23-8907-44a0-89e6-8f29d7b05828,95061ac5-5751-4efe-8aec-fb6453b437c2,3,paint brush,frames/retrieval/visual_crops/val/2c9b9f23-890...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7bb41f34-1743-42ad-97d1-c54f4472b85e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,1,carton box,frames/retrieval/visual_crops/val/7bb41f34-174...
1,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,2,bottle spray,frames/retrieval/visual_crops/val/7bb41f34-174...
2,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,3,bulb box,frames/retrieval/visual_crops/val/7bb41f34-174...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f1350714-1aa5-421b-a268-690110ca9c06_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,1,wheels,frames/retrieval/visual_crops/val/f1350714-1aa...
1,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,2,power drill,frames/retrieval/visual_crops/val/f1350714-1aa...
2,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,3,brake shoe,frames/retrieval/visual_crops/val/f1350714-1aa...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ec67faf9-2d1b-41a9-ad96-da31887ba60c_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,2,playstation pad,frames/retrieval/visual_crops/val/ec67faf9-2d1...
1,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,1,remote control,frames/retrieval/visual_crops/val/ec67faf9-2d1...
2,ec67faf9-2d1b-41a9-ad96-da31887ba60c,01bdad2a-af72-4855-b004-9b5d1b4c6cbd,3,mug,frames/retrieval/visual_crops/val/ec67faf9-2d1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7816c769-612c-4256-9bac-885a57ec513f_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,1,oil bottle,frames/retrieval/visual_crops/val/7816c769-612...
1,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,2,lawn mower,frames/retrieval/visual_crops/val/7816c769-612...
2,7816c769-612c-4256-9bac-885a57ec513f,fea6987e-9547-4414-8a6f-ac2eb2ec8cfe,3,bucket,frames/retrieval/visual_crops/val/7816c769-612...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/3482d793-9492-49fa-b98a-770b116e8767_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,1,pan,frames/retrieval/visual_crops/val/3482d793-949...
1,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,2,tray,frames/retrieval/visual_crops/val/3482d793-949...
2,3482d793-9492-49fa-b98a-770b116e8767,2af8cdb0-9ae0-444b-8de6-7b543b36c33e,3,frying pan,frames/retrieval/visual_crops/val/3482d793-949...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,1,wall picture,frames/retrieval/visual_crops/val/8bf2886e-f2e...
1,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,2,global table ball map,frames/retrieval/visual_crops/val/8bf2886e-f2e...
2,8bf2886e-f2e5-47c3-bbf3-4d60c2e2f189,4d6173cd-0e5d-4535-928c-b5a38e08166d,3,study lamp,frames/retrieval/visual_crops/val/8bf2886e-f2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/7ff93f97-d65f-4195-8f37-e4040acb2d09_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,1,grater,frames/retrieval/visual_crops/val/7ff93f97-d65...
1,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,2,bottle,frames/retrieval/visual_crops/val/7ff93f97-d65...
2,7ff93f97-d65f-4195-8f37-e4040acb2d09,a600650f-5f78-4f50-a871-96efbac5567c,3,bucket,frames/retrieval/visual_crops/val/7ff93f97-d65...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6e945b3a-ee26-4a3c-93f0-f60e2456c44a_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,1,bag,frames/retrieval/visual_crops/val/6e945b3a-ee2...
1,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,2,plastic cylinder,frames/retrieval/visual_crops/val/6e945b3a-ee2...
2,6e945b3a-ee26-4a3c-93f0-f60e2456c44a,609381fb-b9b8-4e4c-9a21-9dfbd17f51af,3,stool,frames/retrieval/visual_crops/val/6e945b3a-ee2...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/430be2d1-eb7f-4418-a3bb-06c0d71307d3_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,2,box,frames/retrieval/visual_crops/val/430be2d1-eb7...
1,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,1,diary,frames/retrieval/visual_crops/val/430be2d1-eb7...
2,430be2d1-eb7f-4418-a3bb-06c0d71307d3,e780c316-6b81-4e8b-a8be-976caa58f369,3,cup,frames/retrieval/visual_crops/val/430be2d1-eb7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/87499bfb-3dcf-46fa-aef3-204fcc0496e0_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,1,yellow bowl,frames/retrieval/visual_crops/val/87499bfb-3dc...
1,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,2,dough cutter,frames/retrieval/visual_crops/val/87499bfb-3dc...
2,87499bfb-3dcf-46fa-aef3-204fcc0496e0,1639bcda-c540-4477-8c6d-1e51373c1c06,3,dough bowl,frames/retrieval/visual_crops/val/87499bfb-3dc...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d3b18a63-002a-4538-adef-21ac1f476704_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,1,wood,frames/retrieval/visual_crops/val/d3b18a63-002...
1,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,2,#unsure,frames/retrieval/visual_crops/val/d3b18a63-002...
2,d3b18a63-002a-4538-adef-21ac1f476704,8244b1e4-08e6-4f06-9e5b-c9070cbd5ebb,3,bottle,frames/retrieval/visual_crops/val/d3b18a63-002...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/cf82756f-8e87-443a-972c-405b25858e78_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,1,bucket,frames/retrieval/visual_crops/val/cf82756f-8e8...
1,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,2,broom,frames/retrieval/visual_crops/val/cf82756f-8e8...
2,cf82756f-8e87-443a-972c-405b25858e78,44bfc1f5-c6e0-4854-a287-e6797d399a5b,3,curtain,frames/retrieval/visual_crops/val/cf82756f-8e8...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/69668105-9984-43d0-8c24-74a4ed2adcf4_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,1,electric kettle,frames/retrieval/visual_crops/val/69668105-998...
1,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,2,jug,frames/retrieval/visual_crops/val/69668105-998...
2,69668105-9984-43d0-8c24-74a4ed2adcf4,85b15db1-1245-47f1-92b8-64b7ade1a319,3,book,frames/retrieval/visual_crops/val/69668105-998...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/e7ec16d2-6649-4942-8da9-83e603e78438_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,2,house,frames/retrieval/visual_crops/val/e7ec16d2-664...
1,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,1,basketball board,frames/retrieval/visual_crops/val/e7ec16d2-664...
2,e7ec16d2-6649-4942-8da9-83e603e78438,a11dbf6e-edd5-46ba-8b0b-7e0c55dc773c,3,pick-up,frames/retrieval/visual_crops/val/e7ec16d2-664...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/898e6cc6-082c-483d-ad84-12ec417ca440_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,1,scraper,frames/retrieval/visual_crops/val/898e6cc6-082...
1,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,2,piece of cloth,frames/retrieval/visual_crops/val/898e6cc6-082...
2,898e6cc6-082c-483d-ad84-12ec417ca440,3c6271c7-51f1-48fa-b127-35c038a1e988,3,bottle,frames/retrieval/visual_crops/val/898e6cc6-082...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dbfb3374-94ef-47cb-b179-99ad19e55ff1_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,1,car jack,frames/retrieval/visual_crops/val/dbfb3374-94e...
1,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,2,terminal,frames/retrieval/visual_crops/val/dbfb3374-94e...
2,dbfb3374-94ef-47cb-b179-99ad19e55ff1,3e7a7c61-75d0-4e49-9ecc-850ef1498049,3,trash can,frames/retrieval/visual_crops/val/dbfb3374-94e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/c2229daf-ec7b-45c5-84e3-bb4f4d145d93_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,1,tin,frames/retrieval/visual_crops/val/c2229daf-ec7...
1,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,2,glove,frames/retrieval/visual_crops/val/c2229daf-ec7...
2,c2229daf-ec7b-45c5-84e3-bb4f4d145d93,3764fc2a-480f-4f97-a7db-6dced7f62b03,3,drill,frames/retrieval/visual_crops/val/c2229daf-ec7...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/49b8d3e9-de69-49cf-819b-5af1fd69b732_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,1,hammer,frames/retrieval/visual_crops/val/49b8d3e9-de6...
1,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,2,toolbox,frames/retrieval/visual_crops/val/49b8d3e9-de6...
2,49b8d3e9-de69-49cf-819b-5af1fd69b732,8d9b5cff-640a-40de-b44b-2de1883a4f6a,3,pliers,frames/retrieval/visual_crops/val/49b8d3e9-de6...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b391003e-a302-43a0-a451-75cc8b4ccede_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,1,sponge,frames/retrieval/visual_crops/val/b391003e-a30...
1,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,2,stainless bowl,frames/retrieval/visual_crops/val/b391003e-a30...
2,b391003e-a302-43a0-a451-75cc8b4ccede,b2ffad3e-5a87-4458-9633-ab8fcfda9599,3,watering can,frames/retrieval/visual_crops/val/b391003e-a30...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/9ca1c968-8346-4fc1-a704-e7dffc79afa7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,1,cup,frames/retrieval/visual_crops/val/9ca1c968-834...
1,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,3,plastic bag,frames/retrieval/visual_crops/val/9ca1c968-834...
2,9ca1c968-8346-4fc1-a704-e7dffc79afa7,6dc38a7c-0caf-4767-b91d-37661dbe78fe,2,kitchen towel,frames/retrieval/visual_crops/val/9ca1c968-834...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/281b9507-4bea-4549-9912-90d6fd257f05_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,3,green serving spoon,frames/retrieval/visual_crops/val/281b9507-4be...
1,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,1,chopping board,frames/retrieval/visual_crops/val/281b9507-4be...
2,281b9507-4bea-4549-9912-90d6fd257f05,cf2d2f56-f6a7-4b8d-ab72-ac869f4079b3,2,cloth,frames/retrieval/visual_crops/val/281b9507-4be...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6c0c2145-2b3d-48cd-a61c-e29d8541218f_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,1,white flipflop,frames/retrieval/visual_crops/val/6c0c2145-2b3...
1,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,2,transparent cup,frames/retrieval/visual_crops/val/6c0c2145-2b3...
2,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,3,chopsticks,frames/retrieval/visual_crops/val/6c0c2145-2b3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fa43490f-22c7-44db-868f-4998791069ac_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,1,tool box,frames/retrieval/visual_crops/val/fa43490f-22c...
1,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,2,jerrycan,frames/retrieval/visual_crops/val/fa43490f-22c...
2,fa43490f-22c7-44db-868f-4998791069ac,d8279762-80e8-4942-9da3-8ba9be86ebf3,3,micropipette,frames/retrieval/visual_crops/val/fa43490f-22c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/629cb4e4-65a5-45f5-909d-2ff93e57a0bf_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,1,cutting pliers,frames/retrieval/visual_crops/val/629cb4e4-65a...
1,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,2,ball pein hammer,frames/retrieval/visual_crops/val/629cb4e4-65a...
2,629cb4e4-65a5-45f5-909d-2ff93e57a0bf,80f404e5-0823-42a1-ac18-cc5de7c226df,3,brake rotor,frames/retrieval/visual_crops/val/629cb4e4-65a...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/0ba8203a-5825-464b-8d95-32a24e84acf0_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,1,paper bag,frames/retrieval/visual_crops/val/0ba8203a-582...
1,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,2,chair,frames/retrieval/visual_crops/val/0ba8203a-582...
2,0ba8203a-5825-464b-8d95-32a24e84acf0,8149f291-2d38-49d7-b3de-e5def287edf6,3,knife,frames/retrieval/visual_crops/val/0ba8203a-582...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/09dde7aa-58bd-402e-a107-32c0f33e7115_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,2,bottle,frames/retrieval/visual_crops/val/09dde7aa-58b...
1,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,1,washing machine,frames/retrieval/visual_crops/val/09dde7aa-58b...
2,09dde7aa-58bd-402e-a107-32c0f33e7115,b605fd8c-14c3-4d16-9503-65c3fe515611,3,pan,frames/retrieval/visual_crops/val/09dde7aa-58b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6f7f5312-db3f-42db-98c0-f650a3899568_query_metadata.parquet
Shape: (2, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6f7f5312-db3f-42db-98c0-f650a3899568,d05881bc-4d63-4dcb-a5ef-08d1db73712f,1,phone,frames/retrieval/visual_crops/val/6f7f5312-db3...
1,6f7f5312-db3f-42db-98c0-f650a3899568,d05881bc-4d63-4dcb-a5ef-08d1db73712f,2,mug,frames/retrieval/visual_crops/val/6f7f5312-db3...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/074ff05f-e0cb-41b7-96fe-25a9a79ce918_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,1,oil drum,frames/retrieval/visual_crops/val/074ff05f-e0c...
1,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,3,oil box,frames/retrieval/visual_crops/val/074ff05f-e0c...
2,074ff05f-e0cb-41b7-96fe-25a9a79ce918,5eb34807-724e-48a1-8c00-40f52dc90687,2,phone,frames/retrieval/visual_crops/val/074ff05f-e0c...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d444eac6-5d1b-4198-97d8-e3ec96dae37e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,1,pair of glasses,frames/retrieval/visual_crops/val/d444eac6-5d1...
1,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,2,bag,frames/retrieval/visual_crops/val/d444eac6-5d1...
2,d444eac6-5d1b-4198-97d8-e3ec96dae37e,377484a3-bff8-4c2b-adea-172e1026378a,3,dog,frames/retrieval/visual_crops/val/d444eac6-5d1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bc01d0dd-be04-474e-9fc6-de83292a5062_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,1,water bottle,frames/retrieval/visual_crops/val/bc01d0dd-be0...
1,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,3,cup,frames/retrieval/visual_crops/val/bc01d0dd-be0...
2,bc01d0dd-be04-474e-9fc6-de83292a5062,44ee16c7-cea5-4609-876d-5a94a8afd04e,2,mobile phone,frames/retrieval/visual_crops/val/bc01d0dd-be0...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f090ba34-9f57-40de-8fce-f2d3503d55ef_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,1,hose pipe,frames/retrieval/visual_crops/val/f090ba34-9f5...
1,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,3,pliers,frames/retrieval/visual_crops/val/f090ba34-9f5...
2,f090ba34-9f57-40de-8fce-f2d3503d55ef,2b0cdb39-ac1b-4df8-a76a-ce0a891b9de9,2,cellphone,frames/retrieval/visual_crops/val/f090ba34-9f5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/81221073-c095-4129-b095-97f3d6e4a6b1_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,2,bangle,frames/retrieval/visual_crops/val/81221073-c09...
1,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,3,wire,frames/retrieval/visual_crops/val/81221073-c09...
2,81221073-c095-4129-b095-97f3d6e4a6b1,49380ef5-7c76-42bf-9c8b-808de81023ad,1,post,frames/retrieval/visual_crops/val/81221073-c09...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f16b6028-4624-4224-a368-a18d59aefe70_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,2,cloth,frames/retrieval/visual_crops/val/f16b6028-462...
1,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,3,carton box,frames/retrieval/visual_crops/val/f16b6028-462...
2,f16b6028-4624-4224-a368-a18d59aefe70,56d560b5-2845-42a7-b760-d823c9195faf,1,bucket,frames/retrieval/visual_crops/val/f16b6028-462...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/5699168a-b5d3-4957-8ec1-87a4377b2e94_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,1,scissors,frames/retrieval/visual_crops/val/5699168a-b5d...
1,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,2,basket,frames/retrieval/visual_crops/val/5699168a-b5d...
2,5699168a-b5d3-4957-8ec1-87a4377b2e94,dcdc735c-9f34-49fc-a349-6660477e1474,3,box pack,frames/retrieval/visual_crops/val/5699168a-b5d...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f0861378-ff5f-47d8-b1b3-59cf5b07acc7_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,1,backpack,frames/retrieval/visual_crops/val/f0861378-ff5...
1,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,2,yellow nylon,frames/retrieval/visual_crops/val/f0861378-ff5...
2,f0861378-ff5f-47d8-b1b3-59cf5b07acc7,02611892-dd8e-4752-bb2c-65c1403dc63f,3,bicycle,frames/retrieval/visual_crops/val/f0861378-ff5...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/50df286e-fe12-434e-95c6-d8160787512b_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,1,sweeping brush,frames/retrieval/visual_crops/val/50df286e-fe1...
1,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,2,baking weighing scale,frames/retrieval/visual_crops/val/50df286e-fe1...
2,50df286e-fe12-434e-95c6-d8160787512b,edcd2a90-5f6a-4ac5-a8df-27bdb02b275c,3,measuring jar,frames/retrieval/visual_crops/val/50df286e-fe1...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/fbf8b92f-8472-4195-8b9c-4c365714ff94_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,1,toilet paper,frames/retrieval/visual_crops/val/fbf8b92f-847...
1,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,2,shopping basket,frames/retrieval/visual_crops/val/fbf8b92f-847...
2,fbf8b92f-8472-4195-8b9c-4c365714ff94,fe20ba58-da62-426c-a362-d8cc49fdcf60,3,disposable cup,frames/retrieval/visual_crops/val/fbf8b92f-847...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/d2e61675-14b6-481f-9206-34bbc1375ea6_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,1,vase,frames/retrieval/visual_crops/val/d2e61675-14b...
1,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,2,tv,frames/retrieval/visual_crops/val/d2e61675-14b...
2,d2e61675-14b6-481f-9206-34bbc1375ea6,7922466c-05f5-41fa-ad44-0d0b29db6233,3,paper towel,frames/retrieval/visual_crops/val/d2e61675-14b...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/b157270d-c67a-41db-91ec-32bb3ec738fc_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,1,dispensing bottle,frames/retrieval/visual_crops/val/b157270d-c67...
1,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,3,adapter,frames/retrieval/visual_crops/val/b157270d-c67...
2,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,2,impact driver,frames/retrieval/visual_crops/val/b157270d-c67...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,1,plastic chair,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...
1,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,2,plastic stool,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...
2,f9c9c2ec-c5fd-46b8-bbb6-49c7dda702af,dd6bc98d-2add-4be1-bbc3-d915cd524db1,3,sack,frames/retrieval/visual_crops/val/f9c9c2ec-c5f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/704943b6-2922-43d7-9b16-81c021b96232_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,2,bulb,frames/retrieval/visual_crops/val/704943b6-292...
1,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,3,chair,frames/retrieval/visual_crops/val/704943b6-292...
2,704943b6-2922-43d7-9b16-81c021b96232,98d1a99d-a880-4c73-a74a-14636f4253ca,1,bottle,frames/retrieval/visual_crops/val/704943b6-292...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6e4a69cf-b603-4797-8d68-11f27919b40c_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,1,pliers,frames/retrieval/visual_crops/val/6e4a69cf-b60...
1,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,3,nut gun,frames/retrieval/visual_crops/val/6e4a69cf-b60...
2,6e4a69cf-b603-4797-8d68-11f27919b40c,e85b5f4e-b791-4dfe-b968-3f8b8325cfe6,2,spanner,frames/retrieval/visual_crops/val/6e4a69cf-b60...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/82abc0e6-c282-4492-89cb-c6005f1cb0f5_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,1,spray tin,frames/retrieval/visual_crops/val/82abc0e6-c28...
1,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,2,cordless drill,frames/retrieval/visual_crops/val/82abc0e6-c28...
2,82abc0e6-c282-4492-89cb-c6005f1cb0f5,0c4477fd-ede5-44bd-bc83-fc723444b763,3,phone,frames/retrieval/visual_crops/val/82abc0e6-c28...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/307c3ec6-886e-4d25-9ef7-7bea3cf7a243_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,1,blowtorch,frames/retrieval/visual_crops/val/307c3ec6-886...
1,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,2,tape,frames/retrieval/visual_crops/val/307c3ec6-886...
2,307c3ec6-886e-4d25-9ef7-7bea3cf7a243,4652c16c-7179-4576-a91f-27bebefa4ef2,3,plastic container,frames/retrieval/visual_crops/val/307c3ec6-886...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,3,ball,frames/retrieval/visual_crops/val/bd87e5e6-d2e...
1,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,2,golf stick,frames/retrieval/visual_crops/val/bd87e5e6-d2e...
2,bd87e5e6-d2e3-4e8e-8c0d-dc57a93f8b76,962d3511-1308-462e-8bb1-c044911eca3c,1,mobile phone,frames/retrieval/visual_crops/val/bd87e5e6-d2e...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/1004f7fe-c397-4123-bad9-e02df2e154dd_query_metadata.parquet
Shape: (6, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,1,plate,frames/retrieval/visual_crops/val/1004f7fe-c39...
1,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,2,bowl,frames/retrieval/visual_crops/val/1004f7fe-c39...
2,1004f7fe-c397-4123-bad9-e02df2e154dd,604ae2ef-313b-467d-b638-17af7170f462,3,cooking pot,frames/retrieval/visual_crops/val/1004f7fe-c39...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,2,rice cooker,frames/retrieval/visual_crops/val/6ed430d1-e42...
1,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,1,bowl,frames/retrieval/visual_crops/val/6ed430d1-e42...
2,6ed430d1-e42c-4fc1-b81c-a8b25fcd8d4e,6fbb50ec-f7f6-46e4-bb2e-126b9d3bbd56,3,tissue paper,frames/retrieval/visual_crops/val/6ed430d1-e42...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/ccc4408f-8420-481d-b5aa-0c0013e3a109_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,1,pliers,frames/retrieval/visual_crops/val/ccc4408f-842...
1,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,3,painting brush,frames/retrieval/visual_crops/val/ccc4408f-842...
2,ccc4408f-8420-481d-b5aa-0c0013e3a109,6ef02b95-0c15-43ba-842e-bb745534affe,2,thread,frames/retrieval/visual_crops/val/ccc4408f-842...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/query_embeddings/dc3ba39f-62f4-480b-a187-ca723c8666bd_query_metadata.parquet
Shape: (3, 5)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob
0,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,1,shopping basket,frames/retrieval/visual_crops/val/dc3ba39f-62f...
1,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,3,scarf,frames/retrieval/visual_crops/val/dc3ba39f-62f...
2,dc3ba39f-62f4-480b-a187-ca723c8666bd,d79aa223-5429-4b48-aabe-1378d3daaad3,2,knitted beret,frames/retrieval/visual_crops/val/dc3ba39f-62f...

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/b144e06c-ac25-4584-9ff4-93d6a8d04865_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,1,basket,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a basket
1,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,2,phone,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a phone
2,b144e06c-ac25-4584-9ff4-93d6a8d04865,279c38b4-0101-48d7-948f-277954940e3c,3,mirror,frames/retrieval/visual_crops/val/b144e06c-ac2...,a photo of a mirror

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,1,lamp shade,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a lamp shade
1,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,2,desk top,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a desk top
2,8b1676e2-8a98-47d7-a97b-bc91c6b3ffdb,567c715b-e27a-4190-8a6a-131eeb2cffbe,3,plant pot,frames/retrieval/visual_crops/val/8b1676e2-8a9...,a photo of a plant pot

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/8530a122-787b-4e95-b848-5543e8d772c7_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,1,flower pot,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a flower pot
1,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,2,trash bin,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a trash bin
2,8530a122-787b-4e95-b848-5543e8d772c7,93de932f-a0b4-4037-acb6-39fead540672,3,bucket,frames/retrieval/visual_crops/val/8530a122-787...,a photo of a bucket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/293a2530-a4a8-4776-92d5-741142dfdd3e_text_metadata_a_photo_of_a_object.parquet
Shape: (2, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,1,cooking pan,frames/retrieval/visual_crops/val/293a2530-a4a...,a photo of a cooking pan
1,293a2530-a4a8-4776-92d5-741142dfdd3e,4419debc-8a47-4891-8567-080eda6452c3,3,bucket,frames/retrieval/visual_crops/val/293a2530-a4a...,a photo of a bucket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/cc7d11f0-445e-426a-904e-e7faafdb07f7_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,3,kurta tunic,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a kurta tunic
1,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,1,iron box,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a iron box
2,cc7d11f0-445e-426a-904e-e7faafdb07f7,dd74cd45-980d-498f-8234-ae8ed0fd97e4,2,cloth,frames/retrieval/visual_crops/val/cc7d11f0-445...,a photo of a cloth

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/aef0725a-1005-4a17-ad33-4522808c3a17_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,2,kettle,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a kettle
1,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,1,jug,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a jug
2,aef0725a-1005-4a17-ad33-4522808c3a17,361d8895-b4c7-47dc-bab9-c40af8f11a24,3,bottle,frames/retrieval/visual_crops/val/aef0725a-100...,a photo of a bottle

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/3e95b70a-e2b1-4d6f-a229-b07d4f8eadea_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,1,dough cutter,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a dough cutter
1,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,2,scrubber,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a scrubber
2,3e95b70a-e2b1-4d6f-a229-b07d4f8eadea,e787384c-59d8-4bc0-bbae-47fd8363d478,3,weighing scale,frames/retrieval/visual_crops/val/3e95b70a-e2b...,a photo of a weighing scale

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/f1350714-1aa5-421b-a268-690110ca9c06_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,1,wheels,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a wheels
1,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,2,power drill,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a power drill
2,f1350714-1aa5-421b-a268-690110ca9c06,91bbd728-276a-407b-9e6c-c3e7ace5a257,3,brake shoe,frames/retrieval/visual_crops/val/f1350714-1aa...,a photo of a brake shoe

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/99ddfcb3-bb2a-45d3-903e-d7e858969957_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,1,bag,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a bag
1,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,2,pruning sheers,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a pruning sheers
2,99ddfcb3-bb2a-45d3-903e-d7e858969957,27b4a232-d34a-4c17-bb43-97a303c92e02,3,basket,frames/retrieval/visual_crops/val/99ddfcb3-bb2...,a photo of a basket

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/30ca6fa7-dbe0-4f55-84c8-8797de99c290_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,3,flower pot,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a flower pot
1,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,1,pillows,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a pillows
2,30ca6fa7-dbe0-4f55-84c8-8797de99c290,3ed07a6c-a7ae-45bf-83ad-d494c476c4a2,2,cloth,frames/retrieval/visual_crops/val/30ca6fa7-dbe...,a photo of a cloth

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/b0612ea7-11f9-486e-a4aa-e0f8ba67e2df_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,1,drill,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a drill
1,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,2,hammer,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a hammer
2,b0612ea7-11f9-486e-a4aa-e0f8ba67e2df,909b3429-b3a1-4dd8-9aa4-501dca7ffbbe,3,tin,frames/retrieval/visual_crops/val/b0612ea7-11f...,a photo of a tin

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/f052ac6f-832d-41f0-b00f-7cb85c20a15c_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,1,plastic container,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a plastic container
1,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,3,paper towel,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a paper towel
2,f052ac6f-832d-41f0-b00f-7cb85c20a15c,05c4c7ef-291e-42b6-a9bb-34afe2d9487c,2,toothbrush,frames/retrieval/visual_crops/val/f052ac6f-832...,a photo of a toothbrush

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/72e90719-c2b8-4b17-b120-e904dbbf1184_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,1,tray,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a tray
1,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,3,plastic water jar,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a plastic water jar
2,72e90719-c2b8-4b17-b120-e904dbbf1184,dea9a6a8-1eed-45be-a3be-64d29cd0b14f,2,pressure cooker,frames/retrieval/visual_crops/val/72e90719-c2b...,a photo of a pressure cooker

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/ddb94361-b4c3-4343-8a80-daad1ea69476_text_metadata_a_photo_of_a_object.parquet
Shape: (2, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,1,book stand,frames/retrieval/visual_crops/val/ddb94361-b4c...,a photo of a book stand
1,ddb94361-b4c3-4343-8a80-daad1ea69476,26ba2a11-f8be-44cd-930f-25b17eddda63,3,house plant,frames/retrieval/visual_crops/val/ddb94361-b4c...,a photo of a house plant

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/efe7dfaa-07e0-42d5-85eb-1e6f93409ab5_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,1,plastic bottle,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a plastic bottle
1,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,2,screwdriver,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a screwdriver
2,efe7dfaa-07e0-42d5-85eb-1e6f93409ab5,bd34befc-c40b-4b6d-852f-5f8109458c6c,3,t wrench,frames/retrieval/visual_crops/val/efe7dfaa-07e...,a photo of a t wrench

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/ae8727ba-fe6f-4411-b277-48a8b7326a2a_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,1,container,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a container
1,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,2,bottle,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a bottle
2,ae8727ba-fe6f-4411-b277-48a8b7326a2a,462a347e-6b44-449f-b7d5-7393c7526841,3,chair,frames/retrieval/visual_crops/val/ae8727ba-fe6...,a photo of a chair

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/6c0c2145-2b3d-48cd-a61c-e29d8541218f_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,1,white flipflop,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a white flipflop
1,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,2,transparent cup,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a transparent cup
2,6c0c2145-2b3d-48cd-a61c-e29d8541218f,dfb3cf4b-a53f-4c66-a613-0803f5b82ca1,3,chopsticks,frames/retrieval/visual_crops/val/6c0c2145-2b3...,a photo of a chopsticks

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/09d85b55-d473-49c1-9ebc-e871714785cd_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,1,calculator,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a calculator
1,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,2,tray,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a tray
2,09d85b55-d473-49c1-9ebc-e871714785cd,29db216a-320b-4861-972a-d4a9ae719ced,3,spray bottle,frames/retrieval/visual_crops/val/09d85b55-d47...,a photo of a spray bottle

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/e4728a65-3184-4239-9b84-be43dfd7377e_text_metadata_a_photo_of_a_object.parquet
Shape: (3, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,2,jug,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a jug
1,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,3,wood cutting machine,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a wood cutting machine
2,e4728a65-3184-4239-9b84-be43dfd7377e,310aef6e-4b04-4605-8192-0690451d94a3,1,container,frames/retrieval/visual_crops/val/e4728a65-318...,a photo of a container

====================================================================================================
/home/jupyter/results/retrieval_subset/cache/clip_text_query_embeddings/67c47998-eabe-4b31-9096-b286c18e1beb_text_metadata_a_photo_of_a_object.parquet
Shape: (6, 6)
Columns: ['clip_uid', 'annotation_uid', 'qs_id', 'object_title', 'vc_blob', 'prompt']

,clip_uid,annotation_uid,qs_id,object_title,vc_blob,prompt
0,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,1,basket,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a basket
1,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,2,wallet,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a wallet
2,67c47998-eabe-4b31-9096-b286c18e1beb,6cb2d772-cba3-4cf5-baba-5987319a75db,3,receipt,frames/retrieval/visual_crops/val/67c47998-eab...,a photo of a receipt

In [ ]:
# ---------------- 8. Focused search for source metadata files ----------------

from pathlib import Path
import pandas as pd

focus_roots = [
    Path("/home/jupyter"),
    Path("/home/jupyter/egorecall_retrieval_subset"),
    Path("/home/jupyter/results/retrieval_subset"),
]

target_names = [
    "vq_query_sets.parquet",
    "retrieval_metadata.parquet",
    "extraction_manifest.parquet",
    "response_track.parquet",
    "response_tracks.parquet",
]

focused_matches = []

for root in focus_roots:
    if not root.exists():
        continue

    for name in target_names:
        focused_matches.extend(list(root.rglob(name)))

# Remove duplicates while preserving order
seen = set()
focused_matches_unique = []
for p in focused_matches:
    if str(p) not in seen:
        focused_matches_unique.append(p)
        seen.add(str(p))

print("Focused matches:", len(focused_matches_unique))
for p in focused_matches_unique:
    print(p)

Focused matches: 4
/home/jupyter/egorecall_retrieval_work/vq_query_sets.parquet
/home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet
/home/jupyter/egorecall_retrieval_subset/retrieval_metadata.parquet
/home/jupyter/egorecall_retrieval_subset/extraction_manifest.parquet

In [ ]:
# ---------------- 9. Inspect focused metadata tables ----------------

for p in focused_matches_unique:
    print("=" * 120)
    print("File:", p)

    try:
        df_tmp = pd.read_parquet(p)
        print("Shape:", df_tmp.shape)
        print("Columns:", df_tmp.columns.tolist())
        display(df_tmp.head(5))

    except Exception as e:
        print("Failed to read:", repr(e))

========================================================================================================================
File: /home/jupyter/egorecall_retrieval_work/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667
3,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,69b2bddb-8160-4779-9157-8696cb019bd2,1,basket,1090.0,14639.0,True,False,True,...,300.0,269.987695,569.987695,True,0.005293,0.069316,0.740477,0.910401,1500,0.726667
4,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,69b2bddb-8160-4779-9157-8696cb019bd2,2,carton box,1283.0,15797.0,True,False,True,...,300.0,269.987695,569.987695,True,0.028745,0.814385,0.597898,1.443516,1500,0.855333

========================================================================================================================
File: /home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet
Shape: (18114, 33)
Columns: ['split', 'video_uid', 'annotation_uid', 'qs_id', 'object_title', 'query_frame', 'query_video_frame', 'is_valid', 'has_errors', 'has_warnings', 'response_track_len', 'vc_frame', 'vc_x', 'vc_y', 'vc_w', 'vc_h', 'orig_w', 'orig_h', 'clip_uid', 'source_clip_uid', 'clip_fps', 'clip_start_sec', 'clip_end_sec', 'clip_duration_sec', 'video_start_sec', 'video_end_sec', 'annotation_complete', 'vc_area_norm', 'vc_cx_norm', 'vc_cy_norm', 'vc_aspect', 'clip_total_frames', 'query_pos_norm']

,split,video_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,is_valid,has_errors,has_warnings,...,clip_duration_sec,video_start_sec,video_end_sec,annotation_complete,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,1,mr krips,1190.0,15239.0,True,False,True,...,300.0,269.987695,569.987695,True,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,2,oats & more,1176.0,15155.0,True,False,True,...,300.0,269.987695,569.987695,True,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,c64628fc-f163-4eb6-b7b1-f89b35cdcf54,3,tissue,1339.0,16133.0,True,False,True,...,300.0,269.987695,569.987695,True,0.009538,0.718073,0.338042,0.626356,1500,0.892667
3,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,69b2bddb-8160-4779-9157-8696cb019bd2,1,basket,1090.0,14639.0,True,False,True,...,300.0,269.987695,569.987695,True,0.005293,0.069316,0.740477,0.910401,1500,0.726667
4,train,56a3b49c-6979-4253-9ff5-2733c3e2f229,69b2bddb-8160-4779-9157-8696cb019bd2,2,carton box,1283.0,15797.0,True,False,True,...,300.0,269.987695,569.987695,True,0.028745,0.814385,0.597898,1.443516,1500,0.855333

========================================================================================================================
File: /home/jupyter/egorecall_retrieval_subset/retrieval_metadata.parquet
Failed to read: ArrowInvalid("Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes")
========================================================================================================================
File: /home/jupyter/egorecall_retrieval_subset/extraction_manifest.parquet
Shape: (1743, 7)
Columns: ['video_uid', 'split', 'n_clips', 'detection_frames', 'yolo_labels', 'visual_crops', 'status']

,video_uid,split,n_clips,detection_frames,yolo_labels,visual_crops,status
0,56a3b49c-6979-4253-9ff5-2733c3e2f229,train,5.0,281.0,281.0,24.0,ok
1,a7a6e05d-ffe6-47a4-a08c-b4b386e9911f,train,2.0,55.0,55.0,6.0,ok
2,ee114c86-05fc-4d47-8c9a-8dfeafed0457,train,2.0,140.0,140.0,9.0,ok
3,95710114-4168-47b4-a63e-a4d220b42fcf,train,1.0,36.0,36.0,3.0,ok
4,6146205c-f045-4368-acc2-a60dc5e1490b,train,1.0,154.0,154.0,3.0,ok

In [ ]:
# ---------------- 10. Inspect vq_query_sets response-track fields ----------------

VQ_QUERY_PATH = Path("/home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet")

vq_df = pd.read_parquet(VQ_QUERY_PATH)

print("vq_df shape:", vq_df.shape)
print("\nAll columns:")
for i, col in enumerate(vq_df.columns):
    print(i, col)

print("\nColumns containing frame / track / response / vc / query:")
key_cols = [
    c for c in vq_df.columns
    if any(k in c.lower() for k in ["frame", "track", "response", "vc", "query", "clip"])
]
for c in key_cols:
    print(c)

display(vq_df[key_cols].head(10))

vq_df shape: (18114, 33)

All columns:
0 split
1 video_uid
2 annotation_uid
3 qs_id
4 object_title
5 query_frame
6 query_video_frame
7 is_valid
8 has_errors
9 has_warnings
10 response_track_len
11 vc_frame
12 vc_x
13 vc_y
14 vc_w
15 vc_h
16 orig_w
17 orig_h
18 clip_uid
19 source_clip_uid
20 clip_fps
21 clip_start_sec
22 clip_end_sec
23 clip_duration_sec
24 video_start_sec
25 video_end_sec
26 annotation_complete
27 vc_area_norm
28 vc_cx_norm
29 vc_cy_norm
30 vc_aspect
31 clip_total_frames
32 query_pos_norm

Columns containing frame / track / response / vc / query:
query_frame
query_video_frame
response_track_len
vc_frame
vc_x
vc_y
vc_w
vc_h
clip_uid
source_clip_uid
clip_fps
clip_start_sec
clip_end_sec
clip_duration_sec
vc_area_norm
vc_cx_norm
vc_cy_norm
vc_aspect
clip_total_frames
query_pos_norm

,query_frame,query_video_frame,response_track_len,vc_frame,vc_x,vc_y,vc_w,vc_h,clip_uid,source_clip_uid,clip_fps,clip_start_sec,clip_end_sec,clip_duration_sec,vc_area_norm,vc_cx_norm,vc_cy_norm,vc_aspect,clip_total_frames,query_pos_norm
0,1190.0,15239.0,11,1198.0,742.08,587.21,78.35,121.73,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.006133,0.542538,0.600069,0.643638,1500,0.793333
1,1176.0,15155.0,13,1182.0,918.92,362.68,146.60,553.15,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.052142,0.689042,0.591903,0.265028,1500,0.784000
2,1339.0,16133.0,9,1356.0,985.83,288.14,96.39,153.89,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.009538,0.718073,0.338042,0.626356,1500,0.892667
3,1090.0,14639.0,15,1053.0,56.53,752.17,86.57,95.09,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.005293,0.069316,0.740477,0.910401,1500,0.726667
4,1283.0,15797.0,12,1111.0,1045.70,557.74,254.03,175.98,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.028745,0.814385,0.597898,1.443516,1500,0.855333
5,1315.0,15989.0,13,1284.0,1187.62,543.55,171.72,228.49,3fe39989-54ed-4a3a-bea4-88be05ff8df7,e970b901-fd09-4e00-ad86-12bbc04b02fb,5.0,0.0,300.000000,300.000000,0.025229,0.884361,0.609069,0.751543,1500,0.876667
6,113.0,677.0,8,114.0,1308.87,909.47,73.28,114.99,769b357e-508a-4741-a93f-642bb14dd2a0,011ebb4e-e7fa-47a9-bf36-453cfa015053,5.0,0.0,959.966667,959.966667,0.005418,0.934382,0.895338,0.637273,4800,0.023542
7,513.0,3077.0,11,49.0,146.89,722.63,95.20,186.47,769b357e-508a-4741-a93f-642bb14dd2a0,011ebb4e-e7fa-47a9-bf36-453cfa015053,5.0,0.0,959.966667,959.966667,0.011415,0.135062,0.755431,0.510538,4800,0.106875
8,384.0,2303.0,9,394.0,726.71,582.80,227.59,206.77,769b357e-508a-4741-a93f-642bb14dd2a0,011ebb4e-e7fa-47a9-bf36-453cfa015053,5.0,0.0,959.966667,959.966667,0.030259,0.583684,0.635356,1.100692,4800,0.080000
9,325.0,18149.0,11,348.0,609.61,646.73,117.90,168.00,bdc60480-9ef7-4092-b470-4a75368a312c,84cba418-7727-4504-92af-30112ce27a7b,5.0,0.0,300.000000,300.000000,0.012736,0.464278,0.676602,0.701786,1500,0.216667

In [ ]:
# ---------------- 11. Filter vq_query_sets to our 300 cached clips ----------------

vq_300_df = vq_df[vq_df["clip_uid"].astype(str).isin(all_300_clip_uids)].copy()

print("vq_300_df shape:", vq_300_df.shape)
print("Unique clips in vq_300_df:", vq_300_df["clip_uid"].nunique())

display(
    vq_300_df[
        [
            "clip_uid",
            "annotation_uid",
            "qs_id",
            "object_title",
            "query_frame",
            "query_video_frame",
            "response_track_len",
            "clip_total_frames",
        ]
    ].head(20)
)

vq_300_df shape: (1157, 33)
Unique clips in vq_300_df: 300

,clip_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,response_track_len,clip_total_frames
13610,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,298.0,42288.0,30,1500
13611,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,1044.0,46764.0,7,1500
13612,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,1498.0,49488.0,49,1500
13613,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,1499.0,49494.0,18,1500
13614,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,363.0,42678.0,13,1500
13615,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,489.0,43434.0,8,1500
13622,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,1,dispensing bottle,827.0,29262.0,3,1500
13623,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,3,adapter,674.0,28344.0,8,1500
13624,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,2,impact driver,963.0,30078.0,9,1500
13625,b157270d-c67a-41db-91ec-32bb3ec738fc,3cedcbbe-7dd0-4ef0-b0ac-e7f26a4c20cb,2,orange towel,125.0,25050.0,33,1500
13626,b157270d-c67a-41db-91ec-32bb3ec738fc,3cedcbbe-7dd0-4ef0-b0ac-e7f26a4c20cb,1,orange torch,501.0,27306.0,16,1500
13627,b157270d-c67a-41db-91ec-32bb3ec738fc,3cedcbbe-7dd0-4ef0-b0ac-e7f26a4c20cb,3,water spray bottle,1306.0,32136.0,23,1500
13631,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,1,carton box,614.0,63464.0,7,2397
13632,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,2,bottle spray,1650.0,69680.0,5,2397
13633,7bb41f34-1743-42ad-97d1-c54f4472b85e,9bc3105a-2ab1-4228-971b-03343a98c1ef,3,bulb box,1652.0,69692.0,4,2397
13634,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,1,spray bottle,169.0,15414.0,5,4800
13635,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,3,red jerry can,1530.0,23580.0,25,4800
13636,ea365183-5841-4f00-9a2e-1b81c5e09c98,d5a42c12-5fbd-4d17-9b85-1cf04ca22fce,2,orange shock absorber,2287.0,28122.0,7,4800
13655,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,1,weighing scale,140.0,17039.0,12,1500
13656,b961eb69-cfdd-4d5c-b427-4b667fedfcda,67c45fcd-e7fa-4274-8ce0-0df3e7c1d8e4,2,chair,394.0,18563.0,2,1500

In [ ]:
# ---------------- 12. Build response-track labels / rt_lookup ----------------

VQ_QUERY_PATH = Path("/home/jupyter/egorecall_retrieval_subset/vq_query_sets.parquet")

vq_df = pd.read_parquet(VQ_QUERY_PATH)

# Keep only rows for our 300 cached clips
vq_300_df = vq_df[vq_df["clip_uid"].astype(str).isin(all_300_clip_uids)].copy()

# Make key columns consistent
vq_300_df["clip_uid"] = vq_300_df["clip_uid"].astype(str)
vq_300_df["annotation_uid"] = vq_300_df["annotation_uid"].astype(str)
vq_300_df["qs_id"] = vq_300_df["qs_id"].astype(int)

# Build response-track range in video-frame coordinates
vq_300_df["rt_min_frame"] = vq_300_df["query_video_frame"].astype(float)
vq_300_df["rt_max_frame"] = (
    vq_300_df["query_video_frame"].astype(float)
    + vq_300_df["response_track_len"].astype(float)
    - 1
)

# Keep only valid rows
label_df = vq_300_df[
    (vq_300_df["is_valid"] == True)
    & (vq_300_df["has_errors"] == False)
    & vq_300_df["query_video_frame"].notna()
    & vq_300_df["response_track_len"].notna()
].copy()

label_cols = [
    "clip_uid",
    "annotation_uid",
    "qs_id",
    "object_title",
    "query_frame",
    "query_video_frame",
    "response_track_len",
    "rt_min_frame",
    "rt_max_frame",
    "clip_total_frames",
]

label_df = label_df[label_cols].copy()

print("label_df shape:", label_df.shape)
print("Unique clips in label_df:", label_df["clip_uid"].nunique())
print("Unique query labels:", label_df[["clip_uid", "annotation_uid", "qs_id"]].drop_duplicates().shape[0])

display(label_df.head(10))

# Build lookup: key = (clip_uid, annotation_uid, qs_id)
rt_lookup = {}

for _, row in label_df.iterrows():
    key = (
        str(row["clip_uid"]),
        str(row["annotation_uid"]),
        int(row["qs_id"]),
    )
    rt_lookup[key] = {
        "object_title": row["object_title"],
        "query_frame": float(row["query_frame"]),
        "query_video_frame": float(row["query_video_frame"]),
        "response_track_len": float(row["response_track_len"]),
        "rt_min_frame": float(row["rt_min_frame"]),
        "rt_max_frame": float(row["rt_max_frame"]),
    }

print("\nrt_lookup entries:", len(rt_lookup))

sample_key = next(iter(rt_lookup))
print("Sample key:", sample_key)
print("Sample value:", rt_lookup[sample_key])

label_df shape: (1157, 10)
Unique clips in label_df: 300
Unique query labels: 1157

,clip_uid,annotation_uid,qs_id,object_title,query_frame,query_video_frame,response_track_len,rt_min_frame,rt_max_frame,clip_total_frames
13610,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,298.0,42288.0,30,42288.0,42317.0,1500
13611,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,1044.0,46764.0,7,46764.0,46770.0,1500
13612,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,1498.0,49488.0,49,49488.0,49536.0,1500
13613,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,1499.0,49494.0,18,49494.0,49511.0,1500
13614,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,363.0,42678.0,13,42678.0,42690.0,1500
13615,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,489.0,43434.0,8,43434.0,43441.0,1500
13622,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,1,dispensing bottle,827.0,29262.0,3,29262.0,29264.0,1500
13623,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,3,adapter,674.0,28344.0,8,28344.0,28351.0,1500
13624,b157270d-c67a-41db-91ec-32bb3ec738fc,dd64c5e8-7679-4068-acc6-50b21970e2e0,2,impact driver,963.0,30078.0,9,30078.0,30086.0,1500
13625,b157270d-c67a-41db-91ec-32bb3ec738fc,3cedcbbe-7dd0-4ef0-b0ac-e7f26a4c20cb,2,orange towel,125.0,25050.0,33,25050.0,25082.0,1500

rt_lookup entries: 1157
Sample key: ('dfe962ab-6aa7-4888-9378-796817a30ab6', '3b057788-ad90-432d-90ff-de1c45361df6', 2)
Sample value: {'object_title': 'portable fan', 'query_frame': 298.0, 'query_video_frame': 42288.0, 'response_track_len': 30.0, 'rt_min_frame': 42288.0, 'rt_max_frame': 42317.0}

In [ ]:
# ---------------- 13. Verify query cache metadata can match rt_lookup ----------------

all_query_meta_rows = []

for clip_uid in tqdm(all_300_clip_uids, desc="Loading query metadata"):
    query_cache = load_query_cache(clip_uid)
    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)
    all_query_meta_rows.append(qmeta)

all_query_meta_df = pd.concat(all_query_meta_rows, ignore_index=True)

print("All query metadata shape:", all_query_meta_df.shape)
print("Unique clips:", all_query_meta_df["clip_uid"].nunique())
print("Unique query rows:", all_query_meta_df[["clip_uid", "annotation_uid", "qs_id"]].drop_duplicates().shape[0])

# Add lookup match flag
def has_rt_label(row):
    key = (
        str(row["clip_uid"]),
        str(row["annotation_uid"]),
        int(row["qs_id"]),
    )
    return key in rt_lookup

all_query_meta_df["has_rt_label"] = all_query_meta_df.apply(has_rt_label, axis=1)

print("\nRT label match count:")
print(all_query_meta_df["has_rt_label"].value_counts(dropna=False))

missing_rt_df = all_query_meta_df[~all_query_meta_df["has_rt_label"]].copy()

print("\nMissing RT labels:", len(missing_rt_df))
display(missing_rt_df.head(20))

Loading query metadata:   0%|          | 0/300 [00:00<?, ?it/s]

All query metadata shape: (1157, 5)
Unique clips: 300
Unique query rows: 1157

RT label match count:
has_rt_label
True    1157
Name: count, dtype: int64

Missing RT labels: 0

Empty DataFrame
Columns: [clip_uid, annotation_uid, qs_id, object_title, vc_blob, has_rt_label]
Index: []

In [ ]:
# ---------------- 14. Baseline retrieval sanity check on one clip ----------------

def evaluate_one_clip_baseline(clip_uid, model_name="clip", topk=100, tolerance_frames=TOLERANCE_FRAMES):
    """
    Evaluate retrieval for one clip using cached embeddings.

    model_name:
        - "clip": use CLIP embeddings
        - "blip": use BLIP embeddings
    """
    index_cache = load_index_cache(clip_uid)
    query_cache = load_query_cache(clip_uid)

    frame_numbers = index_cache["frame_numbers"]

    if model_name == "clip":
        index_embs = index_cache["clip_embs"]
        query_embs = query_cache["clip_embs"]
    elif model_name == "blip":
        index_embs = index_cache["blip_embs"]
        query_embs = query_cache["blip_embs"]
    else:
        raise ValueError("model_name must be 'clip' or 'blip'")

    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for q_idx, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]
        query_emb = query_embs[q_idx]

        scores = compute_similarity_scores(index_embs, query_emb)
        topk_df = get_topk_frames(frame_numbers, scores, k=topk)

        rank = first_correct_rank(
            topk_df=topk_df,
            rt_min_frame=rt["rt_min_frame"],
            rt_max_frame=rt["rt_max_frame"],
            tolerance_frames=tolerance_frames,
        )

        top1_frame = int(topk_df.iloc[0]["frame_number"])
        top1_score = float(topk_df.iloc[0]["score"])

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "model_name": model_name,
            "top1_frame": top1_frame,
            "top1_score": top1_score,
            "rt_min_frame": rt["rt_min_frame"],
            "rt_max_frame": rt["rt_max_frame"],
            "first_correct_rank": rank,
            "top1_success": bool(rank == 1),
            "top5_success": bool(pd.notna(rank) and rank <= 5),
            "top10_success": bool(pd.notna(rank) and rank <= 10),
            "top20_success": bool(pd.notna(rank) and rank <= 20),
            "top50_success": bool(pd.notna(rank) and rank <= 50),
            "top100_success": bool(pd.notna(rank) and rank <= 100),
        })

    return pd.DataFrame(rows)


test_clip_uid = all_300_clip_uids[0]

clip_test_df = evaluate_one_clip_baseline(
    clip_uid=test_clip_uid,
    model_name="clip",
    topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(clip_test_df))
display(clip_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,model_name,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,clip,43470,0.820488,42288.0,42317.0,88.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,clip,41370,0.795074,46764.0,46770.0,5.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,clip,41370,0.795995,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,clip,46770,0.852550,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,clip,46770,0.883756,42678.0,42690.0,53.0,False,False,False,False,False,True
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,clip,44400,0.855764,43434.0,43441.0,79.0,False,False,False,False,False,True

In [ ]:
# ---------------- 15. BLIP baseline sanity check on one clip ----------------

blip_test_df = evaluate_one_clip_baseline(
    clip_uid=test_clip_uid,
    model_name="blip",
    topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(blip_test_df))
display(blip_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,model_name,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,blip,42390,0.753312,42288.0,42317.0,73.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,blip,41370,0.622319,46764.0,46770.0,3.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,blip,47670,0.650754,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,blip,46770,0.703079,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,blip,42300,0.721368,42678.0,42690.0,47.0,False,False,False,False,True,True
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,blip,42480,0.714370,43434.0,43441.0,NaN,False,False,False,False,False,False

In [ ]:
# ---------------- 16. Run full baseline: CLIP + BLIP over 300 clips ----------------

baseline_rows = []

for model_name in ["clip", "blip"]:
    print("=" * 80)
    print("Running baseline:", model_name)

    for clip_uid in tqdm(all_300_clip_uids, desc=f"{model_name} baseline"):
        df_one = evaluate_one_clip_baseline(
            clip_uid=clip_uid,
            model_name=model_name,
            topk=100,
        )
        baseline_rows.append(df_one)

baseline_df = pd.concat(baseline_rows, ignore_index=True)

print("Baseline rows:", len(baseline_df))
print("Models:", baseline_df["model_name"].value_counts())

display(baseline_df.head())

baseline_path = RESULTS_DIR / f"baseline_clip_blip_nclips{N_CLIPS}_top100.csv"
baseline_df.to_csv(baseline_path, index=False)

print("Saved baseline results to:", baseline_path)

================================================================================
Running baseline: clip

clip baseline:   0%|          | 0/300 [00:00<?, ?it/s]

================================================================================
Running baseline: blip

blip baseline:   0%|          | 0/300 [00:00<?, ?it/s]

Baseline rows: 2314
Models: model_name
clip    1157
blip    1157
Name: count, dtype: int64

,clip_uid,annotation_uid,qs_id,object_title,model_name,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,clip,43470,0.820488,42288.0,42317.0,88.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,clip,41370,0.795074,46764.0,46770.0,5.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,clip,41370,0.795995,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,clip,46770,0.852550,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,clip,46770,0.883756,42678.0,42690.0,53.0,False,False,False,False,False,True

Saved baseline results to: /home/jupyter/results/retrieval_subset/baseline_clip_blip_nclips300_top100.csv

In [ ]:
# ---------------- 17. Summarize baseline metrics ----------------

metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

baseline_summary = (
    baseline_df
    .groupby("model_name")[metric_cols]
    .mean()
    .reset_index()
)

# Convert to percentage
for col in metric_cols:
    baseline_summary[col] = baseline_summary[col] * 100

display(baseline_summary)

summary_path = RESULTS_DIR / f"baseline_summary_nclips{N_CLIPS}_top100.csv"
baseline_summary.to_csv(summary_path, index=False)

print("Saved baseline summary to:", summary_path)

,model_name,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,blip,0.518583,1.469317,2.852204,5.617978,13.569576,25.669836
1,clip,0.518583,1.728608,2.938634,5.272256,15.038894,24.978392

Saved baseline summary to: /home/jupyter/results/retrieval_subset/baseline_summary_nclips300_top100.csv

In [ ]:
# ---------------- 18. First correct rank distribution ----------------

for model_name in ["clip", "blip"]:
    df_m = baseline_df[baseline_df["model_name"] == model_name].copy()

    print("=" * 80)
    print("Model:", model_name)
    print("Total queries:", len(df_m))
    print("Queries with correct frame in top100:", df_m["first_correct_rank"].notna().sum())
    print("Queries without correct frame in top100:", df_m["first_correct_rank"].isna().sum())

    display(
        df_m["first_correct_rank"]
        .describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95])
    )

================================================================================
Model: clip
Total queries: 1157
Queries with correct frame in top100: 289
Queries without correct frame in top100: 868

count    289.000000
mean      45.719723
std       27.021487
min        1.000000
25%       26.000000
50%       45.000000
75%       66.000000
90%       86.000000
95%       91.200000
max      100.000000
Name: first_correct_rank, dtype: float64

================================================================================
Model: blip
Total queries: 1157
Queries with correct frame in top100: 297
Queries without correct frame in top100: 860

count    297.000000
mean      49.070707
std       29.141634
min        1.000000
25%       23.000000
50%       48.000000
75%       73.000000
90%       91.000000
95%       95.000000
max      100.000000
Name: first_correct_rank, dtype: float64

## Baseline Retrieval Results: CLIP-only vs BLIP-only

We evaluated cached retrieval embeddings on 300 clips, covering 1,157 query/object cases.  
For each query, the system ranks cached index frames by cosine similarity and checks whether the retrieved frame falls within the ground-truth response-track frame range.

### Baseline Summary

| Model | Top-1 | Top-5 | Top-10 | Top-20 | Top-50 | Top-100 |
|---|---:|---:|---:|---:|---:|---:|
| BLIP | 0.52% | 1.47% | 2.85% | 5.62% | 13.57% | 25.67% |
| CLIP | 0.52% | 1.73% | 2.94% | 5.27% | 15.04% | 24.98% |

### Interpretation

The baseline retrieval performance is low, especially at Top-1. Both CLIP-only and BLIP-only retrieval achieve only around 0.52% Top-1 accuracy. Even at Top-100, the correct response-track frame appears for only about 25% of the queries.

This suggests that the main bottleneck is not only final ranking quality, but also candidate recall: for many queries, the correct frame does not appear in the top candidate set. Therefore, simple reranking may have limited impact unless the correct frame is already included among the retrieved candidates.

CLIP and BLIP perform similarly overall. CLIP is slightly better at Top-50, while BLIP is slightly better at Top-100. This suggests that the two embedding spaces may contain partially complementary signals, making CLIP/BLIP score fusion a reasonable next experiment.

Before applying more complex reranking methods, we should verify whether the sampled index frames actually cover the ground-truth response-track windows. If many response tracks are not represented by any sampled index frame, retrieval cannot succeed regardless of the ranking model.

In [ ]:
# ---------------- 19. Ground-truth coverage upper bound check ----------------

def check_gt_frame_coverage_for_one_clip(
    clip_uid,
    tolerance_frames=TOLERANCE_FRAMES,
):
    """
    Check whether each query's ground-truth response-track range
    is covered by at least one sampled index frame.
    """
    index_cache = load_index_cache(clip_uid)
    frame_numbers = index_cache["frame_numbers"]

    query_cache = load_query_cache(clip_uid)
    qmeta = query_cache["query_metadata"].copy()

    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for _, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]

        rt_min = rt["rt_min_frame"]
        rt_max = rt["rt_max_frame"]

        covered_mask = (
            (frame_numbers >= rt_min - tolerance_frames)
            & (frame_numbers <= rt_max + tolerance_frames)
        )

        covered_frames = frame_numbers[covered_mask]

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "rt_min_frame": rt_min,
            "rt_max_frame": rt_max,
            "response_track_len": rt["response_track_len"],
            "num_index_frames": len(frame_numbers),
            "num_gt_covered_index_frames": len(covered_frames),
            "gt_covered_by_index": len(covered_frames) > 0,
            "first_covered_frame": covered_frames[0] if len(covered_frames) > 0 else np.nan,
            "last_covered_frame": covered_frames[-1] if len(covered_frames) > 0 else np.nan,
        })

    return pd.DataFrame(rows)


coverage_rows = []

for clip_uid in tqdm(all_300_clip_uids, desc="Checking GT frame coverage"):
    coverage_rows.append(
        check_gt_frame_coverage_for_one_clip(
            clip_uid=clip_uid,
            tolerance_frames=TOLERANCE_FRAMES,
        )
    )

coverage_df = pd.concat(coverage_rows, ignore_index=True)

print("Coverage rows:", len(coverage_df))
print("Unique clips:", coverage_df["clip_uid"].nunique())
print("GT covered count:", coverage_df["gt_covered_by_index"].sum())
print("GT not covered count:", (~coverage_df["gt_covered_by_index"]).sum())
print("GT coverage rate:", coverage_df["gt_covered_by_index"].mean() * 100)

display(coverage_df.head())

coverage_path = RESULTS_DIR / f"gt_coverage_nclips{N_CLIPS}_tolerance{TOLERANCE_FRAMES}.csv"
coverage_df.to_csv(coverage_path, index=False)

print("Saved GT coverage results to:", coverage_path)

Checking GT frame coverage:   0%|          | 0/300 [00:00<?, ?it/s]

Coverage rows: 1157
Unique clips: 300
GT covered count: 775
GT not covered count: 382
GT coverage rate: 66.98357821953329

,clip_uid,annotation_uid,qs_id,object_title,rt_min_frame,rt_max_frame,response_track_len,num_index_frames,num_gt_covered_index_frames,gt_covered_by_index,first_covered_frame,last_covered_frame
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,42288.0,42317.0,30.0,300,1,True,42300.0,42300.0
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,46764.0,46770.0,7.0,300,1,True,46770.0,46770.0
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,49488.0,49536.0,49.0,300,0,False,NaN,NaN
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,49494.0,49511.0,18.0,300,0,False,NaN,NaN
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,42678.0,42690.0,13.0,300,1,True,42690.0,42690.0

Saved GT coverage results to: /home/jupyter/results/retrieval_subset/gt_coverage_nclips300_tolerance5.csv

## Ground-truth Coverage Upper Bound

We checked whether each query's ground-truth response-track window is covered by at least one sampled index frame in the cached frame set.

### Result

| Metric | Value |
|---|---:|
| Total query cases | 1,157 |
| Unique clips | 300 |
| GT covered by sampled index frames | 775 |
| GT not covered | 382 |
| GT coverage rate | 66.98% |

### Interpretation

The coverage upper bound is substantially higher than the CLIP-only and BLIP-only Top-100 retrieval performance. While CLIP and BLIP achieve only around 25% Top-100 success, approximately 67% of query cases have at least one ground-truth response-track frame present in the sampled index frame set.

This means the low baseline performance is not only caused by missing ground-truth frames in the sampled index. In many cases, the correct frame is available in the index cache but is not ranked highly enough by the current embedding similarity score.

Therefore, tuning strategies such as CLIP/BLIP score fusion, temporal smoothing, and candidate reranking are meaningful next steps.

However, around 33% of query cases are not covered by the sampled index frames. These cases cannot be solved by reranking alone unless we increase frame sampling density or introduce a second-stage search around candidate regions.

In [ ]:
# ---------------- 20. Define CLIP/BLIP alpha fusion retrieval ----------------

def evaluate_one_clip_alpha_fusion(
    clip_uid,
    alpha=0.5,
    topk=100,
    tolerance_frames=TOLERANCE_FRAMES,
):
    """
    Evaluate retrieval for one clip using alpha fusion:

        fusion_score = alpha * CLIP_score + (1 - alpha) * BLIP_score

    alpha = 1.0 -> CLIP-only
    alpha = 0.0 -> BLIP-only
    """
    index_cache = load_index_cache(clip_uid)
    query_cache = load_query_cache(clip_uid)

    frame_numbers = index_cache["frame_numbers"]

    index_clip_embs = index_cache["clip_embs"]
    index_blip_embs = index_cache["blip_embs"]

    query_clip_embs = query_cache["clip_embs"]
    query_blip_embs = query_cache["blip_embs"]

    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for q_idx, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]

        clip_scores = compute_similarity_scores(index_clip_embs, query_clip_embs[q_idx])
        blip_scores = compute_similarity_scores(index_blip_embs, query_blip_embs[q_idx])

        fusion_scores = alpha * clip_scores + (1 - alpha) * blip_scores

        topk_df = get_topk_frames(frame_numbers, fusion_scores, k=topk)

        rank = first_correct_rank(
            topk_df=topk_df,
            rt_min_frame=rt["rt_min_frame"],
            rt_max_frame=rt["rt_max_frame"],
            tolerance_frames=tolerance_frames,
        )

        top1_frame = int(topk_df.iloc[0]["frame_number"])
        top1_score = float(topk_df.iloc[0]["score"])

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "method": "alpha_fusion",
            "alpha": alpha,
            "top1_frame": top1_frame,
            "top1_score": top1_score,
            "rt_min_frame": rt["rt_min_frame"],
            "rt_max_frame": rt["rt_max_frame"],
            "first_correct_rank": rank,
            "top1_success": bool(rank == 1),
            "top5_success": bool(pd.notna(rank) and rank <= 5),
            "top10_success": bool(pd.notna(rank) and rank <= 10),
            "top20_success": bool(pd.notna(rank) and rank <= 20),
            "top50_success": bool(pd.notna(rank) and rank <= 50),
            "top100_success": bool(pd.notna(rank) and rank <= 100),
        })

    return pd.DataFrame(rows)


print("Alpha fusion function defined.")

Alpha fusion function defined.

In [ ]:
# ---------------- 21. One-clip alpha fusion sanity check ----------------

test_clip_uid = all_300_clip_uids[0]

fusion_test_df = evaluate_one_clip_alpha_fusion(
    clip_uid=test_clip_uid,
    alpha=0.5,
    topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(fusion_test_df))
display(fusion_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,alpha_fusion,0.5,42390,0.774597,42288.0,42317.0,71.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,alpha_fusion,0.5,41370,0.708696,46764.0,46770.0,3.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,alpha_fusion,0.5,41370,0.714960,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,alpha_fusion,0.5,46770,0.777815,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,alpha_fusion,0.5,46770,0.786738,42678.0,42690.0,34.0,False,False,False,False,True,True
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,alpha_fusion,0.5,42480,0.780019,43434.0,43441.0,83.0,False,False,False,False,False,True

In [ ]:
# ---------------- 22. Run alpha fusion grid over 300 clips ----------------

alphas = [0.0, 0.25, 0.5, 0.75, 1.0]

fusion_rows = []

for alpha in alphas:
    print("=" * 80)
    print("Running alpha fusion:", alpha)

    for clip_uid in tqdm(all_300_clip_uids, desc=f"alpha={alpha}"):
        df_one = evaluate_one_clip_alpha_fusion(
            clip_uid=clip_uid,
            alpha=alpha,
            topk=100,
        )
        fusion_rows.append(df_one)

fusion_df = pd.concat(fusion_rows, ignore_index=True)

print("Fusion rows:", len(fusion_df))
print("Alpha counts:")
print(fusion_df["alpha"].value_counts().sort_index())

display(fusion_df.head())

fusion_path = RESULTS_DIR / f"alpha_fusion_nclips{N_CLIPS}_top100.csv"
fusion_df.to_csv(fusion_path, index=False)

print("Saved alpha fusion results to:", fusion_path)

================================================================================
Running alpha fusion: 0.0

alpha=0.0:   0%|          | 0/300 [00:00<?, ?it/s]

================================================================================
Running alpha fusion: 0.25

alpha=0.25:   0%|          | 0/300 [00:00<?, ?it/s]

================================================================================
Running alpha fusion: 0.5

alpha=0.5:   0%|          | 0/300 [00:00<?, ?it/s]

================================================================================
Running alpha fusion: 0.75

alpha=0.75:   0%|          | 0/300 [00:00<?, ?it/s]

================================================================================
Running alpha fusion: 1.0

alpha=1.0:   0%|          | 0/300 [00:00<?, ?it/s]

Fusion rows: 5785
Alpha counts:
alpha
0.00    1157
0.25    1157
0.50    1157
0.75    1157
1.00    1157
Name: count, dtype: int64

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,alpha_fusion,0.0,42390,0.753312,42288.0,42317.0,73.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,alpha_fusion,0.0,41370,0.622319,46764.0,46770.0,3.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,alpha_fusion,0.0,47670,0.650754,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,alpha_fusion,0.0,46770,0.703079,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,alpha_fusion,0.0,42300,0.721368,42678.0,42690.0,47.0,False,False,False,False,True,True

Saved alpha fusion results to: /home/jupyter/results/retrieval_subset/alpha_fusion_nclips300_top100.csv

In [ ]:
# ---------------- 23. Summarize alpha fusion results ----------------

metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

fusion_summary = (
    fusion_df
    .groupby("alpha")[metric_cols]
    .mean()
    .reset_index()
)

for col in metric_cols:
    fusion_summary[col] = fusion_summary[col] * 100

display(fusion_summary)

fusion_summary_path = RESULTS_DIR / f"alpha_fusion_summary_nclips{N_CLIPS}_top100.csv"
fusion_summary.to_csv(fusion_summary_path, index=False)

print("Saved alpha fusion summary to:", fusion_summary_path)

,alpha,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,0.00,0.518583,1.469317,2.852204,5.617978,13.569576,25.669836
1,0.25,0.518583,1.555748,2.852204,5.185825,13.742437,25.151253
2,0.50,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
3,0.75,0.432152,1.901469,3.025065,5.445117,14.174589,25.496975
4,1.00,0.518583,1.728608,2.938634,5.272256,15.038894,24.978392

Saved alpha fusion summary to: /home/jupyter/results/retrieval_subset/alpha_fusion_summary_nclips300_top100.csv

Simple CLIP/BLIP alpha fusion provides only marginal improvement over single-model baselines.
The best early-rank setting is alpha=0.75, suggesting that CLIP should dominate the fusion score while BLIP provides auxiliary signal.
However, the improvement is small, so later experiments should focus more on temporal/candidate reranking rather than relying only on linear score fusion.

In [ ]:
## CLIP/BLIP Alpha Fusion Results

We evaluated simple linear score fusion between CLIP and BLIP embeddings:

`fusion_score = alpha * CLIP_score + (1 - alpha) * BLIP_score`

### Result

| Alpha | Interpretation | Top-1 | Top-5 | Top-10 | Top-20 | Top-50 | Top-100 |
|---:|---|---:|---:|---:|---:|---:|---:|
| 0.00 | BLIP-only | 0.52% | 1.47% | 2.85% | 5.62% | 13.57% | 25.67% |
| 0.25 | 25% CLIP + 75% BLIP | 0.52% | 1.56% | 2.85% | 5.19% | 13.74% | 25.15% |
| 0.50 | 50% CLIP + 50% BLIP | 0.61% | 1.73% | 2.77% | 5.45% | 13.83% | 25.84% |
| 0.75 | 75% CLIP + 25% BLIP | 0.43% | 1.90% | 3.03% | 5.45% | 14.17% | 25.50% |
| 1.00 | CLIP-only | 0.52% | 1.73% | 2.94% | 5.27% | 15.04% | 24.98% |

### Interpretation

Simple CLIP/BLIP fusion provides only marginal improvement over single-model baselines. The best Top-100 result is achieved by alpha = 0.50, but the gain over BLIP-only is very small. For early-rank retrieval, alpha = 0.75 performs best at Top-5 and Top-10, suggesting that CLIP should remain the dominant signal while BLIP provides auxiliary information.

Overall, linear fusion alone is not sufficient to substantially improve retrieval. Since the ground-truth coverage upper bound is around 67%, while Top-100 retrieval remains around 25%, the next improvement should focus on temporal smoothing or candidate-guided reranking rather than simple score fusion alone.

In [ ]:
# ---------------- 24. Define temporal smoothing helper ----------------

def smooth_scores(scores, window_size=5, mode="mean"):
    """
    Smooth similarity scores across neighboring sampled index frames.

    window_size:
        Number of neighboring index positions included in smoothing.
        Should be an odd number, e.g. 3, 5, 7.

    mode:
        - "mean": average score in the window
        - "max": max score in the window
    """
    scores = np.asarray(scores, dtype=float)
    n = len(scores)

    if window_size <= 1:
        return scores.copy()

    if window_size % 2 == 0:
        raise ValueError("window_size should be odd, e.g. 3, 5, 7.")

    half = window_size // 2
    smoothed = np.zeros_like(scores)

    for i in range(n):
        start = max(0, i - half)
        end = min(n, i + half + 1)
        window_scores = scores[start:end]

        if mode == "mean":
            smoothed[i] = window_scores.mean()
        elif mode == "max":
            smoothed[i] = window_scores.max()
        else:
            raise ValueError("mode must be 'mean' or 'max'.")

    return smoothed


print("Temporal smoothing helper defined.")

Temporal smoothing helper defined.

In [ ]:
# ---------------- 25. Define one-clip temporal smoothing evaluation ----------------

def evaluate_one_clip_temporal_smoothing(
    clip_uid,
    alpha=0.75,
    window_size=5,
    smoothing_mode="mean",
    topk=100,
    tolerance_frames=TOLERANCE_FRAMES,
):
    """
    Evaluate alpha-fusion retrieval after temporal smoothing.

    Steps:
    1. Compute CLIP score
    2. Compute BLIP score
    3. Fuse scores
    4. Smooth fused scores across neighboring sampled index frames
    5. Rank frames by smoothed score
    """
    index_cache = load_index_cache(clip_uid)
    query_cache = load_query_cache(clip_uid)

    frame_numbers = index_cache["frame_numbers"]

    index_clip_embs = index_cache["clip_embs"]
    index_blip_embs = index_cache["blip_embs"]

    query_clip_embs = query_cache["clip_embs"]
    query_blip_embs = query_cache["blip_embs"]

    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for q_idx, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]

        clip_scores = compute_similarity_scores(index_clip_embs, query_clip_embs[q_idx])
        blip_scores = compute_similarity_scores(index_blip_embs, query_blip_embs[q_idx])

        fusion_scores = alpha * clip_scores + (1 - alpha) * blip_scores
        smoothed_scores = smooth_scores(
            fusion_scores,
            window_size=window_size,
            mode=smoothing_mode,
        )

        topk_df = get_topk_frames(frame_numbers, smoothed_scores, k=topk)

        rank = first_correct_rank(
            topk_df=topk_df,
            rt_min_frame=rt["rt_min_frame"],
            rt_max_frame=rt["rt_max_frame"],
            tolerance_frames=tolerance_frames,
        )

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "method": "temporal_smoothing",
            "alpha": alpha,
            "window_size": window_size,
            "smoothing_mode": smoothing_mode,
            "top1_frame": int(topk_df.iloc[0]["frame_number"]),
            "top1_score": float(topk_df.iloc[0]["score"]),
            "rt_min_frame": rt["rt_min_frame"],
            "rt_max_frame": rt["rt_max_frame"],
            "first_correct_rank": rank,
            "top1_success": bool(rank == 1),
            "top5_success": bool(pd.notna(rank) and rank <= 5),
            "top10_success": bool(pd.notna(rank) and rank <= 10),
            "top20_success": bool(pd.notna(rank) and rank <= 20),
            "top50_success": bool(pd.notna(rank) and rank <= 50),
            "top100_success": bool(pd.notna(rank) and rank <= 100),
        })

    return pd.DataFrame(rows)


print("Temporal smoothing evaluation function defined.")

Temporal smoothing evaluation function defined.

In [ ]:
# ---------------- 26. One-clip temporal smoothing sanity check ----------------

test_clip_uid = all_300_clip_uids[0]

smooth_test_df = evaluate_one_clip_temporal_smoothing(
    clip_uid=test_clip_uid,
    alpha=0.75,
    window_size=5,
    smoothing_mode="mean",
    topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(smooth_test_df))
display(smooth_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,window_size,smoothing_mode,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,temporal_smoothing,0.75,5,mean,43770,0.753529,42288.0,42317.0,78.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,temporal_smoothing,0.75,5,mean,43440,0.634601,46764.0,46770.0,NaN,False,False,False,False,False,False
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,temporal_smoothing,0.75,5,mean,43440,0.664668,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,temporal_smoothing,0.75,5,mean,44430,0.742072,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,temporal_smoothing,0.75,5,mean,43440,0.759456,42678.0,42690.0,NaN,False,False,False,False,False,False
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,temporal_smoothing,0.75,5,mean,44460,0.740068,43434.0,43441.0,11.0,False,False,False,True,True,True

In [ ]:
# ---------------- 27. Run temporal smoothing grid over 300 clips ----------------

smoothing_grid = []

alphas = [0.5, 0.75, 1.0]
window_sizes = [3, 5, 7]
smoothing_modes = ["mean", "max"]

for alpha in alphas:
    for window_size in window_sizes:
        for smoothing_mode in smoothing_modes:
            smoothing_grid.append({
                "alpha": alpha,
                "window_size": window_size,
                "smoothing_mode": smoothing_mode,
            })

print("Total smoothing settings:", len(smoothing_grid))
display(pd.DataFrame(smoothing_grid))

Total smoothing settings: 18

    alpha  window_size smoothing_mode
0    0.50            3           mean
1    0.50            3            max
2    0.50            5           mean
3    0.50            5            max
4    0.50            7           mean
5    0.50            7            max
6    0.75            3           mean
7    0.75            3            max
8    0.75            5           mean
9    0.75            5            max
10   0.75            7           mean
11   0.75            7            max
12   1.00            3           mean
13   1.00            3            max
14   1.00            5           mean
15   1.00            5            max
16   1.00            7           mean
17   1.00            7            max

In [ ]:
# ---------------- 28. Full temporal smoothing grid evaluation ----------------

smooth_rows = []

for cfg in smoothing_grid:
    alpha = cfg["alpha"]
    window_size = cfg["window_size"]
    smoothing_mode = cfg["smoothing_mode"]

    print("=" * 100)
    print(f"Running temporal smoothing | alpha={alpha} | window={window_size} | mode={smoothing_mode}")

    for clip_uid in tqdm(
        all_300_clip_uids,
        desc=f"a={alpha}, w={window_size}, {smoothing_mode}"
    ):
        df_one = evaluate_one_clip_temporal_smoothing(
            clip_uid=clip_uid,
            alpha=alpha,
            window_size=window_size,
            smoothing_mode=smoothing_mode,
            topk=100,
        )
        smooth_rows.append(df_one)

smooth_df = pd.concat(smooth_rows, ignore_index=True)

print("Temporal smoothing rows:", len(smooth_df))
print("Expected rows:", 1157 * len(smoothing_grid))

display(smooth_df.head())

smooth_path = RESULTS_DIR / f"temporal_smoothing_nclips{N_CLIPS}_top100.csv"
smooth_df.to_csv(smooth_path, index=False)

print("Saved temporal smoothing results to:", smooth_path)

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=3 | mode=mean

a=0.5, w=3, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=3 | mode=max

a=0.5, w=3, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=5 | mode=mean

a=0.5, w=5, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=5 | mode=max

a=0.5, w=5, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=7 | mode=mean

a=0.5, w=7, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.5 | window=7 | mode=max

a=0.5, w=7, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=3 | mode=mean

a=0.75, w=3, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=3 | mode=max

a=0.75, w=3, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=5 | mode=mean

a=0.75, w=5, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=5 | mode=max

a=0.75, w=5, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=7 | mode=mean

a=0.75, w=7, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=0.75 | window=7 | mode=max

a=0.75, w=7, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=3 | mode=mean

a=1.0, w=3, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=3 | mode=max

a=1.0, w=3, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=5 | mode=mean

a=1.0, w=5, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=5 | mode=max

a=1.0, w=5, max:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=7 | mode=mean

a=1.0, w=7, mean:   0%|          | 0/300 [00:00<?, ?it/s]

====================================================================================================
Running temporal smoothing | alpha=1.0 | window=7 | mode=max

a=1.0, w=7, max:   0%|          | 0/300 [00:00<?, ?it/s]

Temporal smoothing rows: 20826
Expected rows: 20826

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,window_size,smoothing_mode,top1_frame,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,temporal_smoothing,0.5,3,mean,42420,0.745986,42288.0,42317.0,74.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,temporal_smoothing,0.5,3,mean,41370,0.622939,46764.0,46770.0,37.0,False,False,False,False,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,temporal_smoothing,0.5,3,mean,41370,0.654436,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,temporal_smoothing,0.5,3,mean,43440,0.711185,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,temporal_smoothing,0.5,3,mean,41340,0.733470,42678.0,42690.0,70.0,False,False,False,False,False,True

Saved temporal smoothing results to: /home/jupyter/results/retrieval_subset/temporal_smoothing_nclips300_top100.csv

In [ ]:
# ---------------- 29. Summarize temporal smoothing results ----------------

metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

smooth_summary = (
    smooth_df
    .groupby(["alpha", "window_size", "smoothing_mode"])[metric_cols]
    .mean()
    .reset_index()
)

for col in metric_cols:
    smooth_summary[col] = smooth_summary[col] * 100

smooth_summary_sorted = smooth_summary.sort_values(
    ["top100_success", "top50_success", "top20_success", "top10_success"],
    ascending=False,
).reset_index(drop=True)

display(smooth_summary_sorted)

smooth_summary_path = RESULTS_DIR / f"temporal_smoothing_summary_nclips{N_CLIPS}_top100.csv"
smooth_summary_sorted.to_csv(smooth_summary_path, index=False)

print("Saved temporal smoothing summary to:", smooth_summary_path)

,alpha,window_size,smoothing_mode,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,0.50,7,max,0.777874,1.987900,3.630078,7.000864,14.606742,25.756266
1,0.50,3,max,0.432152,2.074330,4.062230,5.790838,13.396716,25.756266
2,0.75,3,max,0.172861,1.987900,4.321521,6.222990,13.396716,25.151253
3,0.75,5,max,0.259291,1.210026,2.938634,6.309421,12.705272,25.064823
4,0.50,5,max,0.518583,1.901469,3.889369,6.482282,13.137424,24.891962
5,0.75,7,max,0.172861,1.123596,3.284356,6.568712,13.569576,24.805532
6,1.00,3,max,0.172861,1.901469,3.457217,5.704408,13.310285,24.805532
7,0.50,3,mean,0.000000,1.210026,3.025065,5.012965,12.273120,24.805532
8,1.00,5,max,0.345722,1.382887,2.765774,5.531547,12.791703,24.459810
9,0.50,5,mean,0.259291,0.950735,2.247191,5.445117,11.668107,24.286949
10,0.75,3,mean,0.000000,0.950735,2.333621,4.580812,13.396716,24.114088
11,1.00,3,mean,0.172861,1.210026,2.333621,4.753673,12.791703,24.114088
12,1.00,7,max,0.518583,1.728608,2.938634,4.926534,12.273120,24.027658
13,0.75,5,mean,0.172861,0.950735,2.506482,4.580812,11.581677,23.768366
14,0.50,7,mean,0.259291,1.210026,2.679343,5.099395,12.186690,23.595506
15,1.00,5,mean,0.345722,1.210026,2.765774,5.185825,11.063094,23.076923
16,0.75,7,mean,0.259291,1.210026,3.025065,4.494382,12.705272,22.385480
17,1.00,7,mean,0.172861,1.555748,2.592913,4.753673,12.013829,22.212619

Saved temporal smoothing summary to: /home/jupyter/results/retrieval_subset/temporal_smoothing_summary_nclips300_top100.csv

## Temporal Smoothing Results

We evaluated temporal smoothing over fused CLIP/BLIP similarity scores using different alpha values, window sizes, and smoothing modes.

The best Top-100 performance is achieved by max smoothing with alpha = 0.50 and window size = 3 or 7, reaching approximately 25.76% Top-100 accuracy. This is close to, but does not exceed, the best alpha-fusion result of 25.84%.

However, temporal smoothing improves early-rank retrieval. The best Top-20 result increases to 7.00%, compared with around 5.45% from alpha fusion. This suggests that temporal smoothing helps promote correct frames when they are already near strong candidates, but it does not substantially improve overall candidate recall.

Max smoothing consistently performs better than mean smoothing. This likely happens because response tracks can be short, and averaging across neighboring frames may dilute sharp local similarity peaks. Max smoothing preserves these local peaks better.

Overall, temporal smoothing is useful as a lightweight reranking strategy, especially for improving Top-10 and Top-20 performance, but it does not solve the broader recall gap between the 66.98% ground-truth coverage upper bound and the roughly 25% Top-100 retrieval performance.

In [ ]:
# ---------------- 30 fixed. Candidate-guided window reranking ----------------

def evaluate_one_clip_candidate_window(
    clip_uid,
    alpha=0.5,
    candidate_topk=20,
    window_radius=2,
    score_mode="max",
    final_topk=100,
    tolerance_frames=TOLERANCE_FRAMES,
):
    """
    Candidate-guided window reranking.

    Steps:
    1. Compute CLIP and BLIP similarity scores.
    2. Fuse scores.
    3. Select top candidate_topk frames as anchors.
    4. Expand around each anchor by +/- window_radius index positions.
    5. Aggregate scores for frames in candidate windows.
    6. Rank expanded candidate frames by aggregated score.
    """

    index_cache = load_index_cache(clip_uid)
    query_cache = load_query_cache(clip_uid)

    frame_numbers = index_cache["frame_numbers"]

    index_clip_embs = index_cache["clip_embs"]
    index_blip_embs = index_cache["blip_embs"]

    query_clip_embs = query_cache["clip_embs"]
    query_blip_embs = query_cache["blip_embs"]

    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for q_idx, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]

        clip_scores = compute_similarity_scores(index_clip_embs, query_clip_embs[q_idx])
        blip_scores = compute_similarity_scores(index_blip_embs, query_blip_embs[q_idx])

        fusion_scores = alpha * clip_scores + (1 - alpha) * blip_scores

        candidate_topk_actual = min(candidate_topk, len(fusion_scores))
        anchor_indices = np.argsort(-fusion_scores)[:candidate_topk_actual]

        expanded_scores = {}

        for anchor_idx in anchor_indices:
            start = max(0, anchor_idx - window_radius)
            end = min(len(fusion_scores), anchor_idx + window_radius + 1)

            for idx in range(start, end):
                if idx not in expanded_scores:
                    expanded_scores[idx] = []
                expanded_scores[idx].append(float(fusion_scores[idx]))

        rerank_rows = []

        for idx, score_list in expanded_scores.items():
            if score_mode == "max":
                agg_score = max(score_list)
            elif score_mode == "mean":
                agg_score = float(np.mean(score_list))
            else:
                raise ValueError("score_mode must be 'max' or 'mean'.")

            rerank_rows.append({
                "frame_number": int(frame_numbers[idx]),
                "score": agg_score,
                "index_position": int(idx),
            })

        topk_df = (
            pd.DataFrame(rerank_rows)
            .sort_values("score", ascending=False)
            .head(final_topk)
            .reset_index(drop=True)
        )

        # Important: first_correct_rank() expects a rank column
        topk_df["rank"] = np.arange(1, len(topk_df) + 1)

        rank = first_correct_rank(
            topk_df=topk_df,
            rt_min_frame=rt["rt_min_frame"],
            rt_max_frame=rt["rt_max_frame"],
            tolerance_frames=tolerance_frames,
        )

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "method": "candidate_window",
            "alpha": alpha,
            "candidate_topk": candidate_topk,
            "window_radius": window_radius,
            "score_mode": score_mode,
            "num_expanded_frames": len(topk_df),
            "top1_frame": int(topk_df.iloc[0]["frame_number"]),
            "top1_score": float(topk_df.iloc[0]["score"]),
            "rt_min_frame": rt["rt_min_frame"],
            "rt_max_frame": rt["rt_max_frame"],
            "first_correct_rank": rank,
            "top1_success": bool(rank == 1),
            "top5_success": bool(pd.notna(rank) and rank <= 5),
            "top10_success": bool(pd.notna(rank) and rank <= 10),
            "top20_success": bool(pd.notna(rank) and rank <= 20),
            "top50_success": bool(pd.notna(rank) and rank <= 50),
            "top100_success": bool(pd.notna(rank) and rank <= 100),
        })

    return pd.DataFrame(rows)


print("Fixed candidate-guided window reranking function defined.")

Fixed candidate-guided window reranking function defined.

In [ ]:
# ---------------- 31. One-clip candidate-window sanity check ----------------

test_clip_uid = all_300_clip_uids[0]

candidate_test_df = evaluate_one_clip_candidate_window(
    clip_uid=test_clip_uid,
    alpha=0.5,
    candidate_topk=20,
    window_radius=2,
    score_mode="max",
    final_topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(candidate_test_df))
display(candidate_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,candidate_topk,window_radius,score_mode,num_expanded_frames,...,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,candidate_window,0.5,20,2,max,41,...,0.774597,42288.0,42317.0,NaN,False,False,False,False,False,False
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,candidate_window,0.5,20,2,max,65,...,0.708696,46764.0,46770.0,3.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,candidate_window,0.5,20,2,max,78,...,0.714960,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,candidate_window,0.5,20,2,max,73,...,0.777815,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,candidate_window,0.5,20,2,max,78,...,0.786738,42678.0,42690.0,NaN,False,False,False,False,False,False
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,candidate_window,0.5,20,2,max,67,...,0.780019,43434.0,43441.0,42.0,False,False,False,False,True,True

In [ ]:
# ---------------- 32. Define candidate-window grid ----------------

candidate_grid = []

alphas = [0.5, 0.75]
candidate_topks = [20, 50, 100]
window_radii = [1, 2, 3, 5]
score_modes = ["max"]

for alpha in alphas:
    for candidate_topk in candidate_topks:
        for window_radius in window_radii:
            for score_mode in score_modes:
                candidate_grid.append({
                    "alpha": alpha,
                    "candidate_topk": candidate_topk,
                    "window_radius": window_radius,
                    "score_mode": score_mode,
                })

candidate_grid_df = pd.DataFrame(candidate_grid)

print("Total candidate-window settings:", len(candidate_grid_df))
display(candidate_grid_df)

Total candidate-window settings: 24

    alpha  candidate_topk  window_radius score_mode
0    0.50              20              1        max
1    0.50              20              2        max
2    0.50              20              3        max
3    0.50              20              5        max
4    0.50              50              1        max
5    0.50              50              2        max
6    0.50              50              3        max
7    0.50              50              5        max
8    0.50             100              1        max
9    0.50             100              2        max
10   0.50             100              3        max
11   0.50             100              5        max
12   0.75              20              1        max
13   0.75              20              2        max
14   0.75              20              3        max
15   0.75              20              5        max
16   0.75              50              1        max
17   0.75              50              2        max
18   0.75              50              3        max
19   0.75              50              5        max
20   0.75             100              1        max
21   0.75             100              2        max
22   0.75             100              3        max
23   0.75             100              5        max

In [ ]:
# ---------------- 33. Run candidate-window grid safely ----------------

CANDIDATE_RESULT_DIR = RESULTS_DIR / "candidate_window_results"
CANDIDATE_RESULT_DIR.mkdir(parents=True, exist_ok=True)

print("Candidate result dir:", CANDIDATE_RESULT_DIR)

all_candidate_result_paths = []

for cfg_idx, cfg in enumerate(candidate_grid):
    alpha = cfg["alpha"]
    candidate_topk = cfg["candidate_topk"]
    window_radius = cfg["window_radius"]
    score_mode = cfg["score_mode"]

    cfg_name = (
        f"candidate_window_"
        f"alpha{alpha}_"
        f"topk{candidate_topk}_"
        f"radius{window_radius}_"
        f"{score_mode}_"
        f"nclips{N_CLIPS}.csv"
    )

    cfg_path = CANDIDATE_RESULT_DIR / cfg_name
    all_candidate_result_paths.append(cfg_path)

    print("=" * 100)
    print(f"[{cfg_idx + 1}/{len(candidate_grid)}] Running:", cfg)
    print("Save path:", cfg_path)

    # Skip if already completed
    if cfg_path.exists():
        existing_df = pd.read_csv(cfg_path)
        if len(existing_df) == 1157:
            print("Already completed. Skipping.")
            continue
        else:
            print("Existing file incomplete. Recomputing:", len(existing_df))

    cfg_rows = []

    for clip_uid in tqdm(
        all_300_clip_uids,
        desc=f"a={alpha}, topk={candidate_topk}, r={window_radius}"
    ):
        df_one = evaluate_one_clip_candidate_window(
            clip_uid=clip_uid,
            alpha=alpha,
            candidate_topk=candidate_topk,
            window_radius=window_radius,
            score_mode=score_mode,
            final_topk=100,
        )
        cfg_rows.append(df_one)

    cfg_df = pd.concat(cfg_rows, ignore_index=True)

    print("Rows:", len(cfg_df))
    cfg_df.to_csv(cfg_path, index=False)
    print("Saved:", cfg_path)

print("All candidate-window config runs finished or skipped.")

Candidate result dir: /home/jupyter/results/retrieval_subset/candidate_window_results
====================================================================================================
[1/24] Running: {'alpha': 0.5, 'candidate_topk': 20, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk20_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[2/24] Running: {'alpha': 0.5, 'candidate_topk': 20, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk20_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[3/24] Running: {'alpha': 0.5, 'candidate_topk': 20, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk20_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[4/24] Running: {'alpha': 0.5, 'candidate_topk': 20, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk20_radius5_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[5/24] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk50_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[6/24] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk50_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[7/24] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk50_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[8/24] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk50_radius5_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[9/24] Running: {'alpha': 0.5, 'candidate_topk': 100, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk100_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[10/24] Running: {'alpha': 0.5, 'candidate_topk': 100, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk100_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[11/24] Running: {'alpha': 0.5, 'candidate_topk': 100, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk100_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[12/24] Running: {'alpha': 0.5, 'candidate_topk': 100, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.5_topk100_radius5_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[13/24] Running: {'alpha': 0.75, 'candidate_topk': 20, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk20_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[14/24] Running: {'alpha': 0.75, 'candidate_topk': 20, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk20_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[15/24] Running: {'alpha': 0.75, 'candidate_topk': 20, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk20_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[16/24] Running: {'alpha': 0.75, 'candidate_topk': 20, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk20_radius5_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[17/24] Running: {'alpha': 0.75, 'candidate_topk': 50, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk50_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[18/24] Running: {'alpha': 0.75, 'candidate_topk': 50, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk50_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[19/24] Running: {'alpha': 0.75, 'candidate_topk': 50, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk50_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[20/24] Running: {'alpha': 0.75, 'candidate_topk': 50, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk50_radius5_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[21/24] Running: {'alpha': 0.75, 'candidate_topk': 100, 'window_radius': 1, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk100_radius1_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[22/24] Running: {'alpha': 0.75, 'candidate_topk': 100, 'window_radius': 2, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk100_radius2_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[23/24] Running: {'alpha': 0.75, 'candidate_topk': 100, 'window_radius': 3, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk100_radius3_max_nclips300.csv
Already completed. Skipping.
====================================================================================================
[24/24] Running: {'alpha': 0.75, 'candidate_topk': 100, 'window_radius': 5, 'score_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_window_results/candidate_window_alpha0.75_topk100_radius5_max_nclips300.csv
Already completed. Skipping.
All candidate-window config runs finished or skipped.

In [ ]:
# ---------------- 34. Combine candidate-window results and summarize ----------------

candidate_result_files = sorted(CANDIDATE_RESULT_DIR.glob("candidate_window_*.csv"))

print("Candidate result files:", len(candidate_result_files))
for p in candidate_result_files[:5]:
    print(p.name)

candidate_dfs = []

for p in candidate_result_files:
    df = pd.read_csv(p)
    candidate_dfs.append(df)

candidate_df = pd.concat(candidate_dfs, ignore_index=True)

print("Combined candidate-window rows:", len(candidate_df))
print("Expected rows:", 1157 * len(candidate_result_files))

display(candidate_df.head())

candidate_all_path = RESULTS_DIR / f"candidate_window_all_nclips{N_CLIPS}_top100.csv"
candidate_df.to_csv(candidate_all_path, index=False)

print("Saved combined candidate-window results to:", candidate_all_path)


metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

candidate_summary = (
    candidate_df
    .groupby(["alpha", "candidate_topk", "window_radius", "score_mode"])[metric_cols]
    .mean()
    .reset_index()
)

for col in metric_cols:
    candidate_summary[col] = candidate_summary[col] * 100

candidate_summary_sorted = candidate_summary.sort_values(
    ["top100_success", "top50_success", "top20_success", "top10_success"],
    ascending=False,
).reset_index(drop=True)

display(candidate_summary_sorted)

candidate_summary_path = RESULTS_DIR / f"candidate_window_summary_nclips{N_CLIPS}_top100.csv"
candidate_summary_sorted.to_csv(candidate_summary_path, index=False)

print("Saved candidate-window summary to:", candidate_summary_path)

Candidate result files: 24
candidate_window_alpha0.5_topk100_radius1_max_nclips300.csv
candidate_window_alpha0.5_topk100_radius2_max_nclips300.csv
candidate_window_alpha0.5_topk100_radius3_max_nclips300.csv
candidate_window_alpha0.5_topk100_radius5_max_nclips300.csv
candidate_window_alpha0.5_topk20_radius1_max_nclips300.csv
Combined candidate-window rows: 27768
Expected rows: 27768

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,candidate_topk,window_radius,score_mode,num_expanded_frames,...,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,candidate_window,0.5,100,1,max,100,...,0.774597,42288.0,42317.0,71.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,candidate_window,0.5,100,1,max,100,...,0.708696,46764.0,46770.0,3.0,False,True,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,candidate_window,0.5,100,1,max,100,...,0.714960,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,candidate_window,0.5,100,1,max,100,...,0.777815,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,candidate_window,0.5,100,1,max,100,...,0.786738,42678.0,42690.0,34.0,False,False,False,False,True,True

Saved combined candidate-window results to: /home/jupyter/results/retrieval_subset/candidate_window_all_nclips300_top100.csv

,alpha,candidate_topk,window_radius,score_mode,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,0.50,50,5,max,0.605013,1.728608,2.765774,5.445117,13.828868,26.620570
1,0.75,50,5,max,0.432152,1.901469,3.025065,5.445117,14.174589,26.274849
2,0.50,100,1,max,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
3,0.50,100,2,max,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
4,0.50,100,3,max,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
5,0.50,100,5,max,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
6,0.50,20,5,max,0.605013,1.728608,2.765774,5.445117,14.520311,25.583405
7,0.75,100,1,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.496975
8,0.75,100,2,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.496975
9,0.75,100,3,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.496975
10,0.75,100,5,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.496975
11,0.75,50,3,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.410545
12,0.75,20,5,max,0.432152,1.901469,3.025065,5.445117,14.952463,25.324114
13,0.75,50,2,max,0.432152,1.901469,3.025065,5.445117,14.174589,25.151253
14,0.50,50,3,max,0.605013,1.728608,2.765774,5.445117,13.828868,24.891962
15,0.50,50,1,max,0.605013,1.728608,2.765774,5.445117,13.828868,24.632671
16,0.50,50,2,max,0.605013,1.728608,2.765774,5.445117,13.828868,24.114088
17,0.75,50,1,max,0.432152,1.901469,3.025065,5.445117,14.174589,24.027658
18,0.50,20,3,max,0.605013,1.728608,2.765774,5.445117,13.656007,21.434745
19,0.75,20,3,max,0.432152,1.901469,3.025065,5.445117,13.396716,20.570441
20,0.50,20,2,max,0.605013,1.728608,2.765774,5.445117,12.791703,16.940363
21,0.75,20,2,max,0.432152,1.901469,3.025065,5.445117,12.705272,16.508211
22,0.75,20,1,max,0.432152,1.901469,3.025065,5.445117,12.186690,12.273120
23,0.50,20,1,max,0.605013,1.728608,2.765774,5.445117,11.754538,12.100259

Saved candidate-window summary to: /home/jupyter/results/retrieval_subset/candidate_window_summary_nclips300_top100.csv

## Candidate-Guided Window Reranking Results

We evaluated candidate-guided window reranking over 24 configurations using different CLIP/BLIP fusion weights, candidate anchor sizes, and temporal window radii.

The best Top-100 performance was achieved with:

- alpha = 0.50
- candidate_topk = 50
- window_radius = 5
- score_mode = max

This configuration achieved approximately 26.62% Top-100 accuracy, which improves over the previous best alpha-fusion result of 25.84% and the best temporal smoothing result of 25.76%.

However, candidate-window reranking did not improve early-rank retrieval as much as temporal smoothing. Its Top-20 accuracy remains around 5.45%, while temporal smoothing reached approximately 7.00% Top-20 accuracy. This suggests that candidate-window expansion is more useful for improving candidate recall than for pushing correct frames into the very top ranks.

Overall, candidate-guided window reranking is the best current method for Top-100 retrieval, while temporal smoothing remains useful for early-rank improvement.

In [ ]:
# ---------------- 35. Final comparison across methods ----------------

# Load saved summaries if needed
baseline_summary_path = RESULTS_DIR / f"baseline_summary_nclips{N_CLIPS}_top100.csv"
alpha_summary_path = RESULTS_DIR / f"alpha_fusion_summary_nclips{N_CLIPS}_top100.csv"
temporal_summary_path = RESULTS_DIR / f"temporal_smoothing_summary_nclips{N_CLIPS}_top100.csv"
candidate_summary_path = RESULTS_DIR / f"candidate_window_summary_nclips{N_CLIPS}_top100.csv"

print("Checking summary files:")
for p in [
    baseline_summary_path,
    alpha_summary_path,
    temporal_summary_path,
    candidate_summary_path,
]:
    print(p.name, "| exists:", p.exists())

baseline_summary = pd.read_csv(baseline_summary_path)
alpha_summary = pd.read_csv(alpha_summary_path)
temporal_summary = pd.read_csv(temporal_summary_path)
candidate_summary = pd.read_csv(candidate_summary_path)

metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

# Baseline: keep CLIP and BLIP rows
baseline_rows = baseline_summary.copy()
baseline_rows["method"] = baseline_rows["model_name"] + "_baseline"
baseline_rows["setting"] = baseline_rows["model_name"]

baseline_rows = baseline_rows[
    ["method", "setting"] + metric_cols
]

# Alpha fusion: best by top100
alpha_best = (
    alpha_summary
    .sort_values(["top100_success", "top50_success", "top20_success", "top10_success"], ascending=False)
    .head(1)
    .copy()
)
alpha_best["method"] = "alpha_fusion"
alpha_best["setting"] = alpha_best.apply(
    lambda r: f"alpha={r['alpha']}",
    axis=1,
)
alpha_best = alpha_best[["method", "setting"] + metric_cols]

# Temporal smoothing: best by top100
temporal_best = (
    temporal_summary
    .sort_values(["top100_success", "top50_success", "top20_success", "top10_success"], ascending=False)
    .head(1)
    .copy()
)
temporal_best["method"] = "temporal_smoothing"
temporal_best["setting"] = temporal_best.apply(
    lambda r: (
        f"alpha={r['alpha']}, "
        f"window={int(r['window_size'])}, "
        f"mode={r['smoothing_mode']}"
    ),
    axis=1,
)
temporal_best = temporal_best[["method", "setting"] + metric_cols]

# Candidate-window: best by top100
candidate_best = (
    candidate_summary
    .sort_values(["top100_success", "top50_success", "top20_success", "top10_success"], ascending=False)
    .head(1)
    .copy()
)
candidate_best["method"] = "candidate_window"
candidate_best["setting"] = candidate_best.apply(
    lambda r: (
        f"alpha={r['alpha']}, "
        f"candidate_topk={int(r['candidate_topk'])}, "
        f"radius={int(r['window_radius'])}, "
        f"mode={r['score_mode']}"
    ),
    axis=1,
)
candidate_best = candidate_best[["method", "setting"] + metric_cols]

# Combine
final_comparison = pd.concat(
    [
        baseline_rows,
        alpha_best,
        temporal_best,
        candidate_best,
    ],
    ignore_index=True,
)

# Sort by top100
final_comparison = final_comparison.sort_values(
    ["top100_success", "top50_success", "top20_success", "top10_success"],
    ascending=False,
).reset_index(drop=True)

display(final_comparison)

final_comparison_path = RESULTS_DIR / f"final_method_comparison_nclips{N_CLIPS}_top100.csv"
final_comparison.to_csv(final_comparison_path, index=False)

print("Saved final comparison to:", final_comparison_path)

Checking summary files:
baseline_summary_nclips300_top100.csv | exists: True
alpha_fusion_summary_nclips300_top100.csv | exists: True
temporal_smoothing_summary_nclips300_top100.csv | exists: True
candidate_window_summary_nclips300_top100.csv | exists: True

,method,setting,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,candidate_window,"alpha=0.5, candidate_topk=50, radius=5, mode=max",0.605013,1.728608,2.765774,5.445117,13.828868,26.620570
1,alpha_fusion,alpha=0.5,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
2,temporal_smoothing,"alpha=0.5, window=7, mode=max",0.777874,1.987900,3.630078,7.000864,14.606742,25.756266
3,blip_baseline,blip,0.518583,1.469317,2.852204,5.617978,13.569576,25.669836
4,clip_baseline,clip,0.518583,1.728608,2.938634,5.272256,15.038894,24.978392

Saved final comparison to: /home/jupyter/results/retrieval_subset/final_method_comparison_nclips300_top100.csv

## Final Method Comparison

Among all tested retrieval strategies, candidate-guided window reranking achieved the best Top-100 performance. The best configuration used alpha = 0.5, candidate_topk = 50, window_radius = 5, and max aggregation. It reached 26.62% Top-100 accuracy, improving over the best alpha-fusion baseline of 25.84%.

Temporal smoothing did not achieve the best Top-100 performance, but it produced the strongest early-rank performance, reaching 3.63% Top-10 and 7.00% Top-20 accuracy. This suggests that temporal smoothing can help promote correct frames toward the top ranks, while candidate-guided window reranking is more effective for expanding the candidate set.

Overall, candidate-window reranking is selected as the main final method for Top-100 retrieval, while temporal smoothing provides a useful secondary insight for early-rank improvement.

In [ ]:
# ---------------- 36. Candidate-window + local temporal smoothing ----------------

def evaluate_one_clip_candidate_local_smoothing(
    clip_uid,
    alpha=0.5,
    candidate_topk=50,
    window_radius=5,
    local_smooth_radius=2,
    smooth_mode="max",
    final_topk=100,
    tolerance_frames=TOLERANCE_FRAMES,
):
    """
    Hybrid method:
    1. Compute CLIP/BLIP fusion scores.
    2. Select top candidate_topk anchor frames.
    3. Expand each anchor by +/- window_radius index positions.
    4. Only within expanded candidate frames, apply local temporal smoothing.
    5. Rank by locally smoothed scores.
    """

    index_cache = load_index_cache(clip_uid)
    query_cache = load_query_cache(clip_uid)

    frame_numbers = index_cache["frame_numbers"]

    index_clip_embs = index_cache["clip_embs"]
    index_blip_embs = index_cache["blip_embs"]

    query_clip_embs = query_cache["clip_embs"]
    query_blip_embs = query_cache["blip_embs"]

    qmeta = query_cache["query_metadata"].copy()
    qmeta["clip_uid"] = qmeta["clip_uid"].astype(str)
    qmeta["annotation_uid"] = qmeta["annotation_uid"].astype(str)
    qmeta["qs_id"] = qmeta["qs_id"].astype(int)

    rows = []

    for q_idx, qrow in qmeta.iterrows():
        key = (
            str(qrow["clip_uid"]),
            str(qrow["annotation_uid"]),
            int(qrow["qs_id"]),
        )

        if key not in rt_lookup:
            continue

        rt = rt_lookup[key]

        clip_scores = compute_similarity_scores(index_clip_embs, query_clip_embs[q_idx])
        blip_scores = compute_similarity_scores(index_blip_embs, query_blip_embs[q_idx])

        fusion_scores = alpha * clip_scores + (1 - alpha) * blip_scores

        # 1. Candidate anchors
        candidate_topk_actual = min(candidate_topk, len(fusion_scores))
        anchor_indices = np.argsort(-fusion_scores)[:candidate_topk_actual]

        # 2. Expanded candidate index set
        expanded_indices = set()

        for anchor_idx in anchor_indices:
            start = max(0, anchor_idx - window_radius)
            end = min(len(fusion_scores), anchor_idx + window_radius + 1)

            for idx in range(start, end):
                expanded_indices.add(idx)

        expanded_indices = sorted(expanded_indices)

        # 3. Local smoothing only for expanded indices
        rerank_rows = []

        for idx in expanded_indices:
            smooth_start = max(0, idx - local_smooth_radius)
            smooth_end = min(len(fusion_scores), idx + local_smooth_radius + 1)

            local_scores = fusion_scores[smooth_start:smooth_end]

            if smooth_mode == "max":
                smoothed_score = float(np.max(local_scores))
            elif smooth_mode == "mean":
                smoothed_score = float(np.mean(local_scores))
            else:
                raise ValueError("smooth_mode must be 'max' or 'mean'.")

            rerank_rows.append({
                "frame_number": int(frame_numbers[idx]),
                "score": smoothed_score,
                "index_position": int(idx),
            })

        topk_df = (
            pd.DataFrame(rerank_rows)
            .sort_values("score", ascending=False)
            .head(final_topk)
            .reset_index(drop=True)
        )

        topk_df["rank"] = np.arange(1, len(topk_df) + 1)

        rank = first_correct_rank(
            topk_df=topk_df,
            rt_min_frame=rt["rt_min_frame"],
            rt_max_frame=rt["rt_max_frame"],
            tolerance_frames=tolerance_frames,
        )

        rows.append({
            "clip_uid": clip_uid,
            "annotation_uid": qrow["annotation_uid"],
            "qs_id": int(qrow["qs_id"]),
            "object_title": qrow["object_title"],
            "method": "candidate_local_smoothing",
            "alpha": alpha,
            "candidate_topk": candidate_topk,
            "window_radius": window_radius,
            "local_smooth_radius": local_smooth_radius,
            "smooth_mode": smooth_mode,
            "num_expanded_frames": len(expanded_indices),
            "top1_frame": int(topk_df.iloc[0]["frame_number"]),
            "top1_score": float(topk_df.iloc[0]["score"]),
            "rt_min_frame": rt["rt_min_frame"],
            "rt_max_frame": rt["rt_max_frame"],
            "first_correct_rank": rank,
            "top1_success": bool(rank == 1),
            "top5_success": bool(pd.notna(rank) and rank <= 5),
            "top10_success": bool(pd.notna(rank) and rank <= 10),
            "top20_success": bool(pd.notna(rank) and rank <= 20),
            "top50_success": bool(pd.notna(rank) and rank <= 50),
            "top100_success": bool(pd.notna(rank) and rank <= 100),
        })

    return pd.DataFrame(rows)


print("Candidate-window + local smoothing function defined.")

Candidate-window + local smoothing function defined.

In [ ]:
# ---------------- 37. One-clip candidate-local-smoothing sanity check ----------------

test_clip_uid = all_300_clip_uids[0]

hybrid_test_df = evaluate_one_clip_candidate_local_smoothing(
    clip_uid=test_clip_uid,
    alpha=0.5,
    candidate_topk=50,
    window_radius=5,
    local_smooth_radius=2,
    smooth_mode="max",
    final_topk=100,
)

print("Test clip:", test_clip_uid)
print("Rows:", len(hybrid_test_df))
display(hybrid_test_df)

Test clip: dfe962ab-6aa7-4888-9378-796817a30ab6
Rows: 6

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,candidate_topk,window_radius,local_smooth_radius,smooth_mode,...,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,candidate_local_smoothing,0.5,50,5,2,max,...,0.774597,42288.0,42317.0,42.0,False,False,False,False,True,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,candidate_local_smoothing,0.5,50,5,2,max,...,0.708696,46764.0,46770.0,14.0,False,False,False,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,candidate_local_smoothing,0.5,50,5,2,max,...,0.714960,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,candidate_local_smoothing,0.5,50,5,2,max,...,0.777815,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,candidate_local_smoothing,0.5,50,5,2,max,...,0.786738,42678.0,42690.0,NaN,False,False,False,False,False,False
5,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,1,stool,candidate_local_smoothing,0.5,50,5,2,max,...,0.780019,43434.0,43441.0,9.0,False,False,True,True,True,True

In [ ]:
# ---------------- 38. Define hybrid candidate-local-smoothing grid ----------------

hybrid_grid = []

local_smooth_radii = [1, 2, 3, 5]
smooth_modes = ["max", "mean"]

for local_smooth_radius in local_smooth_radii:
    for smooth_mode in smooth_modes:
        hybrid_grid.append({
            "alpha": 0.5,
            "candidate_topk": 50,
            "window_radius": 5,
            "local_smooth_radius": local_smooth_radius,
            "smooth_mode": smooth_mode,
        })

hybrid_grid_df = pd.DataFrame(hybrid_grid)

print("Total hybrid settings:", len(hybrid_grid_df))
display(hybrid_grid_df)

Total hybrid settings: 8

   alpha  candidate_topk  window_radius  local_smooth_radius smooth_mode
0    0.5              50              5                    1         max
1    0.5              50              5                    1        mean
2    0.5              50              5                    2         max
3    0.5              50              5                    2        mean
4    0.5              50              5                    3         max
5    0.5              50              5                    3        mean
6    0.5              50              5                    5         max
7    0.5              50              5                    5        mean

In [ ]:
# ---------------- 39. Run hybrid candidate-local-smoothing grid safely ----------------

HYBRID_RESULT_DIR = RESULTS_DIR / "candidate_local_smoothing_results"
HYBRID_RESULT_DIR.mkdir(parents=True, exist_ok=True)

print("Hybrid result dir:", HYBRID_RESULT_DIR)

all_hybrid_result_paths = []

for cfg_idx, cfg in enumerate(hybrid_grid):
    alpha = cfg["alpha"]
    candidate_topk = cfg["candidate_topk"]
    window_radius = cfg["window_radius"]
    local_smooth_radius = cfg["local_smooth_radius"]
    smooth_mode = cfg["smooth_mode"]

    cfg_name = (
        f"candidate_local_smoothing_"
        f"alpha{alpha}_"
        f"topk{candidate_topk}_"
        f"radius{window_radius}_"
        f"localsmooth{local_smooth_radius}_"
        f"{smooth_mode}_"
        f"nclips{N_CLIPS}.csv"
    )

    cfg_path = HYBRID_RESULT_DIR / cfg_name
    all_hybrid_result_paths.append(cfg_path)

    print("=" * 100)
    print(f"[{cfg_idx + 1}/{len(hybrid_grid)}] Running:", cfg)
    print("Save path:", cfg_path)

    # Skip if already completed
    if cfg_path.exists():
        existing_df = pd.read_csv(cfg_path)
        if len(existing_df) == 1157:
            print("Already completed. Skipping.")
            continue
        else:
            print("Existing file incomplete. Recomputing:", len(existing_df))

    cfg_rows = []

    for clip_uid in tqdm(
        all_300_clip_uids,
        desc=f"local={local_smooth_radius}, mode={smooth_mode}"
    ):
        df_one = evaluate_one_clip_candidate_local_smoothing(
            clip_uid=clip_uid,
            alpha=alpha,
            candidate_topk=candidate_topk,
            window_radius=window_radius,
            local_smooth_radius=local_smooth_radius,
            smooth_mode=smooth_mode,
            final_topk=100,
        )
        cfg_rows.append(df_one)

    cfg_df = pd.concat(cfg_rows, ignore_index=True)

    print("Rows:", len(cfg_df))
    cfg_df.to_csv(cfg_path, index=False)
    print("Saved:", cfg_path)

print("All hybrid candidate-local-smoothing config runs finished or skipped.")

Hybrid result dir: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results
====================================================================================================
[1/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 1, 'smooth_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_max_nclips300.csv

local=1, mode=max:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_max_nclips300.csv
====================================================================================================
[2/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 1, 'smooth_mode': 'mean'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_mean_nclips300.csv

local=1, mode=mean:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_mean_nclips300.csv
====================================================================================================
[3/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 2, 'smooth_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_max_nclips300.csv

local=2, mode=max:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_max_nclips300.csv
====================================================================================================
[4/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 2, 'smooth_mode': 'mean'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_mean_nclips300.csv

local=2, mode=mean:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_mean_nclips300.csv
====================================================================================================
[5/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 3, 'smooth_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_max_nclips300.csv

local=3, mode=max:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_max_nclips300.csv
====================================================================================================
[6/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 3, 'smooth_mode': 'mean'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_mean_nclips300.csv

local=3, mode=mean:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_mean_nclips300.csv
====================================================================================================
[7/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 5, 'smooth_mode': 'max'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_max_nclips300.csv

local=5, mode=max:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_max_nclips300.csv
====================================================================================================
[8/8] Running: {'alpha': 0.5, 'candidate_topk': 50, 'window_radius': 5, 'local_smooth_radius': 5, 'smooth_mode': 'mean'}
Save path: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_mean_nclips300.csv

local=5, mode=mean:   0%|          | 0/300 [00:00<?, ?it/s]

Rows: 1157
Saved: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_results/candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_mean_nclips300.csv
All hybrid candidate-local-smoothing config runs finished or skipped.

In [ ]:
# ---------------- 40. Combine hybrid results and summarize ----------------

hybrid_result_files = sorted(HYBRID_RESULT_DIR.glob("candidate_local_smoothing_*.csv"))

print("Hybrid result files:", len(hybrid_result_files))
for p in hybrid_result_files:
    print(p.name)

hybrid_dfs = []

for p in hybrid_result_files:
    df = pd.read_csv(p)
    hybrid_dfs.append(df)

hybrid_df = pd.concat(hybrid_dfs, ignore_index=True)

print("Combined hybrid rows:", len(hybrid_df))
print("Expected rows:", 1157 * len(hybrid_result_files))

display(hybrid_df.head())

hybrid_all_path = RESULTS_DIR / f"candidate_local_smoothing_all_nclips{N_CLIPS}_top100.csv"
hybrid_df.to_csv(hybrid_all_path, index=False)

print("Saved combined hybrid results to:", hybrid_all_path)


metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

hybrid_summary = (
    hybrid_df
    .groupby([
        "alpha",
        "candidate_topk",
        "window_radius",
        "local_smooth_radius",
        "smooth_mode",
    ])[metric_cols]
    .mean()
    .reset_index()
)

for col in metric_cols:
    hybrid_summary[col] = hybrid_summary[col] * 100

hybrid_summary_sorted = hybrid_summary.sort_values(
    ["top100_success", "top50_success", "top20_success", "top10_success"],
    ascending=False,
).reset_index(drop=True)

display(hybrid_summary_sorted)

hybrid_summary_path = RESULTS_DIR / f"candidate_local_smoothing_summary_nclips{N_CLIPS}_top100.csv"
hybrid_summary_sorted.to_csv(hybrid_summary_path, index=False)

print("Saved hybrid summary to:", hybrid_summary_path)

Hybrid result files: 8
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_max_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth1_mean_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_max_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth2_mean_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_max_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth3_mean_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_max_nclips300.csv
candidate_local_smoothing_alpha0.5_topk50_radius5_localsmooth5_mean_nclips300.csv
Combined hybrid rows: 9256
Expected rows: 9256

,clip_uid,annotation_uid,qs_id,object_title,method,alpha,candidate_topk,window_radius,local_smooth_radius,smooth_mode,...,top1_score,rt_min_frame,rt_max_frame,first_correct_rank,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,2,portable fan,candidate_local_smoothing,0.5,50,5,1,max,...,0.774597,42288.0,42317.0,98.0,False,False,False,False,False,True
1,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,3,tube,candidate_local_smoothing,0.5,50,5,1,max,...,0.708696,46764.0,46770.0,9.0,False,False,True,True,True,True
2,dfe962ab-6aa7-4888-9378-796817a30ab6,3b057788-ad90-432d-90ff-de1c45361df6,1,green bowl,candidate_local_smoothing,0.5,50,5,1,max,...,0.714960,49488.0,49536.0,NaN,False,False,False,False,False,False
3,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,2,stool,candidate_local_smoothing,0.5,50,5,1,max,...,0.777815,49494.0,49511.0,NaN,False,False,False,False,False,False
4,dfe962ab-6aa7-4888-9378-796817a30ab6,dc29a4cf-1430-43fe-98d2-156ca2b303cf,3,bucket,candidate_local_smoothing,0.5,50,5,1,max,...,0.786738,42678.0,42690.0,79.0,False,False,False,False,False,True

Saved combined hybrid results to: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_all_nclips300_top100.csv

,alpha,candidate_topk,window_radius,local_smooth_radius,smooth_mode,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,0.5,50,5,5,max,0.518583,2.074330,3.457217,7.692308,16.853933,27.917027
1,0.5,50,5,1,max,0.345722,2.074330,4.148660,5.877269,13.483146,25.756266
2,0.5,50,5,3,max,0.432152,1.901469,3.630078,7.260156,14.261020,25.669836
3,0.5,50,5,5,mean,0.086430,1.642178,2.852204,4.753673,12.878133,25.669836
4,0.5,50,5,2,max,0.777874,1.901469,3.975799,6.741573,13.310285,24.805532
5,0.5,50,5,1,mean,0.000000,1.210026,3.025065,5.012965,12.273120,24.546240
6,0.5,50,5,2,mean,0.259291,0.950735,2.247191,5.445117,11.840968,24.114088
7,0.5,50,5,3,mean,0.259291,1.210026,2.679343,5.099395,12.186690,23.681936

Saved hybrid summary to: /home/jupyter/results/retrieval_subset/candidate_local_smoothing_summary_nclips300_top100.csv

### Hybrid Candidate-Window with Local Temporal Smoothing

The best-performing method was the hybrid candidate-window plus local temporal smoothing strategy. The best configuration used alpha = 0.5, candidate_topk = 50, window_radius = 5, local_smooth_radius = 5, and max smoothing.

This method achieved 27.92% Top-100 accuracy, outperforming the best candidate-window-only result of 26.62% and the best alpha-fusion result of 25.84%. It also improved Top-20 accuracy to 7.69%, compared with 7.00% from temporal smoothing and 5.45% from candidate-window reranking.

These results suggest that candidate-window expansion improves candidate recall, while local temporal smoothing helps promote correct frames within candidate regions. The max smoothing strategy worked better than mean smoothing, indicating that preserving local peak scores is more effective than averaging nearby scores.

In [ ]:
# ---------------- 41. Final comparison including hybrid best ----------------

# Paths
baseline_summary_path = RESULTS_DIR / f"baseline_summary_nclips{N_CLIPS}_top100.csv"
alpha_summary_path = RESULTS_DIR / f"alpha_fusion_summary_nclips{N_CLIPS}_top100.csv"
temporal_summary_path = RESULTS_DIR / f"temporal_smoothing_summary_nclips{N_CLIPS}_top100.csv"
candidate_summary_path = RESULTS_DIR / f"candidate_window_summary_nclips{N_CLIPS}_top100.csv"
hybrid_summary_path = RESULTS_DIR / f"candidate_local_smoothing_summary_nclips{N_CLIPS}_top100.csv"

print("Checking summary files:")
for p in [
    baseline_summary_path,
    alpha_summary_path,
    temporal_summary_path,
    candidate_summary_path,
    hybrid_summary_path,
]:
    print(p.name, "| exists:", p.exists())

# Load summaries
baseline_summary = pd.read_csv(baseline_summary_path)
alpha_summary = pd.read_csv(alpha_summary_path)
temporal_summary = pd.read_csv(temporal_summary_path)
candidate_summary = pd.read_csv(candidate_summary_path)
hybrid_summary = pd.read_csv(hybrid_summary_path)

metric_cols = [
    "top1_success",
    "top5_success",
    "top10_success",
    "top20_success",
    "top50_success",
    "top100_success",
]

# 1. Baseline rows
baseline_rows = baseline_summary.copy()
baseline_rows["method"] = baseline_rows["model_name"] + "_baseline"
baseline_rows["setting"] = baseline_rows["model_name"]
baseline_rows = baseline_rows[["method", "setting"] + metric_cols]

# 2. Alpha fusion best
alpha_best = (
    alpha_summary
    .sort_values(
        ["top100_success", "top50_success", "top20_success", "top10_success"],
        ascending=False,
    )
    .head(1)
    .copy()
)
alpha_best["method"] = "alpha_fusion"
alpha_best["setting"] = alpha_best.apply(
    lambda r: f"alpha={r['alpha']}",
    axis=1,
)
alpha_best = alpha_best[["method", "setting"] + metric_cols]

# 3. Temporal smoothing best
temporal_best = (
    temporal_summary
    .sort_values(
        ["top100_success", "top50_success", "top20_success", "top10_success"],
        ascending=False,
    )
    .head(1)
    .copy()
)
temporal_best["method"] = "temporal_smoothing"
temporal_best["setting"] = temporal_best.apply(
    lambda r: (
        f"alpha={r['alpha']}, "
        f"window={int(r['window_size'])}, "
        f"mode={r['smoothing_mode']}"
    ),
    axis=1,
)
temporal_best = temporal_best[["method", "setting"] + metric_cols]

# 4. Candidate-window best
candidate_best = (
    candidate_summary
    .sort_values(
        ["top100_success", "top50_success", "top20_success", "top10_success"],
        ascending=False,
    )
    .head(1)
    .copy()
)
candidate_best["method"] = "candidate_window"
candidate_best["setting"] = candidate_best.apply(
    lambda r: (
        f"alpha={r['alpha']}, "
        f"candidate_topk={int(r['candidate_topk'])}, "
        f"radius={int(r['window_radius'])}, "
        f"mode={r['score_mode']}"
    ),
    axis=1,
)
candidate_best = candidate_best[["method", "setting"] + metric_cols]

# 5. Hybrid best
hybrid_best = (
    hybrid_summary
    .sort_values(
        ["top100_success", "top50_success", "top20_success", "top10_success"],
        ascending=False,
    )
    .head(1)
    .copy()
)
hybrid_best["method"] = "candidate_local_smoothing"
hybrid_best["setting"] = hybrid_best.apply(
    lambda r: (
        f"alpha={r['alpha']}, "
        f"candidate_topk={int(r['candidate_topk'])}, "
        f"window_radius={int(r['window_radius'])}, "
        f"local_smooth_radius={int(r['local_smooth_radius'])}, "
        f"mode={r['smooth_mode']}"
    ),
    axis=1,
)
hybrid_best = hybrid_best[["method", "setting"] + metric_cols]

# Combine all methods
final_comparison_with_hybrid = pd.concat(
    [
        baseline_rows,
        alpha_best,
        temporal_best,
        candidate_best,
        hybrid_best,
    ],
    ignore_index=True,
)

final_comparison_with_hybrid = final_comparison_with_hybrid.sort_values(
    ["top100_success", "top50_success", "top20_success", "top10_success"],
    ascending=False,
).reset_index(drop=True)

display(final_comparison_with_hybrid)

# Save
final_comparison_with_hybrid_path = (
    RESULTS_DIR / f"final_method_comparison_with_hybrid_nclips{N_CLIPS}_top100.csv"
)

final_comparison_with_hybrid.to_csv(
    final_comparison_with_hybrid_path,
    index=False,
)

print("Saved final comparison with hybrid to:", final_comparison_with_hybrid_path)

Checking summary files:
baseline_summary_nclips300_top100.csv | exists: True
alpha_fusion_summary_nclips300_top100.csv | exists: True
temporal_smoothing_summary_nclips300_top100.csv | exists: True
candidate_window_summary_nclips300_top100.csv | exists: True
candidate_local_smoothing_summary_nclips300_top100.csv | exists: True

,method,setting,top1_success,top5_success,top10_success,top20_success,top50_success,top100_success
0,candidate_local_smoothing,"alpha=0.5, candidate_topk=50, window_radius=5,...",0.518583,2.074330,3.457217,7.692308,16.853933,27.917027
1,candidate_window,"alpha=0.5, candidate_topk=50, radius=5, mode=max",0.605013,1.728608,2.765774,5.445117,13.828868,26.620570
2,alpha_fusion,alpha=0.5,0.605013,1.728608,2.765774,5.445117,13.828868,25.842697
3,temporal_smoothing,"alpha=0.5, window=7, mode=max",0.777874,1.987900,3.630078,7.000864,14.606742,25.756266
4,blip_baseline,blip,0.518583,1.469317,2.852204,5.617978,13.569576,25.669836
5,clip_baseline,clip,0.518583,1.728608,2.938634,5.272256,15.038894,24.978392

Saved final comparison with hybrid to: /home/jupyter/results/retrieval_subset/final_method_comparison_with_hybrid_nclips300_top100.csv

# Final Experiment Summary

We evaluated several retrieval strategies on a 300-clip subset using cached CLIP and BLIP embeddings.

The experiment followed a progressive retrieval pipeline:

1. Single-model baseline retrieval using CLIP and BLIP.
2. Score-level CLIP/BLIP alpha fusion.
3. Temporal smoothing as a post-processing strategy.
4. Candidate-guided window reranking.
5. Hybrid candidate-window reranking with local temporal smoothing.

The best final method was **candidate-guided local temporal smoothing**, using:

- alpha = 0.5
- candidate_topk = 50
- window_radius = 5
- local_smooth_radius = 5
- smooth_mode = max

This method achieved the best overall performance:

- Top20 accuracy: approximately 7.69%
- Top50 accuracy: approximately 16.85%
- Top100 accuracy: approximately 27.92%

The results show that candidate-window expansion improves candidate recall, while local temporal smoothing improves ranking within the expanded candidate regions. The hybrid method therefore provides the best balance between broad candidate retrieval and early-rank accuracy.